MODULE MIE_PHMX_PACE

USE PACE_INSTRUMENT_DESIGN,ONLY : NWV_BAND,WV_BAND,&
               NWV_BAND_SEG1P2,NWV_BAND_SEG3,NWV_BAND_SEG4
USE AEROSOL_MICROPHYSICAL_MODEL
USE RTUTILITY, ONLY : PI,FACTOR,NUMMIEANGMAX,MAXLFULL

INTEGER,DIMENSION(:),ALLOCATABLE :: NUM_SCAT_ANG,NUMBETAL
REAL*8 :: REFF_MINERAL,AREA_MINERAL,WAVELENGTH_MICRON_REF

REAL*8,DIMENSION(:),ALLOCATABLE:: CEXT_Plankton_BAND,CSCAT_Plankton_BAND,BBFRAC_Plankton_BAND, &
				 CEXT_Mineral_BAND,CSCAT_Mineral_BAND,BBFRAC_Mineral_BAND

REAL*8,DIMENSION(:,:,:),ALLOCATABLE :: PHMXMIE_Plankton_PACE,PHMXMIE_Mineral_PACE

REAL*8,DIMENSION(:,:),ALLOCATABLE:: CEXT_ARSL_BAND,CSCAT_ARSL_BAND
REAL*8,DIMENSION(:,:,:,:),ALLOCATABLE::PHMXMIE_ARSL
REAL*8,DIMENSION(:,:,:),ALLOCATABLE::COEFFMIE_ARSL
REAL*8,DIMENSION(:,:),ALLOCATABLE::FTRUNC_ARSL
REAL*8,DIMENSION(:,:,:),ALLOCATABLE:: BETAL_ARSL,ALPHAL_ARSL,ZETAL_ARSL, &
								 DELTAL_ARSL,GAMMAL_ARSL,EPSILONL_ARSL


CONTAINS

SUBROUTINE PHMXMIE_PACE_ALLO(NUMMIEUSE)
INTEGER,INTENT(IN):: NUMMIEUSE

ALLOCATE(NUM_SCAT_ANG(NUMMIEUSE),NUMBETAL(NUMMIEUSE))
ALLOCATE(CEXT_ARSL_BAND(0:NUMMIEUSE, NWV_BAND),CSCAT_ARSL_BAND(0:NUMMIEUSE,NWV_BAND), &
         CEXT_Plankton_BAND(NWV_BAND),CSCAT_Plankton_BAND(NWV_BAND),BBFRAC_Plankton_BAND(NWV_BAND), &
         CEXT_Mineral_BAND(NWV_BAND),CSCAT_Mineral_BAND(NWV_BAND),BBFRAC_Mineral_BAND(NWV_BAND) )

ALLOCATE(PHMXMIE_ARSL(NUMMIEUSE,NWV_BAND,NUMMIEANGMAX,0:6), &
         PHMXMIE_Plankton_PACE(NWV_BAND,NUMMIEANGMAX,0:6), &
         PHMXMIE_Mineral_PACE(NWV_BAND,NUMMIEANGMAX,0:6) )

ALLOCATE(COEFFMIE_ARSL(NUMMIEUSE,NWV_BAND,0:MAXLFULL) )
ALLOCATE(FTRUNC_ARSL(NUMMIEUSE,NWV_BAND), &
		 BETAL_ARSL(NUMMIEUSE,NWV_BAND,0:MAXLFULL),ALPHAL_ARSL(NUMMIEUSE,NWV_BAND,0:MAXLFULL), &
		ZETAL_ARSL(NUMMIEUSE,NWV_BAND,0:MAXLFULL),DELTAL_ARSL(NUMMIEUSE,NWV_BAND,0:MAXLFULL), &
		GAMMAL_ARSL(NUMMIEUSE,NWV_BAND,0:MAXLFULL),EPSILONL_ARSL(NUMMIEUSE,NWV_BAND,0:MAXLFULL) )

ENDSUBROUTINE PHMXMIE_PACE_ALLO

SUBROUTINE PHMXMIE_PACE_DEALLO

DEALLOCATE(CEXT_ARSL_BAND,CSCAT_ARSL_BAND, &
		   CEXT_Plankton_BAND,CSCAT_Plankton_BAND,BBFRAC_Plankton_BAND, &
		   CEXT_Mineral_BAND,CSCAT_Mineral_BAND,BBFRAC_Mineral_BAND)

DEALLOCATE(PHMXMIE_ARSL,PHMXMIE_Plankton_PACE,PHMXMIE_Mineral_PACE)

DEALLOCATE(COEFFMIE_ARSL,FTRUNC_ARSL, BETAL_ARSL,ALPHAL_ARSL,ZETAL_ARSL, &
		   DELTAL_ARSL,GAMMAL_ARSL,EPSILONL_ARSL)

DEALLOCATE(NUM_SCAT_ANG,NUMBETAL)

ENDSUBROUTINE PHMXMIE_PACE_DEALLO

SUBROUTINE PHMXMIE_PACE_READIN(CFILE_AEROSOLS,NUMMIEUSE,NWV_PHMX,REFF1_Save,VEFF1_Save,      &
             REFF2_Save,VEFF2_Save,MRR1_Save,MRI1_Save,MRR2_Save,MRI2_Save, &
		     ARSLND1_Save,ARSLND2_Save,ARSLND_NonSpherical,REFF_NonSpherical,&
             VEFF_NonSpherical,MRR_NonSpherical,MRI_NonSpherical)
USE RTUTILITY,ONLY : FACTOR,NUMMIEANGMAX
USE HDF5
IMPLICIT NONE
INTEGER,INTENT(IN):: NUMMIEUSE,NWV_PHMX
CHARACTER(LEN=360),DIMENSION(NUMMIEUSE), INTENT(IN) :: CFILE_AEROSOLS
REAL*8,DIMENSION(NUMMIEUSE),INTENT(OUT) :: REFF1_Save,REFF2_Save,VEFF1_Save,VEFF2_Save,&
										   ARSLND1_Save,ARSLND2_Save
REAL*8,DIMENSION(NUMMIEUSE,NWV_PHMX),INTENT(OUT) :: MRR1_Save,MRI1_Save,MRR2_Save,MRI2_Save

REAL*8, INTENT(INOUT) :: ARSLND_NonSpherical,REFF_NonSpherical,VEFF_NonSpherical
REAL*8, INTENT(INOUT),DIMENSION(:) :: MRR_NonSpherical,MRI_NonSpherical

! HDF 5 DEFINITION
INTEGER(HID_T)  :: file, space, dset, attr ! Handles
INTEGER :: hdferr
INTEGER(hsize_t),   DIMENSION(1:2) :: dims
INTEGER(hsize_t),DIMENSION(1) :: dimscl
INTEGER(HSIZE_T), DIMENSION(1:2) :: maxdims
TYPE(C_PTR) :: f_ptr
REAL*4,DIMENSION(1),TARGET :: HDF5RTMP
INTEGER,DIMENSION(1),TARGET :: HDF5ITMP
REAL*4,DIMENSION(:),TARGET,ALLOCATABLE :: HDF5RARR
REAL*4,DIMENSION(:,:),TARGET,ALLOCATABLE :: HDF5RARR2DIM

INTEGER(hsize_t), DIMENSION(1:3) :: dims3
REAL*4,DIMENSION(:,:,:),TARGET,ALLOCATABLE :: HDF5RARR3DIM

INTEGER :: IMIE,INDXVAR,ILTERM,itheta,NANGMIE_LOCAL

integer::numanglocal
integer::numordfull_local
real*8,dimension(:),allocatable::muang,p11
real*8,dimension(:),allocatable::fullbetal_local

CSCAT_ARSL_BAND=0.0d0
CEXT_ARSL_BAND=0.0d0
COEFFMIE_ARSL=0.0D0
NUMBETAL=0
DO IMIE=1,NUMMIEUSE

! READ IN SCATTERING MATRIX
CALL h5open_f(hdferr)
CALL h5fopen_f(CFILE_AEROSOLS(IMIE), H5F_ACC_RDONLY_F, file, hdferr)

!CALL h5dopen_f (file,'NUMMIEANG', dset, hdferr)
!CALL h5dread_f(dset, H5T_NATIVE_INTEGER,NANGMIE_LOCAL,dimscl, hdferr)
!CALL h5dclose_f(dset , hdferr)

dimscl=(/ 1 /)
CALL h5dopen_f (file,'NUM_SCAT_ANG', dset, hdferr)
CALL h5dread_f(dset, H5T_NATIVE_INTEGER,HDF5ITMP,dimscl, hdferr)
CALL h5dclose_f(dset , hdferr)
NANGMIE_LOCAL=HDF5ITMP(1)
IF(NANGMIE_LOCAL>NUMMIEANGMAX) STOP 'ERROR, NANGMIE_LOCAL>NUMMIEANGMAX'
NUM_SCAT_ANG(IMIE)=NANGMIE_LOCAL

CALL h5dopen_f (file,'Aerosol_Ndf', dset, hdferr)
CALL h5dread_f(dset, H5T_NATIVE_REAL,HDF5RTMP,dimscl, hdferr)
CALL h5dclose_f(dset , hdferr)
ARSLND1_Save(IMIE)=HDF5RTMP(1)

CALL h5dopen_f (file,'Aerosol_Ndc', dset, hdferr)
CALL h5dread_f(dset, H5T_NATIVE_REAL,HDF5RTMP,dimscl, hdferr)
CALL h5dclose_f(dset , hdferr)
ARSLND2_Save(IMIE)=HDF5RTMP(1)

CALL h5dopen_f (file,'Aerosol_NdD', dset, hdferr)
CALL h5dread_f(dset, H5T_NATIVE_REAL,HDF5RTMP,dimscl, hdferr)
CALL h5dclose_f(dset , hdferr)
ARSLND_NonSpherical=HDF5RTMP(1)

CALL h5dopen_f (file,'Aerosol_Rf', dset, hdferr)
CALL h5dread_f(dset, H5T_NATIVE_REAL,HDF5RTMP,dimscl, hdferr)
CALL h5dclose_f(dset , hdferr)
REFF1_Save(IMIE)=HDF5RTMP(1)

CALL h5dopen_f (file,'Aerosol_Rc', dset, hdferr)
CALL h5dread_f(dset, H5T_NATIVE_REAL,HDF5RTMP,dimscl, hdferr)
CALL h5dclose_f(dset , hdferr)
REFF2_Save(IMIE)=HDF5RTMP(1)

CALL h5dopen_f (file,'Aerosol_RD', dset, hdferr)
CALL h5dread_f(dset, H5T_NATIVE_REAL,HDF5RTMP,dimscl, hdferr)
CALL h5dclose_f(dset , hdferr)
REFF_NonSpherical=HDF5RTMP(1)

CALL h5dopen_f (file,'Aerosol_Vf', dset, hdferr)
CALL h5dread_f(dset, H5T_NATIVE_REAL,HDF5RTMP,dimscl, hdferr)
CALL h5dclose_f(dset , hdferr)
VEFF1_Save(IMIE)=HDF5RTMP(1)

CALL h5dopen_f (file,'Aerosol_Vc', dset, hdferr)
CALL h5dread_f(dset, H5T_NATIVE_REAL,HDF5RTMP,dimscl, hdferr)
CALL h5dclose_f(dset , hdferr)
VEFF2_Save(IMIE)=HDF5RTMP(1)

CALL h5dopen_f (file,'Aerosol_VD', dset, hdferr)
CALL h5dread_f(dset, H5T_NATIVE_REAL,HDF5RTMP,dimscl, hdferr)
CALL h5dclose_f(dset , hdferr)
VEFF_NonSpherical=HDF5RTMP(1)

dimscl=(/ NWV_BAND_SEG1P2 /)
ALLOCATE(HDF5RARR(NWV_BAND_SEG1P2))
CALL h5dopen_f (file,'WaveLength_OCI', dset, hdferr)
CALL h5dread_f(dset, H5T_NATIVE_REAL,HDF5RARR,dimscl, hdferr)
CALL h5dclose_f(dset , hdferr)

IF(ABS(HDF5RARR(NWV_BAND_SEG1P2)-WV_BAND(NWV_BAND_SEG1P2))>1.0E-6)THEN
   WRITE(*,*)'WAVELENGTH READ IN FROM AEROSOL FILE IS',HDF5RARR(NWV_BAND_SEG1P2)
   WRITE(*,*)'WV_BAND(NWV_BAND_SEG1P2)=',WV_BAND(NWV_BAND_SEG1P2)
   STOP
ENDIF

HDF5RARR=0.0d0
CALL h5dopen_f (file,'Aerosol_Cext_OCI', dset, hdferr)
CALL h5dread_f(dset, H5T_NATIVE_REAL,HDF5RARR,dimscl, hdferr)
CALL h5dclose_f(dset , hdferr)
CEXT_ARSL_BAND(IMIE,1:NWV_BAND_SEG1P2)=HDF5RARR(1:NWV_BAND_SEG1P2)

HDF5RARR=0.0d0
CALL h5dopen_f (file,'Aerosol_Cscat_OCI', dset, hdferr)
CALL h5dread_f(dset, H5T_NATIVE_REAL,HDF5RARR,dimscl, hdferr)
CALL h5dclose_f(dset , hdferr)
CSCAT_ARSL_BAND(IMIE,1:NWV_BAND_SEG1P2)=HDF5RARR(1:NWV_BAND_SEG1P2)

HDF5RARR=0.0d0
CALL h5dopen_f (file,'Aerosol_Mrf_OCI', dset, hdferr)
CALL h5dread_f(dset, H5T_NATIVE_REAL,HDF5RARR,dimscl, hdferr)
CALL h5dclose_f(dset , hdferr)
MRR1_Save(IMIE,1:NWV_BAND_SEG1P2)=HDF5RARR(1:NWV_BAND_SEG1P2)

HDF5RARR=0.0d0
CALL h5dopen_f (file,'Aerosol_Mif_OCI', dset, hdferr)
CALL h5dread_f(dset, H5T_NATIVE_REAL,HDF5RARR,dimscl, hdferr)
CALL h5dclose_f(dset , hdferr)
MRI1_Save(IMIE,1:NWV_BAND_SEG1P2)=HDF5RARR(1:NWV_BAND_SEG1P2)

HDF5RARR=0.0d0
CALL h5dopen_f (file,'Aerosol_Mrc_OCI', dset, hdferr)
CALL h5dread_f(dset, H5T_NATIVE_REAL,HDF5RARR,dimscl, hdferr)
CALL h5dclose_f(dset , hdferr)
MRR2_Save(IMIE,1:NWV_BAND_SEG1P2)=HDF5RARR(1:NWV_BAND_SEG1P2)

HDF5RARR=0.0d0
CALL h5dopen_f (file,'Aerosol_Mic_OCI', dset, hdferr)
CALL h5dread_f(dset, H5T_NATIVE_REAL,HDF5RARR,dimscl, hdferr)
CALL h5dclose_f(dset , hdferr)
MRI2_Save(IMIE,1:NWV_BAND_SEG1P2)=HDF5RARR(1:NWV_BAND_SEG1P2)

HDF5RARR=0.0d0
CALL h5dopen_f (file,'Aerosol_MrD_OCI', dset, hdferr)
CALL h5dread_f(dset, H5T_NATIVE_REAL,HDF5RARR,dimscl, hdferr)
CALL h5dclose_f(dset , hdferr)
MRR_NonSpherical(1:NWV_BAND_SEG1P2)=HDF5RARR(1:NWV_BAND_SEG1P2)

HDF5RARR=0.0d0
CALL h5dopen_f (file,'Aerosol_MiD_OCI', dset, hdferr)
CALL h5dread_f(dset, H5T_NATIVE_REAL,HDF5RARR,dimscl, hdferr)
CALL h5dclose_f(dset , hdferr)
MRI_NonSpherical(1:NWV_BAND_SEG1P2)=HDF5RARR(1:NWV_BAND_SEG1P2)

DEALLOCATE(HDF5RARR)

dimscl=(/ NWV_BAND_SEG3 /)
ALLOCATE(HDF5RARR(NWV_BAND_SEG3))
CALL h5dopen_f (file,'WaveLength_SPEX', dset, hdferr)
CALL h5dread_f(dset, H5T_NATIVE_REAL,HDF5RARR,dimscl, hdferr)
CALL h5dclose_f(dset , hdferr)

IF(ABS(HDF5RARR(NWV_BAND_SEG3)-WV_BAND(NWV_BAND_SEG1P2+NWV_BAND_SEG3))>1.0E-6)THEN
   WRITE(*,*)'WAVELENGTH READ IN FROM AEROSOL FILE IS',HDF5RARR(NWV_BAND_SEG3)
   WRITE(*,*)'WV_BAND(NWV_BAND_SEG1P2+NWV_BAND_SEG3)=',WV_BAND(NWV_BAND_SEG1P2+NWV_BAND_SEG3)
   STOP
ENDIF

HDF5RARR=0.0d0
CALL h5dopen_f (file,'Aerosol_Cext_SPEX', dset, hdferr)
CALL h5dread_f(dset, H5T_NATIVE_REAL,HDF5RARR,dimscl, hdferr)
CALL h5dclose_f(dset , hdferr)
CEXT_ARSL_BAND(IMIE,NWV_BAND_SEG1P2+1:NWV_BAND_SEG1P2+NWV_BAND_SEG3)=HDF5RARR(1:NWV_BAND_SEG3)

HDF5RARR=0.0d0
CALL h5dopen_f (file,'Aerosol_Cscat_SPEX', dset, hdferr)
CALL h5dread_f(dset, H5T_NATIVE_REAL,HDF5RARR,dimscl, hdferr)
CALL h5dclose_f(dset , hdferr)
CSCAT_ARSL_BAND(IMIE,NWV_BAND_SEG1P2+1:NWV_BAND_SEG1P2+NWV_BAND_SEG3)=HDF5RARR(1:NWV_BAND_SEG3)

HDF5RARR=0.0d0
CALL h5dopen_f (file,'Aerosol_Mrf_SPEX', dset, hdferr)
CALL h5dread_f(dset, H5T_NATIVE_REAL,HDF5RARR,dimscl, hdferr)
CALL h5dclose_f(dset , hdferr)
MRR1_Save(IMIE,NWV_BAND_SEG1P2+1:NWV_BAND_SEG1P2+NWV_BAND_SEG3)=HDF5RARR(1:NWV_BAND_SEG3)

HDF5RARR=0.0d0
CALL h5dopen_f (file,'Aerosol_Mif_SPEX', dset, hdferr)
CALL h5dread_f(dset, H5T_NATIVE_REAL,HDF5RARR,dimscl, hdferr)
CALL h5dclose_f(dset , hdferr)
MRI1_Save(IMIE,NWV_BAND_SEG1P2+1:NWV_BAND_SEG1P2+NWV_BAND_SEG3)=HDF5RARR(1:NWV_BAND_SEG3)

HDF5RARR=0.0d0
CALL h5dopen_f (file,'Aerosol_Mrc_SPEX', dset, hdferr)
CALL h5dread_f(dset, H5T_NATIVE_REAL,HDF5RARR,dimscl, hdferr)
CALL h5dclose_f(dset , hdferr)
MRR2_Save(IMIE,NWV_BAND_SEG1P2+1:NWV_BAND_SEG1P2+NWV_BAND_SEG3)=HDF5RARR(1:NWV_BAND_SEG3)

HDF5RARR=0.0d0
CALL h5dopen_f (file,'Aerosol_Mic_SPEX', dset, hdferr)
CALL h5dread_f(dset, H5T_NATIVE_REAL,HDF5RARR,dimscl, hdferr)
CALL h5dclose_f(dset , hdferr)
MRI2_Save(IMIE,NWV_BAND_SEG1P2+1:NWV_BAND_SEG1P2+NWV_BAND_SEG3)=HDF5RARR(1:NWV_BAND_SEG3)

HDF5RARR=0.0d0
CALL h5dopen_f (file,'Aerosol_MrD_SPEX', dset, hdferr)
CALL h5dread_f(dset, H5T_NATIVE_REAL,HDF5RARR,dimscl, hdferr)
CALL h5dclose_f(dset , hdferr)
MRR_NonSpherical(NWV_BAND_SEG1P2+1:NWV_BAND_SEG1P2+NWV_BAND_SEG3)=HDF5RARR(1:NWV_BAND_SEG3)

HDF5RARR=0.0d0
CALL h5dopen_f (file,'Aerosol_MiD_SPEX', dset, hdferr)
CALL h5dread_f(dset, H5T_NATIVE_REAL,HDF5RARR,dimscl, hdferr)
CALL h5dclose_f(dset , hdferr)
MRI_NonSpherical(NWV_BAND_SEG1P2+1:NWV_BAND_SEG1P2+NWV_BAND_SEG3)=HDF5RARR(1:NWV_BAND_SEG3)

DEALLOCATE(HDF5RARR)

dimscl=(/ NWV_BAND_SEG4 /)
ALLOCATE(HDF5RARR(NWV_BAND_SEG4))
CALL h5dopen_f (file,'WaveLength_HARP', dset, hdferr)
CALL h5dread_f(dset, H5T_NATIVE_REAL,HDF5RARR,dimscl, hdferr)
CALL h5dclose_f(dset , hdferr)

IF(ABS(HDF5RARR(NWV_BAND_SEG4)-WV_BAND(NWV_BAND_SEG1P2+NWV_BAND_SEG3+NWV_BAND_SEG4))>1.0E-6)THEN
   WRITE(*,*)'WAVELENGTH READ IN FROM AEROSOL FILE IS',HDF5RARR(NWV_BAND_SEG4)
   WRITE(*,*)'WV_BAND(NWV_BAND_SEG1P2+NWV_BAND_SEG3+NWV_SEG4)=',WV_BAND(NWV_BAND_SEG1P2+NWV_BAND_SEG3+NWV_BAND_SEG4)
   STOP
ENDIF

HDF5RARR=0.0d0
CALL h5dopen_f (file,'Aerosol_Cext_HARP', dset, hdferr)
CALL h5dread_f(dset, H5T_NATIVE_REAL,HDF5RARR,dimscl, hdferr)
CALL h5dclose_f(dset , hdferr)
CEXT_ARSL_BAND(IMIE,NWV_BAND_SEG1P2+NWV_BAND_SEG3+1:NWV_BAND)=HDF5RARR(1:NWV_BAND_SEG4)

HDF5RARR=0.0d0
CALL h5dopen_f (file,'Aerosol_Cscat_HARP', dset, hdferr)
CALL h5dread_f(dset, H5T_NATIVE_REAL,HDF5RARR,dimscl, hdferr)
CALL h5dclose_f(dset , hdferr)
CSCAT_ARSL_BAND(IMIE,NWV_BAND_SEG1P2+NWV_BAND_SEG3+1:NWV_BAND)=HDF5RARR(1:NWV_BAND_SEG4)

HDF5RARR=0.0d0
CALL h5dopen_f (file,'Aerosol_Mrf_HARP', dset, hdferr)
CALL h5dread_f(dset, H5T_NATIVE_REAL,HDF5RARR,dimscl, hdferr)
CALL h5dclose_f(dset , hdferr)
MRR1_Save(IMIE,NWV_BAND_SEG1P2+NWV_BAND_SEG3+1:NWV_BAND)=HDF5RARR(1:NWV_BAND_SEG4)

HDF5RARR=0.0d0
CALL h5dopen_f (file,'Aerosol_Mif_HARP', dset, hdferr)
CALL h5dread_f(dset, H5T_NATIVE_REAL,HDF5RARR,dimscl, hdferr)
CALL h5dclose_f(dset , hdferr)
MRI1_Save(IMIE,NWV_BAND_SEG1P2+NWV_BAND_SEG3+1:NWV_BAND)=HDF5RARR(1:NWV_BAND_SEG4)

HDF5RARR=0.0d0
CALL h5dopen_f (file,'Aerosol_Mrc_HARP', dset, hdferr)
CALL h5dread_f(dset, H5T_NATIVE_REAL,HDF5RARR,dimscl, hdferr)
CALL h5dclose_f(dset , hdferr)
MRR2_Save(IMIE,NWV_BAND_SEG1P2+NWV_BAND_SEG3+1:NWV_BAND)=HDF5RARR(1:NWV_BAND_SEG4)

HDF5RARR=0.0d0
CALL h5dopen_f (file,'Aerosol_Mic_HARP', dset, hdferr)
CALL h5dread_f(dset, H5T_NATIVE_REAL,HDF5RARR,dimscl, hdferr)
CALL h5dclose_f(dset , hdferr)
MRI2_Save(IMIE,NWV_BAND_SEG1P2+NWV_BAND_SEG3+1:NWV_BAND)=HDF5RARR(1:NWV_BAND_SEG4)

HDF5RARR=0.0d0
CALL h5dopen_f (file,'Aerosol_MrD_HARP', dset, hdferr)
CALL h5dread_f(dset, H5T_NATIVE_REAL,HDF5RARR,dimscl, hdferr)
CALL h5dclose_f(dset , hdferr)
MRR_NonSpherical(NWV_BAND_SEG1P2+NWV_BAND_SEG3+1:NWV_BAND)=HDF5RARR(1:NWV_BAND_SEG4)

HDF5RARR=0.0d0
CALL h5dopen_f (file,'Aerosol_MiD_HARP', dset, hdferr)
CALL h5dread_f(dset, H5T_NATIVE_REAL,HDF5RARR,dimscl, hdferr)
CALL h5dclose_f(dset , hdferr)
MRI_NonSpherical(NWV_BAND_SEG1P2+NWV_BAND_SEG3+1:NWV_BAND)=HDF5RARR(1:NWV_BAND_SEG4)

DEALLOCATE(HDF5RARR)

dimscl=(/ NANGMIE_LOCAL/)
ALLOCATE(HDF5RARR(NANGMIE_LOCAL))
CALL h5dopen_f (file,'Aerosol_Phmxmie_Scatang', dset, hdferr)
CALL h5dread_f(dset, H5T_NATIVE_REAL,HDF5RARR,dimscl, hdferr)
CALL h5dclose_f(dset , hdferr)
DO INDXVAR=1,NWV_BAND
   PHMXMIE_ARSL(IMIE,INDXVAR,1:NANGMIE_LOCAL,0)=HDF5RARR(1:NANGMIE_LOCAL)
ENDDO
DEALLOCATE(HDF5RARR)

IF(PHMXMIE_ARSL(IMIE,1,1,0)>1.0E-6) STOP 'SCATTERING ANGLE (1) IS NOT ZERO'
IF(ABS(PHMXMIE_ARSL(IMIE,1,NANGMIE_LOCAL,0)-180.0D0)>1.0E-6) STOP 'LAST SCATTERING ANGLE IS NOT 180'

dims3= (/NWV_BAND_SEG1P2,NANGMIE_LOCAL,6/)
ALLOCATE(HDF5RARR3DIM(NWV_BAND_SEG1P2,NANGMIE_LOCAL,6))
HDF5RARR3DIM=0.0D0
CALL h5dopen_f (file,'Aerosol_Phmxmie_OCI', dset, hdferr)
CALL h5dread_f(dset, H5T_NATIVE_REAL,HDF5RARR3DIM,dims, hdferr)
CALL h5dclose_f(dset , hdferr)
DO INDXVAR=1,NWV_BAND_SEG1P2
   PHMXMIE_ARSL(IMIE,INDXVAR,1:NANGMIE_LOCAL,1:6)=HDF5RARR3DIM(INDXVAR,1:NANGMIE_LOCAL,1:6)
ENDDO
DEALLOCATE(HDF5RARR3DIM)

dims3= (/NWV_BAND_SEG3,NANGMIE_LOCAL,6/)
ALLOCATE(HDF5RARR3DIM(NWV_BAND_SEG3,NANGMIE_LOCAL,6))
HDF5RARR3DIM=0.0D0
CALL h5dopen_f (file,'Aerosol_Phmxmie_SPEX', dset, hdferr)
CALL h5dread_f(dset, H5T_NATIVE_REAL,HDF5RARR3DIM,dims, hdferr)
CALL h5dclose_f(dset , hdferr)
DO INDXVAR=NWV_BAND_SEG1P2+1,NWV_BAND_SEG1P2+NWV_BAND_SEG3
   PHMXMIE_ARSL(IMIE,INDXVAR,1:NANGMIE_LOCAL,1:6) = &
           HDF5RARR3DIM(INDXVAR-NWV_BAND_SEG1P2,1:NANGMIE_LOCAL,1:6)
ENDDO
DEALLOCATE(HDF5RARR3DIM)

dims3= (/NWV_BAND_SEG4,NANGMIE_LOCAL,6/)
ALLOCATE(HDF5RARR3DIM(NWV_BAND_SEG4,NANGMIE_LOCAL,6))
HDF5RARR3DIM=0.0D0
CALL h5dopen_f (file,'Aerosol_Phmxmie_HARP', dset, hdferr)
CALL h5dread_f(dset, H5T_NATIVE_REAL,HDF5RARR3DIM,dims, hdferr)
CALL h5dclose_f(dset , hdferr)
DO INDXVAR=NWV_BAND_SEG1P2+NWV_BAND_SEG3+1,NWV_BAND_SEG1P2+NWV_BAND_SEG3+NWV_BAND_SEG4
   PHMXMIE_ARSL(IMIE,INDXVAR,1:NANGMIE_LOCAL,1:6) = &
          HDF5RARR3DIM(INDXVAR-NWV_BAND_SEG1P2-NWV_BAND_SEG3,1:NANGMIE_LOCAL,1:6)
ENDDO
DEALLOCATE(HDF5RARR3DIM)

CALL h5fclose_f(file , hdferr)
CALL h5close_f(hdferr)

ENDDO ! NUMMIEUSE LOOP

allocate(muang(NANGMIE_LOCAL),p11(NANGMIE_LOCAL))
allocate(fullbetal_local(0:MAXLFULL))

DO IMIE=1,NUMMIEUSE
DO INDXVAR=1,NWV_BAND

	do itheta=1,NANGMIE_LOCAL
		  muang(itheta)=cos(PHMXMIE_ARSL(IMIE,INDXVAR,itheta,0)*FACTOR)
		  p11(itheta)=PHMXMIE_ARSL(IMIE,INDXVAR,itheta,1)
	enddo
	call FULLBETAL_MONO(NANGMIE_LOCAL,muang,p11,numordfull_local,MAXLFULL,fullbetal_local)
	IF(NUMBETAL(IMIE)<numordfull_local)NUMBETAL(IMIE)=numordfull_local

	DO ILTERM=0,numordfull_local
		COEFFMIE_ARSL(IMIE,INDXVAR,ILTERM)=fullbetal_local(ILTERM)
	ENDDO

ENDDO
ENDDO ! NUMMIEUSE LOOP

deallocate(muang,p11,fullbetal_local)

ENDSUBROUTINE PHMXMIE_PACE_READIN

SUBROUTINE PHMXMIE_PACE_INIT(FREEFORMFLAG,IAEROSOL,NUMMIEUSE,AeroFMF,RH_Simu,NWV_PHMX,REFF1,VEFF1,REFF2,VEFF2,&
			WV_PACE_REF,MRR1,MRI1,MRR2,MRI2,ARSLND1,ARSLND2,PHYTOPLANKTON_INDEX_REFRACTION,&
            PHYTOPLANKTON_SPECTRAL_SLOPE,SEDIMENT_INDEX_REFRACTION,SEDIMENT_SPECTRAL_SLOPE)
IMPLICIT NONE

INTEGER,INTENT(IN) :: FREEFORMFLAG
! FREEFORMFLAG==0  FREE FORM AEROSOL CALCULATION, USING REFF, VEFF, MR,MI AS INPUTS
! FREEFORMFLAG==1  PRE-BUILD AEROSOL CALCULATION
! FREEFORMFLAG==2  PLANKTON MIE CALCULATION 
! FREEFORMFLAG==3  MINERAL MIE CALCULATION

INTEGER,INTENT(IN) :: IAEROSOL,NWV_PHMX,NUMMIEUSE
REAL*8,INTENT(IN) :: WV_PACE_REF,RH_Simu
REAL*8,INTENT(INOUT) :: AeroFMF
REAL*8,INTENT(INOUT)::REFF1,VEFF1,REFF2,VEFF2,ARSLND1,ARSLND2
REAL*8,DIMENSION(NWV_PHMX),INTENT(INOUT)::MRR1,MRI1,MRR2,MRI2

REAL*8,DIMENSION(NWV_PHMX)::WV_BAND_MICRON
REAL*8,DIMENSION(NUMMIEANGMAX,0:6)::PHMXMIE_LOCAL1,PHMXMIE_LOCAL2
REAL*8,DIMENSION(0:MAXLFULL,1:6)::COEFFMIE_LOCAL1,COEFFMIE_LOCAL2

REAL*8, INTENT(IN) :: PHYTOPLANKTON_INDEX_REFRACTION,PHYTOPLANKTON_SPECTRAL_SLOPE,&
                      SEDIMENT_INDEX_REFRACTION,SEDIMENT_SPECTRAL_SLOPE

INTEGER :: NDISTR,NANGMIE_LOCAL,NUMBETAL_LOCAL,ICOM,IRH
REAL*8 :: AA1,BB1,AA2,BB2,GAMMAI,REFFO,VEFFO,AREA,CEXT1,CEXT2,CSCAT1,CSCAT2

REAL*8::REFF1_LOCAL,VEFF1_LOCAL,REFF2_LOCAL,VEFF2_LOCAL,ARSLND1_LOCAL,ARSLND2_LOCAL

REAL*8 :: RTMP,RTMP1,BBFRAC_LOCAL
INTEGER,DIMENSION(1):: INTARR
INTEGER :: IWV_BAND,INTTMP,IMIE

REAL*8 :: POLINT_SIMPLE
REAL*8,DIMENSION(NRH) :: XARRY,YARRY

WAVELENGTH_MICRON_REF=WV_PACE_REF/1000.0d0
CALL WV_REF_ASSIGN(WAVELENGTH_MICRON_REF) ! aerosol optical depth reference wavelength

WV_BAND_MICRON=WV_BAND/1000.0D0

IF(IAEROSOL>0)THEN
	INTARR=MINLOC(ABS(RH-RH_simu))
	IRH=INTARR(1)
	IF(abs(RH(IRH)-RH_simu)>1.0e-4) THEN
	   WRITE(*,*)'INPUT RH_simu VALUE:',RH_simu,'NOT IN RH TABLE'
	   WRITE(*,*)'RELATIVE HUMIDTY TABLE:', IRH, RH(IRH)
	ENDIF
ENDIF

IF(FREEFORMFLAG==0)THEN
  IF(REFF1<0 .OR. REFF2<0 .OR. VEFF1<0 .OR. VEFF2<0 .OR. ARSLND1<0 .OR. ARSLND2<0) &
       STOP 'CHECK AEROSOL MICROPHYSICAL INPUT PARAMETERS'
  DO IWV_BAND=1,NWV_PHMX
     IF(MRR1(IWV_BAND)<0.0) STOP 'CHECK AEROSOL REFRACTIVE INDEX'
     IF(MRI1(IWV_BAND)<0.0) STOP 'CHECK AEROSOL REFRACTIVE INDEX'
     IF(MRR2(IWV_BAND)<0.0) STOP 'CHECK AEROSOL REFRACTIVE INDEX'
     IF(MRI2(IWV_BAND)<0.0) STOP 'CHECK AEROSOL REFRACTIVE INDEX'
  ENDDO
  REFF1_LOCAL=REFF1
  VEFF1_LOCAL=VEFF1
  REFF2_LOCAL=REFF2
  VEFF2_LOCAL=VEFF2
  NDISTR=2
ELSEIF(FREEFORMFLAG==1)THEN

  CALL ARSL_INDX_INIT(NWV_PHMX,WV_BAND_MICRON)

  IF(IAEROSOL==1)THEN
       REFF1=RTROPOSPHERE(IRH)
       REFF2=RRURALC(IRH)
  ELSEIF(IAEROSOL>=2 .AND. IAEROSOL<=6)THEN
       REFF1=RURBANF(IRH)
       REFF2=RURBANC(IRH)
  ELSEIF(IAEROSOL>=7 .AND. IAEROSOL<=9)THEN
       REFF1=RTROPOSPHERE(IRH)
       REFF2=ROCEANIC(IRH)
  ELSEIF(IAEROSOL==10)THEN
       REFF1=RTROPOSPHERE(IRH)
       REFF2=0.0D0
  ELSEIF(IAEROSOL==-1 .OR. (IAEROSOL>=11 .AND. IAEROSOL<=20))THEN
!       REFF1=exp(log(RZIAF(IRH))-3.0*SIGF_ZIA*SIGF_ZIA)
            ! Rg in number space read Eq.3a in Ahmad 2000 for details
!       REFF2=exp(log(RZIAC(IRH))-3.0*SIGC_ZIA*SIGC_ZIA)
		RTMP=POLINT_SIMPLE(NRH,RH,RZIAF,RH_simu,3)
		REFF1=exp(log(RTMP)-3.0*SIGF_ZIA*SIGF_ZIA)
		! Rg in number space read Eq.3a in Ahmad 2000 for details
		RTMP=POLINT_SIMPLE(NRH,RH,RZIAC,RH_simu,3)
		REFF2=exp(log(RTMP)-3.0*SIGC_ZIA*SIGC_ZIA)
  ENDIF
  IF(IAEROSOL>0 .and. IAEROSOL<=10)THEN
     VEFF1=SIGF_SF
     VEFF2=SIGC_SF
  ELSEIF(IAEROSOL==-1 .or. (IAEROSOL>10 .and. IAEROSOL<=20))THEN
     VEFF1=SIGF_ZIA
     VEFF2=SIGC_ZIA
  ELSE
     STOP 'IAEROSOL SHOULD BE -1 OR BETWEEN 1 AND 20'
  ENDIF

  IF(IAEROSOL>0 .AND. IAEROSOL<7)THEN
     ARSLND1=0.999875
     ARSLND2=0.000125
  ELSEIF(IAEROSOL==7)THEN
     ARSLND1=0.99
     ARSLND2=0.01
  ELSEIF(IAEROSOL==8)THEN
     ARSLND1=0.995
     ARSLND2=0.005
  ELSEIF(IAEROSOL==9)THEN
     ARSLND1=0.998
     ARSLND2=0.002
  ELSEIF(IAEROSOL==10)THEN
     ARSLND1=1.0D0
     ARSLND2=0.0D0
  ELSEIF(IAEROSOL==-1 .or. IAEROSOL>=11)THEN
     IF(IAEROSOL>=11 .and. IAEROSOL<=20)THEN
	    INTTMP=IAEROSOL-10
	    AeroFMF=RATIO_FINE_MODE_ZIA(INTTMP)
     ELSEIF(IAEROSOL>20)THEN
	    INTTMP=IAEROSOL-20
	    AeroFMF=RATIO_FINE_MODE_ZIA(INTTMP)
     ELSEIF(IAEROSOL==-1)THEN
	    IF(AeroFMF<0.0D0 .OR.AeroFMF>1.0D0) THEN
		   WRITE(*,*)'INPUT AeroFMF=',AeroFMF,' IS OUT OF 0-1'
		   STOP 'STOPING DUE TO INVALID AeroFMF VALUE'
	    ENDIF
     ENDIF
     RTMP=4.0D0*PI*(REFF1**3)/3.0D0
     RTMP=AeroFMF/RTMP*EXP(-4.5D0*VEFF1*VEFF1)
     RTMP1=4.0D0*PI*(REFF2**3)/3.0D0
     RTMP1=(1.0D0-AeroFMF)/RTMP1*EXP(-4.5D0*VEFF2*VEFF2)
     RTMP=RTMP/(RTMP+RTMP1)
     ARSLND1=RTMP
     ARSLND2=(1.0D0-RTMP)
!     WRITE(*,*)'FINE MODE FRACTION=',RTMP
  ENDIF

  IF(IAEROSOL==1)THEN !rural 
       MRR1(1:NWV_PHMX)=MR_TRPOSPHERE(1:NWV_PHMX,IRH)
       MRI1(1:NWV_PHMX)=MI_TRPOSPHERE(1:NWV_PHMX,IRH)
       MRR2(1:NWV_PHMX)=MR_RURALC(1:NWV_PHMX,IRH)
       MRI2(1:NWV_PHMX)=MI_RURALC(1:NWV_PHMX,IRH)
  ELSEIF(IAEROSOL==2)THEN ! URBAN
       MRR1(1:NWV_PHMX)=MR_URBANF(1:NWV_PHMX,IRH)
       MRI1(1:NWV_PHMX)=MI_URBANF(1:NWV_PHMX,IRH)
       MRR2(1:NWV_PHMX)=MR_URBANC(1:NWV_PHMX,IRH)
       MRI2(1:NWV_PHMX)=MI_URBANC(1:NWV_PHMX,IRH)
  ELSEIF(IAEROSOL==3)THEN ! URBAN A
       MRR1(1:NWV_PHMX)=MR_URBANAF(1:NWV_PHMX,IRH)
       MRI1(1:NWV_PHMX)=MI_URBANAF(1:NWV_PHMX,IRH)
       MRR2(1:NWV_PHMX)=MR_URBANAC(1:NWV_PHMX,IRH)
       MRI2(1:NWV_PHMX)=MI_URBANAC(1:NWV_PHMX,IRH)
  ELSEIF(IAEROSOL==4)THEN  ! URBAN A1
       MRR1(1:NWV_PHMX)=MR_URBANA1F(1:NWV_PHMX,IRH)
       MRI1(1:NWV_PHMX)=MI_URBANA1F(1:NWV_PHMX,IRH)
       MRR2(1:NWV_PHMX)=MR_URBANA1C(1:NWV_PHMX,IRH)
       MRI2(1:NWV_PHMX)=MI_URBANA1C(1:NWV_PHMX,IRH)
    ELSEIF(IAEROSOL==5)THEN! URBAN A2
       MRR1(1:NWV_PHMX)=MR_URBANA2F(1:NWV_PHMX,IRH)
       MRI1(1:NWV_PHMX)=MI_URBANA2F(1:NWV_PHMX,IRH)
       MRR2(1:NWV_PHMX)=MR_URBANA2C(1:NWV_PHMX,IRH)
       MRI2(1:NWV_PHMX)=MI_URBANA2C(1:NWV_PHMX,IRH)
    ELSEIF(IAEROSOL==6)THEN! URBAN A3
       MRR1(1:NWV_PHMX)=MR_URBANA3F(1:NWV_PHMX,IRH)
       MRI1(1:NWV_PHMX)=MI_URBANA3F(1:NWV_PHMX,IRH)
       MRR2(1:NWV_PHMX)=MR_URBANA3C(1:NWV_PHMX,IRH)
       MRI2(1:NWV_PHMX)=MI_URBANA3C(1:NWV_PHMX,IRH)
    ELSEIF(IAEROSOL>=7 .AND. IAEROSOL<=9)THEN! MARINETIME
       MRR1(1:NWV_PHMX)=MR_TRPOSPHERE(1:NWV_PHMX,IRH)
       MRI1(1:NWV_PHMX)=MI_TRPOSPHERE(1:NWV_PHMX,IRH)
       MRR2(1:NWV_PHMX)=MR_OCEANIC(1:NWV_PHMX,IRH)
       MRI2(1:NWV_PHMX)=MI_OCEANIC(1:NWV_PHMX,IRH)
    ELSEIF(IAEROSOL==10)THEN
       MRR1(1:NWV_PHMX)=MR_TRPOSPHERE(1:NWV_PHMX,IRH)
       MRI1(1:NWV_PHMX)=MI_TRPOSPHERE(1:NWV_PHMX,IRH)
       MRR2(1:NWV_PHMX)=1.0
       MRI2(1:NWV_PHMX)=0.0
    ELSEIF(IAEROSOL==-1 .or. (IAEROSOL>10 .AND. IAEROSOL<=20))THEN
!       MRR1(1:NWV_PHMX)=MR_ZIAF(1:NWV_PHMX,IRH)
!       MRI1(1:NWV_PHMX)=MI_ZIAF(1:NWV_PHMX,IRH)
!       MRR2(1:NWV_PHMX)=MR_ZIAC(1:NWV_PHMX,IRH)
!       MRI2(1:NWV_PHMX)=MI_ZIAC(1:NWV_PHMX,IRH)
		XARRY=RH
		DO IWV_BAND=1,NWV_PHMX
			YARRY=MR_ZIAF(IWV_BAND,:)
			MRR1(IWV_BAND)=POLINT_SIMPLE(NRH,XARRY,YARRY,RH_simu,2)
			YARRY=MI_ZIAF(IWV_BAND,:)
			MRI1(IWV_BAND)=POLINT_SIMPLE(NRH,XARRY,YARRY,RH_simu,2)
			YARRY=MR_ZIAC(IWV_BAND,:)
			MRR2(IWV_BAND)=POLINT_SIMPLE(NRH,XARRY,YARRY,RH_simu,2)
			YARRY=MI_ZIAC(IWV_BAND,:)
			MRI2(IWV_BAND)=POLINT_SIMPLE(NRH,XARRY,YARRY,RH_simu,2)
		ENDDO
    ENDIF
! CONVERT TO EFFECT RADIUS AND VARIANCE BEFORE CALL SPHER_INTERFACE
    REFF1_LOCAL=REFF1
    VEFF1_LOCAL=VEFF1
    REFF2_LOCAL=REFF2
    VEFF2_LOCAL=VEFF2

    VEFF1_LOCAL=VEFF1_LOCAL*VEFF1_LOCAL
    VEFF2_LOCAL=VEFF2_LOCAL*VEFF2_LOCAL

    REFF1_LOCAL=REFF1_LOCAL*EXP(2.5D0*VEFF1_LOCAL)
    REFF2_LOCAL=REFF2_LOCAL*EXP(2.5D0*VEFF2_LOCAL)
    VEFF1_LOCAL=EXP(VEFF1_LOCAL)-1.0D0
    VEFF2_LOCAL=EXP(VEFF2_LOCAL)-1.0D0

! pass effective radius and variance back to main program for output
	REFF1=REFF1_LOCAL
	VEFF1=VEFF1_LOCAL
	REFF2=REFF2_LOCAL
	VEFF2=VEFF2_LOCAL


    CALL ARSL_INDX_DEALLO
    NDISTR=2
ELSEIF(FREEFORMFLAG==2)THEN
    NDISTR=7
    MRR1=PHYTOPLANKTON_INDEX_REFRACTION
    MRI1=0.0D0
    GAMMAI=PHYTOPLANKTON_SPECTRAL_SLOPE
ELSEIF(FREEFORMFLAG==3)THEN
    NDISTR=7
    MRR1=SEDIMENT_INDEX_REFRACTION
    MRI1=0.0D0
    GAMMAI=SEDIMENT_SPECTRAL_SLOPE
ELSE
    STOP 'FREEFORMFLAG VALUE NOT ASSIGNED'
ENDIF


DO IWV_BAND=1,NWV_PHMX

  CALL SPHER_INTERFACE(NDISTR,REFF1_LOCAL,VEFF1_LOCAL,WV_BAND_MICRON(IWV_BAND),&
                       MRR1(IWV_BAND),MRI1(IWV_BAND),AA1,BB1,AA2,BB2,GAMMAI,&
                       REFFO,VEFFO,AREA,CEXT1,CSCAT1,NANGMIE_LOCAL,PHMXMIE_LOCAL1,  &
					   NUMBETAL_LOCAL,COEFFMIE_LOCAL1)
  NUMBETAL(1:NUMMIEUSE)=NUMBETAL_LOCAL
  IF(ARSLND2>0.0D0 .AND. FREEFORMFLAG<=1)THEN
    CALL SPHER_INTERFACE(NDISTR,REFF2_LOCAL,VEFF2_LOCAL,WV_BAND_MICRON(IWV_BAND),&
                       MRR2(IWV_BAND),MRI2(IWV_BAND),AA1,BB1,AA2,BB2,GAMMAI,&
                       REFFO,VEFFO,AREA,CEXT2,CSCAT2,NANGMIE_LOCAL,PHMXMIE_LOCAL2,  &
					   NUMBETAL_LOCAL,COEFFMIE_LOCAL2)
  ELSE
      CEXT2=0.0D0
      CSCAT2=0.0D0
  ENDIF
  IF(MAXVAL(NUMBETAL)<NUMBETAL_LOCAL) NUMBETAL(1:NUMMIEUSE)=NUMBETAL_LOCAL

  IF(FREEFORMFLAG<=1)THEN
	  NUM_SCAT_ANG(1:NUMMIEUSE)=NANGMIE_LOCAL
	  CEXT_ARSL_BAND(1:NUMMIEUSE,IWV_BAND)=ARSLND1*CEXT1+ARSLND2*CEXT2
	  CSCAT_ARSL_BAND(1:NUMMIEUSE,IWV_BAND)=ARSLND1*CSCAT1+ARSLND2*CSCAT2
	  DO IMIE=1,NUMMIEUSE
		PHMXMIE_ARSL(IMIE,IWV_BAND,:,:)=(ARSLND1*CSCAT1*PHMXMIE_LOCAL1(:,:) + &
								ARSLND2*CSCAT2*PHMXMIE_LOCAL2(:,:))/ &
								CSCAT_ARSL_BAND(IMIE,IWV_BAND)

        COEFFMIE_ARSL(IMIE,IWV_BAND,:)=(ARSLND1*CSCAT1*COEFFMIE_LOCAL1(:,1) + &
					ARSLND2*CSCAT2*COEFFMIE_LOCAL2(:,1))/ &
					CSCAT_ARSL_BAND(IMIE,IWV_BAND)

	  ENDDO


  ELSEIF(FREEFORMFLAG==2)THEN
	  NUM_SCAT_ANG(3)=NANGMIE_LOCAL
	  CEXT_Plankton_BAND(IWV_BAND)=CEXT1
	  CSCAT_Plankton_BAND(IWV_BAND)=CSCAT1
	  PHMXMIE_Plankton_PACE(IWV_BAND,:,:)=PHMXMIE_LOCAL1(:,:)
	  CALL BBFRAC_CAL(NANGMIE_LOCAL,PHMXMIE_LOCAL1,BBFRAC_LOCAL)
	  BBFRAC_Plankton_BAND(IWV_BAND)=BBFRAC_LOCAL
  ELSEIF(FREEFORMFLAG==3)THEN
	  NUM_SCAT_ANG(4)=NANGMIE_LOCAL
	  REFF_MINERAL=REFFO
	  AREA_MINERAL=AREA
	  CEXT_Mineral_BAND(IWV_BAND)=CEXT1
	  CSCAT_Mineral_BAND(IWV_BAND)=CSCAT1
	  PHMXMIE_Mineral_PACE(IWV_BAND,:,:)=PHMXMIE_LOCAL1(:,:)
	  CALL BBFRAC_CAL(NANGMIE_LOCAL,PHMXMIE_LOCAL1,BBFRAC_LOCAL)
	  BBFRAC_Mineral_BAND(IWV_BAND)=BBFRAC_LOCAL
  ENDIF
ENDDO

END SUBROUTINE PHMXMIE_PACE_INIT

END MODULE

SUBROUTINE BBFRAC_CAL(NANGMIE_LOCAL,PHMXMIE_LOCAL1,BBFRAC_LOCAL)
USE RTUTILITY,ONLY : FACTOR,NUMMIEANGMAX
INTEGER,INTENT(IN) :: NANGMIE_LOCAL
REAL*8,DIMENSION(NUMMIEANGMAX,0:6),INTENT(IN)::PHMXMIE_LOCAL1
REAL*8,INTENT(OUT) :: BBFRAC_LOCAL

INTEGER,DIMENSION(1) ::LOCINDXTMP
INTEGER :: NSIZE
REAL*8, DIMENSION(:),ALLOCATABLE :: XARRAY,YARRAY
REAL*8 :: RTMP,RTMP1,TRAPZOID

ALLOCATE(XARRAY(NANGMIE_LOCAL),YARRAY(NANGMIE_LOCAL))
XARRAY(:)=PHMXMIE_LOCAL1(1:NANGMIE_LOCAL,0)
YARRAY(:)=PHMXMIE_LOCAL1(1:NANGMIE_LOCAL,1)
XARRAY=COS(XARRAY*FACTOR)
RTMP=TRAPZOID(NANGMIE_LOCAL,XARRAY,YARRAY)

LOCINDXTMP =MINLOC(ABS(90.0d0-PHMXMIE_LOCAL1(:,0)))
IF(LOCINDXTMP(1)==1 .OR. LOCINDXTMP(1)>=NANGMIE_LOCAL) STOP 'CHECK BBFRAC_CAL 1'
NSIZE=NANGMIE_LOCAL-LOCINDXTMP(1)+1
DEALLOCATE(XARRAY,YARRAY)

ALLOCATE(XARRAY(NSIZE),YARRAY(NSIZE))
XARRAY(:)=PHMXMIE_LOCAL1(LOCINDXTMP(1):NANGMIE_LOCAL,0)
YARRAY(:)=PHMXMIE_LOCAL1(LOCINDXTMP(1):NANGMIE_LOCAL,1)
XARRAY=COS(XARRAY*FACTOR)
IF(XARRAY(2)>0.0D0 .OR. XARRAY(NSIZE)>0.0D0)STOP 'CHECK BBFRAC_CAL 2'
RTMP1=TRAPZOID(NSIZE,XARRAY,YARRAY)
!WRITE(*,*)'PHASE FUCNTION, NORMALIZATION AND BACKSCATTERING FACTOR=',RTMP,RTMP1
!WRITE(*,*)'PHASE FUCNTION,Ang(90),Ang(180) =',PHMXMIE_LOCAL1(LOCINDXTMP,0),&
!                          PHMXMIE_LOCAL1(NANGMIE_LOCAL,0)
BBFRAC_LOCAL=RTMP1/RTMP
DEALLOCATE(XARRAY,YARRAY)

ENDSUBROUTINE BBFRAC_CAL

SUBROUTINE SPHER_INTERFACE(NDISTR,REFFI,VEFFI,LAM,MRR,MRI,AA1,BB1,AA2,BB2,GAMMAI,&
              REFFO,VEFFO,AREA,CEXT,CSCAT,NANGMIE_LOCAL,PHMXMIE_LOCAL,&
			  NUMBETAL_LOCAL,COEFFMIE_LOCAL)

USE RTUTILITY,ONLY : NUMMIEANGMAX,PI,MAXLFULL

IMPLICIT REAL*8 (A-H,O-Z)                           
INTEGER ::  NANGMIE_LOCAL,NUMBETAL_LOCAL
REAL*8,DIMENSION(NUMMIEANGMAX,0:6)::PHMXMIE_LOCAL
REAL*8,DIMENSION(0:MAXLFULL,1:6)::COEFFMIE_LOCAL

INTEGER,PARAMETER:: NMIE=10000, NPL=2*NMIE
INTEGER NDISTR,LMAXI,IL
REAL*8 REFFI,VEFFI,LAM,MRR,MRI,AA1,BB1,AA2,BB2,GAMMAI,REFFO,VEFFO,AREA,CEXT,CSCAT
REAL*8 AL1(NPL),AL2(NPL),AL3(NPL),AL4(NPL),BET1(NPL),BET2(NPL)

!      CHARACTER*40 :: CFILE1,CHARTMP
!      open (6, file='spher.coeff')
!      AA=0.6D0
!      BB=0.2 D0
!      AA1=0.17D0
!      AA2=3.44D0
!      BB1=DLOG(1.96D0)*DLOG(1.96D0)
!      BB2=DLOG(2.37D0)*DLOG(2.37D0)
!      GAM=1D0                                                               
!      LAM=0.63D0                                            
!      MRR=1.53 D0                                               
!      MRI=0.008 D0                                            
!      NDISTR=3
!      NK=100
!      N=100
!      NP=4
      R1=0.0D0
      R2=20.0D0    

       IF(NDISTR==1) THEN
!     NDISTR = 1 - modified gamma distribution                         
!          [Eq. (5.242) of Ref. 1]                                        
!              AA=alpha                                                
!              BB=r_c                                                  
!              GAM=gamma                                               

            AA=GAMMAI-1
            BB=AA*REFFI/(GAMMAI+2.0D0)
            GAM=1.0D0
            
       ELSE IF(NDISTR==2) THEN
!C     NDISTR = 2 - log normal distribution                             
!C          [Eq. (5.243) of Ref. 1]                                        
!C              AA=r_g                                                  
!C              BB=[ln(sigma_g)]**2                                      
            BB=log(VEFFI+1.0D0)
            AA=REFFI*EXP(-2.5d0*BB)

       ELSE IF(NDISTR==3) THEN
!C     NDISTR = 3 - power law distribution                              
!C          [Eq. (5.244) of Ref. 1]                                        
!C               AA=r_eff (effective radius)                            
!C               BB=v_eff (effective variance)                          
!C               Parameters R1 and R2 (see below) are calculated        
!C               automatically for given AA and BB                      
                AA=REFFI
                BB=VEFFI

       ELSE IF(NDISTR==4) THEN
!C     NDISTR = 4 - gamma distribution                                  
!C          [Eq. (5.245) of Ref. 1]                                        
!C               AA=a                                                   
!C               BB=b      
!http://www.ess.uci.edu/~cmclinden/link/xx/node22.html
!HANSEN AND TRAVIS 1974 EQ. 2.56
                AA=REFFI  
                BB=VEFFI
                                                     
       ELSE IF(NDISTR==5) THEN
!C     NDISTR = 5 - modified power law distribution                     
!C          [Eq. (5.246) of Ref. 1]                                        
!C              BB=alpha          
               BB=GAMMAI
       ELSE IF(NDISTR==6) THEN
!C     NDISTR = 6 - bimodal volume log normal distribution              
!C              [Eq. (5.247) of Ref. 1]             
!C              AA1=r_g1                                                
!C              BB1=[ln(sigma_g1)]**2                                   
!C              AA2=r_g2                                                
!C              BB2=[ln(sigma_g2)]**2                                   
!C              GAM=gamma                                               
               GAM=GAMMAI
!C
       ELSE IF(NDISTR==7) THEN
!C    Added by Zhai, Pengwang Oct. 29 2008
!C     NDISTR = 7 - Junge distribution                              
!C          [n(r)=Constant*r^{-s}; s=4]
!C               Parameters R1 and R2 (see below)
!C               BB=JUNGE EXPONENTIAL FACTOR s                           
                BB=GAMMAI
                R1=0.1D0
                R2=50.0D0
       ELSE
          STOP 'NDISTR<1 OR > 7'
       ENDIF
       NK=20
       N=100
       NP=4
       WVNM=LAM*1000
       DDELT=1D-7

      CALL SPHER (AA,BB,GAM,LAM,MRR,MRI,R1,R2,N,NP,NDISTR,             &
            NK,L1,AL1,AL2,AL3,AL4,BET1,BET2,CEXT,CSCAT,AREA,VOL,RVW,  &
            RMEAN,REFFO,VEFFO,AA1,BB1,AA2,BB2,DDELT)
      QE=CEXT/AREA
      LMAX=L1-1

      LMAXI=LMAX
	  IF (LMAX>MAXLFULL) THEN
			 WRITE(*,*)'MAXLFULL,LMAX=',MAXLFULL,LMAX
			 STOP 'LMAX>MAXLFULL, INCREASE MAXLFULL AND RECOMPILE THE CODE'
	  ENDIF
	  COEFFMIE_LOCAL=0.0D0
	  NUMBETAL_LOCAL=LMAX+1
	  COEFFMIE_LOCAL(0:LMAX,1)=AL1(1:LMAX+1)
	  COEFFMIE_LOCAL(0:LMAX,2)=AL2(1:LMAX+1)
	  COEFFMIE_LOCAL(0:LMAX,3)=AL3(1:LMAX+1)
	  COEFFMIE_LOCAL(0:LMAX,4)=AL4(1:LMAX+1)
	  COEFFMIE_LOCAL(0:LMAX,5)=BET1(1:LMAX+1)
	  COEFFMIE_LOCAL(0:LMAX,6)=BET2(1:LMAX+1)

      CALL MATR (AL1,AL2,AL3,AL4,BET1,BET2,LMAX,NUMMIEANGMAX,NANGMIE_LOCAL,PHMXMIE_LOCAL)
      

!      WRITE (*,1001) AREA,VOL,RVW,RMEAN
! 1001 FORMAT ('<G> = ',D12.6,'  <V> = ',D12.6,'  Rvw = ',D12.6,&
!             &'  <R> = ',D12.6)
!write(*,*)'testing'
!  DO INTTMP=1,LMAXI+1
!      write(*,*)AL1(INTTMP),AL2(INTTMP),AL3(INTTMP),AL4(INTTMP),&
!             BET1(INTTMP),BET2(INTTMP)
!  ENDDO
!write(*,*)'testing over'
  
      RETURN
      END SUBROUTINE SPHER_INTERFACE
