MODULE PACE_INSTRUMENT_DESIGN
USE HDF5
USE MAP_INSTRUMENT_DESIGN
INTEGER,PARAMETER :: NWV_BAND_SEG1=282, NWV_BAND_SEG2=9,&
                     NWV_BAND_SEG1P2=291,NWV_BAND_SEG3=50,&
                     NWV_BAND_BLUE=119,NWV_BAND_RED=163

! NWV_BAND_SEG1: OCI UV+Visible+NIR
! NWV_BAND_SEG2: OCI SWIR, 9 bands including two 1250 nm and two 1620 nm bands
! NWV_BAND_SEG3: SPEXone
! NWV_BAND_SEG4: HARP-2 or other MAP with discrete wavelengths
!
!REAL*8,PARAMETER :: WV_START=340D0 !,WV_END=1000.D0
INTEGER :: NWV_BAND
REAL*8,DIMENSION(:),ALLOCATABLE :: WV_BAND,PACE_FWHM

REAL*8,PARAMETER :: OCI_SEG1_RESO_HYPO=5.0D0
!REAL*8,DIMENSION(NWV_BAND_HYPO):: WV_BAND_HYPO,PACE_FWHM_HYPO=0.0d0
!INTEGER,PARAMETER :: NWV_BAND_HYPO=239,NWV_BAND_SEG1_HYPO=119, &
!					 NWV_BAND_SEG1P2_HYPO=126
INTEGER :: NWV_BAND_HYPO,NWV_BAND_SEG1_HYPO,NWV_BAND_SEG2_HYPO, &
		   NWV_BAND_SEG1P2_HYPO
REAL*8,DIMENSION(:),ALLOCATABLE :: WV_BAND_HYPO,PACE_FWHM_HYPO

INTEGER,PARAMETER :: NILS_PACE_RAW=20926,NILS_SPEXone=2001,NILS_HARP=163,NILS_HARP2_HEADER=18
REAL*8,DIMENSION(:),ALLOCATABLE :: ILS_WaveLength
REAL*8,DIMENSION(:,:),ALLOCATABLE :: ILS_DeltaWaveLength_RAW,ILS_PACE_RAW

INTEGER :: NILS_PACE
REAL*8,DIMENSION(:,:),ALLOCATABLE :: ILS_DeltaWaveLength,ILS_PACE
REAL*8,DIMENSION(25) :: RARR_TMP

LOGICAL :: HARP2_READIN_FLAG

CONTAINS

SUBROUTINE WV_PACE_SETUP(aux_dir)
IMPLICIT NONE
INTEGER IWV,ILS_LINE,ILS_LINE_TEMP,NILS_MIN,NILS_MAX,IMIRROR
REAL*8 Delta_Wavelength_Max,Delta_Wavelength_Sub,Factor,RTMP

! HDF 5 DEFINITION
! This should map to REAL*8 on most modern processors
!INTEGER, PARAMETER :: real_kind_15 = SELECTED_REAL_KIND(Fortran_REAL_8)
CHARACTER(LEN=360),intent(in) :: aux_dir

CHARACTER(LEN=360) :: OCI_ILS_Filename,SPEXone_ILS_Filename,HARP2_ILS_Filename


INTEGER(HID_T)  :: file, space, dset, attr ! Handles
INTEGER :: hdferr
INTEGER(hsize_t),   DIMENSION(1:2) :: dims
INTEGER(hsize_t),DIMENSION(1) :: dimscl
INTEGER(HSIZE_T), DIMENSION(1:2) :: maxdims
TYPE(C_PTR) :: f_ptr
REAL*4,DIMENSION(1),TARGET :: HDF5RTMP
INTEGER,DIMENSION(1),TARGET :: HDF5ITMP
REAL*4,DIMENSION(:),TARGET,ALLOCATABLE :: HDF5RARRD1
REAL*4,DIMENSION(:,:),TARGET,ALLOCATABLE :: HDF5RARR2DIM
REAL*4,DIMENSION(:,:,:),TARGET,ALLOCATABLE :: HDF5RARR3DIM

REAL*8,DIMENSION(:),TARGET,ALLOCATABLE :: HDF5RARR_DB1
REAL*8,DIMENSION(:,:),TARGET,ALLOCATABLE :: HDF5RARR_DB2DIM

IMIRROR=1

NWV_BAND = NWV_BAND_SEG1+NWV_BAND_SEG2+NWV_BAND_SEG3+NWV_BAND_SEG4

IF(NWV_BAND_SEG2 /= 9)STOP 'CHECK NWV AND NWV_SEG2'
IF(NWV_BAND_SEG1P2 /= NWV_BAND_SEG1+NWV_BAND_SEG2) STOP 'CHECK NWV_BAND_SEG1P2'

ALLOCATE(WV_BAND(NWV_BAND),PACE_FWHM(NWV_BAND))
PACE_FWHM=0.0D0

ALLOCATE(ILS_WaveLength(NILS_PACE_RAW), &
         ILS_DeltaWaveLength_RAW(NWV_BAND,NILS_PACE_RAW), &
         ILS_PACE_RAW(NWV_BAND,NILS_PACE_RAW))

!OCI_ILS_Filename=trim(aux_dir)//'/OCI_RSR_2.5nm_v7_convert2.h5'
OCI_ILS_Filename=trim(aux_dir)//'PACE_OCI_L1B_LUT_RSR_baseline_1.1.1.nc'
SPEXone_ILS_Filename=trim(aux_dir)//'spexone_isrf.nc'
HARP2_ILS_Filename=trim(aux_dir)//'HARP2_RSR_Composite_v01b.csv'

CALL h5open_f(hdferr)
CALL h5fopen_f(OCI_ILS_Filename, H5F_ACC_RDONLY_F, file, hdferr)

ALLOCATE(HDF5RARR2DIM(2,NWV_BAND_BLUE))
CALL h5dopen_f (file, '/blue/bandwidth', dset, hdferr)
CALL h5dget_space_f(dset,space, hdferr)
f_ptr = C_LOC(HDF5RARR2DIM(1,1))
CALL h5dread_f( dset, H5T_NATIVE_REAL,f_ptr, hdferr)
CALL h5dclose_f(dset , hdferr)
CALL h5sclose_f(space, hdferr)
PACE_FWHM(1:NWV_BAND_BLUE)=HDF5RARR2DIM(IMIRROR,1:NWV_BAND_BLUE)
!DEALLOCATE(HDF5RARR2DIM)

!ALLOCATE(HDF5RARR2DIM(2,NWV_BAND_BLUE))
CALL h5dopen_f (file, '/blue/center_wavelength', dset, hdferr)
CALL h5dget_space_f(dset,space, hdferr)
f_ptr = C_LOC(HDF5RARR2DIM(1,1))
CALL h5dread_f( dset, H5T_NATIVE_REAL,f_ptr, hdferr)
CALL h5dclose_f(dset , hdferr)
CALL h5sclose_f(space, hdferr)
WV_BAND(1:NWV_BAND_BLUE)=HDF5RARR2DIM(IMIRROR,1:NWV_BAND_BLUE)
DEALLOCATE(HDF5RARR2DIM)

ALLOCATE(HDF5RARR2DIM(2,NWV_BAND_RED))
CALL h5dopen_f (file, '/red/bandwidth', dset, hdferr)
CALL h5dget_space_f(dset,space, hdferr)
f_ptr = C_LOC(HDF5RARR2DIM(1,1))
CALL h5dread_f( dset, H5T_NATIVE_REAL,f_ptr, hdferr)
CALL h5dclose_f(dset , hdferr)
CALL h5sclose_f(space, hdferr)
PACE_FWHM(NWV_BAND_BLUE+1:NWV_BAND_SEG1)=HDF5RARR2DIM(IMIRROR,1:NWV_BAND_RED)
!DEALLOCATE(HDF5RARR2DIM)

!ALLOCATE(HDF5RARR2DIM(2,NWV_BAND_RED))
CALL h5dopen_f (file, '/red/center_wavelength', dset, hdferr)
CALL h5dget_space_f(dset,space, hdferr)
f_ptr = C_LOC(HDF5RARR2DIM(1,1))
CALL h5dread_f( dset, H5T_NATIVE_REAL,f_ptr, hdferr)
CALL h5dclose_f(dset , hdferr)
CALL h5sclose_f(space, hdferr)
WV_BAND(NWV_BAND_BLUE+1:NWV_BAND_SEG1)=HDF5RARR2DIM(IMIRROR,1:NWV_BAND_RED)
DEALLOCATE(HDF5RARR2DIM)

!WRITE(*,*)'TESTING, WV_BAND(1),WV_BAND(NWV_BAND_BLUE)=',WV_BAND(1),WV_BAND(NWV_BAND_BLUE)
!WRITE(*,*)'TESTING, WV_BAND(NWV_BAND_BLUE+1),WV_BAND(NWV_BAND_SEG1)=',WV_BAND(NWV_BAND_BLUE+1),WV_BAND(NWV_BAND_SEG1)
!WRITE(*,*)'TESTING, BANDWIDTH(1),BANDWIDTH(NWV_BAND_BLUE)=',PACE_FWHM(1),PACE_FWHM(NWV_BAND_BLUE)
!WRITE(*,*)'TESTING, BANDWIDTH(NWV_BAND_BLUE+1),BANDWIDTH(282)=',PACE_FWHM(NWV_BAND_BLUE+1),PACE_FWHM(282)

ALLOCATE(HDF5RARR2DIM(2,9))
CALL h5dopen_f (file, '/SWIR/bandwidth', dset, hdferr)
CALL h5dget_space_f(dset,space, hdferr)
f_ptr = C_LOC(HDF5RARR2DIM(1,1))
CALL h5dread_f( dset, H5T_NATIVE_REAL,f_ptr, hdferr)
CALL h5dclose_f(dset , hdferr)
CALL h5sclose_f(space, hdferr)
PACE_FWHM(NWV_BAND_SEG1+1:NWV_BAND_SEG1P2)=HDF5RARR2DIM(IMIRROR,1:9)
!DEALLOCATE(HDF5RARR2DIM)

!ALLOCATE(HDF5RARR2DIM(2,9))
CALL h5dopen_f (file, '/SWIR/center_wavelength', dset, hdferr)
CALL h5dget_space_f(dset,space, hdferr)
f_ptr = C_LOC(HDF5RARR2DIM(1,1))
CALL h5dread_f( dset, H5T_NATIVE_REAL,f_ptr, hdferr)
CALL h5dclose_f(dset , hdferr)
CALL h5sclose_f(space, hdferr)
WV_BAND(NWV_BAND_SEG1+1:NWV_BAND_SEG1P2)=HDF5RARR2DIM(IMIRROR,1:9)
DEALLOCATE(HDF5RARR2DIM)


ALLOCATE(HDF5RARRD1(NILS_PACE_RAW))
CALL h5dopen_f (file, '/blue/sampled_wavelength', dset, hdferr)
CALL h5dget_space_f(dset,space, hdferr)
f_ptr = C_LOC(HDF5RARRD1(1))
CALL h5dread_f( dset, H5T_NATIVE_REAL,f_ptr, hdferr)
CALL h5dclose_f(dset , hdferr)
CALL h5sclose_f(space, hdferr)
ILS_WaveLength=HDF5RARRD1
DEALLOCATE(HDF5RARRD1)

!WRITE(*,*)'TESTING, ILS_WaveLength(1),ILS_WaveLength(NILS_PACE_RAW)=', &
!          ILS_WaveLength(1),ILS_WaveLength(NILS_PACE_RAW)

ALLOCATE(HDF5RARR3DIM(2,NILS_PACE_RAW,NWV_BAND_BLUE))
CALL h5dopen_f (file, '/blue/RSR', dset, hdferr)
CALL h5dget_space_f(dset,space, hdferr)
f_ptr = C_LOC(HDF5RARR3DIM(1,1,1))
CALL h5dread_f( dset, H5T_NATIVE_REAL,f_ptr, hdferr)
CALL h5dclose_f(dset , hdferr)
CALL h5sclose_f(space, hdferr)
DO IWV=1,NWV_BAND_BLUE
  ILS_PACE_RAW(IWV,1:NILS_PACE_RAW)=HDF5RARR3DIM(IMIRROR,1:NILS_PACE_RAW,IWV)
ENDDO
DEALLOCATE(HDF5RARR3DIM)

!WRITE(*,*)'TESTING blue, ILS_PACE_RAW(1,1),ILS_PACE_RAW(NWV_BAND_BLUE,NILS_PACE_RAW)=', &
!           ILS_PACE_RAW(1,1),ILS_PACE_RAW(NWV_BAND_BLUE,NILS_PACE_RAW)

ALLOCATE(HDF5RARR3DIM(2,NILS_PACE_RAW,NWV_BAND_RED))
CALL h5dopen_f (file, '/red/RSR', dset, hdferr)
CALL h5dget_space_f(dset,space, hdferr)
f_ptr = C_LOC(HDF5RARR3DIM(1,1,1))
CALL h5dread_f( dset, H5T_NATIVE_REAL,f_ptr, hdferr)
CALL h5dclose_f(dset , hdferr)
CALL h5sclose_f(space, hdferr)
DO IWV=1,NWV_BAND_RED
  ILS_PACE_RAW(NWV_BAND_BLUE+IWV,1:NILS_PACE_RAW)=HDF5RARR3DIM(IMIRROR,1:NILS_PACE_RAW,IWV)
ENDDO
DEALLOCATE(HDF5RARR3DIM)

ALLOCATE(HDF5RARR3DIM(2,NILS_PACE_RAW,9))
CALL h5dopen_f (file, '/SWIR/RSR', dset, hdferr)
CALL h5dget_space_f(dset,space, hdferr)
f_ptr = C_LOC(HDF5RARR3DIM(1,1,1))
CALL h5dread_f( dset, H5T_NATIVE_REAL,f_ptr, hdferr)
CALL h5dclose_f(dset , hdferr)
CALL h5sclose_f(space, hdferr)
DO IWV=1,9
  ILS_PACE_RAW(NWV_BAND_SEG1+IWV,1:NILS_PACE_RAW)=HDF5RARR3DIM(IMIRROR,1:NILS_PACE_RAW,IWV)
ENDDO
DEALLOCATE(HDF5RARR3DIM)

CALL h5fclose_f(file , hdferr)
CALL h5close_f(hdferr)

!WRITE(*,*)'TESTING SWIR, ILS_PACE_RAW(NWV_BAND_SEG1+1,1),ILS_PACE_RAW(NWV_BAND_SEG1+9,1)=', &
!           ILS_PACE_RAW(NWV_BAND_SEG1+1,1),ILS_PACE_RAW(NWV_BAND_SEG1+9,1)
!WRITE(*,*)'TESTING SWIR, ILS_PACE_RAW(NWV_BAND_SEG1+1,NILS_PACE_RAW),ILS_PACE_RAW(NWV_BAND_SEG1+9,NILS_PACE_RAW)=', &
!           ILS_PACE_RAW(NWV_BAND_SEG1+1,NILS_PACE_RAW),ILS_PACE_RAW(NWV_BAND_SEG1+9,NILS_PACE_RAW)


NILS_PACE=0
ILS_DeltaWaveLength_RAW=0.0d0
DO IWV=1,NWV_BAND_SEG1P2
NILS_MAX=0
DO ILS_LINE=1,NILS_PACE_RAW
   ILS_DeltaWaveLength_RAW(IWV,ILS_LINE)=ILS_WaveLength(ILS_LINE)-WV_BAND(IWV)
   IF(ILS_PACE_RAW(IWV,ILS_LINE)>1.0e-5) NILS_MAX=NILS_MAX+1
ENDDO
IF(NILS_MAX>NILS_PACE)NILS_PACE=NILS_MAX
ENDDO
WRITE(*,*)'NILS_PACE=',NILS_PACE

ALLOCATE(ILS_DeltaWaveLength(NWV_BAND,NILS_PACE),ILS_PACE(NWV_BAND,NILS_PACE))
ILS_DeltaWaveLength=0.0d0
ILS_PACE=0.0d0
DO IWV=1,NWV_BAND_SEG1P2
	DO ILS_LINE=1,NILS_PACE_RAW
	   IF(ILS_PACE_RAW(IWV,ILS_LINE)>1.0e-5) EXIT
	ENDDO
	NILS_MAX=MIN(NILS_PACE_RAW,ILS_LINE+NILS_PACE-1)
	NILS_MIN=ILS_LINE

	ILS_LINE_TEMP=0
	DO ILS_LINE=NILS_MIN,NILS_MAX
	  ILS_LINE_TEMP=ILS_LINE_TEMP+1
	  ILS_DeltaWaveLength(IWV,ILS_LINE_TEMP) = ILS_DeltaWaveLength_RAW(IWV,ILS_LINE)
	  ILS_PACE(IWV,ILS_LINE_TEMP)=ILS_PACE_RAW(IWV,ILS_LINE)
	ENDDO

ENDDO
!write(*,*)'ILS_DeltaWaveLength(1,:)=',ILS_DeltaWaveLength(1,:)
!write(*,*)'ILS_PACE(1,:)=',ILS_PACE(1,:)

CALL h5open_f(hdferr)
CALL h5fopen_f(SPEXone_ILS_Filename, H5F_ACC_RDONLY_F, file, hdferr)

ALLOCATE(HDF5RARR_DB1(NWV_BAND_SEG3))
CALL h5dopen_f (file, '/wavelength', dset, hdferr)
CALL h5dget_space_f(dset,space, hdferr)
f_ptr = C_LOC(HDF5RARR_DB1(1))
CALL h5dread_f( dset, H5T_NATIVE_DOUBLE,f_ptr, hdferr)
CALL h5dclose_f(dset , hdferr)
CALL h5sclose_f(space, hdferr)
WV_BAND(NWV_BAND_SEG1P2+1:NWV_BAND_SEG1P2+NWV_BAND_SEG3)=HDF5RARR_DB1(1:NWV_BAND_SEG3)
DEALLOCATE(HDF5RARR_DB1)

ALLOCATE(HDF5RARR_DB1(NILS_SPEXone))
CALL h5dopen_f (file, '/delta_wavelength', dset, hdferr)
CALL h5dget_space_f(dset,space, hdferr)
f_ptr = C_LOC(HDF5RARR_DB1(1))
CALL h5dread_f( dset, H5T_NATIVE_DOUBLE,f_ptr, hdferr)
CALL h5dclose_f(dset , hdferr)
CALL h5sclose_f(space, hdferr)

ALLOCATE(HDF5RARR_DB2DIM(NILS_SPEXone,NWV_BAND_SEG3))
CALL h5dopen_f (file, '/isrf', dset, hdferr)
CALL h5dget_space_f(dset,space, hdferr)
f_ptr = C_LOC(HDF5RARR_DB2DIM(1,1))
CALL h5dread_f( dset, H5T_NATIVE_DOUBLE,f_ptr, hdferr)
CALL h5dclose_f(dset , hdferr)
CALL h5sclose_f(space, hdferr)

CALL h5fclose_f(file , hdferr)
CALL h5close_f(hdferr)

DO IWV=NWV_BAND_SEG1P2+1,NWV_BAND_SEG1P2+NWV_BAND_SEG3
    DO ILS_LINE=1,NILS_SPEXone
	   ILS_DeltaWaveLength(IWV,ILS_LINE)=HDF5RARR_DB1(ILS_LINE)
	   ILS_PACE(IWV,ILS_LINE)=HDF5RARR_DB2DIM(ILS_LINE,IWV-NWV_BAND_SEG1P2)
	ENDDO
ENDDO
DEALLOCATE(HDF5RARR_DB1,HDF5RARR_DB2DIM)

DO IWV=NWV_BAND_SEG1P2+1,NWV_BAND_SEG1P2+NWV_BAND_SEG3
   PACE_FWHM(IWV)=5.0d0
ENDDO

!write(*,*)'ILS_DeltaWaveLength(NWV_BAND_SEG1P2+1,1:2)=',ILS_DeltaWaveLength(NWV_BAND_SEG1P2+1,1:2)
!write(*,*)'ILS_PACE(NWV_BAND_SEG1P2+1,1:2)=',ILS_PACE(NWV_BAND_SEG1P2+1,1:2)
!write(*,*)'ILS_DeltaWaveLength(NWV_BAND_SEG1P2+NWV_BAND_SEG3,1:2)=',ILS_DeltaWaveLength(NWV_BAND_SEG1P2+NWV_BAND_SEG3,1:2)
!write(*,*)'ILS_PACE(NWV_BAND_SEG1P2+NWV_BAND_SEG3,1:2)=',ILS_PACE(NWV_BAND_SEG1P2+NWV_BAND_SEG3,1:2)

! HARP2 FWHM AND WAVELENGTH
PACE_FWHM(NWV_BAND_SEG1P2+NWV_BAND_SEG3+1:NWV_BAND)=PACE_FWHM_SEG4(1:NWV_BAND_SEG4)
WV_BAND(NWV_BAND_SEG1P2+NWV_BAND_SEG3+1:NWV_BAND)= WV_BAND_SEG4(1:NWV_BAND_SEG4)

HARP2_READIN_FLAG=.FALSE.

IF(NWV_BAND_SEG4==4)THEN
     RTMP=ABS(WV_BAND_SEG4(1)-440.159D0)+ABS(WV_BAND_SEG4(2)-549.465D0) &
         +ABS(WV_BAND_SEG4(3)-664.564D0)+ABS(WV_BAND_SEG4(4)-865.283D0)
     IF(RTMP<1.0D-4) HARP2_READIN_FLAG=.TRUE.
ENDIF

IF(HARP2_READIN_FLAG)THEN
	OPEN(UNIT=1,FILE=HARP2_ILS_Filename,STATUS='OLD',ACTION='READ')

	DO ILS_LINE=1,NILS_HARP2_HEADER
	   READ(1,*)
	ENDDO

	DO ILS_LINE=1,NILS_HARP
	   READ(1,*)RARR_TMP(1:10)
       DO ILS_LINE_TEMP=2,10
          IF(RARR_TMP(ILS_LINE_TEMP)<0.0d0)RARR_TMP(ILS_LINE_TEMP)=0.0d0
       ENDDO

	   ILS_DeltaWaveLength(NWV_BAND_SEG1P2+NWV_BAND_SEG3+1,ILS_LINE)=RARR_TMP(1)-WV_BAND_SEG4(1)
	   ILS_PACE(NWV_BAND_SEG1P2+NWV_BAND_SEG3+1,ILS_LINE)=RARR_TMP(2)

	   ILS_DeltaWaveLength(NWV_BAND_SEG1P2+NWV_BAND_SEG3+2,ILS_LINE)=RARR_TMP(1)-WV_BAND_SEG4(2)
	   ILS_PACE(NWV_BAND_SEG1P2+NWV_BAND_SEG3+2,ILS_LINE)=RARR_TMP(4)

       ILS_DeltaWaveLength(NWV_BAND_SEG1P2+NWV_BAND_SEG3+3,ILS_LINE)=RARR_TMP(1)-WV_BAND_SEG4(3)
	   ILS_PACE(NWV_BAND_SEG1P2+NWV_BAND_SEG3+3,ILS_LINE)=RARR_TMP(6)

       ILS_DeltaWaveLength(NWV_BAND_SEG1P2+NWV_BAND_SEG3+4,ILS_LINE)=RARR_TMP(1)-WV_BAND_SEG4(4)
	   ILS_PACE(NWV_BAND_SEG1P2+NWV_BAND_SEG3+4,ILS_LINE)=RARR_TMP(8)
	ENDDO

!write(*,*)'ILS_DeltaWaveLength(NWV_BAND_SEG1P2+NWV_BAND_SEG3+1,1:2)=',ILS_DeltaWaveLength(NWV_BAND_SEG1P2+NWV_BAND_SEG3+1,1:2)
!write(*,*)'ILS_PACE(NWV_BAND_SEG1P2+NWV_BAND_SEG3+1,1:2)=',ILS_PACE(NWV_BAND_SEG1P2+NWV_BAND_SEG3+1,1:2)
!write(*,*)'ILS_DeltaWaveLength(NWV_BAND_SEG1P2+NWV_BAND_SEG3+4,NILS_HARP-1:NILS_HARP)=',ILS_DeltaWaveLength(NWV_BAND_SEG1P2+NWV_BAND_SEG3+4,NILS_HARP-1:NILS_HARP)
!write(*,*)'ILS_PACE(NWV_BAND_SEG1P2+NWV_BAND_SEG3+4,NILS_HARP-1:NILS_HARP)=',ILS_PACE(NWV_BAND_SEG1P2+NWV_BAND_SEG3+4,NILS_HARP-1:NILS_HARP)

ELSE
	DO IWV=NWV_BAND_SEG1P2+NWV_BAND_SEG3+1,NWV_BAND
		Delta_Wavelength_Max=2.0d0*PACE_FWHM(IWV)
		Delta_Wavelength_Sub=Delta_Wavelength_Max/(1.0d0*NILS_HARP)
		Factor=4.0D0*log(2.0D0)/(PACE_FWHM(IWV)**2)

		DO ILS_LINE=1,NILS_HARP
		   ILS_DeltaWaveLength(IWV,ILS_LINE)=(ILS_LINE-NILS_HARP/2)*Delta_Wavelength_Sub
		   ILS_PACE(IWV,ILS_LINE)=exp(-Factor*(ILS_DeltaWaveLength(IWV,ILS_LINE)**2));
		ENDDO
	ENDDO

	! SETTING HARP FWHM AS A BOXCAR TYPE UNTIL DETAILED ILS AVAILABLE
	DO IWV=NWV_BAND_SEG1P2+NWV_BAND_SEG3+1,NWV_BAND
	DO ILS_LINE=1,NILS_HARP
	   IF(ABS(ILS_DeltaWaveLength(IWV,ILS_LINE))>PACE_FWHM(IWV)/2)THEN
		  ILS_PACE(IWV,ILS_LINE)=0.0D0
	   ELSE
		  ILS_PACE(IWV,ILS_LINE)=1.0D0
	   ENDIF
	ENDDO
	ENDDO
ENDIF
!! SETUP HYPOTHETICAL WAVELENGTH BANDS
NWV_BAND_SEG1_HYPO=(WV_BAND(NWV_BAND_SEG1)-WV_BAND(1))/OCI_SEG1_RESO_HYPO+2
NWV_BAND_SEG2_HYPO=NWV_BAND_SEG2 - 2
NWV_BAND_SEG1P2_HYPO=NWV_BAND_SEG1_HYPO + NWV_BAND_SEG2_HYPO
NWV_BAND_HYPO=NWV_BAND_SEG1P2_HYPO+NWV_BAND-NWV_BAND_SEG1P2
ALLOCATE(WV_BAND_HYPO(NWV_BAND_HYPO),PACE_FWHM_HYPO(NWV_BAND_HYPO))
PACE_FWHM_HYPO=0.0D0

DO IWV=1,NWV_BAND_SEG1_HYPO
   WV_BAND_HYPO(IWV)=WV_BAND(1)+(IWV-1)*OCI_SEG1_RESO_HYPO
   PACE_FWHM_HYPO(IWV)=OCI_SEG1_RESO_HYPO
ENDDO

WV_BAND_HYPO(NWV_BAND_SEG1_HYPO+1:NWV_BAND_SEG1_HYPO+3) = &
          WV_BAND(NWV_BAND_SEG1+1:NWV_BAND_SEG1+3)
PACE_FWHM_HYPO(NWV_BAND_SEG1_HYPO+1:NWV_BAND_SEG1_HYPO+3) = &
          PACE_FWHM(NWV_BAND_SEG1+1:NWV_BAND_SEG1+3)

WV_BAND_HYPO(NWV_BAND_SEG1_HYPO+4:NWV_BAND_SEG1_HYPO+5) = &
		  WV_BAND(NWV_BAND_SEG1+5:NWV_BAND_SEG1+6)
PACE_FWHM_HYPO(NWV_BAND_SEG1_HYPO+4:NWV_BAND_SEG1_HYPO+5) = &
		  PACE_FWHM(NWV_BAND_SEG1+5:NWV_BAND_SEG1+6)

WV_BAND_HYPO(NWV_BAND_SEG1_HYPO+6:NWV_BAND_SEG1_HYPO+7) = &
		  WV_BAND(NWV_BAND_SEG1+8:NWV_BAND_SEG1+9)
PACE_FWHM_HYPO(NWV_BAND_SEG1_HYPO+6:NWV_BAND_SEG1_HYPO+7) = &
		  PACE_FWHM(NWV_BAND_SEG1+8:NWV_BAND_SEG1+9)

DO IWV=NWV_BAND_SEG1P2_HYPO+1,NWV_BAND_HYPO
   WV_BAND_HYPO(IWV)=WV_BAND(IWV-NWV_BAND_SEG1P2_HYPO+NWV_BAND_SEG1P2)
   PACE_FWHM_HYPO(IWV)=PACE_FWHM(IWV-NWV_BAND_SEG1P2_HYPO+NWV_BAND_SEG1P2)
ENDDO

DEALLOCATE(ILS_WaveLength,ILS_DeltaWaveLength_RAW,ILS_PACE_RAW)

END SUBROUTINE WV_PACE_SETUP

SUBROUTINE PACE_FWHM_DEALLO
   DEALLOCATE(ILS_DeltaWaveLength,ILS_PACE,WV_BAND_HYPO,PACE_FWHM_HYPO)
   DEALLOCATE(WV_BAND,PACE_FWHM)
END SUBROUTINE PACE_FWHM_DEALLO

END MODULE PACE_INSTRUMENT_DESIGN
