!This version is developed to handle three aerosol modes as well (fine, coarse,dust)
MODULE MIE_PHMX_CAL
USE PACE_INSTRUMENT_DESIGN,ONLY : NWV_BAND,WV_BAND
USE AEROSOL_MICROPHYSICAL_MODEL
!USE RTUTILITY, ONLY : PI,FACTOR,NUMMIEANGMAX
USE DUST_DATA

INTEGER, PARAMETER :: DP = KIND(1.0D0)
REAL(DP), PARAMETER :: PI=3.141592653589793238462643383279502884197_dp
REAL(DP), PARAMETER :: FACTOR=PI/180.0_DP
INTEGER,PARAMETER :: NUMMIEANGMAX=4200

INTEGER ::  NUM_SCAT_ANG
REAL*8,DIMENSION(NWV_BAND):: CEXT_ARSL_BAND,CSCAT_ARSL_BAND 
REAL*8,DIMENSION(NWV_BAND,NUMMIEANGMAX,0:6)::PHMXMIE_ARSL_PACE

CONTAINS

SUBROUTINE PHMXMIE_Instrument_INIT(FREEFORMFLAG,IAEROSOL,IRH,rf1,rf2,rf3,FRACS,FMFRAC,IREFF,IVAR,R0F,R0C,RHI, &
       R0DL,R0WS,R0BC,R0S,R0SS,MIX_FLAG,sigf,sigc,NMODE,DFRAC,DSFRAC,&
       REFF1,VEFF1,REFF2,VEFF2,REFFD,VEFFD,MRR1,MRI1,MRR2,MRI2,MRRD,MRID,ARSLND1,ARSLND2,ARSLNDD) 
USE DUST_DATA
IMPLICIT NONE

INTEGER,INTENT(IN) :: FREEFORMFLAG
INTEGER,INTENT(IN) :: IAEROSOL,IRH, IREFF, IVAR, MIX_FLAG,NMODE
REAL*8, INTENT(IN) :: rf1,rf2,rf3,FRACS,FMFRAC,R0F,R0C,RHI,R0DL,R0WS,R0BC,R0S,R0SS,sigf,sigc,DFRAC,DSFRAC
REAL*8,INTENT(INOUT)::REFF1,VEFF1,REFF2,VEFF2,ARSLND1,ARSLND2,ARSLNDD,REFFD,VEFFD
REAL*8,PARAMETER :: VDL=0.693D0,VWS=0.806D0,VBC=0.693D0,VS=0.693D0,VSS=0.7083D0
REAL*8,DIMENSION(NWV_BAND),INTENT(INOUT)::MRR1,MRI1,MRR2,MRI2,MRRD,MRID
REAL*8,DIMENSION(NWV_BAND)::WV_BAND_MICRON
REAL*8,DIMENSION(NUMMIEANGMAX,0:6)::PHMXMIE_LOCAL1,PHMXMIE_LOCAL2
REAL*8,DIMENSION(NUMMIEANGMAX) :: MIE_SCAT_ANG
INTEGER :: NDISTR,NANGMIE_LOCAL,ICO, IPHMX
REAL*8 :: AA1,BB1,AA2,BB2,GAMMAI,REFFO,VEFFO,AREA,CEXT1,CEXT2,CSCAT1,CSCAT2
REAL*8::REFF1_LOCAL,VEFF1_LOCAL,REFF2_LOCAL,VEFF2_LOCAL,ARSLND1_LOCAL,ARSLND2_LOCAL
REAL*8 :: RRH_F,RRH_C
REAL*8 :: RTMP,RTMP1,RTMP2, RTMP3, RTMP4,RTMP5,RTMP6
REAL*8 :: POL_TMP
INTEGER :: IWV_BAND, IWV, IANG, IELE
REAL*8 :: WV_tmp
REAL*8 :: WV_REF=0.55d0
real*8 :: VDLN, VWSN, VBCN,VSN, VSSN
!dust aerosol properties
REAL*8, DIMENSION(NWV_D,NSCATANG,1:6):: PHMX_DUST_TMP
REAL*8, DIMENSION(NWV_BAND,NSCATANG,1:6):: PHMX_DUST_TMP2
REAL*8, DIMENSION(NWV_D):: CEXT_DUST_TMP, CSCAT_DUST_TMP
REAL*8, DIMENSION(NWV_BAND,NUMMIEANGMAX,1:6):: PHMX_DUST, PHMXC, PHMXF
REAL*8, DIMENSION(NWV_BAND):: CEXT_DUST, CSCAT_DUST, CEXTC, CSCATC,MRR_DUST,MRI_DUST, CSCATF,CEXTF
REAL*8 :: POLINT_SIMPLE, FRACSV
INTEGER :: NUMSCATANG
REAl*8,DIMENSION(NWV_BAND):: MRR2_MIE,MRI2_MIE,CEXT2_MIE,CSCAT2_MIE, &
      MRR1_MIE,MRI1_MIE,CEXT1_MIE,CSCAT1_MIE
REAL*8, DIMENSION(NWV_BAND,NUMMIEANGMAX,0:6) :: PHMXMIE_LOCAL2_MIE, PHMXMIE_LOCAL1_MIE
REAL*8, DIMENSION(NSCATANG)::SCATANG
REAL*8:: R_G1, R_G2,R_GD,R_GC,  SIGMA_G1, SIGMA_G2,SIGMA_GD,SIGMA_GC, R_M2, R_MD, M22, M32, M2D, M3D, &
     M21DL,M21WS,M21BC,M21S,M22SS,M31DL,M31WS,M31BC,M31S,M32SS
REAL*8 :: REFF1_DL, REFF1_WS, REFF1_BC, REFF1_S,REFF2_SS, ARSLND1_DL, ARSLND1_WS, ARSLND1_BC, ARSLND1_S, &
     ARSLND2_SS, SIGMA_GDL,SIGMA_GWS, SIGMA_GBC, SIGMA_GS, SIGMA_GSS,R_GDL, R_GWS, R_GBC, R_GS, R_GSS, &
     ARSLNDSC, ARSLNDDC, SIGMA_GF, R_GF,ARSLND2_D
REAL*8, DIMENSION(NWV_BAND)::MRR1_DL, MRR1_WS, MRR1_BC, MRR1_S, MRR2_SS, MRI1_DL, MRI1_WS,MRI1_BC, MRI1_S,MRI2_SS, &
     CEXT1A_DL,CEXT1A_WS,CEXT1A_BC,CEXT1A_S,CEXT2A_SS, CSCAT1A_DL, CSCAT1A_WS,CSCAT1A_BC,CSCAT1A_S, CSCAT2A_SS

REAL*8, DIMENSION(NWV_BAND,NUMMIEANGMAX,0:6):: PHMXMIE_LOCAL1A_DL,PHMXMIE_LOCAL1A_WS,PHMXMIE_LOCAL1A_BC, &
     PHMXMIE_LOCAL1A_S,PHMXMIE_LOCAL2A_SS

REAL*8, DIMENSION(NUMMIEANGMAX,0:6)::PHMXMIE_LOCAL1_DL,PHMXMIE_LOCAL1_WS,PHMXMIE_LOCAL1_BC,PHMXMIE_LOCAL1_S,&
     PHMXMIE_LOCAL2_SS

REAL*8:: CEXT1_BC,CEXT1_DL,CEXT1_WS,CEXT1_S,CEXT2_SS,CSCAT1_DL,CSCAT1_WS,CSCAT1_BC,CSCAT1_S,CSCAT2_SS
REAL*8:: RRH_DL,RRH_WS,RRH_BC,RRH_S,RRH_SS
!3 aerosol modes
REAL*8:: SIGMA_GD2,R_GD2,DSFRACV,REFFD_LOCAL,VEFFD_LOCAL,REFFDS,SIGMA_GDS,R_GDS,&
     CEXTD,CSCATD,M22DS,M32DS
REAL*8, DIMENSION(NWV_BAND):: MRRDS,MRIDS,MRRD_MIE,MRID_MIE,CEXTD_MIE,CSCATD_MIE,CEXT_DUSTF,CSCAT_DUSTF,MRRDT,MRIDT
     
REAL*8, DIMENSION(NWV_BAND,NUMMIEANGMAX,0:6) :: PHMXMIE_LOCALD_MIE,PHMX_DUSTF
REAL*8, DIMENSION(NUMMIEANGMAX,0:6) :: PHMXMIE_LOCALD

CALL WV_REF_ASSIGN(WV_REF) ! aerosol optical depth reference wavelength

WV_BAND_MICRON=WV_BAND/1000.0D0

!write(*,*) 'FREEFORMFLAG',FREEFORMFLAG

IF(FREEFORMFLAG==0)THEN
  IF(REFF1<0 .OR. REFF2<0 .OR. VEFF1<0 .OR. VEFF2<0 .OR. ARSLND1<0 .OR. ARSLND2<0) &
       STOP 'CHECK AEROSOL MICROPHYSICAL INPUT PARAMETERS'
  DO IWV_BAND=1,NWV_BAND
     IF(MRR1(IWV_BAND)<0.0) STOP 'CHECK AEROSOL REFRACTIVE INDEX'
     IF(MRI1(IWV_BAND)<0.0) STOP 'CHECK AEROSOL REFRACTIVE INDEX'
     IF(MRR2(IWV_BAND)<0.0) STOP 'CHECK AEROSOL REFRACTIVE INDEX'
     IF(MRI2(IWV_BAND)<0.0) STOP 'CHECK AEROSOL REFRACTIVE INDEX'
  ENDDO
  REFF1_LOCAL=REFF1
  VEFF1_LOCAL=VEFF1
  REFF2_LOCAL=REFF2
  VEFF2_LOCAL=VEFF2
  NDISTR=2
ENDIF

IF(FREEFORMFLAG==1 .AND. IAEROSOL>0 .AND. IAEROSOL<21)THEN

write(*,*) 'IAEROSOL',IAEROSOL

CALL ARSL_INDX_INIT(NWV_BAND,WV_BAND_MICRON)
   
  IF(IAEROSOL==1)THEN
       REFF1=RTROPOSPHERE(IRH)
       REFF2=RRURALC(IRH)
  ELSEIF(IAEROSOL<=6 .AND. IAEROSOL>0)THEN
       REFF1=RURBANF(IRH)
       REFF2=RURBANC(IRH)
  ELSEIF(IAEROSOL<=9 .AND. IAEROSOL>0)THEN
       REFF1=RTROPOSPHERE(IRH)
       REFF2=ROCEANIC(IRH)
  ELSEIF(IAEROSOL==10)THEN
       REFF1=RTROPOSPHERE(IRH)
       REFF2=0.0D0
  ELSEIF(IAEROSOL>10 .AND. IAEROSOL<21 .AND. IAEROSOL>0)THEN
       REFF1=exp(log(RZIAF(IRH))-3.0*SIGF_ZIA*SIGF_ZIA)
            ! Rg in number space read Eq.3a in Ahmad 2000 for details
       REFF2=exp(log(RZIAC(IRH))-3.0*SIGC_ZIA*SIGC_ZIA)
    ENDIF
    

  IF(IAEROSOL<=10 .AND. IAEROSOL>0)THEN
     VEFF1=SIGF_SF
     VEFF2=SIGC_SF
  ELSE
     VEFF1=SIGF_ZIA
     VEFF2=SIGC_ZIA
  ENDIF

  
  IF(IAEROSOL<7 .AND. IAEROSOL>0)THEN
     ARSLND1=0.999875
     ARSLND2=0.000125
  ELSEIF(IAEROSOL==7)THEN
     ARSLND1=0.99
     ARSLND2=0.01
  ELSEIF(IAEROSOL==8)THEN
     ARSLND1=0.995
     ARSLND2=0.005
  ELSEIF(IAEROSOL==9)THEN
     ARSLND1=0.998
     ARSLND2=0.002
  ELSEIF(IAEROSOL==10)THEN
     ARSLND1=1.0D0
     ARSLND2=0.0D0
  ELSEIF(IAEROSOL>10 .AND. IAEROSOL<21 .AND. IAEROSOL>0) THEN 
     RTMP=4.0D0*PI*(REFF1**3)/3.0D0
     RTMP=RATIO_FINE_MODE_ZIA(IAEROSOL-10)/RTMP*EXP(-4.5D0*VEFF1*VEFF1)
     RTMP1=4.0D0*PI*(REFF2**3)/3.0D0
     RTMP1=(1.0D0-RATIO_FINE_MODE_ZIA(IAEROSOL-10))/RTMP1*EXP(-4.5D0*VEFF2*VEFF2)
     RTMP=RTMP/(RTMP+RTMP1)
     ARSLND1=RTMP
     ARSLND2=(1.0D0-RTMP)
  ENDIF

  
  IF(IAEROSOL==1)THEN !rural 
       MRR1(1:NWV_BAND)=MR_TRPOSPHERE(1:NWV_BAND,IRH)
       MRI1(1:NWV_BAND)=MI_TRPOSPHERE(1:NWV_BAND,IRH)
       MRR2(1:NWV_BAND)=MR_RURALC(1:NWV_BAND,IRH)
       MRI2(1:NWV_BAND)=MI_RURALC(1:NWV_BAND,IRH)
  ELSEIF(IAEROSOL==2)THEN ! URBAN
       MRR1(1:NWV_BAND)=MR_URBANF(1:NWV_BAND,IRH)
       MRI1(1:NWV_BAND)=MI_URBANF(1:NWV_BAND,IRH)
       MRR2(1:NWV_BAND)=MR_URBANC(1:NWV_BAND,IRH)
       MRI2(1:NWV_BAND)=MI_URBANC(1:NWV_BAND,IRH)
  ELSEIF(IAEROSOL==3)THEN ! URBAN A
       MRR1(1:NWV_BAND)=MR_URBANAF(1:NWV_BAND,IRH)
       MRI1(1:NWV_BAND)=MI_URBANAF(1:NWV_BAND,IRH)
       MRR2(1:NWV_BAND)=MR_URBANAC(1:NWV_BAND,IRH)
       MRI2(1:NWV_BAND)=MI_URBANAC(1:NWV_BAND,IRH)
  ELSEIF(IAEROSOL==4)THEN  ! URBAN A1
       MRR1(1:NWV_BAND)=MR_URBANA1F(1:NWV_BAND,IRH)
       MRI1(1:NWV_BAND)=MI_URBANA1F(1:NWV_BAND,IRH)
       MRR2(1:NWV_BAND)=MR_URBANA1C(1:NWV_BAND,IRH)
       MRI2(1:NWV_BAND)=MI_URBANA1C(1:NWV_BAND,IRH)
    ELSEIF(IAEROSOL==5)THEN! URBAN A2
       MRR1(1:NWV_BAND)=MR_URBANA2F(1:NWV_BAND,IRH)
       MRI1(1:NWV_BAND)=MI_URBANA2F(1:NWV_BAND,IRH)
       MRR2(1:NWV_BAND)=MR_URBANA2C(1:NWV_BAND,IRH)
       MRI2(1:NWV_BAND)=MI_URBANA2C(1:NWV_BAND,IRH)
    ELSEIF(IAEROSOL==6)THEN! URBAN A3
       MRR1(1:NWV_BAND)=MR_URBANA3F(1:NWV_BAND,IRH)
       MRI1(1:NWV_BAND)=MI_URBANA3F(1:NWV_BAND,IRH)
       MRR2(1:NWV_BAND)=MR_URBANA3C(1:NWV_BAND,IRH)
       MRI2(1:NWV_BAND)=MI_URBANA3C(1:NWV_BAND,IRH)
    ELSEIF(IAEROSOL>=7 .AND. IAEROSOL<=9 .AND. IAEROSOL>0)THEN! MARINETIME
       MRR1(1:NWV_BAND)=MR_TRPOSPHERE(1:NWV_BAND,IRH)
       MRI1(1:NWV_BAND)=MI_TRPOSPHERE(1:NWV_BAND,IRH)
       MRR2(1:NWV_BAND)=MR_OCEANIC(1:NWV_BAND,IRH)
       MRI2(1:NWV_BAND)=MI_OCEANIC(1:NWV_BAND,IRH)
    ELSEIF(IAEROSOL==10)THEN
       MRR1(1:NWV_BAND)=MR_TRPOSPHERE(1:NWV_BAND,IRH)
       MRI1(1:NWV_BAND)=MI_TRPOSPHERE(1:NWV_BAND,IRH)
       MRR2(1:NWV_BAND)=1.0
       MRI2(1:NWV_BAND)=0.0
    ELSEIF((IAEROSOL>10).AND.(IAEROSOL<21) .AND. IAEROSOL>0)THEN
       MRR1(1:NWV_BAND)=MR_ZIAF(1:NWV_BAND,IRH)
       MRI1(1:NWV_BAND)=MI_ZIAF(1:NWV_BAND,IRH)
       MRR2(1:NWV_BAND)=MR_ZIAC(1:NWV_BAND,IRH)
       MRI2(1:NWV_BAND)=MI_ZIAC(1:NWV_BAND,IRH)
    ENDIF

    
    ! CONVERT TO EFFECT RADIUS AND VARIANCE BEFORE CALL SPHER_INTERFACE
    REFF1_LOCAL=REFF1
    VEFF1_LOCAL=VEFF1
    REFF2_LOCAL=REFF2
    VEFF2_LOCAL=VEFF2

    VEFF1_LOCAL=VEFF1_LOCAL*VEFF1_LOCAL
    VEFF2_LOCAL=VEFF2_LOCAL*VEFF2_LOCAL
    
    !converted to effective  values from geometric values
    REFF1_LOCAL=REFF1_LOCAL*EXP(2.5D0*VEFF1_LOCAL)
    REFF2_LOCAL=REFF2_LOCAL*EXP(2.5D0*VEFF2_LOCAL)
    VEFF1_LOCAL=EXP(VEFF1_LOCAL)-1.0D0
    VEFF2_LOCAL=EXP(VEFF2_LOCAL)-1.0D0


! pass effective radius and variance back to main program for output
	REFF1=REFF1_LOCAL
	VEFF1=VEFF1_LOCAL
	REFF2=REFF2_LOCAL
	VEFF2=VEFF2_LOCAL


    CALL ARSL_INDX_DEALLO

    
    NDISTR=2

    
 DO IWV_BAND=1,NWV_BAND

    CALL SPHER_INTERFACE(NDISTR,REFF1_LOCAL,VEFF1_LOCAL,WV_BAND_MICRON(IWV_BAND),&
         MRR1(IWV_BAND),MRI1(IWV_BAND),AA1,BB1,AA2,BB2,GAMMAI,&
         REFFO,VEFFO,AREA,CEXT1,CSCAT1,NANGMIE_LOCAL,PHMXMIE_LOCAL1)
    IF(ARSLND2>0.0D0 .AND. FREEFORMFLAG<=1)THEN
       CALL SPHER_INTERFACE(NDISTR,REFF2_LOCAL,VEFF2_LOCAL,WV_BAND_MICRON(IWV_BAND),&
            MRR2(IWV_BAND),MRI2(IWV_BAND),AA1,BB1,AA2,BB2,GAMMAI,&
            REFFO,VEFFO,AREA,CEXT2,CSCAT2,NANGMIE_LOCAL,PHMXMIE_LOCAL2)
    ELSE
       CEXT2=0.0D0
       CSCAT2=0.0D0
    ENDIF

          IF(FREEFORMFLAG<=1)THEN
             NUM_SCAT_ANG=NANGMIE_LOCAL
             CEXT_ARSL_BAND(IWV_BAND)=ARSLND1*CEXT1+ARSLND2*CEXT2
             CSCAT_ARSL_BAND(IWV_BAND)=ARSLND1*CSCAT1+ARSLND2*CSCAT2
             PHMXMIE_ARSL_PACE(IWV_BAND,:,1:6)= &
                 (ARSLND1*CSCAT1*PHMXMIE_LOCAL1(:,1:6)  &
				+ ARSLND2*CSCAT2*PHMXMIE_LOCAL2(:,1:6)) &
				/ CSCAT_ARSL_BAND(IWV_BAND)
          ENDIF 
          ENDDO

 END IF


 
 IF(FREEFORMFLAG>=0 .AND. IAEROSOL==-99 .AND. MIX_FLAG==0) THEN !INTERNAL MIXING OF FINE MODE AEROSOLS

    WRITE(*,*) 'IAEROSOL',IAEROSOL
    CALL HYGROSCOPIC_GROWTH_IMIX(R0F, R0C, RHI, RRH_F, RRH_C)

    !from volume space to number space GEOMETRICAL RADIUS
    REFF1=exp(log(RRH_F)-3.0D0*SIGF_ZIA*SIGF_ZIA)
    REFF2=exp(log(RRH_C)-3.0D0*SIGC_ZIA*SIGC_ZIA)
    VEFF1=sigf !SIGF_ZIA !sigf
    VEFF2=sigc !SIGC_ZIA !sigc

    write(*,*) 'R1, R2', REFF1, REFF2
    write(*,*) ' sig1, sig2', VEFF1,VEFF2
    

    CALL ARSL_REF_INDX_INIT_IMIX(NWV_BAND,WV_BAND_MICRON,RHI,R0F,R0C,rf1,rf2,rf3,NMODE)
    MRR1(1:NWV_BAND)=MR_FLEXF(1:NWV_BAND)
    MRI1(1:NWV_BAND)=MI_FLEXF(1:NWV_BAND)
    MRR2(1:NWV_BAND)=MR_FLEXC(1:NWV_BAND)
    MRI2(1:NWV_BAND)=MI_FLEXC(1:NWV_BAND)

    DEALLOCATE(MR_ZIACR,MI_ZIACR, MR_FLEXF, MR_FLEXC, MI_FLEXF,MI_FLEXC)

    REFF1_LOCAL=REFF1
    VEFF1_LOCAL=VEFF1
    REFF2_LOCAL=REFF2
    VEFF2_LOCAL=VEFF2

    VEFF1_LOCAL=VEFF1_LOCAL*VEFF1_LOCAL
    VEFF2_LOCAL=VEFF2_LOCAL*VEFF2_LOCAL

    !converted to effective  values from geometric values
    REFF1_LOCAL=REFF1_LOCAL*EXP(2.5D0*VEFF1_LOCAL)
    REFF2_LOCAL=REFF2_LOCAL*EXP(2.5D0*VEFF2_LOCAL)
    VEFF1_LOCAL=EXP(VEFF1_LOCAL)-1.0D0
    VEFF2_LOCAL=EXP(VEFF2_LOCAL)-1.0D0

! pass effective radius and variance back to main program for output
	REFF1=REFF1_LOCAL
	VEFF1=VEFF1_LOCAL
	REFF2=REFF2_LOCAL
	VEFF2=VEFF2_LOCAL

    NDISTR=2
    

!DUST DATA
!wavelength interpolation
CALL DUST_SCAT_PROP_INIT(IREFF,IVAR,PHMX_DUST_TMP,CEXT_DUST_TMP,CSCAT_DUST_TMP,SCATANG)

DO IWV_BAND=1,NWV_BAND
    WV_tmp=WV_BAND_MICRON(IWV_BAND)
    
    CEXT_DUST(IWV_BAND)=POLINT_SIMPLE(NWV_D,WVL,CEXT_DUST_TMP,WV_tmp,3)
    CSCAT_DUST(IWV_BAND)=POLINT_SIMPLE(NWV_D,WVL,CSCAT_DUST_TMP,WV_tmp,3)
    MRR_DUST(IWV_BAND)=POLINT_SIMPLE(NWV_D,WVL,MRD,WV_tmp,3)
    MRI_DUST(IWV_BAND)=POLINT_SIMPLE(NWV_D,WVL,MID,WV_tmp,3)
    DO IANG=1,NSCATANG
       DO IPHMX=1,6
          PHMX_DUST_TMP2(IWV_BAND,IANG,IPHMX)=POLINT_SIMPLE(NWV_D,WVL,PHMX_DUST_TMP(:,IANG,IPHMX),WV_tmp,3)
       END DO
    END DO
 END DO

!MIE CACULATIONS
 DO IWV_BAND=1,NWV_BAND
  IF(FMFRAC<1.0D0) THEN 
   CALL SPHER_INTERFACE(NDISTR,REFF2_LOCAL,VEFF2_LOCAL,WV_BAND_MICRON(IWV_BAND),&
        MRR2(IWV_BAND),MRI2(IWV_BAND),AA1,BB1,AA2,BB2,GAMMAI,&
        REFFO,VEFFO,AREA,CEXT2,CSCAT2,NANGMIE_LOCAL,PHMXMIE_LOCAL2)
   ENDIF

  NUM_SCAT_ANG = NANGMIE_LOCAL
  MRR2_MIE(IWV_BAND)=MRR2(IWV_BAND)
  MRI2_MIE(IWV_BAND)=MRI2(IWV_BAND)
  CEXT2_MIE(IWV_BAND)=CEXT2
  CSCAT2_MIE(IWV_BAND)=CSCAT2
  PHMXMIE_LOCAL2_MIE(IWV_BAND,:,:)=PHMXMIE_LOCAL2(:,:)
  
   IF(FMFRAC>0.0D0) THEN
   CALL SPHER_INTERFACE(NDISTR,REFF1_LOCAL,VEFF1_LOCAL,WV_BAND_MICRON(IWV_BAND),&
        MRR1(IWV_BAND),MRI1(IWV_BAND),AA1,BB1,AA2,BB2,GAMMAI,&
        REFFO,VEFFO,AREA,CEXT1,CSCAT1,NANGMIE_LOCAL,PHMXMIE_LOCAL1)
   ENDIF

   IF(FMFRAC>0.0D0) THEN
   NUM_SCAT_ANG = NANGMIE_LOCAL
   MRR1_MIE(IWV_BAND)=MRR1(IWV_BAND)
   MRI1_MIE(IWV_BAND)=MRI1(IWV_BAND)
   CEXT1_MIE(IWV_BAND)=CEXT1
   CSCAT1_MIE(IWV_BAND)=CSCAT1
   PHMXMIE_LOCAL1_MIE(IWV_BAND,:,:)=PHMXMIE_LOCAL1(:,:)
ENDIF
   END DO

   DO IWV_BAND=1,NWV_BAND
      DO IANG=1,NUM_SCAT_ANG
         DO IPHMX=1,6
            PHMX_DUST(IWV_BAND,IANG,IPHMX)=POLINT_SIMPLE(NSCATANG,SCATANG,PHMX_DUST_TMP2(IWV_BAND,:,IPHMX),&
          PHMXMIE_LOCAL2_MIE(IWV_BAND,IANG,0),3)
         END DO
      END DO
   END DO


   !new corase mode effective radius

   !using values converted into number space to obtain geometric values
   SIGMA_G1 = SQRT(LOG(VEFF1_LOCAL+1))
   SIGMA_G2 = SQRT(LOG(VEFF2_LOCAL+1))
   SIGMA_GD = SQRT(LOG(SIGMA(IVAR))) ! dust is given with variance which is not the effective variance

   R_G1 = REFF1_LOCAL/EXP(2.5*SIGMA_G1*SIGMA_G1)
   R_G2 = REFF2_LOCAL/EXP(2.5*SIGMA_G2*SIGMA_G2)
   R_GD = REFF(IREFF)/EXP(2.5*SIGMA_GD*SIGMA_GD)! dust radius is the effective radius


   IF (NMODE==2) THEN
   !calculating 2nd and 3rd moments
   M22 = R_G2*R_G2*EXP(2*SIGMA_G2*SIGMA_G2)
   M32 = R_G2*R_G2*R_G2*EXP(4.5*SIGMA_G2*SIGMA_G2)

   M2D = R_GD*R_GD*EXP(2*SIGMA_GD*SIGMA_GD)
   M3D = R_GD*R_GD*R_GD*EXP(4.5*SIGMA_GD*SIGMA_GD)

   RTMP2=(1-FRACS)/(4.0D0*PI*(R_GD**3)/3.0D0)*EXP(-4.5D0*SIGMA_GD*SIGMA_GD) !dust
   RTMP3=FRACS/(4.0D0*PI*(R_G2**3)/3.0D0)*EXP(-4.5D0*SIGMA_G2*SIGMA_G2) ! other coarse mode
   FRACSV=RTMP3/(RTMP2+RTMP3)

   REFF2=(FRACSV*M32+(1-FRACSV)*M3D)/(FRACSV*M22+(1-FRACSV)*M2D)
   VEFF2=FRACSV*VEFF2_LOCAL+(1-FRACSV)*EXP(LOG(SIGMA(IVAR))-1)

   CEXTC(:)=FRACSV*CEXT2_MIE(:)+(1-FRACSV)*CEXT_DUST(:)
   CSCATC(:)=FRACSV*CSCAT2_MIE(:)+(1-FRACSV)*CSCAT_DUST(:)


   !new coarse mode refractive indices
   IF (FMFRAC<1.0D0)THEN
	   MRR2=FRACS*MRR2_MIE+(1-FRACS)*MRR_DUST
	   MRI2=FRACS*MRI2_MIE+(1-FRACS)*MRI_DUST
   ELSEIF (FMFRAC==1.0) THEN
	   MRR2=0.0D0
	   MRI2=0.D0
   ELSEIF (FMFRAC==0.0D0) THEN
	   MRR1=0.0D0
	   MRR1=0.0D0
   ENDIF

   !coarse mode geometrical properties
   SIGMA_GC = SQRT(LOG(VEFF2)+1)
   R_GC = REFF2/EXP(2.5*SIGMA_GC*SIGMA_GC)
   
   !redefining aerosol number density for fine and coarse modes based on modified REFF and VEFF
   RTMP1=4.0D0*PI*(R_G1**3)/3.0D0
   RTMP2=FMFRAC/RTMP1*EXP(-4.5D0*SIGMA_G1*SIGMA_G1)
   RTMP1=4.0D0*PI*(R_GC**3)/3.0D0
   RTMP3=(1.0D0-FMFRAC)/RTMP1*EXP(-4.5D0*SIGMA_GC*SIGMA_GC)
   RTMP1=RTMP2/(RTMP2+RTMP3)
   ARSLND1=RTMP1
   ARSLND2=(1.0D0-RTMP1)



    write(*,*) '****************************************************************'
    WRITE(*,*) 'NUMBER OF AEROSOL MODES = 2'
    write(*,*) 'COARSE MODE - EXTERNAL MIXING'
    WRITE(*,*) 'FINE MODE -  INTERNAL MIXING'
    write(*,*) '****************************************************************'
    IF(FMFRAC>0.0D0)THEN
        write(*,*) 'reff_fine',REFF1_LOCAL
        write(*,*) 'veff_fine', VEFF1_LOCAL
    ENDIF
    IF((1-FMFRAC)>0.0D0)THEN
        write(*,*) 'reff_coarse' , REFF2
        write(*,*) 'veff_coarse',VEFF2
    ENDIF
    write(*,*) 'fine mode number density',ARSLND1
    write(*,*) 'coarse mode number density',ARSLND2


!external mixing of spherical and non-spherical coarse mode aerosol phase  matrix

    DO IWV_BAND=1,NWV_BAND
		PHMXC(IWV_BAND,:,1:6)=               &
             (   FRACSV *CSCAT2_MIE(IWV_BAND)*PHMXMIE_LOCAL2_MIE(IWV_BAND,:,1:6) &
        +     (1-FRACSV)*CSCAT_DUST(IWV_BAND)*PHMX_DUST(IWV_BAND,:,1:6)) &
        /    CSCATC(IWV_BAND)

!    PHMXC(IWV_BAND,:,1)=(FRACSV*CSCAT2_MIE(IWV_BAND)*PHMXMIE_LOCAL2_MIE &
!         (IWV_BAND,:,1)+(1-FRACSV)*CSCAT_DUST(IWV_BAND)* &
!                        PHMX_DUST(IWV_BAND,:,1))/CSCATC(IWV_BAND)
!    PHMXC(IWV_BAND,:,2)=(FRACSV*CSCAT2_MIE(IWV_BAND)*PHMXMIE_LOCAL2_MIE &
!         (IWV_BAND,:,5)+(1-FRACSV)*CSCAT_DUST(IWV_BAND)* &
!                        PHMX_DUST(IWV_BAND,:,2))/CSCATC(IWV_BAND)
!    PHMXC(IWV_BAND,:,3)=(FRACSV*CSCAT2_MIE(IWV_BAND)*PHMXMIE_LOCAL2_MIE &
!         (IWV_BAND,:,2)+(1-FRACSV)*CSCAT_DUST(IWV_BAND)* &
!                        PHMX_DUST(IWV_BAND,:,3))/CSCATC(IWV_BAND)
!    PHMXC(IWV_BAND,:,4)=(FRACSV*CSCAT2_MIE(IWV_BAND)*PHMXMIE_LOCAL2_MIE &
!         (IWV_BAND,:,3)+(1-FRACSV)*CSCAT_DUST(IWV_BAND)* &
!                        PHMX_DUST(IWV_BAND,:,4))/CSCATC(IWV_BAND)
!    PHMXC(IWV_BAND,:,5)=(FRACSV*CSCAT2_MIE(IWV_BAND)*PHMXMIE_LOCAL2_MIE &
!         (IWV_BAND,:,6)+(1-FRACSV)*CSCAT_DUST(IWV_BAND)* &
!                        PHMX_DUST(IWV_BAND,:,5))/CSCATC(IWV_BAND)
!    PHMXC(IWV_BAND,:,6)=(FRACSV*CSCAT2_MIE(IWV_BAND)*PHMXMIE_LOCAL2_MIE &
!         (IWV_BAND,:,4)+(1-FRACSV)*CSCAT_DUST(IWV_BAND)* &
!                        PHMX_DUST(IWV_BAND,:,6))/CSCATC(IWV_BAND)
 END DO

 
CEXT_ARSL_BAND=ARSLND1*CEXT1_MIE+ARSLND2*CEXTC
CSCAT_ARSL_BAND=ARSLND1*CSCAT1_MIE+ARSLND2*CSCATC

    DO IWV_BAND=1,NWV_BAND
       IF (FMFRAC==0.0D0) THEN
       PHMXMIE_ARSL_PACE(IWV_BAND,:,0)=PHMXMIE_LOCAL2_MIE(IWV_BAND,:,0)
    ELSEIF (FMFRAC>0.0D0) THEN
       PHMXMIE_ARSL_PACE(IWV_BAND,:,0)=PHMXMIE_LOCAL1_MIE(IWV_BAND,:,0)
    ENDIF

	PHMXMIE_ARSL_PACE(IWV_BAND,:,1:6)= ( &
		 ARSLND1*CSCAT1_MIE(IWV_BAND)* PHMXMIE_LOCAL1_MIE(IWV_BAND,:,1:6) + &
		 ARSLND2*CSCATC(IWV_BAND)*PHMXC(IWV_BAND,:,1:6))/CSCAT_ARSL_BAND(IWV_BAND)

!       PHMXMIE_ARSL_PACE(IWV_BAND,:,1)= ( &
!            ARSLND1*CSCAT1_MIE(IWV_BAND)* PHMXMIE_LOCAL1_MIE(IWV_BAND,:,1) + &
!            ARSLND2*CSCATC(IWV_BAND)*PHMXC(IWV_BAND,:,1))/CSCAT_ARSL_BAND(IWV_BAND)
!
!       PHMXMIE_ARSL_PACE(IWV_BAND,:,2)=(ARSLND1*CSCAT1_MIE(IWV_BAND)* &
!            PHMXMIE_LOCAL1_MIE(IWV_BAND,:,5) + &
!            ARSLND2*CSCATC(IWV_BAND)*PHMXC(IWV_BAND,:,2))/CSCAT_ARSL_BAND(IWV_BAND)
!
!       PHMXMIE_ARSL_PACE(IWV_BAND,:,3)=(ARSLND1*CSCAT1_MIE(IWV_BAND)* &
!            PHMXMIE_LOCAL1_MIE(IWV_BAND,:,2) + &
!            ARSLND2*CSCATC(IWV_BAND)*PHMXC(IWV_BAND,:,3))/CSCAT_ARSL_BAND(IWV_BAND)
!
!       PHMXMIE_ARSL_PACE(IWV_BAND,:,4)=(ARSLND1*CSCAT1_MIE(IWV_BAND)* &
!            PHMXMIE_LOCAL1_MIE(IWV_BAND,:,3) + &
!            ARSLND2*CSCATC(IWV_BAND)*PHMXC(IWV_BAND,:,4))/CSCAT_ARSL_BAND(IWV_BAND)
!
!       PHMXMIE_ARSL_PACE(IWV_BAND,:,5)=(ARSLND1*CSCAT1_MIE(IWV_BAND)* &
!            PHMXMIE_LOCAL1_MIE(IWV_BAND,:,6) + &
!            ARSLND2*CSCATC(IWV_BAND)*PHMXC(IWV_BAND,:,5))/CSCAT_ARSL_BAND(IWV_BAND)
!
!       PHMXMIE_ARSL_PACE(IWV_BAND,:,6)=(ARSLND1*CSCAT1_MIE(IWV_BAND)* &
!            PHMXMIE_LOCAL1_MIE(IWV_BAND,:,4) + &
!            ARSLND2*CSCATC(IWV_BAND)*PHMXC(IWV_BAND,:,6))/CSCAT_ARSL_BAND(IWV_BAND)
       END DO
    ENDIF



    IF(NMODE==3)THEN
       CALL ARSL_REF_INDX_INIT_EMIX(NWV_BAND,WV_BAND_MICRON,RHI,R0DL,R0WS,R0BC,R0S,R0SS)
       MRRDS(1:NWV_BAND) = MR_DUSTF_TMP1(1:NWV_BAND)
       MRIDS(1:NWV_BAND) = MI_DUSTF_TMP1(1:NWV_BAND)

       DEALLOCATE(MR_SOOTF_TMP1,MI_SOOTF_TMP1,MR_DUSTF_TMP1,MI_DUSTF_TMP1, &
            MR_WATER_SOLUBLE_TMP1,MI_WATER_SOLUBLE_TMP1,MR_BRC_TMP1, MI_BRC_TMP1, &
            MR_ZIACR, MI_ZIACR)

       
       REFFDS = EXP(LOG(R0DL)-3.0D0*VDL*VDL)
       VDLN = VDL*VDL
       REFFD_LOCAL = REFFDS*EXP(2.5D0*VDLN)
       VEFFD_LOCAL = EXP(VDLN)-1.0D0

       DO IWV_BAND=1,NWV_BAND
          IF(DSFRAC>0.0D0) THEN !DUST MODE SPHERICAL DUST
             CALL SPHER_INTERFACE(NDISTR,REFFD_LOCAL,VEFFD_LOCAL,WV_BAND_MICRON(IWV_BAND),&
                  MRRDS(IWV_BAND),MRIDS(IWV_BAND),AA1,BB1,AA2,BB2,GAMMAI,&
                  REFFO,VEFFO,AREA,CEXTD,CSCATD,NANGMIE_LOCAL,PHMXMIE_LOCALD)
          ENDIF

          NUM_SCAT_ANG = NANGMIE_LOCAL
          CEXTD_MIE(IWV_BAND)=CEXTD
          CSCATD_MIE(IWV_BAND)=CSCATD
          PHMXMIE_LOCALD_MIE(IWV_BAND,:,:)=PHMXMIE_LOCALD(:,:)

       ENDDO


          SIGMA_GDS = SQRT(LOG(VEFFD_LOCAL+1))
          R_GDS = REFFD_LOCAL/EXP(2.5*SIGMA_GDS*SIGMA_GDS)
          
          M22DS = R_GDS*R_GDS*EXP(2*SIGMA_GDS*SIGMA_GDS)
          M32DS = R_GDS*R_GDS*R_GDS*EXP(4.5*SIGMA_GDS*SIGMA_GDS)

          M2D = R_GD*R_GD*EXP(2*SIGMA_GD*SIGMA_GD)
          M3D = R_GD*R_GD*R_GD*EXP(4.5*SIGMA_GD*SIGMA_GD)

          RTMP2=(1-DSFRAC)/(4.0D0*PI*(R_GD**3)/3.0D0)*EXP(-4.5D0*SIGMA_GD*SIGMA_GD) !dust
          RTMP3=DSFRAC/(4.0D0*PI*(R_GDS**3)/3.0D0)*EXP(-4.5D0*SIGMA_GDS*SIGMA_GDS) ! other coarse mode
          DSFRACV=RTMP3/(RTMP2+RTMP3)

          REFFD=(DSFRACV*M32DS+(1-DSFRACV)*M3D)/(DSFRACV*M22DS+(1-DSFRACV)*M2D)
          VEFFD=DSFRACV*VEFFD_LOCAL+(1-DSFRACV)*EXP(LOG(SIGMA(IVAR))-1)
         
          CEXT_DUSTF(:)=DSFRACV*CEXTD_MIE(:)+(1-DSFRACV)*CEXT_DUST(:)
          CSCAT_DUSTF(:)=DSFRACV*CSCATD_MIE(:)+(1-DSFRACV)*CSCAT_DUST(:)

          
          DO IWV_BAND=1,NWV_BAND
            PHMX_DUSTF(IWV_BAND,:,1:6)= ( &
				DSFRACV *CSCATD_MIE(IWV_BAND)* PHMXMIE_LOCALD_MIE(IWV_BAND,:,1:6) + &
			 (1-DSFRACV)*CSCAT_DUST(IWV_BAND)* PHMX_DUST(IWV_BAND,:,1:6))/CSCAT_DUSTF(IWV_BAND)

!          PHMX_DUSTF(IWV_BAND,:,1)= ( &
!               DSFRACV*CSCATD_MIE(IWV_BAND)* PHMXMIE_LOCALD_MIE(IWV_BAND,:,1) + &
!               (1-DSFRACV)*CSCAT_DUST(IWV_BAND)*PHMX_DUST(IWV_BAND,:,1))/CSCAT_DUSTF(IWV_BAND)
!          PHMX_DUSTF(IWV_BAND,:,2)= ( &
!               DSFRACV*CSCATD_MIE(IWV_BAND)* PHMXMIE_LOCALD_MIE(IWV_BAND,:,5) + &
!               (1-DSFRACV)*CSCAT_DUST(IWV_BAND)*PHMX_DUST(IWV_BAND,:,2))/CSCAT_DUSTF(IWV_BAND)
!          PHMX_DUSTF(IWV_BAND,:,3)= ( &
!               DSFRACV*CSCATD_MIE(IWV_BAND)* PHMXMIE_LOCALD_MIE(IWV_BAND,:,2) + &
!               (1-DSFRACV)*CSCAT_DUST(IWV_BAND)*PHMX_DUST(IWV_BAND,:,3))/CSCAT_DUSTF(IWV_BAND)
!          PHMX_DUSTF(IWV_BAND,:,4)= ( &
!               DSFRACV*CSCATD_MIE(IWV_BAND)* PHMXMIE_LOCALD_MIE(IWV_BAND,:,3) + &
!               (1-DSFRACV)*CSCAT_DUST(IWV_BAND)*PHMX_DUST(IWV_BAND,:,4))/CSCAT_DUSTF(IWV_BAND)
!          PHMX_DUSTF(IWV_BAND,:,5)= ( &
!               DSFRACV*CSCATD_MIE(IWV_BAND)* PHMXMIE_LOCALD_MIE(IWV_BAND,:,6) + &
!               (1-DSFRACV)*CSCAT_DUST(IWV_BAND)*PHMX_DUST(IWV_BAND,:,5))/CSCAT_DUSTF(IWV_BAND)
!          PHMX_DUSTF(IWV_BAND,:,6)= ( &
!               DSFRACV*CSCATD_MIE(IWV_BAND)* PHMXMIE_LOCALD_MIE(IWV_BAND,:,4) + &
!               (1-DSFRACV)*CSCAT_DUST(IWV_BAND)*PHMX_DUST(IWV_BAND,:,6))/CSCAT_DUSTF(IWV_BAND)
       ENDDO

          
          SIGMA_GD2 = SQRT(LOG(VEFFD)+1)
          R_GD2 = REFFD/EXP(2.5*SIGMA_GD2*SIGMA_GD2)

          MRRDT = DSFRAC*MRRDS+(1-DSFRAC)*MRR_DUST
          MRIDT = DSFRAC*MRIDS+(1-DSFRAC)*MRI_DUST

          !AEROSOL NUMBER DENSITYCALCULATION

          RTMP1=4.0D0*PI*(R_G1**3)/3.0D0 !fine
          RTMP2=FMFRAC/RTMP1*EXP(-4.5D0*SIGMA_G1*SIGMA_G1)
          RTMP1=4.0D0*PI*(R_GD2**3)/3.0D0!dust
          RTMP3=DFRAC/RTMP1*EXP(-4.5D0*SIGMA_GD2*SIGMA_GD2)
          RTMP1=4.0D0*PI*(R_G2**3)/3.0D0!coarse
          RTMP4=(1-(FMFRAC+DFRAC))/RTMP1*EXP(-4.5D0*SIGMA_G2*SIGMA_G2)
          RTMP1=RTMP2+RTMP3+RTMP4
          ARSLND1=RTMP2/RTMP1
          ARSLND2=RTMP4/RTMP1
          ARSLNDD=RTMP3/RTMP1


        write(*,*) '****************************************************************'
        WRITE(*,*) 'NUMBER OF AEROSOL MODES = 3'
        write(*,*) 'COARSE MODE - EXTERNAL MIXING'
        WRITE(*,*) 'FINE MODE -  INTERNAL MIXING'
        WRITE(*,*) 'DUST MODE - EXTERNAL MIXING'
        write(*,*) '****************************************************************'
        IF(FMFRAC>0.0D0) THEN
            write(*,*) 'reff_fine',REFF1_LOCAL
            write(*,*) 'veff_fine', VEFF1_LOCAL
        ENDIF
        IF(DFRAC>0.0D0)THEN
            write(*,*) 'reff_dust',REFFD
            write(*,*) 'veff_dust',VEFFD
        ENDIF
        IF((1-(FMFRAC+DFRAC))>0.0D0)THEN
            write(*,*) 'reff_coarse', REFF2_LOCAL
            write(*,*) 'veff_coarse', VEFF2_LOCAL
        ENDIF

        WRITE(*,*)'fine mode number density',ARSLND1
        WRITE(*,*)'coarse mode number density',ARSLND2
        WRITE(*,*)'dust mode number density',ARSLNDD


          MRRD = MRRDT
          MRID = MRIDT
          IF(ARSLND1==0)THEN
             MRR1=0
             MRI1=0
          ENDIF
          IF(ARSLND2==0)THEN
             MRR2=0
             MRI2=0
          ENDIF
          IF(ARSLNDD==0)THEN
             MRRD=0
             MRID=0
          ENDIF  
            
          CEXT_ARSL_BAND = ARSLND1*CEXT1_MIE+ARSLND2*CEXT2_MIE+ARSLNDD*CEXT_DUSTF
          CSCAT_ARSL_BAND = ARSLND1*CSCAT1_MIE+ARSLND2*CSCAT2_MIE+ARSLNDD*CSCAT_DUSTF
          
          DO IWV_BAND=1,NWV_BAND
             IF (FMFRAC==0.0D0) THEN
                PHMXMIE_ARSL_PACE(IWV_BAND,:,0)=PHMXMIE_LOCAL2_MIE(IWV_BAND,:,0)
             ELSEIF (FMFRAC>0.0D0) THEN
                PHMXMIE_ARSL_PACE(IWV_BAND,:,0)=PHMXMIE_LOCAL1_MIE(IWV_BAND,:,0)
             ENDIF

             PHMXMIE_ARSL_PACE(IWV_BAND,:,1:6)= ( &
				 ARSLND1*CSCAT1_MIE(IWV_BAND)* PHMXMIE_LOCAL1_MIE(IWV_BAND,:,1:6) + &
				 ARSLND2*CSCAT2_MIE(IWV_BAND)* PHMXMIE_LOCAL2_MIE(IWV_BAND,:,1:6) + &
				 ARSLNDD*CSCAT_DUSTF(IWV_BAND)*PHMX_DUSTF(IWV_BAND,:,1:6))/CSCAT_ARSL_BAND(IWV_BAND)


!             PHMXMIE_ARSL_PACE(IWV_BAND,:,1)= ( &
!                  ARSLND1*CSCAT1_MIE(IWV_BAND)* PHMXMIE_LOCAL1_MIE(IWV_BAND,:,1) + &
!                  ARSLND2*CSCAT2_MIE(IWV_BAND)* PHMXMIE_LOCAL2_MIE(IWV_BAND,:,1) + &
!                  ARSLNDD*CSCAT_DUSTF(IWV_BAND)*PHMX_DUSTF(IWV_BAND,:,1))/CSCAT_ARSL_BAND(IWV_BAND)
!
!             PHMXMIE_ARSL_PACE(IWV_BAND,:,2)=( &
!                  ARSLND1*CSCAT1_MIE(IWV_BAND)*PHMXMIE_LOCAL1_MIE(IWV_BAND,:,5) + &
!                  ARSLND2*CSCAT2_MIE(IWV_BAND)*PHMXMIE_LOCAL2_MIE(IWV_BAND,:,5) + &
!                  ARSLNDD*CSCAT_DUSTF(IWV_BAND)*PHMX_DUSTF(IWV_BAND,:,2))/CSCAT_ARSL_BAND(IWV_BAND)
!
!             PHMXMIE_ARSL_PACE(IWV_BAND,:,3)=(&
!                  ARSLND1*CSCAT1_MIE(IWV_BAND)*PHMXMIE_LOCAL1_MIE(IWV_BAND,:,2) + &
!                  ARSLND2*CSCAT2_MIE(IWV_BAND)*PHMXMIE_LOCAL2_MIE(IWV_BAND,:,2) + &
!                  ARSLNDD*CSCAT_DUSTF(IWV_BAND)*PHMX_DUSTF(IWV_BAND,:,3))/CSCAT_ARSL_BAND(IWV_BAND)
!
!             PHMXMIE_ARSL_PACE(IWV_BAND,:,4)=(&
!                  ARSLND1*CSCAT1_MIE(IWV_BAND)*PHMXMIE_LOCAL1_MIE(IWV_BAND,:,3) + &
!                  ARSLND2*CSCAT2_MIE(IWV_BAND)*PHMXMIE_LOCAL2_MIE(IWV_BAND,:,3) + &
!                  ARSLNDD*CSCAT_DUSTF(IWV_BAND)*PHMX_DUSTF(IWV_BAND,:,4))/CSCAT_ARSL_BAND(IWV_BAND)
!
!             PHMXMIE_ARSL_PACE(IWV_BAND,:,5)=(&
!                  ARSLND1*CSCAT1_MIE(IWV_BAND)*PHMXMIE_LOCAL1_MIE(IWV_BAND,:,6) + &
!                  ARSLND2*CSCAT2_MIE(IWV_BAND)*PHMXMIE_LOCAL2_MIE(IWV_BAND,:,6) + &
!                  ARSLNDD*CSCAT_DUSTF(IWV_BAND)*PHMX_DUSTF(IWV_BAND,:,5))/CSCAT_ARSL_BAND(IWV_BAND)
!
!             PHMXMIE_ARSL_PACE(IWV_BAND,:,6)=(&
!                  ARSLND1*CSCAT1_MIE(IWV_BAND)*PHMXMIE_LOCAL1_MIE(IWV_BAND,:,4) + &
!                  ARSLND2*CSCAT2_MIE(IWV_BAND)*PHMXMIE_LOCAL2_MIE(IWV_BAND,:,4) + &
!                  ARSLNDD*CSCAT_DUSTF(IWV_BAND)*PHMX_DUSTF(IWV_BAND,:,6))/CSCAT_ARSL_BAND(IWV_BAND)
          END DO
       ENDIF
ENDIF






 
 IF(FREEFORMFLAG>0 .AND. IAEROSOL==-99 .AND. MIX_FLAG==2) THEN
    write(*,*) 'scattering calculations for external mixing started'
    CALL ARSL_REF_INDX_INIT_EMIX(NWV_BAND,WV_BAND_MICRON,RHI,R0DL,R0WS,R0BC,R0S,R0SS)
    CALL HYGROSCOPIC_GROWTH_EMIX(R0DL,R0WS,R0BC,R0S,R0SS,RHI, RRH_DL,RRH_WS,RRH_BC,RRH_S,RRH_SS)
    CALL HYGROSCOPIC_GROWTH_IMIX(1.0D0,R0SS,RHI, RRH_F,RRH_C)

     NDISTR=2

    !CONVERT TO NUMBER SPACE
    REFF1_DL = EXP(LOG(RRH_DL)-3.0D0*VDL*VDL)
    REFF1_WS = EXP(LOG(RRH_WS)-3.0D0*VWS*VWS)
    REFF1_BC = EXP(LOG(RRH_BC)-3.0D0*VBC*VBC)
    REFF1_S = EXP(LOG(RRH_S)-3.0D0*VS*VS)
    REFF2_SS = EXP(LOG(RRH_C)-3.0D0*VSS*VSS)

    IF(NMODE==2)THEN
    RTMP = 4.0D0*PI*(REFF1_DL**3)/3.0D0
    RTMP1 = RF1/RTMP*EXP(-4.5D0*VDL*VDL)
    RTMP = 4.0D0*PI*(REFF1_WS**3)/3.0D0
    RTMP2 = RF2/RTMP*EXP(-4.5D0*VWS*VWS)
    RTMP = 4.0D0*PI*(REFF1_BC**3)/3.0D0
    RTMP3 = RF3/RTMP*EXP(-4.5D0*VBC*VBC)
    RTMP = 4.0D0*PI*(REFF1_S**3)/3.0D0
    RTMP4 = (1-(RF1+RF2+RF3))/RTMP*EXP(-4.5D0*VS*VS)

    RTMP = RTMP1+RTMP2+RTMP3+RTMP4
    ARSLND1_DL = RTMP1/RTMP
    ARSLND1_WS = RTMP2/RTMP
    ARSLND1_BC = RTMP3/RTMP
    ARSLND1_S = RTMP4/RTMP
    ENDIF

    IF(NMODE==3)THEN
    RTMP = 4.0D0*PI*(REFF1_WS**3)/3.0D0
    RTMP2 = RF2/RTMP*EXP(-4.5D0*VWS*VWS)
    RTMP = 4.0D0*PI*(REFF1_BC**3)/3.0D0
    RTMP3 = RF3/RTMP*EXP(-4.5D0*VBC*VBC)
    RTMP = 4.0D0*PI*(REFF1_S**3)/3.0D0
    RTMP4 = (1-(RF2+RF3))/RTMP*EXP(-4.5D0*VS*VS)

    RTMP = RTMP2+RTMP3+RTMP4
    ARSLND1_DL = DFRAC*DSFRAC !dummy (not in calculations)
    ARSLND1_WS = RTMP2/RTMP
    ARSLND1_BC = RTMP3/RTMP
    ARSLND1_S = RTMP4/RTMP
    ENDIF

 
    MRR1_DL(1:NWV_BAND) = MR_DUSTF_TMP1(1:NWV_BAND)
    MRR1_WS(1:NWV_BAND) = MR_WATER_SOLUBLE_TMP1(1:NWV_BAND)
    MRR1_BC(1:NWV_BAND) = MR_BRC_TMP1(1:NWV_BAND)
    MRR1_S(1:NWV_BAND) = MR_SOOTF_TMP1(1:NWV_BAND)
    MRR2_SS(1:NWV_BAND) = MR_ZIACR(1:NWV_BAND)

    MRI1_DL(1:NWV_BAND) = MI_DUSTF_TMP1(1:NWV_BAND)
    MRI1_WS(1:NWV_BAND) = MI_WATER_SOLUBLE_TMP1(1:NWV_BAND)
    MRI1_BC(1:NWV_BAND) = MI_BRC_TMP1(1:NWV_BAND)
    MRI1_S(1:NWV_BAND) = MI_SOOTF_TMP1(1:NWV_BAND)
    MRI2_SS(1:NWV_BAND) = MI_ZIACR(1:NWV_BAND)
    
    DEALLOCATE(MR_SOOTF_TMP1,MI_SOOTF_TMP1,MR_DUSTF_TMP1,MI_DUSTF_TMP1, &
         MR_WATER_SOLUBLE_TMP1,MI_WATER_SOLUBLE_TMP1,MR_BRC_TMP1, MI_BRC_TMP1, &
         MR_ZIACR, MI_ZIACR)


    VDLN = VDL*VDL
    VWSN = VWS*VWS
    VBCN = VBC*VBC
    VSN = VS*VS
    VSSN = VSS*VSS

    REFF1_DL = REFF1_DL*EXP(2.5D0*VDLN)
    REFF1_WS = REFF1_WS*EXP(2.5D0*VWSN)
    REFF1_BC = REFF1_BC*EXP(2.5D0*VBCN)
    REFF1_S = REFF1_S*EXP(2.5D0*VSN)
    REFF2_SS = REFF2_SS*EXP(2.5D0*VSSN)

    VDLN = EXP(VDLN)-1.0D0
    VWSN = EXP(VWSN)-1.0D0
    VBCN = EXP(VBCN)-1.0D0
    VSN = EXP(VSN)-1.0D0
    VSSN = EXP(VSSN)-1.0D0

    
    CALL DUST_SCAT_PROP_INIT(IREFF,IVAR,PHMX_DUST_TMP,CEXT_DUST_TMP,CSCAT_DUST_TMP,SCATANG)
    
    DO IWV_BAND=1,NWV_BAND
       WV_tmp=WV_BAND_MICRON(IWV_BAND)

       CEXT_DUST(IWV_BAND)=POLINT_SIMPLE(NWV_D,WVL,CEXT_DUST_TMP,WV_tmp,3)
       CSCAT_DUST(IWV_BAND)=POLINT_SIMPLE(NWV_D,WVL,CSCAT_DUST_TMP,WV_tmp,3)
       MRR_DUST(IWV_BAND)=POLINT_SIMPLE(NWV_D,WVL,MRD,WV_tmp,3)
       MRI_DUST(IWV_BAND)=POLINT_SIMPLE(NWV_D,WVL,MID,WV_tmp,3)
       DO IANG=1,NSCATANG
          DO IPHMX=1,6
             PHMX_DUST_TMP2(IWV_BAND,IANG,IPHMX)=POLINT_SIMPLE(NWV_D,WVL,&
                  PHMX_DUST_TMP(:,IANG,IPHMX),WV_tmp,3)
          END DO
       END DO
        END DO

    IF(NMODE==2)THEN
    RTMP = 4.0D0*PI*(REFF2_SS**3)/3.0D0
    RTMP5 = FRACS/RTMP*EXP(-4.5D0*VSS*VSS)
    
    SIGMA_GD = SQRT(LOG(SIGMA(IVAR)))
    R_GD = REFF(IREFF)/EXP(2.5*SIGMA_GD*SIGMA_GD)
   
    RTMP = 4.0D0*PI*(R_GD**3)/3.0D0
    RTMP6 = (1-FRACS)/RTMP*EXP(-4.5D0*SIGMA_GD*SIGMA_GD)
    RTMP = RTMP5+RTMP6
    ARSLND2_SS = RTMP5/RTMP
    ARSLND2_D = RTMP6/RTMP
    ENDIF

    IF(NMODE==3)THEN
       ARSLND2_SS=1-(FMFRAC+DFRAC)
       ARSLND2_D=DFRAC*(1-DSFRAC)
    ENDIF

    
    !MIE SCATTERING CALCULATION
     DO IWV_BAND=1,NWV_BAND
        IF(ARSLND1_DL>0.0D0 .AND. FREEFORMFLAG<=1)THEN
           CALL SPHER_INTERFACE(NDISTR,REFF1_DL,VDLN,WV_BAND_MICRON(IWV_BAND),&
                MRR1_DL(IWV_BAND),MRI1_DL(IWV_BAND),AA1,BB1,AA2,BB2,GAMMAI,&
                REFFO,VEFFO,AREA,CEXT1_DL,CSCAT1_DL,NANGMIE_LOCAL,PHMXMIE_LOCAL1_DL)
        ELSE
           CEXT1_DL = 0.0D0
           CSCAT1_DL = 0.0D0
        ENDIF
        NUM_SCAT_ANG = NANGMIE_LOCAL
        CEXT1A_DL(IWV_BAND)=CEXT1_DL
        CSCAT1A_DL(IWV_BAND)=CSCAT1_DL
        PHMXMIE_LOCAL1A_DL(IWV_BAND,:,:)=PHMXMIE_LOCAL1_DL(:,:)
           

        IF(FMFRAC>0.0D0 .AND. ARSLND1_WS>0.0D0 .AND. FREEFORMFLAG<=1)THEN
           CALL SPHER_INTERFACE(NDISTR,REFF1_WS,VWSN,WV_BAND_MICRON(IWV_BAND),&
                MRR1_WS(IWV_BAND),MRI1_WS(IWV_BAND),AA1,BB1,AA2,BB2,GAMMAI,&
                REFFO,VEFFO,AREA,CEXT1_WS,CSCAT1_WS,NANGMIE_LOCAL,PHMXMIE_LOCAL1_WS)
        ELSE
           CEXT1_WS = 0.0D0
           CSCAT1_WS = 0.0D0
        ENDIF
        NUM_SCAT_ANG = NANGMIE_LOCAL
        CEXT1A_WS(IWV_BAND)=CEXT1_WS
        CSCAT1A_WS(IWV_BAND)=CSCAT1_WS
        PHMXMIE_LOCAL1A_WS(IWV_BAND,:,:)=PHMXMIE_LOCAL1_WS(:,:)
                   
        
        IF(FMFRAC>0.0D0 .AND. ARSLND1_BC>0.0D0 .AND. FREEFORMFLAG<=1)THEN
           CALL SPHER_INTERFACE(NDISTR,REFF1_BC,VBCN,WV_BAND_MICRON(IWV_BAND),&
                MRR1_BC(IWV_BAND),MRI1_BC(IWV_BAND),AA1,BB1,AA2,BB2,GAMMAI,&
                REFFO,VEFFO,AREA,CEXT1_BC,CSCAT1_BC,NANGMIE_LOCAL,PHMXMIE_LOCAL1_BC)
        ELSE
           CEXT1_BC = 0.0D0
           CSCAT1_BC = 0.0D0
        ENDIF
        NUM_SCAT_ANG = NANGMIE_LOCAL
        CEXT1A_BC(IWV_BAND)=CEXT1_BC
        CSCAT1A_BC(IWV_BAND)=CSCAT1_BC
        PHMXMIE_LOCAL1A_BC(IWV_BAND,:,:)=PHMXMIE_LOCAL1_BC(:,:)
          
        
        IF(FMFRAC>0.0D0 .AND. ARSLND1_S>0.0D0 .AND. FREEFORMFLAG<=1)THEN
           CALL SPHER_INTERFACE(NDISTR,REFF1_S,VSN,WV_BAND_MICRON(IWV_BAND),&
                MRR1_S(IWV_BAND),MRI1_S(IWV_BAND),AA1,BB1,AA2,BB2,GAMMAI,&
                REFFO,VEFFO,AREA,CEXT1_S,CSCAT1_S,NANGMIE_LOCAL,PHMXMIE_LOCAL1_S)
        ELSE
           CEXT1_S = 0.0D0
           CSCAT1_S = 0.0D0
        ENDIF
        NUM_SCAT_ANG = NANGMIE_LOCAL
        CEXT1A_S(IWV_BAND)=CEXT1_S
        CSCAT1A_S(IWV_BAND)=CSCAT1_S
        PHMXMIE_LOCAL1A_S(IWV_BAND,:,:)=PHMXMIE_LOCAL1_S(:,:)
           


        CALL SPHER_INTERFACE(NDISTR,REFF2_SS,VSSN,WV_BAND_MICRON(IWV_BAND),&
               MRR2_SS(IWV_BAND),MRI2_SS(IWV_BAND),AA1,BB1,AA2,BB2,GAMMAI,&
                REFFO,VEFFO,AREA,CEXT2_SS,CSCAT2_SS,NANGMIE_LOCAL,PHMXMIE_LOCAL2_SS)

        NUM_SCAT_ANG = NANGMIE_LOCAL
        CEXT2A_SS(IWV_BAND)=CEXT2_SS
        CSCAT2A_SS(IWV_BAND)=CSCAT2_SS
        PHMXMIE_LOCAL2A_SS(IWV_BAND,:,:)=PHMXMIE_LOCAL2_SS(:,:)
     ENDDO


    !angle interpolation dust 
     DO IWV_BAND=1,NWV_BAND
        DO IANG=1,NUM_SCAT_ANG
           DO IPHMX=1,6
              PHMX_DUST(IWV_BAND,IANG,IPHMX)=POLINT_SIMPLE(NSCATANG,SCATANG,PHMX_DUST_TMP2(IWV_BAND,:,IPHMX),&
                   PHMXMIE_LOCAL2A_SS(IWV_BAND,IANG,0),3)
           END DO
        END DO
     END DO

     SIGMA_GDL = SQRT(LOG(VDLN+1))
     SIGMA_GWS = SQRT(LOG(VWSN+1))
     SIGMA_GBC = SQRT(LOG(VBCN+1))
     SIGMA_GS = SQRT(LOG(VSN+1))
     SIGMA_GSS = SQRT(LOG(VSSN+1))
     SIGMA_GD = SQRT(LOG(SIGMA(IVAR)))
      
     R_GDL = REFF1_DL/EXP(2.5D0*SIGMA_GDL*SIGMA_GDL)
     R_GWS = REFF1_WS/EXP(2.5D0*SIGMA_GWS*SIGMA_GWS)
     R_GBC = REFF1_BC/EXP(2.5D0*SIGMA_GBC*SIGMA_GBC)
     R_GS = REFF1_S/EXP(2.5D0*SIGMA_GS*SIGMA_GS)
     R_GSS = REFF2_SS/EXP(2.5D0*SIGMA_GSS*SIGMA_GSS)
     R_GD = REFF(IREFF)/EXP(2.5*SIGMA_GD*SIGMA_GD)


     IF(NMODE==2)THEN
     !external mixing of fine mode aerosol components
     CEXTF = ARSLND1_DL*CEXT1A_DL + ARSLND1_WS*CEXT1A_WS +ARSLND1_BC*CEXT1A_BC + &
          ARSLND1_S*CEXT1A_S
     CSCATF = ARSLND1_DL*CSCAT1A_DL + ARSLND1_WS*CSCAT1A_WS +ARSLND1_BC*CSCAT1A_BC + &
          ARSLND1_S*CSCAT1A_S

     CEXTC = ARSLND2_SS*CEXT2A_SS + ARSLND2_D*CEXT_DUST
     CSCATC = ARSLND2_SS*CSCAT2A_SS + ARSLND2_D*CSCAT_DUST

     MRR2=FRACS*MRR2_SS+(1-FRACS)*MRR_DUST
     MRI2=FRACS*MRI2_SS+(1-FRACS)*MRI_DUST
     MRR1=rf1*MRR1_DL+rf2*MRR1_WS+rf3*MRR1_BC+(1-(rf1+rf2+rf3))*MRR1_S
     MRI1=rf1*MRI1_DL+rf2*MRI1_WS+rf3*MRI1_BC+(1-(rf1+rf2+rf3))*MRI1_S
    
     IF (FMFRAC==1.0) THEN
        MRR2=0.0D0
        MRI2=0.D0
     ELSEIF (FMFRAC==0.0D0) THEN
        MRR1=0.0D0
        MRR1=0.0D0
        ENDIF

     !CALCULATING MOMENTS OF EACH COMPONENT
     M21DL = R_GDL*R_GDL*EXP(2*SIGMA_GDL*SIGMA_GDL)
     M31DL = R_GDL*R_GDL*R_GDL*EXP(4.5*SIGMA_GDL*SIGMA_GDL)
     
     M21WS = R_GWS*R_GWS*EXP(2*SIGMA_GWS*SIGMA_GWS)
     M31WS = R_GWS*R_GWS*R_GWS*EXP(4.5*SIGMA_GWS*SIGMA_GWS)

     M21BC = R_GBC*R_GBC*EXP(2*SIGMA_GBC*SIGMA_GBC)
     M31BC = R_GBC*R_GBC*R_GBC*EXP(4.5*SIGMA_GBC*SIGMA_GBC)

     M21S = R_GS*R_GS*EXP(2*SIGMA_GS*SIGMA_GS)
     M31S = R_GS*R_GS*R_GS*EXP(4.5*SIGMA_GS*SIGMA_GS)

     M22SS = R_GSS*R_GSS*EXP(2*SIGMA_GSS*SIGMA_GSS)
     M32SS = R_GSS*R_GSS*R_GSS*EXP(4.5*SIGMA_GSS*SIGMA_GSS)

     M2D = R_GD*R_GD*EXP(2*SIGMA_GD*SIGMA_GD)
     M3D = R_GD*R_GD*R_GD*EXP(4.5*SIGMA_GD*SIGMA_GD)


     !EFFECTIVE RADIUS AFTER MIXING
     REFF1 = (ARSLND1_DL*M31DL +ARSLND1_WS*M31WS +ARSLND1_BC*M31BC +ARSLND1_S*M31S)/&
          (ARSLND1_DL*M21DL +ARSLND1_WS*M21WS+ARSLND1_BC*M21BC +ARSLND1_S*M21S)
     VEFF1 = ARSLND1_DL*VDLN + ARSLND1_WS*VWSN + ARSLND1_BC*VBCN + ARSLND1_S*VSN

     REFF2 = (ARSLND2_SS*M32SS + ARSLND2_D*M3D)/(ARSLND2_SS*M22SS +ARSLND2_D*M2D)
     VEFF2 = ARSLND2_SS*VSSN + ARSLND2_D*EXP(LOG(SIGMA(IVAR))-1)


     !CONVERTING TO GEOMETRICAL VALUES
     SIGMA_GF = SQRT(LOG(VEFF1)+1)
     R_GF = REFF1/EXP(2.5D0*SIGMA_GF*SIGMA_GF)

     SIGMA_GC =SQRT(LOG(VEFF2)+1)
     R_GC = REFF2/EXP(2.5D0*SIGMA_GC*SIGMA_GC)


     !CALCULATE AEROSOL COMPOSITION FINE MODE AND COARSE MODE
     RTMP=4.0D0*PI*(R_GF**3)/3.0D0
     RTMP1=FMFRAC/RTMP*EXP(-4.5D0*SIGMA_GF*SIGMA_GF)
     RTMP=4.0D0*PI*(R_GC**3)/3.0D0
     RTMP2=(1.0D0-FMFRAC)/RTMP*EXP(-4.5D0*SIGMA_GC*SIGMA_GC)
     RTMP=RTMP1+RTMP2
     ARSLND1=RTMP1/RTMP
     ARSLND2=RTMP2/RTMP
     IF (FMFRAC==0.0D0) THEN
        ARSLND1=0.0D0
     ENDIF
     IF(FMFRAC==1.0D0) THEN
        ARSLND2=0.0D0
     ENDIF


     write(*,*) '****************************************************************'
     WRITE(*,*) 'NUMBER OF AEROSOL MODES = 2'
     write(*,*) 'FINE AND COARSE MODE - EXTERNAL MIXING'
     write(*,*) '****************************************************************'
     IF(FMFRAC>0.0D0)THEN
        WRITE(*,*) 'REFF FINE MODE',REFF1
        WRITE(*,*) 'VEFF FINE MODE', VEFF1
    ENDIF
    IF((1-FMFRAC)>0.0D0)THEN
        WRITE(*,*) 'REFF COARSE MODE',REFF2
        WRITE(*,*) 'VEFF COARSE MODE', VEFF2
    ENDIF
    WRITE(*,*) 'fine mode number density', ARSLND1
    WRITE(*,*) 'coarse mode number density', ARSLND2

     !external mixing of spherical and non-spherical coarse mode aerosol phase  matrix
     FRACSV = ARSLND2_SS
     
     DO IWV_BAND=1,NWV_BAND

		PHMXC(IWV_BAND,:,1:6)= &
          (FRACSV *CSCAT2A_SS(IWV_BAND)*PHMXMIE_LOCAL2A_SS(IWV_BAND,:,1:6) &
	   +(1-FRACSV)*CSCAT_DUST(IWV_BAND)*         PHMX_DUST(IWV_BAND,:,1:6))&
           /CSCATC(IWV_BAND)

!        PHMXC(IWV_BAND,:,1)=(FRACSV*CSCAT2A_SS(IWV_BAND)*PHMXMIE_LOCAL2A_SS &
!             (IWV_BAND,:,1)+(1-FRACSV)*CSCAT_DUST(IWV_BAND)* &
!             PHMX_DUST(IWV_BAND,:,1))/CSCATC(IWV_BAND)
!        PHMXC(IWV_BAND,:,2)=(FRACSV*CSCAT2A_SS(IWV_BAND)*PHMXMIE_LOCAL2A_SS &
!             (IWV_BAND,:,5)+(1-FRACSV)*CSCAT_DUST(IWV_BAND)* &
!             PHMX_DUST(IWV_BAND,:,2))/CSCATC(IWV_BAND)
!        PHMXC(IWV_BAND,:,3)=(FRACSV*CSCAT2A_SS(IWV_BAND)*PHMXMIE_LOCAL2A_SS &
!             (IWV_BAND,:,2)+(1-FRACSV)*CSCAT_DUST(IWV_BAND)* &
!             PHMX_DUST(IWV_BAND,:,3))/CSCATC(IWV_BAND)
!        PHMXC(IWV_BAND,:,4)=(FRACSV*CSCAT2A_SS(IWV_BAND)*PHMXMIE_LOCAL2A_SS &
!             (IWV_BAND,:,3)+(1-FRACSV)*CSCAT_DUST(IWV_BAND)* &
!             PHMX_DUST(IWV_BAND,:,4))/CSCATC(IWV_BAND)
!        PHMXC(IWV_BAND,:,5)=(FRACSV*CSCAT2A_SS(IWV_BAND)*PHMXMIE_LOCAL2A_SS &
!             (IWV_BAND,:,6)+(1-FRACSV)*CSCAT_DUST(IWV_BAND)* &
!             PHMX_DUST(IWV_BAND,:,5))/CSCATC(IWV_BAND)
!        PHMXC(IWV_BAND,:,6)=(FRACSV*CSCAT2A_SS(IWV_BAND)*PHMXMIE_LOCAL2A_SS &
!             (IWV_BAND,:,4)+(1-FRACSV)*CSCAT_DUST(IWV_BAND)* &
!             PHMX_DUST(IWV_BAND,:,6))/CSCATC(IWV_BAND)
         END DO

         !EXTERNAL MIXING FINE MODE AEROSOLS
         DO IWV_BAND=1,NWV_BAND
            DO IELE=1,6
               PHMXF(IWV_BAND,:,IELE) = ( &
                    ARSLND1_DL*CSCAT1A_DL(IWV_BAND)*PHMXMIE_LOCAL1A_DL(IWV_BAND,:,IELE) + &
                    ARSLND1_WS*CSCAT1A_WS(IWV_BAND)*PHMXMIE_LOCAL1A_WS(IWV_BAND,:,IELE) + &
                    ARSLND1_BC*CSCAT1A_BC(IWV_BAND)*PHMXMIE_LOCAL1A_BC(IWV_BAND,:,IELE) + &
                    ARSLND1_S*CSCAT1A_S(IWV_BAND)*PHMXMIE_LOCAL1A_S(IWV_BAND,:,IELE))/ CSCATF(IWV_BAND)
            ENDDO
         ENDDO
         
         IF(FMFRAC==0.0D0) THEN
            PHMXF=0.0D0
         ENDIF
         IF(FMFRAC==1.0D0) THEN
            PHMXC=0.0D0
		 ENDIF

         
    CEXT_ARSL_BAND=ARSLND1*CEXTF+ARSLND2*CEXTC
    CSCAT_ARSL_BAND=ARSLND1*CSCATF+ARSLND2*CSCATC

     DO IWV_BAND=1,NWV_BAND
        PHMXMIE_ARSL_PACE(IWV_BAND,:,0)=PHMXMIE_LOCAL2A_SS(IWV_BAND,:,0)

        PHMXMIE_ARSL_PACE(IWV_BAND,:,1:6)= &
            (ARSLND1*CSCATF(IWV_BAND)*PHMXF(IWV_BAND,:,1:6) + &
        	 ARSLND2*CSCATC(IWV_BAND)*PHMXC(IWV_BAND,:,1:6)) / CSCAT_ARSL_BAND(IWV_BAND)


!        PHMXMIE_ARSL_PACE(IWV_BAND,:,1)=(ARSLND1*CSCATF(IWV_BAND)* PHMXF(IWV_BAND,:,1) + &
!             ARSLND2*CSCATC(IWV_BAND)*PHMXC(IWV_BAND,:,1))/CSCAT_ARSL_BAND(IWV_BAND)
!
!        PHMXMIE_ARSL_PACE(IWV_BAND,:,2)=(ARSLND1*CSCATF(IWV_BAND)*PHMXF(IWV_BAND,:,5) + &
!             ARSLND2*CSCATC(IWV_BAND)*PHMXC(IWV_BAND,:,2))/CSCAT_ARSL_BAND(IWV_BAND)
!
!        PHMXMIE_ARSL_PACE(IWV_BAND,:,3)=(ARSLND1*CSCATF(IWV_BAND)*PHMXF(IWV_BAND,:,2) + &
!             ARSLND2*CSCATC(IWV_BAND)*PHMXC(IWV_BAND,:,3))/CSCAT_ARSL_BAND(IWV_BAND)
!
!        PHMXMIE_ARSL_PACE(IWV_BAND,:,4)=(ARSLND1*CSCATF(IWV_BAND)*PHMXF(IWV_BAND,:,3) + &
!             ARSLND2*CSCATC(IWV_BAND)*PHMXC(IWV_BAND,:,4))/CSCAT_ARSL_BAND(IWV_BAND)
!
!        PHMXMIE_ARSL_PACE(IWV_BAND,:,5)=(ARSLND1*CSCATF(IWV_BAND)*PHMXF(IWV_BAND,:,6) + &
!             ARSLND2*CSCATC(IWV_BAND)*PHMXC(IWV_BAND,:,5))/CSCAT_ARSL_BAND(IWV_BAND)
!
!        PHMXMIE_ARSL_PACE(IWV_BAND,:,6)=(ARSLND1*CSCATF(IWV_BAND)* PHMXF(IWV_BAND,:,4) + &
!             ARSLND2*CSCATC(IWV_BAND)*PHMXC(IWV_BAND,:,6))/CSCAT_ARSL_BAND(IWV_BAND)

     ENDDO
  ENDIF


  IF(NMODE==3)THEN !dust like is not included in fine mode
     write(*,*) 'nmode 3 routing started'
     
    M21DL = R_GDL*R_GDL*EXP(2*SIGMA_GDL*SIGMA_GDL)
    M31DL = R_GDL*R_GDL*R_GDL*EXP(4.5*SIGMA_GDL*SIGMA_GDL)
    M21WS = R_GWS*R_GWS*EXP(2*SIGMA_GWS*SIGMA_GWS)
    M31WS = R_GWS*R_GWS*R_GWS*EXP(4.5*SIGMA_GWS*SIGMA_GWS)
    M21BC = R_GBC*R_GBC*EXP(2*SIGMA_GBC*SIGMA_GBC)
    M31BC = R_GBC*R_GBC*R_GBC*EXP(4.5*SIGMA_GBC*SIGMA_GBC)
    M21S = R_GS*R_GS*EXP(2*SIGMA_GS*SIGMA_GS)
    M31S = R_GS*R_GS*R_GS*EXP(4.5*SIGMA_GS*SIGMA_GS)
    M2D = R_GD*R_GD*EXP(2*SIGMA_GD*SIGMA_GD)
    M3D = R_GD*R_GD*R_GD*EXP(4.5*SIGMA_GD*SIGMA_GD)

    !fine mode
    CEXTF = ARSLND1_WS*CEXT1A_WS + ARSLND1_BC*CEXT1A_BC + ARSLND1_S*CEXT1A_S
    CSCATF = ARSLND1_WS*CSCAT1A_WS + ARSLND1_BC*CSCAT1A_BC + ARSLND1_S*CSCAT1A_S

    REFF1 = (ARSLND1_WS*M31WS +ARSLND1_BC*M31BC +ARSLND1_S*M31S)/&
            (ARSLND1_WS*M21WS+ARSLND1_BC*M21BC +ARSLND1_S*M21S)
    VEFF1 = ARSLND1_WS*VWSN + ARSLND1_BC*VBCN + ARSLND1_S*VSN

    MRR1=rf2*MRR1_WS + rf3*MRR1_BC + (1-(rf2+rf3))*MRR1_S
    MRI1=rf2*MRI1_WS + rf3*MRI1_BC + (1-(rf2+rf3))*MRI1_S

    !COARSE MODE
    REFF2 = REFF2_SS
    VEFF2 = VSSN

    MRR2=MRR2_SS
    MRI2=MRI2_SS


    
    DO IWV_BAND=1,NWV_BAND
    DO IELE=1,6
    PHMXF(IWV_BAND,:,IELE) = ( &
    ARSLND1_WS*CSCAT1A_WS(IWV_BAND)*PHMXMIE_LOCAL1A_WS(IWV_BAND,:,IELE) + &
    ARSLND1_BC*CSCAT1A_BC(IWV_BAND)*PHMXMIE_LOCAL1A_BC(IWV_BAND,:,IELE) + &
    ARSLND1_S*CSCAT1A_S(IWV_BAND)*PHMXMIE_LOCAL1A_S(IWV_BAND,:,IELE))/ CSCATF(IWV_BAND)
    ENDDO
    ENDDO

    IF(FMFRAC==0.0D0) THEN
       PHMXF=0.0D0
       CEXTF=0.0D0
       CSCATF=0.0D0
    ENDIF 

    
    !dust mode
    RTMP2=(1-DSFRAC)/(4.0D0*PI*(R_GD**3)/3.0D0)*EXP(-4.5D0*SIGMA_GD*SIGMA_GD) !dust
    RTMP3=DSFRAC/(4.0D0*PI*(R_GDL**3)/3.0D0)*EXP(-4.5D0*SIGMA_GDL*SIGMA_GDL) ! other coarse mode
    DSFRACV=RTMP3/(RTMP2+RTMP3)

    !DUST MODE
    REFFD=(DSFRACV*M31DL+(1-DSFRACV)*M3D)/(DSFRACV*M21DL+(1-DSFRACV)*M2D)
    IF(DFRAC==0.0D0)THEN
       REFFD=0.0D0
    ENDIF
    VEFFD=DSFRACV*VDLN+(1-DSFRACV)*EXP(LOG(SIGMA(IVAR))-1)

    CEXT_DUSTF(:)=DSFRACV*CEXT1A_DL(:)+(1-DSFRACV)*CEXT_DUST(:)
    CSCAT_DUSTF(:)=DSFRACV*CSCAT1A_DL(:)+(1-DSFRACV)*CSCAT_DUST(:)

    MRRDT = DSFRAC*MRR1_DL+(1-DSFRAC)*MRR_DUST
    MRIDT = DSFRAC*MRR1_DL+(1-DSFRAC)*MRI_DUST

    MRRD = MRRDT
    MRID = MRIDT

    DO IWV_BAND=1,NWV_BAND
        PHMX_DUSTF(IWV_BAND,:,1:6)= &
            (DSFRACV *CSCAT1A_DL(IWV_BAND)*PHMXMIE_LOCAL1A_DL(IWV_BAND,:,1:6) &
        + (1-DSFRACV)*CSCAT_DUST(IWV_BAND)*PHMX_DUST(IWV_BAND,:,1:6))/CSCAT_DUSTF(IWV_BAND)

!        PHMX_DUSTF(IWV_BAND,:,1)=(DSFRACV*CSCAT1A_DL(IWV_BAND)*PHMXMIE_LOCAL1A_DL &
!        (IWV_BAND,:,1)+(1-DSFRACV)*CSCAT_DUST(IWV_BAND)* &
!        PHMX_DUST(IWV_BAND,:,1))/CSCAT_DUSTF(IWV_BAND)
!
!        PHMX_DUSTF(IWV_BAND,:,2)=(DSFRACV*CSCAT1A_DL(IWV_BAND)*PHMXMIE_LOCAL1A_DL &
!        (IWV_BAND,:,5)+(1-DSFRACV)*CSCAT_DUST(IWV_BAND)* &
!        PHMX_DUST(IWV_BAND,:,2))/CSCAT_DUSTF(IWV_BAND)
!
!        PHMX_DUSTF(IWV_BAND,:,3)=(DSFRACV*CSCAT1A_DL(IWV_BAND)*PHMXMIE_LOCAL1A_DL &
!        (IWV_BAND,:,2)+(1-DSFRACV)*CSCAT_DUST(IWV_BAND)* &
!        PHMX_DUST(IWV_BAND,:,3))/CSCAT_DUSTF(IWV_BAND)
!
!        PHMX_DUSTF(IWV_BAND,:,4)=(DSFRACV*CSCAT1A_DL(IWV_BAND)*PHMXMIE_LOCAL1A_DL &
!        (IWV_BAND,:,3)+(1-DSFRACV)*CSCAT_DUST(IWV_BAND)* &
!        PHMX_DUST(IWV_BAND,:,4))/CSCAT_DUSTF(IWV_BAND)
!
!        PHMX_DUSTF(IWV_BAND,:,5)=(DSFRACV*CSCAT1A_DL(IWV_BAND)*PHMXMIE_LOCAL1A_DL &
!        (IWV_BAND,:,6)+(1-DSFRACV)*CSCAT_DUST(IWV_BAND)* &
!        PHMX_DUST(IWV_BAND,:,5))/CSCAT_DUSTF(IWV_BAND)
!
!        PHMX_DUSTF(IWV_BAND,:,6)=(DSFRACV*CSCAT1A_DL(IWV_BAND)*PHMXMIE_LOCAL1A_DL &
!        (IWV_BAND,:,4)+(1-DSFRACV)*CSCAT_DUST(IWV_BAND)* &
!        PHMX_DUST(IWV_BAND,:,6))/CSCAT_DUSTF(IWV_BAND)
     END DO
     
    IF(DFRAC==0.0D0)THEN
       PHMX_DUSTF=0.0D0
       CEXT_DUSTF=0.0D0
       CSCAT_DUSTF=0.0D0
    ENDIF


    SIGMA_GD2 = SQRT(LOG(VEFFD)+1)
    R_GD2 = REFFD/EXP(2.5*SIGMA_GD2*SIGMA_GD2)

    SIGMA_GF = SQRT(LOG(VEFF1)+1)
    R_GF = REFF1/EXP(2.5D0*SIGMA_GF*SIGMA_GF)
 
    SIGMA_GC =SQRT(LOG(VSSN)+1)
    R_GC = REFF2_SS/EXP(2.5D0*SIGMA_GC*SIGMA_GC)
    
    RTMP1=4.0D0*PI*(R_GF**3)/3.0D0 !fine
    RTMP2=FMFRAC/RTMP1*EXP(-4.5D0*SIGMA_GF*SIGMA_GF)

    RTMP1=4.0D0*PI*(R_GD2**3)/3.0D0!dust
    RTMP3=DFRAC/RTMP1*EXP(-4.5D0*SIGMA_GD2*SIGMA_GD2)

    RTMP1=4.0D0*PI*(R_GC**3)/3.0D0!coarse
    RTMP4=(1-(FMFRAC+DFRAC))/RTMP1*EXP(-4.5D0*SIGMA_GC*SIGMA_GC)

    RTMP1=RTMP2+RTMP3+RTMP4
    ARSLND1=RTMP2/RTMP1
    ARSLND2=RTMP4/RTMP1
    ARSLNDD=RTMP3/RTMP1

    IF(ARSLND1==0.0D0)THEN
       MRR1=0.0D0
       MRI1=0.0D0
    ENDIF
    IF(ARSLND2==0.0D0)THEN
       MRR2=0.0D0
       MRI2=0.0D0
    ENDIF
    IF(ARSLNDD==0.0D0)THEN
       MRRD=0.0D0
       MRID=0.0D0
    ENDIF

    
    CEXT_ARSL_BAND = ARSLND1*CEXTF + ARSLND2*CEXT2A_SS + ARSLNDD*CEXT_DUSTF
    CSCAT_ARSL_BAND = ARSLND1*CSCATF + ARSLND2*CSCAT2A_SS + ARSLNDD*CSCAT_DUSTF
    
    DO IWV_BAND=1,NWV_BAND
        PHMXMIE_ARSL_PACE(IWV_BAND,:,0)=PHMXMIE_LOCAL2A_SS(IWV_BAND,:,0)

		PHMXMIE_ARSL_PACE(IWV_BAND,:,1:6)= ( &
		ARSLND1*CSCATF(IWV_BAND)* PHMXF(IWV_BAND,:,1:6) + &
		ARSLND2*CSCAT2A_SS(IWV_BAND)* PHMXMIE_LOCAL2A_SS(IWV_BAND,:,1:6) + &
		ARSLNDD*CSCAT_DUSTF(IWV_BAND)*PHMX_DUSTF(IWV_BAND,:,1:6))/CSCAT_ARSL_BAND(IWV_BAND)


!        PHMXMIE_ARSL_PACE(IWV_BAND,:,1)= ( &
!        ARSLND1*CSCATF(IWV_BAND)* PHMXF(IWV_BAND,:,1) + &
!        ARSLND2*CSCAT2A_SS(IWV_BAND)* PHMXMIE_LOCAL2A_SS(IWV_BAND,:,1) + &
!        ARSLNDD*CSCAT_DUSTF(IWV_BAND)*PHMX_DUSTF(IWV_BAND,:,1))/CSCAT_ARSL_BAND(IWV_BAND)
!
!        PHMXMIE_ARSL_PACE(IWV_BAND,:,2)=( &
!        ARSLND1*CSCATF(IWV_BAND)*PHMXF(IWV_BAND,:,5) + &
!        ARSLND2*CSCAT2A_SS(IWV_BAND)*PHMXMIE_LOCAL2A_SS(IWV_BAND,:,5) + &
!        ARSLNDD*CSCAT_DUSTF(IWV_BAND)*PHMX_DUSTF(IWV_BAND,:,2))/CSCAT_ARSL_BAND(IWV_BAND)
!
!        PHMXMIE_ARSL_PACE(IWV_BAND,:,3)=(&
!        ARSLND1*CSCATF(IWV_BAND)*PHMXF(IWV_BAND,:,2) + &
!        ARSLND2*CSCAT2A_SS(IWV_BAND)*PHMXMIE_LOCAL2A_SS(IWV_BAND,:,2) + &
!        ARSLNDD*CSCAT_DUSTF(IWV_BAND)*PHMX_DUSTF(IWV_BAND,:,3))/CSCAT_ARSL_BAND(IWV_BAND)
!
!        PHMXMIE_ARSL_PACE(IWV_BAND,:,4)=(&
!        ARSLND1*CSCATF(IWV_BAND)*PHMXF(IWV_BAND,:,3) + &
!        ARSLND2*CSCAT2A_SS(IWV_BAND)*PHMXMIE_LOCAL2A_SS(IWV_BAND,:,3) + &
!        ARSLNDD*CSCAT_DUSTF(IWV_BAND)*PHMX_DUSTF(IWV_BAND,:,4))/CSCAT_ARSL_BAND(IWV_BAND)
!
!        PHMXMIE_ARSL_PACE(IWV_BAND,:,5)=(&
!        ARSLND1*CSCATF(IWV_BAND)*PHMXF(IWV_BAND,:,6) + &
!        ARSLND2*CSCAT2A_SS(IWV_BAND)*PHMXMIE_LOCAL2A_SS(IWV_BAND,:,6) + &
!        ARSLNDD*CSCAT_DUSTF(IWV_BAND)*PHMX_DUSTF(IWV_BAND,:,5))/CSCAT_ARSL_BAND(IWV_BAND)
!
!        PHMXMIE_ARSL_PACE(IWV_BAND,:,6)=(&
!        ARSLND1*CSCATF(IWV_BAND)*PHMXF(IWV_BAND,:,4) + &
!        ARSLND2*CSCAT2A_SS(IWV_BAND)*PHMXMIE_LOCAL2A_SS(IWV_BAND,:,4) + &
!        ARSLNDD*CSCAT_DUSTF(IWV_BAND)*PHMX_DUSTF(IWV_BAND,:,6))/CSCAT_ARSL_BAND(IWV_BAND)
    END DO

    
    write(*,*) '****************************************************************'
    WRITE(*,*) 'NUMBER OF AEROSOL MODES = 3 '
    write(*,*) 'FINE, COARSE AND DUST MODES - EXTERNAL MIXING'
    write(*,*) '****************************************************************'
    IF(FMFRAC>0.0D0)THEN
        WRITE(*,*) 'REFF FINE MODE',REFF1
        WRITE(*,*) 'VEFF FINE  MODE', VEFF1
    ENDIF
    IF(DFRAC>0.0D0)THEN
        WRITE(*,*) 'REFF DUST MODE',REFFD
        WRITE(*,*) 'VEFF DUST MODE',VEFFD
    ENDIF
    IF((1-(FMFRAC+DFRAC))>0.0D0)THEN
        WRITE(*,*) 'REFF COARSE MODE',REFF2
        WRITE(*,*) 'VEFF COARSE MODE', VEFF2
    ENDIF
    WRITE(*,*) 'ARSLND FINE MOE', ARSLND1
    WRITE(*,*) 'ARSLND COARSE MODE', ARSLND2
    WRITE(*,*) 'ARSLND DUST MODE',ARSLNDD
  ENDIF

END IF






IF(FREEFORMFLAG>0 .AND. IAEROSOL==-99 .AND. MIX_FLAG==1) THEN !INTERNAL MIXING OF FINE MODE AEROSOLS
    IF(NMODE==2)THEN
    CALL ARSL_REF_INDX_INIT_IMIX2(NWV_BAND,WV_BAND_MICRON,RHI,R0DL,R0WS,R0BC,R0S,R0SS,RF1,RF2,RF3)
    ELSEIF(NMODE==3)THEN
    CALL ARSL_REF_INDX_INIT_EMIX(NWV_BAND,WV_BAND_MICRON,RHI,R0DL,R0WS,R0BC,R0S,R0SS)
    ENDIF  
    CALL HYGROSCOPIC_GROWTH_EMIX(R0DL,R0WS,R0BC,R0S,R0SS,RHI, RRH_DL,RRH_WS,RRH_BC,RRH_S,RRH_SS)
    CALL HYGROSCOPIC_GROWTH_IMIX(1.0D0,R0SS,RHI, RRH_F,RRH_C)


    REFF1_DL = EXP(LOG(RRH_DL)-3.0D0*VDL*VDL)
    REFF1_WS = EXP(LOG(RRH_WS)-3.0D0*VWS*VWS)
    REFF1_BC = EXP(LOG(RRH_BC)-3.0D0*VBC*VBC)
    REFF1_S = EXP(LOG(RRH_S)-3.0D0*VS*VS)
    REFF2_SS = EXP(LOG(RRH_C)-3.0D0*VSS*VSS)

    IF(NMODE==2)THEN
    RTMP = 4.0D0*PI*(REFF1_DL**3)/3.0D0
    RTMP1 = RF1/RTMP*EXP(-4.5D0*VDL*VDL)
    RTMP = 4.0D0*PI*(REFF1_WS**3)/3.0D0
    RTMP2 = RF2/RTMP*EXP(-4.5D0*VWS*VWS)
    RTMP = 4.0D0*PI*(REFF1_BC**3)/3.0D0
    RTMP3 = RF3/RTMP*EXP(-4.5D0*VBC*VBC)
    RTMP = 4.0D0*PI*(REFF1_S**3)/3.0D0
    RTMP4 = (1-(RF1+RF2+RF3))/RTMP*EXP(-4.5D0*VS*VS)

    RTMP = RTMP1+RTMP2+RTMP3+RTMP4
    ARSLND1_DL = RTMP1/RTMP
    ARSLND1_WS = RTMP2/RTMP
    ARSLND1_BC = RTMP3/RTMP
    ARSLND1_S = RTMP4/RTMP
    ENDIF

    IF(NMODE==3)THEN
       RTMP = 4.0D0*PI*(REFF1_WS**3)/3.0D0
       RTMP2 = RF2/RTMP*EXP(-4.5D0*VWS*VWS)
       RTMP = 4.0D0*PI*(REFF1_BC**3)/3.0D0
       RTMP3 = RF3/RTMP*EXP(-4.5D0*VBC*VBC)
       RTMP = 4.0D0*PI*(REFF1_S**3)/3.0D0
       RTMP4 = (1-(RF2+RF3))/RTMP*EXP(-4.5D0*VS*VS)

       RTMP = RTMP2+RTMP3+RTMP4
       ARSLND1_DL = DFRAC*DSFRAC !dummy
       ARSLND1_WS = RTMP2/RTMP
       ARSLND1_BC = RTMP3/RTMP
       ARSLND1_S = RTMP4/RTMP
    ENDIF

    VDLN = VDL*VDL
    VWSN = VWS*VWS
    VBCN = VBC*VBC
    VSN = VS*VS
    VSSN = VSS*VSS

    !CONVERT TO EFFECTIVE VALUES
    REFF1_DL = REFF1_DL*EXP(2.5D0*VDLN)
    REFF1_WS = REFF1_WS*EXP(2.5D0*VWSN)
    REFF1_BC = REFF1_BC*EXP(2.5D0*VBCN)
    REFF1_S = REFF1_S*EXP(2.5D0*VSN)
    REFF2_SS = REFF2_SS*EXP(2.5D0*VSSN)

    VDLN = EXP(VDLN)-1.0D0
    VWSN = EXP(VWSN)-1.0D0
    VBCN = EXP(VBCN)-1.0D0
    VSN = EXP(VSN)-1.0D0
    VSSN = EXP(VSSN)-1.0D0
                  
    !CONVERT TO GEOMETRIC VALUES
    SIGMA_GDL = SQRT(LOG(VDLN+1))
    SIGMA_GWS = SQRT(LOG(VWSN+1))
    SIGMA_GBC = SQRT(LOG(VBCN+1))
    SIGMA_GS = SQRT(LOG(VSN+1))
    SIGMA_GSS = SQRT(LOG(VSSN+1))
                 

    R_GDL = REFF1_DL/EXP(2.5D0*SIGMA_GDL*SIGMA_GDL)
    R_GWS = REFF1_WS/EXP(2.5D0*SIGMA_GWS*SIGMA_GWS)
    R_GBC = REFF1_BC/EXP(2.5D0*SIGMA_GBC*SIGMA_GBC)
    R_GS = REFF1_S/EXP(2.5D0*SIGMA_GS*SIGMA_GS)
    R_GSS = REFF2_SS/EXP(2.5D0*SIGMA_GSS*SIGMA_GSS)
                 

    !CALCULATE MOMENTS
    M21DL = R_GDL*R_GDL*EXP(2*SIGMA_GDL*SIGMA_GDL)
    M31DL = R_GDL*R_GDL*R_GDL*EXP(4.5*SIGMA_GDL*SIGMA_GDL)

    M21WS = R_GWS*R_GWS*EXP(2*SIGMA_GWS*SIGMA_GWS)
    M31WS = R_GWS*R_GWS*R_GWS*EXP(4.5*SIGMA_GWS*SIGMA_GWS)

    M21BC = R_GBC*R_GBC*EXP(2*SIGMA_GBC*SIGMA_GBC)
    M31BC = R_GBC*R_GBC*R_GBC*EXP(4.5*SIGMA_GBC*SIGMA_GBC)

    M21S = R_GS*R_GS*EXP(2*SIGMA_GS*SIGMA_GS)
    M31S = R_GS*R_GS*R_GS*EXP(4.5*SIGMA_GS*SIGMA_GS)

    M22SS = R_GSS*R_GSS*EXP(2*SIGMA_GSS*SIGMA_GSS)
    M32SS = R_GSS*R_GSS*R_GSS*EXP(4.5*SIGMA_GSS*SIGMA_GSS)

    IF(NMODE==2)THEN
    !CALCULATE EFFECTIVE VALUES OF ALL THE COMPONENTS
    REFF1_LOCAL = (ARSLND1_DL*M31DL +ARSLND1_WS*M31WS +ARSLND1_BC*M31BC +ARSLND1_S*M31S)/&
                       (ARSLND1_DL*M21DL +ARSLND1_WS*M21WS+ARSLND1_BC*M21BC +ARSLND1_S*M21S)
    VEFF1_LOCAL= ARSLND1_DL*VDLN + ARSLND1_WS*VWSN + ARSLND1_BC*VBCN + ARSLND1_S*VSN

    REFF2_LOCAL = REFF2_SS
    VEFF2_LOCAL = VSSN
                  
    !CALL ARSL_REF_INDX_INIT_IMIX(NWV_BAND,WV_BAND_MICRON,RHI,R0F,R0C,rf1,rf2,rf3)
    MRR1(1:NWV_BAND)=MR_FLEXF(1:NWV_BAND)
    MRI1(1:NWV_BAND)=MI_FLEXF(1:NWV_BAND)
    MRR2(1:NWV_BAND)=MR_FLEXC(1:NWV_BAND)
    MRI2(1:NWV_BAND)=MI_FLEXC(1:NWV_BAND)

    DEALLOCATE(MR_ZIACR,MI_ZIACR, MR_FLEXF, MR_FLEXC, MI_FLEXF,MI_FLEXC)
    ENDIF

    NDISTR=2

    !DUST DATA
    !wavelength interpolation

    CALL DUST_SCAT_PROP_INIT(IREFF,IVAR,PHMX_DUST_TMP,CEXT_DUST_TMP,CSCAT_DUST_TMP,SCATANG)
                  
    DO IWV_BAND=1,NWV_BAND
        WV_tmp=WV_BAND_MICRON(IWV_BAND)
        CEXT_DUST(IWV_BAND)=POLINT_SIMPLE(NWV_D,WVL,CEXT_DUST_TMP,WV_tmp,3)
        CSCAT_DUST(IWV_BAND)=POLINT_SIMPLE(NWV_D,WVL,CSCAT_DUST_TMP,WV_tmp,3)
        MRR_DUST(IWV_BAND)=POLINT_SIMPLE(NWV_D,WVL,MRD,WV_tmp,3)
        MRI_DUST(IWV_BAND)=POLINT_SIMPLE(NWV_D,WVL,MID,WV_tmp,3)
        DO IANG=1,NSCATANG
            DO IPHMX=1,6
                PHMX_DUST_TMP2(IWV_BAND,IANG,IPHMX)=POLINT_SIMPLE(NWV_D,WVL,PHMX_DUST_TMP(:,IANG,IPHMX),WV_tmp,3)
                END DO
            END DO
        END DO

                  
        SIGMA_GD = SQRT(LOG(SIGMA(IVAR)))
        R_GD = REFF(IREFF)/EXP(2.5*SIGMA_GD*SIGMA_GD)
        M2D = R_GD*R_GD*EXP(2*SIGMA_GD*SIGMA_GD)
        M3D = R_GD*R_GD*R_GD*EXP(4.5*SIGMA_GD*SIGMA_GD)

        IF(NMODE==2)THEN
        DO IWV_BAND=1,NWV_BAND

          IF (FMFRAC<1.0D0) THEN
            CALL SPHER_INTERFACE(NDISTR,REFF2_LOCAL,VEFF2_LOCAL,WV_BAND_MICRON(IWV_BAND),&
                MRR2(IWV_BAND),MRI2(IWV_BAND),AA1,BB1,AA2,BB2,GAMMAI,&
                REFFO,VEFFO,AREA,CEXT2,CSCAT2,NANGMIE_LOCAL,PHMXMIE_LOCAL2)
         ELSE
            CEXT2=0.D00
            CSCAT2=0.0D0
         ENDIF

         NUM_SCAT_ANG = NANGMIE_LOCAL
         MRR2_MIE(IWV_BAND)=MRR2(IWV_BAND)
         MRI2_MIE(IWV_BAND)=MRI2(IWV_BAND)
         CEXT2_MIE(IWV_BAND)=CEXT2
         CSCAT2_MIE(IWV_BAND)=CSCAT2
         PHMXMIE_LOCAL2_MIE(IWV_BAND,:,:)=PHMXMIE_LOCAL2(:,:)
         
            IF (FMFRAC>0.0D0) THEN
                CALL SPHER_INTERFACE(NDISTR,REFF1_LOCAL,VEFF1_LOCAL,WV_BAND_MICRON(IWV_BAND),&
                    MRR1(IWV_BAND),MRI1(IWV_BAND),AA1,BB1,AA2,BB2,GAMMAI,&
                    REFFO,VEFFO,AREA,CEXT1,CSCAT1,NANGMIE_LOCAL,PHMXMIE_LOCAL1)

                ELSE
                    CEXT1=0.D00
                    CSCAT1=0.0D0
            ENDIF

            NUM_SCAT_ANG = NANGMIE_LOCAL
            MRR1_MIE(IWV_BAND)=MRR1(IWV_BAND)
            MRI1_MIE(IWV_BAND)=MRI1(IWV_BAND)
            CEXT1_MIE(IWV_BAND)=CEXT1
            CSCAT1_MIE(IWV_BAND)=CSCAT1
            PHMXMIE_LOCAL1_MIE(IWV_BAND,:,:)=PHMXMIE_LOCAL1(:,:)
    END DO


    DO IWV_BAND=1,NWV_BAND
        DO IANG=1,NUM_SCAT_ANG
            DO IPHMX=1,6
                PHMX_DUST(IWV_BAND,IANG,IPHMX)=POLINT_SIMPLE(NSCATANG,SCATANG,PHMX_DUST_TMP2(IWV_BAND,:,IPHMX),&
                        PHMXMIE_LOCAL2_MIE(IWV_BAND,IANG,0),3)
            END DO
        END DO
    END DO

    !using values converted into number space to obtain geometric values
    SIGMA_G1 = SQRT(LOG(VEFF1_LOCAL+1))
    SIGMA_G2 = SQRT(LOG(VEFF2_LOCAL+1))
    SIGMA_GD = SQRT(LOG(SIGMA(IVAR)))

    R_G1 = REFF1_LOCAL/EXP(2.5*SIGMA_G1*SIGMA_G1)
    R_G2 = REFF2_LOCAL/EXP(2.5*SIGMA_G2*SIGMA_G2)
    R_GD = REFF(IREFF)/EXP(2.5*SIGMA_GD*SIGMA_GD)

    !calculating 2nd and 3rd moments
    M22 = R_G2*R_G2*EXP(2*SIGMA_G2*SIGMA_G2)
    M32 = R_G2*R_G2*R_G2*EXP(4.5*SIGMA_G2*SIGMA_G2)

    M2D = R_GD*R_GD*EXP(2*SIGMA_GD*SIGMA_GD)
    M3D = R_GD*R_GD*R_GD*EXP(4.5*SIGMA_GD*SIGMA_GD)

    RTMP2=(1-FRACS)/(4.0D0*PI*(R_GD**3)/3.0D0)*EXP(-4.5D0*SIGMA_GD*SIGMA_GD) !dust
    RTMP3=FRACS/(4.0D0*PI*(R_G2**3)/3.0D0)*EXP(-4.5D0*SIGMA_G2*SIGMA_G2) ! other coarse mode
    FRACSV=RTMP3/(RTMP2+RTMP3)

    REFF2=(FRACSV*M32+(1-FRACSV)*M3D)/(FRACSV*M22+(1-FRACSV)*M2D)
    VEFF2=FRACSV*VEFF2_LOCAL+(1-FRACSV)*EXP(LOG(SIGMA(IVAR))-1)

    CEXTC(:)=FRACSV*CEXT2_MIE(:)+(1-FRACSV)*CEXT_DUST(:)
    CSCATC(:)=FRACSV*CSCAT2_MIE(:)+(1-FRACSV)*CSCAT_DUST(:)

    !new coarse mode refractive indices
    IF (FMFRAC<1.0D0)THEN
       MRR2=FRACS*MRR2_MIE+(1-FRACS)*MRR_DUST
       MRI2=FRACS*MRI2_MIE+(1-FRACS)*MRI_DUST
    ELSEIF (FMFRAC==1.0) THEN
       MRR2=0.0D0
       MRI2=0.D0
    ELSEIF (FMFRAC==0.0D0) THEN
       MRR1=0.0D0
       MRR1=0.0D0
       ENDIF

    !coarse mode geometrical properties
    SIGMA_GC = SQRT(LOG(VEFF2)+1)
    R_GC = REFF2/EXP(2.5*SIGMA_GC*SIGMA_GC)

    !redefining aerosol number density for fine and coarse modes based on modified REFF and VEFF
    RTMP1=4.0D0*PI*(R_G1**3)/3.0D0
    RTMP2=FMFRAC/RTMP1*EXP(-4.5D0*SIGMA_G1*SIGMA_G1)
    RTMP1=4.0D0*PI*(R_GC**3)/3.0D0
    RTMP3=(1.0D0-FMFRAC)/RTMP1*EXP(-4.5D0*SIGMA_GC*SIGMA_GC)
    RTMP1=RTMP2/(RTMP2+RTMP3)
    ARSLND1=RTMP1
    ARSLND2=(1.0D0-RTMP1)



    write(*,*) '****************************************************************'
    WRITE(*,*) 'NUMBER OF AEROSOL MODES = 2'
    WRITE(*,*) 'FINE MODE - INTERNAL MIXING'
    write(*,*) 'COARSE MODE - EXTERNAL MIXING'
    write(*,*) '****************************************************************'
    IF(FMFRAC>0.0D0)THEN
        write(*,*) 'reff_fine',REFF1_LOCAL
        write(*,*) 'veff_fine', VEFF1_LOCAL
    ENDIF
    IF((1-FMFRAC)>0.0D0)THEN
        write(*,*) 'reff_coarse' , REFF2
        write(*,*) 'veff_coarse',VEFF2
    ENDIF
    write(*,*) 'fine mode number density',ARSLND1
    write(*,*) 'coarse mode number density',ARSLND2

    ! pass effective radius and variance back to main program for output
    REFF1 = REFF1_LOCAL
    VEFF1 = VEFF1_LOCAL
    
    !external mixing of spherical and non-spherical coarse mode aerosol phase  matrix
    DO IWV_BAND=1,NWV_BAND
         PHMXC(IWV_BAND,:,1:6)= &
          (FRACSV *CSCAT2_MIE(IWV_BAND)*PHMXMIE_LOCAL2_MIE(IWV_BAND,:,1:6) &
	   +(1-FRACSV)*CSCAT_DUST(IWV_BAND)*PHMX_DUST(IWV_BAND,:,1:6))/CSCATC(IWV_BAND)

!        PHMXC(IWV_BAND,:,1)=(FRACSV*CSCAT2_MIE(IWV_BAND)*PHMXMIE_LOCAL2_MIE &
!                          (IWV_BAND,:,1)+(1-FRACSV)*CSCAT_DUST(IWV_BAND)* &
!                          PHMX_DUST(IWV_BAND,:,1))/CSCATC(IWV_BAND)
!        PHMXC(IWV_BAND,:,2)=(FRACSV*CSCAT2_MIE(IWV_BAND)*PHMXMIE_LOCAL2_MIE &
!                          (IWV_BAND,:,5)+(1-FRACSV)*CSCAT_DUST(IWV_BAND)* &
!                          PHMX_DUST(IWV_BAND,:,2))/CSCATC(IWV_BAND)
!        PHMXC(IWV_BAND,:,3)=(FRACSV*CSCAT2_MIE(IWV_BAND)*PHMXMIE_LOCAL2_MIE &
!                          (IWV_BAND,:,2)+(1-FRACSV)*CSCAT_DUST(IWV_BAND)* &
!                          PHMX_DUST(IWV_BAND,:,3))/CSCATC(IWV_BAND)
!        PHMXC(IWV_BAND,:,4)=(FRACSV*CSCAT2_MIE(IWV_BAND)*PHMXMIE_LOCAL2_MIE &
!                          (IWV_BAND,:,3)+(1-FRACSV)*CSCAT_DUST(IWV_BAND)* &
!                          PHMX_DUST(IWV_BAND,:,4))/CSCATC(IWV_BAND)
!        PHMXC(IWV_BAND,:,5)=(FRACSV*CSCAT2_MIE(IWV_BAND)*PHMXMIE_LOCAL2_MIE &
!                          (IWV_BAND,:,6)+(1-FRACSV)*CSCAT_DUST(IWV_BAND)* &
!                          PHMX_DUST(IWV_BAND,:,5))/CSCATC(IWV_BAND)
!        PHMXC(IWV_BAND,:,6)=(FRACSV*CSCAT2_MIE(IWV_BAND)*PHMXMIE_LOCAL2_MIE &
!                          (IWV_BAND,:,4)+(1-FRACSV)*CSCAT_DUST(IWV_BAND)* &
!                          PHMX_DUST(IWV_BAND,:,6))/CSCATC(IWV_BAND)
      END DO

      CEXT_ARSL_BAND=ARSLND1*CEXT1_MIE+ARSLND2*CEXTC
      CSCAT_ARSL_BAND=ARSLND1*CSCAT1_MIE+ARSLND2*CSCATC
                  
      DO IWV_BAND=1,NWV_BAND
            IF (FMFRAC==0.0D0) THEN
               PHMXMIE_ARSL_PACE(IWV_BAND,:,0)=PHMXMIE_LOCAL2_MIE(IWV_BAND,:,0)
            ELSEIF (FMFRAC>0.0D0) THEN
               PHMXMIE_ARSL_PACE(IWV_BAND,:,0)=PHMXMIE_LOCAL1_MIE(IWV_BAND,:,0)
            ENDIF

       PHMXMIE_ARSL_PACE(IWV_BAND,:,1:6)=(ARSLND1*CSCAT1_MIE(IWV_BAND)* &
					PHMXMIE_LOCAL1_MIE(IWV_BAND,:,1:6) + &
					ARSLND2*CSCATC(IWV_BAND)*PHMXC(IWV_BAND,:,1:6))/CSCAT_ARSL_BAND(IWV_BAND)


!      PHMXMIE_ARSL_PACE(IWV_BAND,:,1)=(ARSLND1*CSCAT1_MIE(IWV_BAND)* &
!                          PHMXMIE_LOCAL1_MIE(IWV_BAND,:,1) + &
!                          ARSLND2*CSCATC(IWV_BAND)*PHMXC(IWV_BAND,:,1))/CSCAT_ARSL_BAND(IWV_BAND)
!      PHMXMIE_ARSL_PACE(IWV_BAND,:,2)=(ARSLND1*CSCAT1_MIE(IWV_BAND)* &
!                          PHMXMIE_LOCAL1_MIE(IWV_BAND,:,5) + &
!                          ARSLND2*CSCATC(IWV_BAND)*PHMXC(IWV_BAND,:,2))/CSCAT_ARSL_BAND(IWV_BAND)
!      PHMXMIE_ARSL_PACE(IWV_BAND,:,3)=(ARSLND1*CSCAT1_MIE(IWV_BAND)* &
!                          PHMXMIE_LOCAL1_MIE(IWV_BAND,:,2) + &
!                          ARSLND2*CSCATC(IWV_BAND)*PHMXC(IWV_BAND,:,3))/CSCAT_ARSL_BAND(IWV_BAND)
!      PHMXMIE_ARSL_PACE(IWV_BAND,:,4)=(ARSLND1*CSCAT1_MIE(IWV_BAND)* &
!                          PHMXMIE_LOCAL1_MIE(IWV_BAND,:,3) + &
!                          ARSLND2*CSCATC(IWV_BAND)*PHMXC(IWV_BAND,:,4))/CSCAT_ARSL_BAND(IWV_BAND)
!      PHMXMIE_ARSL_PACE(IWV_BAND,:,5)=(ARSLND1*CSCAT1_MIE(IWV_BAND)* &
!                          PHMXMIE_LOCAL1_MIE(IWV_BAND,:,6) + &
!                          ARSLND2*CSCATC(IWV_BAND)*PHMXC(IWV_BAND,:,5))/CSCAT_ARSL_BAND(IWV_BAND)
!      PHMXMIE_ARSL_PACE(IWV_BAND,:,6)=(ARSLND1*CSCAT1_MIE(IWV_BAND)* &
!                          PHMXMIE_LOCAL1_MIE(IWV_BAND,:,4) + &
!                          ARSLND2*CSCATC(IWV_BAND)*PHMXC(IWV_BAND,:,6))/CSCAT_ARSL_BAND(IWV_BAND)
      END DO
ENDIF

IF(NMODE==3)THEN
   REFF1_LOCAL = (ARSLND1_WS*M31WS + ARSLND1_BC*M31BC + ARSLND1_S*M31S)/&
        (ARSLND1_WS*M21WS + ARSLND1_BC*M21BC + ARSLND1_S*M21S)
   VEFF1_LOCAL= ARSLND1_WS*VWSN + ARSLND1_BC*VBCN + ARSLND1_S*VSN

   REFF2_LOCAL = REFF2_SS
   VEFF2_LOCAL = VSSN
   
   MRR1_DL(1:NWV_BAND) = MR_DUSTF_TMP1(1:NWV_BAND)
   MRR1_WS(1:NWV_BAND) = MR_WATER_SOLUBLE_TMP1(1:NWV_BAND)
   MRR1_BC(1:NWV_BAND) = MR_BRC_TMP1(1:NWV_BAND)
   MRR1_S(1:NWV_BAND) = MR_SOOTF_TMP1(1:NWV_BAND)
   MRR2_SS(1:NWV_BAND) = MR_ZIACR(1:NWV_BAND)

   MRI1_DL(1:NWV_BAND) = MI_DUSTF_TMP1(1:NWV_BAND)
   MRI1_WS(1:NWV_BAND) = MI_WATER_SOLUBLE_TMP1(1:NWV_BAND)
   MRI1_BC(1:NWV_BAND) = MI_BRC_TMP1(1:NWV_BAND)
   MRI1_S(1:NWV_BAND) = MI_SOOTF_TMP1(1:NWV_BAND)
   MRI2_SS(1:NWV_BAND) = MI_ZIACR(1:NWV_BAND)

   
   MRR1(1:NWV_BAND)=RF2*MRR1_WS+RF3*MRR1_BC+(1-(RF2+RF3))*MRR1_S
   MRI1(1:NWV_BAND)=RF2*MRI1_WS+RF3*MRI1_BC+(1-(RF2+RF3))*MRI1_S
   MRR2(1:NWV_BAND)=MRR2_SS
   MRI2(1:NWV_BAND)=MRI2_SS


   DO IWV_BAND=1,NWV_BAND
    IF ((1-(FMFRAC+DFRAC))>0.0D0) THEN
    CALL SPHER_INTERFACE(NDISTR,REFF2_LOCAL,VEFF2_LOCAL,WV_BAND_MICRON(IWV_BAND),&
    MRR2(IWV_BAND),MRI2(IWV_BAND),AA1,BB1,AA2,BB2,GAMMAI,&
    REFFO,VEFFO,AREA,CEXT2,CSCAT2,NANGMIE_LOCAL,PHMXMIE_LOCAL2)
    ELSE
    CEXT2=0.D00
    CSCAT2=0.0D0
    ENDIF

    NUM_SCAT_ANG = NANGMIE_LOCAL
    MRR2_MIE(IWV_BAND)=MRR2(IWV_BAND)
    MRI2_MIE(IWV_BAND)=MRI2(IWV_BAND)
    CEXT2_MIE(IWV_BAND)=CEXT2
    CSCAT2_MIE(IWV_BAND)=CSCAT2
    PHMXMIE_LOCAL2_MIE(IWV_BAND,:,:)=PHMXMIE_LOCAL2(:,:)

    IF (FMFRAC>0.0D0) THEN
    CALL SPHER_INTERFACE(NDISTR,REFF1_LOCAL,VEFF1_LOCAL,WV_BAND_MICRON(IWV_BAND),&
    MRR1(IWV_BAND),MRI1(IWV_BAND),AA1,BB1,AA2,BB2,GAMMAI,&
    REFFO,VEFFO,AREA,CEXT1,CSCAT1,NANGMIE_LOCAL,PHMXMIE_LOCAL1)
    ELSE
    CEXT1=0.D00
    CSCAT1=0.0D0
    ENDIF

    NUM_SCAT_ANG = NANGMIE_LOCAL
    MRR1_MIE(IWV_BAND)=MRR1(IWV_BAND)
    MRI1_MIE(IWV_BAND)=MRI1(IWV_BAND)
    CEXT1_MIE(IWV_BAND)=CEXT1
    CSCAT1_MIE(IWV_BAND)=CSCAT1
    PHMXMIE_LOCAL1_MIE(IWV_BAND,:,:)=PHMXMIE_LOCAL1(:,:)

    IF(DFRAC>0.0D0 .AND. FREEFORMFLAG<=1)THEN
    CALL SPHER_INTERFACE(NDISTR,REFF1_DL,VDLN,WV_BAND_MICRON(IWV_BAND),&
    MRR1_DL(IWV_BAND),MRI1_DL(IWV_BAND),AA1,BB1,AA2,BB2,GAMMAI,&
    REFFO,VEFFO,AREA,CEXT1_DL,CSCAT1_DL,NANGMIE_LOCAL,PHMXMIE_LOCAL1_DL)
    ELSE
    CEXT1_DL = 0.0D0
    CSCAT1_DL = 0.0D0
    ENDIF
    NUM_SCAT_ANG = NANGMIE_LOCAL
    CEXT1A_DL(IWV_BAND)=CEXT1_DL
    CSCAT1A_DL(IWV_BAND)=CSCAT1_DL
    PHMXMIE_LOCAL1A_DL(IWV_BAND,:,:)=PHMXMIE_LOCAL1_DL(:,:)

 ENDDO

 DO IWV_BAND=1,NWV_BAND
    DO IANG=1,NUM_SCAT_ANG
       DO IPHMX=1,6
          PHMX_DUST(IWV_BAND,IANG,IPHMX)=POLINT_SIMPLE(NSCATANG,SCATANG,PHMX_DUST_TMP2(IWV_BAND,:,IPHMX),&
               PHMXMIE_LOCAL1A_DL(IWV_BAND,IANG,0),3)
       END DO
    END DO
 END DO
 
    SIGMA_GD = SQRT(LOG(SIGMA(IVAR)))
    R_GD = REFF(IREFF)/EXP(2.5*SIGMA_GD*SIGMA_GD)

    M2D = R_GD*R_GD*EXP(2*SIGMA_GD*SIGMA_GD)
    M3D = R_GD*R_GD*R_GD*EXP(4.5*SIGMA_GD*SIGMA_GD)

    RTMP2=(1-DSFRAC)/(4.0D0*PI*(R_GD**3)/3.0D0)*EXP(-4.5D0*SIGMA_GD*SIGMA_GD) !dust
    RTMP3=DSFRAC/(4.0D0*PI*(R_GDL**3)/3.0D0)*EXP(-4.5D0*SIGMA_GDL*SIGMA_GDL) ! other coarse mode
    DSFRACV=RTMP3/(RTMP2+RTMP3)


    REFFD=(DSFRACV*M31DL+(1-DSFRACV)*M3D)/(DSFRACV*M21DL+(1-DSFRACV)*M2D)
    VEFFD=DSFRACV*VDLN+(1-DSFRACV)*EXP(LOG(SIGMA(IVAR))-1)

    CEXT_DUSTF(:)=DSFRACV*CEXT1A_DL(:)+(1-DSFRACV)*CEXT_DUST(:)
    CSCAT_DUSTF(:)=DSFRACV*CSCAT1A_DL(:)+(1-DSFRACV)*CSCAT_DUST(:)

    MRRDT = DSFRAC*MRR1_DL+(1-DSFRAC)*MRR_DUST
    MRIDT = DSFRAC*MRR1_DL+(1-DSFRAC)*MRI_DUST
    MRRD = MRRDT
    MRID = MRIDT

    DO IWV_BAND=1,NWV_BAND
		PHMX_DUSTF(IWV_BAND,:,1:6)= &
      (DSFRACV *CSCAT1A_DL(IWV_BAND)*PHMXMIE_LOCAL1A_DL(IWV_BAND,:,1:6) &
   +(1-DSFRACV)*CSCAT_DUST(IWV_BAND)*PHMX_DUST(IWV_BAND,:,1:6))/CSCAT_DUSTF(IWV_BAND)


!	PHMX_DUSTF(IWV_BAND,:,1)=(DSFRACV*CSCAT1A_DL(IWV_BAND)*PHMXMIE_LOCAL1A_DL &
!    (IWV_BAND,:,1)+(1-DSFRACV)*CSCAT_DUST(IWV_BAND)* &
!    PHMX_DUST(IWV_BAND,:,1))/CSCAT_DUSTF(IWV_BAND)
!
!    PHMX_DUSTF(IWV_BAND,:,2)=(DSFRACV*CSCAT1A_DL(IWV_BAND)*PHMXMIE_LOCAL1A_DL &
!    (IWV_BAND,:,5)+(1-DSFRACV)*CSCAT_DUST(IWV_BAND)* &
!    PHMX_DUST(IWV_BAND,:,2))/CSCAT_DUSTF(IWV_BAND)
!
!    PHMX_DUSTF(IWV_BAND,:,3)=(DSFRACV*CSCAT1A_DL(IWV_BAND)*PHMXMIE_LOCAL1A_DL &
!    (IWV_BAND,:,2)+(1-DSFRACV)*CSCAT_DUST(IWV_BAND)* &
!    PHMX_DUST(IWV_BAND,:,3))/CSCAT_DUSTF(IWV_BAND)
!
!    PHMX_DUSTF(IWV_BAND,:,4)=(DSFRACV*CSCAT1A_DL(IWV_BAND)*PHMXMIE_LOCAL1A_DL &
!    (IWV_BAND,:,3)+(1-DSFRACV)*CSCAT_DUST(IWV_BAND)* &
!    PHMX_DUST(IWV_BAND,:,4))/CSCAT_DUSTF(IWV_BAND)
!
!    PHMX_DUSTF(IWV_BAND,:,5)=(DSFRACV*CSCAT1A_DL(IWV_BAND)*PHMXMIE_LOCAL1A_DL &
!    (IWV_BAND,:,6)+(1-DSFRACV)*CSCAT_DUST(IWV_BAND)* &
!    PHMX_DUST(IWV_BAND,:,5))/CSCAT_DUSTF(IWV_BAND)
!
!    PHMX_DUSTF(IWV_BAND,:,6)=(DSFRACV*CSCAT1A_DL(IWV_BAND)*PHMXMIE_LOCAL1A_DL &
!    (IWV_BAND,:,4)+(1-DSFRACV)*CSCAT_DUST(IWV_BAND)* &
!    PHMX_DUST(IWV_BAND,:,6))/CSCAT_DUSTF(IWV_BAND)
    END DO

    
    SIGMA_GD2 = SQRT(LOG(VEFFD)+1)
    R_GD2 = REFFD/EXP(2.5*SIGMA_GD2*SIGMA_GD2)

    SIGMA_GF = SQRT(LOG(VEFF1_LOCAL)+1)
    R_GF = REFF1_LOCAL/EXP(2.5D0*SIGMA_GF*SIGMA_GF)

    SIGMA_GC =SQRT(LOG(VEFF2_LOCAL)+1)
    R_GC = REFF2_LOCAL/EXP(2.5D0*SIGMA_GC*SIGMA_GC)

    RTMP1=4.0D0*PI*(R_GF**3)/3.0D0 !fine
    RTMP2=FMFRAC/RTMP1*EXP(-4.5D0*SIGMA_GF*SIGMA_GF)

    RTMP1=4.0D0*PI*(R_GD2**3)/3.0D0!dust
    RTMP3=DFRAC/RTMP1*EXP(-4.5D0*SIGMA_GD2*SIGMA_GD2)

    RTMP1=4.0D0*PI*(R_GC**3)/3.0D0!coarse
    RTMP4=(1-(FMFRAC+DFRAC))/RTMP1*EXP(-4.5D0*SIGMA_GC*SIGMA_GC)

    RTMP1=RTMP2+RTMP3+RTMP4

    ARSLND1=RTMP2/RTMP1
    ARSLND2=RTMP4/RTMP1
    ARSLNDD=RTMP3/RTMP1

    IF(ARSLND1==0.0D0)THEN
       MRR1=0.0D0
       MRI1=0.0D0
    ENDIF
    IF(ARSLND2==0)THEN
       MRR2=0.0D0
       MRI2=0.0D0
    ENDIF
    IF(ARSLNDD==0)THEN
       MRRD=0.0D0
       MRID=0.D0
    ENDIF

    
    CEXT_ARSL_BAND = ARSLND1*CEXT1_MIE+ARSLND2*CEXT2_MIE+ARSLNDD*CEXT_DUSTF
    CSCAT_ARSL_BAND = ARSLND1*CSCAT1_MIE+ARSLND2*CSCAT2_MIE+ARSLNDD*CSCAT_DUSTF

    DO IWV_BAND=1,NWV_BAND
       IF(FMFRAC>0.0D0)THEN
          PHMXMIE_ARSL_PACE(IWV_BAND,:,0)=PHMXMIE_LOCAL1_MIE(IWV_BAND,:,0)
       ELSEIF(DSFRAC>0.0 .OR. DFRAC>0.0D0)THEN
          PHMXMIE_ARSL_PACE(IWV_BAND,:,0)=PHMXMIE_LOCAL1A_DL(IWV_BAND,:,0)
       ELSEIF((1-(FMFRAC+DFRAC))>0.0D0) THEN
           PHMXMIE_ARSL_PACE(IWV_BAND,:,0)=PHMXMIE_LOCAL2_MIE(IWV_BAND,:,0)
       ENDIF

	PHMXMIE_ARSL_PACE(IWV_BAND,:,1:6)= ( &
	ARSLND1*CSCAT1_MIE(IWV_BAND)* PHMXMIE_LOCAL1_MIE(IWV_BAND,:,1:6) + &
	ARSLND2*CSCAT2_MIE(IWV_BAND)* PHMXMIE_LOCAL2_MIE(IWV_BAND,:,1:6) + &
	ARSLNDD*CSCAT_DUSTF(IWV_BAND)*PHMX_DUSTF(IWV_BAND,:,1:6))/CSCAT_ARSL_BAND(IWV_BAND)


!    PHMXMIE_ARSL_PACE(IWV_BAND,:,1)= ( &
!    ARSLND1*CSCAT1_MIE(IWV_BAND)* PHMXMIE_LOCAL1_MIE(IWV_BAND,:,1) + &
!    ARSLND2*CSCAT2_MIE(IWV_BAND)* PHMXMIE_LOCAL2_MIE(IWV_BAND,:,1) + &
!    ARSLNDD*CSCAT_DUSTF(IWV_BAND)*PHMX_DUSTF(IWV_BAND,:,1))/CSCAT_ARSL_BAND(IWV_BAND)
!
!    PHMXMIE_ARSL_PACE(IWV_BAND,:,2)=( &
!    ARSLND1*CSCAT1_MIE(IWV_BAND)*PHMXMIE_LOCAL1_MIE(IWV_BAND,:,5) + &
!    ARSLND2*CSCAT2_MIE(IWV_BAND)*PHMXMIE_LOCAL2_MIE(IWV_BAND,:,5) + &
!    ARSLNDD*CSCAT_DUSTF(IWV_BAND)*PHMX_DUSTF(IWV_BAND,:,2))/CSCAT_ARSL_BAND(IWV_BAND)
!
!    PHMXMIE_ARSL_PACE(IWV_BAND,:,3)=(&
!    ARSLND1*CSCAT1_MIE(IWV_BAND)*PHMXMIE_LOCAL1_MIE(IWV_BAND,:,2) + &
!    ARSLND2*CSCAT2_MIE(IWV_BAND)*PHMXMIE_LOCAL2_MIE(IWV_BAND,:,2) + &
!    ARSLNDD*CSCAT_DUSTF(IWV_BAND)*PHMX_DUSTF(IWV_BAND,:,3))/CSCAT_ARSL_BAND(IWV_BAND)
!
!    PHMXMIE_ARSL_PACE(IWV_BAND,:,4)=(&
!    ARSLND1*CSCAT1_MIE(IWV_BAND)*PHMXMIE_LOCAL1_MIE(IWV_BAND,:,3) + &
!    ARSLND2*CSCAT2_MIE(IWV_BAND)*PHMXMIE_LOCAL2_MIE(IWV_BAND,:,3) + &
!    ARSLNDD*CSCAT_DUSTF(IWV_BAND)*PHMX_DUSTF(IWV_BAND,:,4))/CSCAT_ARSL_BAND(IWV_BAND)
!
!    PHMXMIE_ARSL_PACE(IWV_BAND,:,5)=(&
!    ARSLND1*CSCAT1_MIE(IWV_BAND)*PHMXMIE_LOCAL1_MIE(IWV_BAND,:,6) + &
!    ARSLND2*CSCAT2_MIE(IWV_BAND)*PHMXMIE_LOCAL2_MIE(IWV_BAND,:,6) + &
!    ARSLNDD*CSCAT_DUSTF(IWV_BAND)*PHMX_DUSTF(IWV_BAND,:,5))/CSCAT_ARSL_BAND(IWV_BAND)
!
!    PHMXMIE_ARSL_PACE(IWV_BAND,:,6)=(&
!    ARSLND1*CSCAT1_MIE(IWV_BAND)*PHMXMIE_LOCAL1_MIE(IWV_BAND,:,4) + &
!    ARSLND2*CSCAT2_MIE(IWV_BAND)*PHMXMIE_LOCAL2_MIE(IWV_BAND,:,4) + &
!    ARSLNDD*CSCAT_DUSTF(IWV_BAND)*PHMX_DUSTF(IWV_BAND,:,6))/CSCAT_ARSL_BAND(IWV_BAND)
    END DO


    write(*,*) '****************************************************************'
    WRITE(*,*) 'NUMBER OF AEROSOL MODES = 3'
    WRITE(*,*) 'FINE MODE - INTERNAL MIXING'
    write(*,*) 'DUST AND COARSE MODE - EXTERNAL MIXING'
    write(*,*) '****************************************************************'
    IF(FMFRAC>0.0D0)THEN
        WRITE(*,*) 'REFF FINE MODE',REFF1_LOCAL
        WRITE(*,*) 'VEFF FINE  MODE', VEFF1_LOCAL
    ENDIF
    IF(DFRAC>0.0D0)THEN
        WRITE(*,*) 'REFF DUST MODE',REFFD
        WRITE(*,*) 'VEFF DUST MODE',VEFFD
    ENDIF
    IF((1-(FMFRAC-DFRAC))>0.0D0)THEN
        WRITE(*,*) 'REFF COARSE MODE',REFF2_LOCAL
        WRITE(*,*) 'VEFF COARSE MODE', VEFF2_LOCAL
    ENDIF
    WRITE(*,*) 'fine mode number density', ARSLND1
    WRITE(*,*) 'coarse mode number density', ARSLND2
    WRITE(*,*) 'dust mode number density',ARSLNDD

    ! pass effective radius and variance back to main program for output
    REFF1 = REFF1_LOCAL
    VEFF1 = VEFF1_LOCAL
    REFF2 = REFF2_LOCAL
    VEFF2 = VEFF2_LOCAL

 ENDIF
ENDIF

END SUBROUTINE PHMXMIE_Instrument_INIT

END MODULE


SUBROUTINE SPHER_INTERFACE(NDISTR,REFFI,VEFFI,LAM,MRR,MRI,AA1,BB1,AA2,BB2,GAMMAI,&
              REFFO,VEFFO,AREA,CEXT,CSCAT,NANGMIE_LOCAL,PHMXMIE_LOCAL)

USE MIE_PHMX_CAL,ONLY : NUMMIEANGMAX,PI

IMPLICIT REAL*8 (A-H,O-Z)                           
INTEGER ::  NANGMIE_LOCAL
REAL*8,DIMENSION(NUMMIEANGMAX,0:6)::PHMXMIE_LOCAL

INTEGER,PARAMETER:: NMIE=10000, NPL=2*NMIE
INTEGER NDISTR,LMAXI,IL
REAL*8 REFFI,VEFFI,LAM,MRR,MRI,AA1,BB1,AA2,BB2,GAMMAI,REFFO,VEFFO,AREA,CEXT,CSCAT
REAL*8 AL1(NPL),AL2(NPL),AL3(NPL),AL4(NPL),BET1(NPL),BET2(NPL)

!      CHARACTER*40 :: CFILE1,CHARTMP
!      open (6, file='spher.coeff')
!      AA=0.6D0
!      BB=0.2 D0
!      AA1=0.17D0
!      AA2=3.44D0
!      BB1=DLOG(1.96D0)*DLOG(1.96D0)
!      BB2=DLOG(2.37D0)*DLOG(2.37D0)
!      GAM=1D0                                                               
!      LAM=0.63D0                                            
!      MRR=1.53 D0                                               
!      MRI=0.008 D0                                            
!      NDISTR=3
!      NK=100
!      N=100
!      NP=4
      R1=0.0D0
      R2=20.0D0    

       IF(NDISTR==1) THEN
!     NDISTR = 1 - modified gamma distribution                         
!          [Eq. (5.242) of Ref. 1]                                        
!              AA=alpha                                                
!              BB=r_c                                                  
!              GAM=gamma                                               

            AA=GAMMAI-1
            BB=AA*REFFI/(GAMMAI+2.0D0)
            GAM=1.0D0
            
       ELSE IF(NDISTR==2) THEN
!C     NDISTR = 2 - log normal distribution                             
!C          [Eq. (5.243) of Ref. 1]                                        
!C              AA=r_g                                                  
!C              BB=[ln(sigma_g)]**2                                      
            BB=log(VEFFI+1.0D0)
            AA=REFFI*EXP(-2.5d0*BB)

       ELSE IF(NDISTR==3) THEN
!C     NDISTR = 3 - power law distribution                              
!C          [Eq. (5.244) of Ref. 1]                                        
!C               AA=r_eff (effective radius)                            
!C               BB=v_eff (effective variance)                          
!C               Parameters R1 and R2 (see below) are calculated        
!C               automatically for given AA and BB                      
                AA=REFFI
                BB=VEFFI

       ELSE IF(NDISTR==4) THEN
!C     NDISTR = 4 - gamma distribution                                  
!C          [Eq. (5.245) of Ref. 1]                                        
!C               AA=a                                                   
!C               BB=b      
!http://www.ess.uci.edu/~cmclinden/link/xx/node22.html
!HANSEN AND TRAVIS 1974 EQ. 2.56
                AA=REFFI  
                BB=VEFFI
                                                     
       ELSE IF(NDISTR==5) THEN
!C     NDISTR = 5 - modified power law distribution                     
!C          [Eq. (5.246) of Ref. 1]                                        
!C              BB=alpha          
               BB=GAMMAI
       ELSE IF(NDISTR==6) THEN
!C     NDISTR = 6 - bimodal volume log normal distribution              
!C              [Eq. (5.247) of Ref. 1]             
!C              AA1=r_g1                                                
!C              BB1=[ln(sigma_g1)]**2                                   
!C              AA2=r_g2                                                
!C              BB2=[ln(sigma_g2)]**2                                   
!C              GAM=gamma                                               
               GAM=GAMMAI
!C
       ELSE IF(NDISTR==7) THEN
!C    Added by Zhai, Pengwang Oct. 29 2008
!C     NDISTR = 7 - Junge distribution                              
!C          [n(r)=Constant*r^{-s}; s=4]
!C               Parameters R1 and R2 (see below)
!C               BB=JUNGE EXPONENTIAL FACTOR s                           
                BB=GAMMAI
                R1=0.1D0
                R2=50.0D0
       ELSE
          STOP 'NDISTR<1 OR > 7'
       ENDIF
       NK=20
       N=100
       NP=4
       WVNM=LAM*1000
       DDELT=1D-7

      CALL SPHER (AA,BB,GAM,LAM,MRR,MRI,R1,R2,N,NP,NDISTR,             &
            NK,L1,AL1,AL2,AL3,AL4,BET1,BET2,CEXT,CSCAT,AREA,VOL,RVW,  &
            RMEAN,REFFO,VEFFO,AA1,BB1,AA2,BB2,DDELT)
      QE=CEXT/AREA
      LMAX=L1-1

      LMAXI=LMAX
      CALL MATR (AL1,AL2,AL3,AL4,BET1,BET2,LMAX,NUMMIEANGMAX,NANGMIE_LOCAL,PHMXMIE_LOCAL)
      

!      WRITE (*,1001) AREA,VOL,RVW,RMEAN
! 1001 FORMAT ('<G> = ',D12.6,'  <V> = ',D12.6,'  Rvw = ',D12.6,&
!             &'  <R> = ',D12.6)
!write(*,*)'testing'
!  DO INTTMP=1,LMAXI+1
!      write(*,*)AL1(INTTMP),AL2(INTTMP),AL3(INTTMP),AL4(INTTMP),&
!             BET1(INTTMP),BET2(INTTMP)
!  ENDDO
!write(*,*)'testing over'
  
      RETURN
      END SUBROUTINE SPHER_INTERFACE




