MODULE AEROSOL_MICROPHYSICAL_MODEL
INTEGER,PARAMETER :: NWV_SF=16, NWV_JM=10
INTEGER,PARAMETER :: NAEROSOL=20,NRH=8,NFINEMODE=10

REAL*8 :: WV_REF=0.55d0  ! additional wavelength at which aerosol optical depth is assigned.

REAL*8,DIMENSION(NRH)::RH=(/0.30,0.50,0.70,0.75,0.80,0.85,0.90,0.95/)

REAL*8,DIMENSION(NWV_SF) :: WV_SF=(/0.30D0, 0.3371D0, 0.40D0, 0.4880D0, 0.5145D0, &
       0.55D0, 0.6322D0, 0.6943D0, 0.86D0, 1.06D0, 1.30D0, 1.5360D0, 1.80D0,     &
       2.D0, 2.25D0, 2.50D0/)

REAL*8,DIMENSION(NWV_JM) :: WV_JM=(/0.305D0,0.311D0, 0.317D0,  0.325D0,  0.332D0,  0.368D0, &
         0.440D0,  0.670D0, 0.870D0, 1.020D0/)


!SF data
REAL*8,DIMENSION(NWV_SF) ::    MR_WATER_SOLUBLE_SF=(/1.53D0, 1.53D0, 1.53D0, 1.53D0, &
       1.53D0, 1.53D0, 1.53D0, 1.53D0, 1.52D0, 1.52D0,1.51D0, 1.51D0, 1.46D0, 1.42D0,&
       1.42D0, 1.42D0/)
REAL*8,DIMENSION(NWV_SF) ::    MI_WATER_SOLUBLE_SF=(/0.008D0, 0.005D0, 0.005D0,  &
       0.005D0, 0.005D0, 0.006D0, 0.006D0, 0.007D0,0.012D0, 0.017D0, 0.02D0,     &
       0.023D0, 0.017D0, 0.008D0, 0.01D0, 0.012D0/)
REAL*8,DIMENSION(NWV_SF) ::    MR_DUST_SF=(/1.53D0, 1.53D0, 1.53D0, 1.53D0,      &
       1.53D0, 1.53D0, 1.53D0, 1.53D0, 1.52D0, 1.52D0, 1.46D0, 1.40D0,1.33D0,    &
       1.26D0, 1.22D0, 1.18D0/)
REAL*8,DIMENSION(NWV_SF) ::    MI_DUST_SF=(/0.008D0, 0.008D0, 0.008D0, 0.008D0,  &
       0.008D0, 0.008D0, 0.008D0, 0.008D0, 0.008D0, 0.008D0,0.008D0, 0.008D0,    &
       0.008D0, 0.008D0, 0.009D0, 0.009D0/)
REAL*8,DIMENSION(NWV_SF) ::    MR_SOOT_SF=(/1.74D0, 1.75D0, 1.75D0, 1.75D0, 1.75D0, &
       1.75D0, 1.75D0, 1.75D0, 1.75D0, 1.75D0, 1.76D0, 1.77D0,1.79D0, 1.80D0, 1.81D0, 1.82D0/)
REAL*8,DIMENSION(NWV_SF) ::    MI_SOOT_SF=(/0.47D0, 0.47D0, 0.46D0, 0.45D0, 0.45D0, &
       0.44D0, 0.43D0, 0.43D0, 0.43D0, 0.44D0, 0.45D0, 0.46D0,0.48D0, 0.49D0, 0.50D0, 0.51D0/)
REAL*8,DIMENSION(NWV_SF) ::    MR_SALT_SF=(/1.51D0,1.51D0,1.50D0,1.50D0,1.50D0, &
       1.50D0,1.49D0,1.49D0,1.48D0,1.47D0,1.47D0,1.46D0,1.45D0,1.45D0,1.44D0,1.43D0/)
REAL*8,DIMENSION(NWV_SF) ::    MI_SALT_SF=(/2.0D-6,4.0D-7,3.0D-8,2.0D-8,1.0D-8,  &
       1.0D-8,2.0D-8,1.0D-7,3.0D-6,2.0D-4,4.0D-4,6.0D-4,8.0D-4,1.0D-3,2.0D-3,4.0D-3/)
REAL*8,DIMENSION(NWV_SF) ::    MR_WATER_SF=(/1.349D0,1.345D0,1.339D0,1.335D0,   &
       1.334D0,1.333D0,1.332D0,1.331D0,1.329D0,1.326D0,1.323D0,1.318D0,1.312D0,1.306D0,1.292D0,1.261D0/)
REAL*8,DIMENSION(NWV_SF) ::    MI_WATER_SF=(/1.6D-8,8.45D-9,1.86D-9,9.69D-10,   &
       1.18D-9,1.96D-9,1.46D-8,3.05D-8,3.29D-7,4.18D-6,3.69D-5,9.97D-5,1.15D-4,1.10D-3,3.9D-4,1.74D-3/)
!Mok et al., 2016 (Impacts of brown carbon from biomass burning on surface UV and ozone photochemistry in the Amazon Basin)
!BrC volume fraction 0.27 (data corresponds to low temperature burn conditions : best estimate)
REAL*8,DIMENSION(NWV_JM) :: MR_BRC_JM=(/1.4905D0,1.4905D0,1.4905D0,1.4905D0,1.4905D0, &
	 1.4905D0,1.4905D0,1.4905D0,1.4905D0,1.4905D0/)
REAL*8, DIMENSION(NWV_JM):: MI_BRC_JM=(/0.4626D0, 0.3146D0, 0.3667D0, 0.1855D0, 0.2607D0, &
	 0.1501D0, 0.0501D0, 0.01051D0, 0.0334D0, 0.0042D0/)

!mode radius for different relative humidities (5)
!RTROPOSPHERE,RRURALC, RURBANF,RURBANC are from table 2 of Shettle, Fenn report
! RH=0.30,0.75,0.85 are interpolated from Table 2 of Shettle and Fenn report.
REAL*8,DIMENSION(NRH) :: RTROPOSPHERE=(/0.027288,0.02748,0.02846,0.0306,0.03274,0.03579,0.03884,0.04238/),  &
                         RRURALC=(/0.43462,0.4377, 0.4571,0.5024,0.5477,0.59695,0.6462,0.7078/),            &
                         ROCEANIC=(/0.1666,0.1711,0.2041,0.26105,0.3180,0.34915,0.3803,0.4606/),            &
                         RURBANF=(/0.025378,0.02563,0.02911,0.032125,0.03514,0.038505,0.04187,0.04904/),        &
                         RURBANC=(/0.40678,0.4113,0.4777,0.5291,0.5805,0.6433,0.7061,0.8634/),             &
                         RZIAF=(/0.150, 0.152, 0.158, 0.167,0.187,0.204, 0.221, 0.246/),           &
                         RZIAC=(/2.441,2.477,2.927,3.481,3.966,4.243,4.638,5.549/),               &
                         RATIO_WETDRY_ZIAF=(/1.006,1.0190,1.0630,1.118,1.2550,1.371, 1.4860, 1.6480/), &
                         RATIO_WETDRY_ZIAC=(/1.009,1.0240,1.2100,1.439,1.6390, 1.753, 1.9170, 2.2930/)
REAL*8,DIMENSION(NFINEMODE) :: RATIO_FINE_MODE_ZIA=(/0.0, 0.01, 0.02, 0.05, 0.1, 0.2,&
                                       0.3, 0.5, 0.8, 0.95/) ! from personal communication with Zia
!standard deviation
REAL*8,PARAMETER :: SIGF_SF=0.35*LOG(10.0),SIGC_SF=0.4*LOG(10.0),&
                    SIGF_ZIA=0.437,SIGC_ZIA=0.672

REAL*8,DIMENSION(:,:),ALLOCATABLE :: MR_TRPOSPHERE,MI_TRPOSPHERE,MR_RURALC,MI_RURALC,&
                             MR_OCEANIC,MI_OCEANIC,MR_URBANF,MI_URBANF,MR_URBANC,MI_URBANC, &
                             MR_URBANAF,MI_URBANAF,MR_URBANAC,MI_URBANAC, &
                             MR_URBANA1F,MI_URBANA1F,MR_URBANA1C,MI_URBANA1C, &
                             MR_URBANA2F,MI_URBANA2F,MR_URBANA2C,MI_URBANA2C, &
                             MR_URBANA3F,MI_URBANA3F,MR_URBANA3C,MI_URBANA3C, &
                             MR_ZIAF,MI_ZIAF,MR_ZIAC,MI_ZIAC
REAL*8,DIMENSION(:), ALLOCATABLE::MR_ZIACR,MI_ZIACR, MR_FLEXF, MR_FLEXC, MI_FLEXF,MI_FLEXC
REAL*8,DIMENSION(:),ALLOCATABLE::MR_SOOTF_TMP1,MI_SOOTF_TMP1,MR_DUSTF_TMP1,MI_DUSTF_TMP1,&
			MR_WATER_SOLUBLE_TMP1,MI_WATER_SOLUBLE_TMP1,MR_BRC_TMP1, MI_BRC_TMP1



CONTAINS
SUBROUTINE ARSL_INDX_DEALLO

DEALLOCATE(MR_TRPOSPHERE,MI_TRPOSPHERE,MR_RURALC,MI_RURALC,&
           MR_OCEANIC,MI_OCEANIC,MR_URBANF,MI_URBANF,MR_URBANC,MI_URBANC, &
           MR_URBANAF,MI_URBANAF,MR_URBANAC,MI_URBANAC, &
           MR_URBANA1F,MI_URBANA1F,MR_URBANA1C,MI_URBANA1C, &
           MR_URBANA2F,MI_URBANA2F,MR_URBANA2C,MI_URBANA2C, &
           MR_URBANA3F,MI_URBANA3F,MR_URBANA3C,MI_URBANA3C, &
           MR_ZIAF,MI_ZIAF,MR_ZIAC,MI_ZIAC)

END SUBROUTINE ARSL_INDX_DEALLO

SUBROUTINE ARSL_INDX_INIT(NWV, WV)
IMPLICIT NONE
INTEGER, INTENT(IN) :: NWV
REAL*8,DIMENSION(NWV),INTENT(IN)::WV

REAL*8,DIMENSION(NRH) ::RATIO_WETDRY_TROPO,RATIO_WETDRY_RURALC,RATIO_WETDRY_OCEANIC,&
                        RATIO_WETDRY_URBANF,RATIO_WETDRY_URBANC
REAL*8,DIMENSION(:),ALLOCATABLE::MR_WATER_SOLUBLE,MI_WATER_SOLUBLE,MR_DUST,MI_DUST,MR_SALT,MI_SALT,&
                      MR_SOOT,MI_SOOT,MR_WATER,MI_WATER,MR_BRC,MI_BRC
REAL*8,DIMENSION(:),ALLOCATABLE::MR_TROPO_RH0,MI_TROPO_RH0,MR_URBAN_RH0,MI_URBAN_RH0, &
	 MR_FLEX_RH0_F, MI_FLEX_RH0_F, MR_FLEX_RH0_C, MI_FLEX_RH0_C
REAL*8,DIMENSION(:,:),ALLOCATABLE::MR_SOOTF_TMP,MI_SOOTF_TMP,MR_DUSTF_TMP,MI_DUSTF_TMP, &
	 MR_WATER_SOLUBLE_TMP,MI_WATER_SOLUBLE_TMP,MR_BRC_TMP, MI_BRC_TMP
REAL*8 :: WV_tmp

REAL*8 :: POLINT_SIMPLE

INTEGER :: IWV,IRH
!N+1 to add reference wavelength (KHNP)

ALLOCATE(MR_TRPOSPHERE(NWV+1,NRH),MI_TRPOSPHERE(NWV+1,NRH),MR_RURALC(NWV+1,NRH),MI_RURALC(NWV+1,NRH),&
         MR_OCEANIC(NWV+1,NRH),MI_OCEANIC(NWV+1,NRH),MR_URBANF(NWV+1,NRH),MI_URBANF(NWV+1,NRH),      &
         MR_URBANC(NWV+1,NRH),MI_URBANC(NWV+1,NRH),MR_URBANAF(NWV+1,NRH),MI_URBANAF(NWV+1,NRH),      &
         MR_URBANAC(NWV+1,NRH),MI_URBANAC(NWV+1,NRH),MR_URBANA1F(NWV+1,NRH),MI_URBANA1F(NWV+1,NRH),  &
         MR_URBANA1C(NWV+1,NRH),MI_URBANA1C(NWV+1,NRH),MR_URBANA2F(NWV+1,NRH),MI_URBANA2F(NWV+1,NRH),&
         MR_URBANA2C(NWV+1,NRH),MI_URBANA2C(NWV+1,NRH),MR_URBANA3F(NWV+1,NRH),MI_URBANA3F(NWV+1,NRH),&
         MR_URBANA3C(NWV+1,NRH),MI_URBANA3C(NWV+1,NRH),MR_ZIAF(NWV+1,NRH),MI_ZIAF(NWV+1,NRH),        &
         MR_ZIAC(NWV+1,NRH),MI_ZIAC(NWV+1,NRH))


ALLOCATE(MR_WATER_SOLUBLE(NWV+1),MI_WATER_SOLUBLE(NWV+1),MR_DUST(NWV+1),MI_DUST(NWV+1),   &
  MR_SALT(NWV+1),MI_SALT(NWV+1),MR_SOOT(NWV+1),MI_SOOT(NWV+1),MR_WATER(NWV+1),MI_WATER(NWV+1),&
  MR_TROPO_RH0(NWV+1),MI_TROPO_RH0(NWV+1),MR_URBAN_RH0(NWV+1),MI_URBAN_RH0(NWV+1),        &
  MR_SOOTF_TMP(NWV+1,NRH),MI_SOOTF_TMP(NWV+1,NRH),MR_DUSTF_TMP(NWV+1,NRH),MI_DUSTF_TMP(NWV+1,NRH),&
  MR_BRC(NWV+1), MI_BRC(NWV+1),MR_BRC_TMP(NWV+1,NRH), MI_BRC_TMP(NWV+1,NRH),&
  MR_WATER_SOLUBLE_TMP(NWV+1,NRH),MI_WATER_SOLUBLE_TMP(NWV+1,NRH))


!interpolation to different wavelength ranges
DO IWV=1,NWV+1
   IF(IWV==NWV+1)THEN
      WV_tmp=WV_REF;
   ELSE
      WV_tmp=WV(IWV);
   ENDIF
   MR_WATER_SOLUBLE(IWV)=POLINT_SIMPLE(NWV_SF,WV_SF,MR_WATER_SOLUBLE_SF,WV_tmp,3)
   MI_WATER_SOLUBLE(IWV)=POLINT_SIMPLE(NWV_SF,WV_SF,MI_WATER_SOLUBLE_SF,WV_tmp,3)

   MR_DUST(IWV)=POLINT_SIMPLE(NWV_SF,WV_SF,MR_DUST_SF,WV_tmp,3)
   MI_DUST(IWV)=POLINT_SIMPLE(NWV_SF,WV_SF,MI_DUST_SF,WV_tmp,3)

   MR_SALT(IWV)=POLINT_SIMPLE(NWV_SF,WV_SF,MR_SALT_SF,WV_tmp,3)
   MI_SALT(IWV)=EXP(POLINT_SIMPLE(NWV_SF,WV_SF,LOG(MI_SALT_SF),WV_tmp,3))

   MR_SOOT(IWV)=POLINT_SIMPLE(NWV_SF,WV_SF,MR_SOOT_SF,WV_tmp,3)
   MI_SOOT(IWV)=POLINT_SIMPLE(NWV_SF,WV_SF,MI_SOOT_SF,WV_tmp,3)

   MR_WATER(IWV)=POLINT_SIMPLE(NWV_SF,WV_SF,MR_WATER_SF,WV_tmp,3)
   MI_WATER(IWV)=POLINT_SIMPLE(NWV_SF,WV_SF,MI_WATER_SF,WV_tmp,3)

   MR_BRC(IWV)=POLINT_SIMPLE(NWV_JM,WV_JM,MR_BRC_JM,WV_tmp,3)
!   MI_BRC(IWV)=POLINT_SIMPLE(NWV_JM,WV_JM,MI_BRC_JM,WV_tmp,3)
   MI_BRC(IWV)=0.0370D0*(0.368D0/WV_tmp)**5.6D0
ENDDO


RATIO_WETDRY_TROPO=RTROPOSPHERE/0.027d0
RATIO_WETDRY_RURALC=RRURALC/0.43d0
RATIO_WETDRY_OCEANIC=ROCEANIC/0.16d0
RATIO_WETDRY_URBANF=RURBANF/0.025d0
RATIO_WETDRY_URBANC=RURBANC/0.4d0

!construction of dry refractive index of different aerosol modes; fine and coarse under different conditions
MR_TROPO_RH0=0.7*MR_WATER_SOLUBLE+0.3*MR_DUST
MI_TROPO_RH0=0.7*MI_WATER_SOLUBLE+0.3*MI_DUST
   DO IWV=1,NWV+1
   DO IRH=1,NRH
    MR_TRPOSPHERE(IWV,IRH)=MR_WATER(IWV)+(MR_TROPO_RH0(IWV)-MR_WATER(IWV))&
               /RATIO_WETDRY_TROPO(IRH)**3
!equation adopted from Zia 2010 paper
   ENDDO
   ENDDO
   DO IWV=1,NWV+1
   DO IRH=1,NRH
    MI_TRPOSPHERE(IWV,IRH)=MI_WATER(IWV)+(MI_TROPO_RH0(IWV)-MI_WATER(IWV))&
               /RATIO_WETDRY_TROPO(IRH)**3
   ENDDO
   ENDDO

   DO IWV=1,NWV+1 
   DO IRH=1,NRH
    MR_RURALC(IWV,IRH)=MR_WATER(IWV)+(MR_TROPO_RH0(IWV)-MR_WATER(IWV))&
               /RATIO_WETDRY_RURALC(IRH)**3
   ENDDO 
   ENDDO
   DO IWV=1,NWV+1 
   DO IRH=1,NRH
    MI_RURALC(IWV,IRH)=MI_WATER(IWV)+(MI_TROPO_RH0(IWV)-MI_WATER(IWV))&
               /RATIO_WETDRY_RURALC(IRH)**3
   ENDDO 
   ENDDO
   
   DO IWV=1,NWV+1 
   DO IRH=1,NRH
    MR_OCEANIC(IWV,IRH)=MR_WATER(IWV)+(MR_SALT(IWV)-MR_WATER(IWV))&
               /RATIO_WETDRY_OCEANIC(IRH)**3
   ENDDO 
   ENDDO
   DO IWV=1,NWV+1 
   DO IRH=1,NRH
    MI_OCEANIC(IWV,IRH)=MI_WATER(IWV)+(MI_SALT(IWV)-MI_WATER(IWV))&
               /RATIO_WETDRY_OCEANIC(IRH)**3
   ENDDO 
   ENDDO

   MR_URBAN_RH0=0.8*MR_TROPO_RH0+0.2*MR_SOOT
   MI_URBAN_RH0=0.8*MI_TROPO_RH0+0.2*MI_SOOT

   DO IWV=1,NWV+1 
   DO IRH=1,NRH
    MR_URBANF(IWV,IRH)=MR_WATER(IWV)+(MR_URBAN_RH0(IWV)-MR_WATER(IWV))&
               /RATIO_WETDRY_URBANF(IRH)**3
!        write(*,*)WV(IWV),RH(IRH),MR_URBANF(IWV,IRH)
   ENDDO 
   ENDDO
   DO IWV=1,NWV+1 
   DO IRH=1,NRH
    MI_URBANF(IWV,IRH)=MI_WATER(IWV)+(MI_URBAN_RH0(IWV)-MI_WATER(IWV))&
               /RATIO_WETDRY_URBANF(IRH)**3
!       write(*,*)WV(IWV),RH(IRH),MI_URBANF(IWV,IRH),MI_WATER(IWV)
   ENDDO 
   ENDDO
   
   DO IWV=1,NWV+1 
   DO IRH=1,NRH
    MR_URBANC(IWV,IRH)=MR_WATER(IWV)+(MR_URBAN_RH0(IWV)-MR_WATER(IWV))&
               /RATIO_WETDRY_URBANC(IRH)**3
   ENDDO
   ENDDO
   DO IWV=1,NWV+1 
   DO IRH=1,NRH
    MI_URBANC(IWV,IRH)=MI_WATER(IWV)+(MI_URBAN_RH0(IWV)-MI_WATER(IWV))&
               /RATIO_WETDRY_URBANC(IRH)**3
   ENDDO 
   ENDDO

   ! URBAN A !
   MR_URBAN_RH0=0.85*MR_TROPO_RH0 +0.15*MR_SOOT
   MI_URBAN_RH0=0.85*MI_TROPO_RH0+0.15*MI_SOOT

   DO IWV=1,NWV+1 
   DO IRH=1,NRH
    MR_URBANAF(IWV,IRH)=MR_WATER(IWV)+(MR_URBAN_RH0(IWV)-MR_WATER(IWV))&
               /RATIO_WETDRY_URBANF(IRH)**3
   ENDDO 
   ENDDO
   DO IWV=1,NWV+1 
   DO IRH=1,NRH
    MI_URBANAF(IWV,IRH)=MI_WATER(IWV)+(MI_URBAN_RH0(IWV)-MI_WATER(IWV))&
               /RATIO_WETDRY_URBANF(IRH)**3
   ENDDO 
   ENDDO
   
   DO IWV=1,NWV+1 
   DO IRH=1,NRH
    MR_URBANAC(IWV,IRH)=MR_WATER(IWV)+(MR_URBAN_RH0(IWV)-MR_WATER(IWV))&
               /RATIO_WETDRY_URBANC(IRH)**3
   ENDDO 
   ENDDO
   DO IWV=1,NWV+1 
   DO IRH=1,NRH
    MI_URBANAC(IWV,IRH)=MI_WATER(IWV)+(MI_URBAN_RH0(IWV)-MI_WATER(IWV))&
               /RATIO_WETDRY_URBANC(IRH)**3
   ENDDO 
   ENDDO
   
   ! URBAN A1 !
   MR_URBAN_RH0=0.90*MR_TROPO_RH0+0.10*MR_SOOT
   MI_URBAN_RH0=0.90*MI_TROPO_RH0+0.10*MI_SOOT


   DO IWV=1,NWV+1 
   DO IRH=1,NRH
    MR_URBANA1F(IWV,IRH)=MR_WATER(IWV)+(MR_URBAN_RH0(IWV)-MR_WATER(IWV))&
               /RATIO_WETDRY_URBANF(IRH)**3
   ENDDO 
   ENDDO
   DO IWV=1,NWV+1 
   DO IRH=1,NRH
    MI_URBANA1F(IWV,IRH)=MI_WATER(IWV)+(MI_URBAN_RH0(IWV)-MI_WATER(IWV))&
               /RATIO_WETDRY_URBANF(IRH)**3
   ENDDO 
   ENDDO
   
   DO IWV=1,NWV+1 
   DO IRH=1,NRH
    MR_URBANA1C(IWV,IRH)=MR_WATER(IWV)+(MR_URBAN_RH0(IWV)-MR_WATER(IWV))&
               /RATIO_WETDRY_URBANC(IRH)**3
   ENDDO 
   ENDDO
   DO IWV=1,NWV+1 
   DO IRH=1,NRH
    MI_URBANA1C(IWV,IRH)=MI_WATER(IWV)+(MI_URBAN_RH0(IWV)-MI_WATER(IWV))&
               /RATIO_WETDRY_URBANC(IRH)**3
   ENDDO 
   ENDDO

   
   ! URBAN A2 !
   MR_URBAN_RH0=0.95*MR_TROPO_RH0+0.05*MR_SOOT
   MI_URBAN_RH0=0.95*MI_TROPO_RH0+0.05*MI_SOOT

   DO IWV=1,NWV+1 
   DO IRH=1,NRH
    MR_URBANA2F(IWV,IRH)=MR_WATER(IWV)+(MR_URBAN_RH0(IWV)-MR_WATER(IWV))&
               /RATIO_WETDRY_URBANF(IRH)**3
   ENDDO 
   ENDDO
   DO IWV=1,NWV+1 
   DO IRH=1,NRH
    MI_URBANA2F(IWV,IRH)=MI_WATER(IWV)+(MI_URBAN_RH0(IWV)-MI_WATER(IWV))&
               /RATIO_WETDRY_URBANF(IRH)**3
   ENDDO 
   ENDDO
   
   DO IWV=1,NWV+1 
   DO IRH=1,NRH
    MR_URBANA2C(IWV,IRH)=MR_WATER(IWV)+(MR_URBAN_RH0(IWV)-MR_WATER(IWV))&
               /RATIO_WETDRY_URBANC(IRH)**3
   ENDDO 
   ENDDO
   DO IWV=1,NWV+1 
   DO IRH=1,NRH
    MI_URBANA2C(IWV,IRH)=MI_WATER(IWV)+(MI_URBAN_RH0(IWV)-MI_WATER(IWV))&
               /RATIO_WETDRY_URBANC(IRH)**3
   ENDDO 
   ENDDO
   
      ! URBAN A3 !
   MR_URBAN_RH0=0.975*MR_TROPO_RH0+0.025*MR_SOOT
   MI_URBAN_RH0=0.975*MI_TROPO_RH0+0.025*MI_SOOT

   DO IWV=1,NWV+1 
   DO IRH=1,NRH
    MR_URBANA3F(IWV,IRH)=MR_WATER(IWV)+(MR_URBAN_RH0(IWV)-MR_WATER(IWV))&
               /RATIO_WETDRY_URBANF(IRH)**3
   ENDDO 
   ENDDO
   DO IWV=1,NWV+1 
   DO IRH=1,NRH
    MI_URBANA3F(IWV,IRH)=MI_WATER(IWV)+(MI_URBAN_RH0(IWV)-MI_WATER(IWV))&
               /RATIO_WETDRY_URBANF(IRH)**3
   ENDDO 
   ENDDO

   DO IWV=1,NWV+1 
   DO IRH=1,NRH
    MR_URBANA3C(IWV,IRH)=MR_WATER(IWV)+(MR_URBAN_RH0(IWV)-MR_WATER(IWV))&
               /RATIO_WETDRY_URBANC(IRH)**3
   ENDDO 
   ENDDO
   DO IWV=1,NWV+1
   DO IRH=1,NRH
    MI_URBANA3C(IWV,IRH)=MI_WATER(IWV)+(MI_URBAN_RH0(IWV)-MI_WATER(IWV))&
               /RATIO_WETDRY_URBANC(IRH)**3
   ENDDO 
   ENDDO
   
   DO IWV=1,NWV+1 
   DO IRH=1,NRH
    MR_ZIAC(IWV,IRH)=MR_WATER(IWV)+(MR_SALT(IWV)-MR_WATER(IWV)) &
               /RATIO_WETDRY_ZIAC(IRH)**3
   ENDDO 
   ENDDO


   DO IWV=1,NWV+1 
   DO IRH=1,NRH
    MI_ZIAC(IWV,IRH)=MI_WATER(IWV)+(MI_SALT(IWV)-MI_WATER(IWV)) &
               /RATIO_WETDRY_ZIAC(IRH)**3
   ENDDO 
   ENDDO
   
   DO IWV=1,NWV+1 
   DO IRH=1,NRH
    MR_SOOTF_TMP(IWV,IRH)=MR_WATER(IWV)+(MR_SOOT(IWV)-MR_WATER(IWV)) &
               /RATIO_WETDRY_ZIAF(IRH)**3
    MR_DUSTF_TMP(IWV,IRH)=MR_WATER(IWV)+(MR_DUST(IWV)-MR_WATER(IWV)) &
               /RATIO_WETDRY_ZIAF(IRH)**3
   ENDDO 
   ENDDO
   
   MR_ZIAF=0.995*MR_DUSTF_TMP+0.005*MR_SOOTF_TMP

   DO IWV=1,NWV+1 
   DO IRH=1,NRH
    MI_SOOTF_TMP(IWV,IRH)=MI_WATER(IWV)+(MI_SOOT(IWV)-MI_WATER(IWV)) &
               /RATIO_WETDRY_ZIAF(IRH)**3
    MI_DUSTF_TMP(IWV,IRH)=MI_WATER(IWV)+(MI_DUST(IWV)-MI_WATER(IWV)) &
               /RATIO_WETDRY_ZIAF(IRH)**3
   ENDDO 
   ENDDO
   
   MI_ZIAF=0.995*MI_DUSTF_TMP+0.005*MI_SOOTF_TMP


DEALLOCATE(MR_WATER_SOLUBLE,MI_WATER_SOLUBLE,MR_DUST,MI_DUST,MR_SALT,MI_SALT,&
           MR_SOOT,MI_SOOT,MR_WATER,MI_WATER,MR_TROPO_RH0,MI_TROPO_RH0,      &
           MR_URBAN_RH0,MI_URBAN_RH0,MR_SOOTF_TMP,MI_SOOTF_TMP,MR_DUSTF_TMP, &
           MI_DUSTF_TMP,MR_BRC,MI_BRC,MR_BRC_TMP, MI_BRC_TMP,&
           MR_WATER_SOLUBLE_TMP,MI_WATER_SOLUBLE_TMP)

END SUBROUTINE ARSL_INDX_INIT



SUBROUTINE ARSL_REF_INDX_INIT_IMIX(NWV,WV,rhi,r0f,r0c, rf1,rf2,rf3,nmode)

  INTEGER, INTENT(IN) :: NWV,NMODE
  REAL*8, DIMENSION(NWV),INTENT(IN)::WV
  REAL*8,  INTENT(IN) :: rf1,rf2,rf3,RHI,R0F,R0C
  REAL*8 :: RRH_F,RRH_C
  REAL*8 :: WDRF,WDRC
  REAL*8,DIMENSION(:),ALLOCATABLE::MR_WATER_SOLUBLE,MI_WATER_SOLUBLE,MR_DUST,MI_DUST,MR_SALT,MI_SALT,&
       MR_SOOT,MI_SOOT,MR_WATER,MI_WATER,MI_BRC,MR_BRC
  REAL*8,DIMENSION(:),ALLOCATABLE:: MR_FLEX_RH0_F, MI_FLEX_RH0_F, MR_FLEX_RH0_C, MI_FLEX_RH0_C
  REAL*8,DIMENSION(:),ALLOCATABLE::MR_SOOTF_TMP,MI_SOOTF_TMP,MR_DUSTF_TMP,MI_DUSTF_TMP, &
       MR_WATER_SOLUBLE_TMP,MI_WATER_SOLUBLE_TMP,MR_BRC_TMP, MI_BRC_TMP
  REAL*8 :: WV_tmp
  REAL*8 :: POLINT_SIMPLE
  INTEGER :: IWV

  ALLOCATE(MR_FLEXF(NWV+1), MI_FLEXF(NWV+1), MR_FLEXC(NWV+1), MI_FLEXC(NWV+1))

  ALLOCATE(MR_WATER_SOLUBLE(NWV+1),MI_WATER_SOLUBLE(NWV+1),MR_DUST(NWV+1),MI_DUST(NWV+1),   &
       MR_SALT(NWV+1),MI_SALT(NWV+1),MR_SOOT(NWV+1),MI_SOOT(NWV+1),MR_WATER(NWV+1),MI_WATER(NWV+1),&
       MR_SOOTF_TMP(NWV+1),MI_SOOTF_TMP(NWV+1),MR_DUSTF_TMP(NWV+1),MI_DUSTF_TMP(NWV+1),&
       MR_BRC(NWV+1), MI_BRC(NWV+1),MR_BRC_TMP(NWV+1), MI_BRC_TMP(NWV+1),&
       MR_WATER_SOLUBLE_TMP(NWV+1),MI_WATER_SOLUBLE_TMP(NWV+1),MR_ZIACR(NWV+1),MI_ZIACR(NWV+1))

  !interpolation to different wavelength ranges
  DO IWV=1,NWV+1
     IF(IWV==NWV+1)THEN
        WV_tmp=WV_REF;
     ELSE
        WV_tmp=WV(IWV);
     ENDIF
     MR_WATER_SOLUBLE(IWV)=POLINT_SIMPLE(NWV_SF,WV_SF,MR_WATER_SOLUBLE_SF,WV_tmp,3)
     MI_WATER_SOLUBLE(IWV)=POLINT_SIMPLE(NWV_SF,WV_SF,MI_WATER_SOLUBLE_SF,WV_tmp,3)

     MR_DUST(IWV)=POLINT_SIMPLE(NWV_SF,WV_SF,MR_DUST_SF,WV_tmp,3)
     MI_DUST(IWV)=POLINT_SIMPLE(NWV_SF,WV_SF,MI_DUST_SF,WV_tmp,3)

     MR_SALT(IWV)=POLINT_SIMPLE(NWV_SF,WV_SF,MR_SALT_SF,WV_tmp,3)
     MI_SALT(IWV)=EXP(POLINT_SIMPLE(NWV_SF,WV_SF,LOG(MI_SALT_SF),WV_tmp,3))

     MR_SOOT(IWV)=POLINT_SIMPLE(NWV_SF,WV_SF,MR_SOOT_SF,WV_tmp,3)
     MI_SOOT(IWV)=POLINT_SIMPLE(NWV_SF,WV_SF,MI_SOOT_SF,WV_tmp,3)

     MR_WATER(IWV)=POLINT_SIMPLE(NWV_SF,WV_SF,MR_WATER_SF,WV_tmp,3)
     MI_WATER(IWV)=POLINT_SIMPLE(NWV_SF,WV_SF,MI_WATER_SF,WV_tmp,3)

     MR_BRC(IWV)=POLINT_SIMPLE(NWV_JM,WV_JM,MR_BRC_JM,WV_tmp,3)
!     MI_BRC(IWV)=POLINT_SIMPLE(NWV_JM,WV_JM,MI_BRC_JM,WV_tmp,3)
     MI_BRC(IWV)=0.0370D0*(0.368D0/WV_tmp)**5.6D0
  ENDDO

  CALL HYGROSCOPIC_GROWTH_IMIX(R0F,R0C,RHI, RRH_F,RRH_C)
  
  WDRF = RRH_F/R0F
  WDRC = RRH_C/R0C
  
  DO IWV=1,NWV+1
        MR_SOOTF_TMP(IWV)=MR_WATER(IWV)+(MR_SOOT(IWV)-MR_WATER(IWV)) &
             /WDRF**3
        MR_DUSTF_TMP(IWV)=MR_WATER(IWV)+(MR_DUST(IWV)-MR_WATER(IWV)) &
             /WDRF**3
  ENDDO

  DO IWV=1,NWV+1
        MI_SOOTF_TMP(IWV)=MI_WATER(IWV)+(MI_SOOT(IWV)-MI_WATER(IWV)) &
             /WDRF**3
        MI_DUSTF_TMP(IWV)=MI_WATER(IWV)+(MI_DUST(IWV)-MI_WATER(IWV)) &
             /WDRF**3
  ENDDO

 
  DO IWV=1,NWV+1
        MR_BRC_TMP(IWV)=MR_WATER(IWV)+(MR_BRC(IWV)-MR_WATER(IWV))&
             /WDRF**3
        MI_BRC_TMP(IWV)=MI_WATER(IWV)+(MI_BRC(IWV)-MI_WATER(IWV))&
             /WDRF**3
  ENDDO

 

  DO IWV=1,NWV+1
        MR_WATER_SOLUBLE_TMP(IWV)=MR_WATER(IWV)+(MR_WATER_SOLUBLE(IWV)-MR_WATER(IWV))&
             /WDRF**3
        MI_WATER_SOLUBLE_TMP(IWV)=MI_WATER(IWV)+(MI_WATER_SOLUBLE(IWV)-MI_WATER(IWV))&
             /WDRF**3
     END DO

     DO IWV=1,NWV+1
        MR_ZIACR(IWV)=MR_WATER(IWV)+(MR_SALT(IWV)-MR_WATER(IWV)) &
             /WDRC**3
        MI_ZIACR(IWV)=MI_WATER(IWV)+(MI_SALT(IWV)-MI_WATER(IWV)) &
                            /WDRC**3
     ENDDO

     IF (NMODE==2) THEN
     MR_FLEXF=rf1*MR_DUSTF_TMP + rf2*MR_WATER_SOLUBLE_TMP + rf3*MR_BRC_TMP + (1-(rf1+rf2+rf3))*MR_SOOTF_TMP
     MI_FLEXF=rf1*MI_DUSTF_TMP + rf2*MI_WATER_SOLUBLE_TMP + rf3*MI_BRC_TMP + (1-(rf1+rf2+rf3))*MI_SOOTF_TMP
     ELSEIF (NMODE==3)THEN
     MR_FLEXF=rf2*MR_WATER_SOLUBLE_TMP + rf3*MR_BRC_TMP + (1-(rf2+rf3))*MR_SOOTF_TMP
     MI_FLEXF=rf2*MI_WATER_SOLUBLE_TMP + rf3*MI_BRC_TMP + (1-(rf2+rf3))*MI_SOOTF_TMP
  ENDIF
  
     MR_FLEXC=MR_ZIACR
     MI_FLEXC=MI_ZIACR
     
   END SUBROUTINE ARSL_REF_INDX_INIT_IMIX



SUBROUTINE ARSL_REF_INDX_INIT_EMIX(NWV,WV,RHI,R0DL,R0WS,R0BC,R0S,R0SS)

  IMPLICIT NONE
  INTEGER, INTENT(IN) :: NWV
  REAL*8, DIMENSION(NWV),INTENT(IN)::WV
  REAL*8, INTENT(IN) :: R0DL,R0WS,R0BC,R0S,R0SS,RHI
  REAL*8,DIMENSION(:),ALLOCATABLE::MR_WATER_SOLUBLE,MI_WATER_SOLUBLE,MR_DUST,MI_DUST,MR_SALT,MI_SALT,&
       MR_SOOT,MI_SOOT,MR_WATER,MI_WATER,MI_BRC,MR_BRC
  REAL*8,DIMENSION(:),ALLOCATABLE:: MR_FLEX_RH0_F, MI_FLEX_RH0_F, MR_FLEX_RH0_C, MI_FLEX_RH0_C
  REAL*8 :: WV_tmp
  REAL*8 :: POLINT_SIMPLE
  INTEGER :: IWV
  REAL*8 :: RRH_DL,RRH_WS,RRH_BC,RRH_S,RRH_SS, RRH_F,RRH_C
  REAL*8 :: WDRDL,WDRWS,WDRBC,WDRS,WDRSS

  ALLOCATE(MR_WATER_SOLUBLE(NWV+1),MI_WATER_SOLUBLE(NWV+1),MR_DUST(NWV+1),MI_DUST(NWV+1),   &
       MR_SALT(NWV+1),MI_SALT(NWV+1),MR_SOOT(NWV+1),MI_SOOT(NWV+1),MR_WATER(NWV+1),MI_WATER(NWV+1),&
       MR_SOOTF_TMP1(NWV+1),MI_SOOTF_TMP1(NWV+1),MR_DUSTF_TMP1(NWV+1),MI_DUSTF_TMP1(NWV+1),&
       MR_BRC(NWV+1), MI_BRC(NWV+1),MR_BRC_TMP1(NWV+1), MI_BRC_TMP1(NWV+1),&
       MR_WATER_SOLUBLE_TMP1(NWV+1),MI_WATER_SOLUBLE_TMP1(NWV+1),MR_ZIACR(NWV+1),MI_ZIACR(NWV+1))

  !interpolation to different wavelength ranges
  DO IWV=1,NWV+1
     IF(IWV==NWV+1)THEN
        WV_tmp=WV_REF;
     ELSE
        WV_tmp=WV(IWV);
     ENDIF
     MR_WATER_SOLUBLE(IWV)=POLINT_SIMPLE(NWV_SF,WV_SF,MR_WATER_SOLUBLE_SF,WV_tmp,3)
     MI_WATER_SOLUBLE(IWV)=POLINT_SIMPLE(NWV_SF,WV_SF,MI_WATER_SOLUBLE_SF,WV_tmp,3)

     MR_DUST(IWV)=POLINT_SIMPLE(NWV_SF,WV_SF,MR_DUST_SF,WV_tmp,3)
     MI_DUST(IWV)=POLINT_SIMPLE(NWV_SF,WV_SF,MI_DUST_SF,WV_tmp,3)

     MR_SALT(IWV)=POLINT_SIMPLE(NWV_SF,WV_SF,MR_SALT_SF,WV_tmp,3)
     MI_SALT(IWV)=EXP(POLINT_SIMPLE(NWV_SF,WV_SF,LOG(MI_SALT_SF),WV_tmp,3))

     MR_SOOT(IWV)=POLINT_SIMPLE(NWV_SF,WV_SF,MR_SOOT_SF,WV_tmp,3)
     MI_SOOT(IWV)=POLINT_SIMPLE(NWV_SF,WV_SF,MI_SOOT_SF,WV_tmp,3)

     MR_WATER(IWV)=POLINT_SIMPLE(NWV_SF,WV_SF,MR_WATER_SF,WV_tmp,3)
     MI_WATER(IWV)=POLINT_SIMPLE(NWV_SF,WV_SF,MI_WATER_SF,WV_tmp,3)

     MR_BRC(IWV)=POLINT_SIMPLE(NWV_JM,WV_JM,MR_BRC_JM,WV_tmp,3)
!     MI_BRC(IWV)=POLINT_SIMPLE(NWV_JM,WV_JM,MI_BRC_JM,WV_tmp,3)
     MI_BRC(IWV)=0.0370D0*(0.368D0/WV_tmp)**5.6D0
  ENDDO

  CALL HYGROSCOPIC_GROWTH_EMIX(R0DL,R0WS,R0BC,R0S,R0SS,RHI, RRH_DL,RRH_WS,RRH_BC,RRH_S,RRH_SS)
  CALL HYGROSCOPIC_GROWTH_IMIX(1.0D0,R0SS,RHI, RRH_F,RRH_C)
  WDRDL = RRH_DL/R0DL
  WDRWS = RRH_WS/R0WS
  WDRBC = RRH_BC/R0BC
  WDRS = RRH_S/R0S
  WDRSS = RRH_C/R0SS
  
  DO IWV=1,NWV+1
     MR_SOOTF_TMP1(IWV)=MR_WATER(IWV)+(MR_SOOT(IWV)-MR_WATER(IWV)) &
          /WDRS**3
     MR_DUSTF_TMP1(IWV)=MR_WATER(IWV)+(MR_DUST(IWV)-MR_WATER(IWV)) &
          /WDRDL**3
  ENDDO

  DO IWV=1,NWV+1
     MI_SOOTF_TMP1(IWV)=MI_WATER(IWV)+(MI_SOOT(IWV)-MI_WATER(IWV)) &
          /WDRS**3
     MI_DUSTF_TMP1(IWV)=MI_WATER(IWV)+(MI_DUST(IWV)-MI_WATER(IWV)) &
          /WDRDL**3
  ENDDO


  DO IWV=1,NWV+1
     MR_BRC_TMP1(IWV)=MR_WATER(IWV)+(MR_BRC(IWV)-MR_WATER(IWV))&
          /WDRBC**3
     MI_BRC_TMP1(IWV)=MI_WATER(IWV)+(MI_BRC(IWV)-MI_WATER(IWV))&
          /WDRBC**3
  ENDDO

  DO IWV=1,NWV+1
     MR_WATER_SOLUBLE_TMP1(IWV)=MR_WATER(IWV)+(MR_WATER_SOLUBLE(IWV)-MR_WATER(IWV))&
          /WDRWS**3
     MI_WATER_SOLUBLE_TMP1(IWV)=MI_WATER(IWV)+(MI_WATER_SOLUBLE(IWV)-MI_WATER(IWV))&
          /WDRWS**3
  END DO

  DO IWV=1,NWV+1
     MR_ZIACR(IWV)=MR_WATER(IWV)+(MR_SALT(IWV)-MR_WATER(IWV)) &
          /WDRSS**3
     MI_ZIACR(IWV)=MI_WATER(IWV)+(MI_SALT(IWV)-MI_WATER(IWV)) &
                         /WDRSS**3
  ENDDO

  
END SUBROUTINE ARSL_REF_INDX_INIT_EMIX


SUBROUTINE ARSL_REF_INDX_INIT_IMIX2(NWV,WV,RHI,R0DL,R0WS,R0BC,R0S,R0SS, RF1,RF2,RF3)

  IMPLICIT NONE
  INTEGER, INTENT(IN) :: NWV
  REAL*8, DIMENSION(NWV),INTENT(IN)::WV
  REAL*8, INTENT(IN) :: R0DL,R0WS,R0BC,R0S,R0SS,RHI, RF1, RF2, RF3
  REAL*8,DIMENSION(:),ALLOCATABLE::MR_WATER_SOLUBLE,MI_WATER_SOLUBLE,MR_DUST,MI_DUST,MR_SALT,MI_SALT,&
       MR_SOOT,MI_SOOT,MR_WATER,MI_WATER,MI_BRC,MR_BRC
  REAL*8,DIMENSION(:),ALLOCATABLE:: MR_FLEX_RH0_F, MI_FLEX_RH0_F, MR_FLEX_RH0_C, MI_FLEX_RH0_C
  REAL*8 :: WV_tmp
  REAL*8 :: POLINT_SIMPLE
  INTEGER :: IWV
  REAL*8 :: RRH_DL,RRH_WS,RRH_BC,RRH_S,RRH_SS, RRH_F,RRH_C
  REAL*8 :: WDRDL,WDRWS,WDRBC,WDRS,WDRSS

  ALLOCATE(MR_FLEXF(NWV+1), MI_FLEXF(NWV+1), MR_FLEXC(NWV+1), MI_FLEXC(NWV+1))
  

  ALLOCATE(MR_WATER_SOLUBLE(NWV+1),MI_WATER_SOLUBLE(NWV+1),MR_DUST(NWV+1),MI_DUST(NWV+1),   &
       MR_SALT(NWV+1),MI_SALT(NWV+1),MR_SOOT(NWV+1),MI_SOOT(NWV+1),MR_WATER(NWV+1),MI_WATER(NWV+1),&
       MR_SOOTF_TMP1(NWV+1),MI_SOOTF_TMP1(NWV+1),MR_DUSTF_TMP1(NWV+1),MI_DUSTF_TMP1(NWV+1),&
       MR_BRC(NWV+1), MI_BRC(NWV+1),MR_BRC_TMP1(NWV+1), MI_BRC_TMP1(NWV+1),&
       MR_WATER_SOLUBLE_TMP1(NWV+1),MI_WATER_SOLUBLE_TMP1(NWV+1),MR_ZIACR(NWV+1),MI_ZIACR(NWV+1))


  DO IWV=1,NWV+1
     IF(IWV==NWV+1)THEN
        WV_tmp=WV_REF;
     ELSE
        WV_tmp=WV(IWV);
     ENDIF
     MR_WATER_SOLUBLE(IWV)=POLINT_SIMPLE(NWV_SF,WV_SF,MR_WATER_SOLUBLE_SF,WV_tmp,3)
     MI_WATER_SOLUBLE(IWV)=POLINT_SIMPLE(NWV_SF,WV_SF,MI_WATER_SOLUBLE_SF,WV_tmp,3)

     MR_DUST(IWV)=POLINT_SIMPLE(NWV_SF,WV_SF,MR_DUST_SF,WV_tmp,3)
     MI_DUST(IWV)=POLINT_SIMPLE(NWV_SF,WV_SF,MI_DUST_SF,WV_tmp,3)

     MR_SALT(IWV)=POLINT_SIMPLE(NWV_SF,WV_SF,MR_SALT_SF,WV_tmp,3)
     MI_SALT(IWV)=EXP(POLINT_SIMPLE(NWV_SF,WV_SF,LOG(MI_SALT_SF),WV_tmp,3))

     MR_SOOT(IWV)=POLINT_SIMPLE(NWV_SF,WV_SF,MR_SOOT_SF,WV_tmp,3)
     MI_SOOT(IWV)=POLINT_SIMPLE(NWV_SF,WV_SF,MI_SOOT_SF,WV_tmp,3)

     MR_WATER(IWV)=POLINT_SIMPLE(NWV_SF,WV_SF,MR_WATER_SF,WV_tmp,3)
     MI_WATER(IWV)=POLINT_SIMPLE(NWV_SF,WV_SF,MI_WATER_SF,WV_tmp,3)

     MR_BRC(IWV)=POLINT_SIMPLE(NWV_JM,WV_JM,MR_BRC_JM,WV_tmp,3)
!     MI_BRC(IWV)=POLINT_SIMPLE(NWV_JM,WV_JM,MI_BRC_JM,WV_tmp,3)
     MI_BRC(IWV)=0.0370D0*(0.368D0/WV_tmp)**5.6D0
  ENDDO

  CALL HYGROSCOPIC_GROWTH_EMIX(R0DL,R0WS,R0BC,R0S,R0SS,RHI, RRH_DL,RRH_WS,RRH_BC,RRH_S,RRH_SS)
  CALL HYGROSCOPIC_GROWTH_IMIX(1.0D0,R0SS,RHI, RRH_F,RRH_C)
  
  WDRDL = RRH_DL/R0DL
  WDRWS = RRH_WS/R0WS
  WDRBC = RRH_BC/R0BC
  WDRS = RRH_S/R0S
  WDRSS = RRH_C/R0SS

  DO IWV=1,NWV+1
     MR_SOOTF_TMP1(IWV)=MR_WATER(IWV)+(MR_SOOT(IWV)-MR_WATER(IWV)) &
          /WDRS**3
     MR_DUSTF_TMP1(IWV)=MR_WATER(IWV)+(MR_DUST(IWV)-MR_WATER(IWV)) &
          /WDRDL**3
  ENDDO

  DO IWV=1,NWV+1
     MI_SOOTF_TMP1(IWV)=MI_WATER(IWV)+(MI_SOOT(IWV)-MI_WATER(IWV)) &
          /WDRS**3
     MI_DUSTF_TMP1(IWV)=MI_WATER(IWV)+(MI_DUST(IWV)-MI_WATER(IWV)) &
          /WDRDL**3
  ENDDO


  DO IWV=1,NWV+1
     MR_BRC_TMP1(IWV)=MR_WATER(IWV)+(MR_BRC(IWV)-MR_WATER(IWV))&
          /WDRBC**3
     MI_BRC_TMP1(IWV)=MI_WATER(IWV)+(MI_BRC(IWV)-MI_WATER(IWV))&
          /WDRBC**3
  ENDDO


  DO IWV=1,NWV+1
     MR_WATER_SOLUBLE_TMP1(IWV)=MR_WATER(IWV)+(MR_WATER_SOLUBLE(IWV)-MR_WATER(IWV))&
          /WDRWS**3
     MI_WATER_SOLUBLE_TMP1(IWV)=MI_WATER(IWV)+(MI_WATER_SOLUBLE(IWV)-MI_WATER(IWV))&
          /WDRWS**3
  END DO

  DO IWV=1,NWV+1
     MR_ZIACR(IWV)=MR_WATER(IWV)+(MR_SALT(IWV)-MR_WATER(IWV)) &
          /WDRSS**3
     MI_ZIACR(IWV)=MI_WATER(IWV)+(MI_SALT(IWV)-MI_WATER(IWV)) &
          /WDRSS**3
  ENDDO

  MR_FLEXF=rf1*MR_DUSTF_TMP1 + rf2*MR_WATER_SOLUBLE_TMP1 + rf3*MR_BRC_TMP1 + (1-(rf1+rf2+rf3))*MR_SOOTF_TMP1
  MI_FLEXF=rf1*MI_DUSTF_TMP1 + rf2*MI_WATER_SOLUBLE_TMP1 + rf3*MI_BRC_TMP1 + (1-(rf1+rf2+rf3))*MI_SOOTF_TMP1
  MR_FLEXC=MR_ZIACR
  MI_FLEXC=MI_ZIACR
  
END SUBROUTINE ARSL_REF_INDX_INIT_IMIX2

SUBROUTINE HYGROSCOPIC_GROWTH_IMIX(R0F,R0C,RHI, RRH_F,RRH_C)
  IMPLICIT NONE
  INTEGER, PARAMETER :: NRH_ZIA=8
  REAL*8,DIMENSION(NRH_ZIA) :: WETDRYRF_ZIA, WETDRYRC_ZIA, RH_ZIA
  REAL*8, INTENT(IN) :: R0F,R0C,RHI
  REAL*8 :: GAMMA_F, GAMMA_C
  REAL*8, INTENT(OUT) :: RRH_F,RRH_C
  REAL*8,DIMENSION(NRH_ZIA) :: GAMMA_FA, GAMMA_CA
  INTEGER :: IRH
  REAL*8 :: POLINT_SIMPLE

  WETDRYRF_ZIA = (/1.006D0, 1.019D0, 1.063D0, 1.118D0, 1.255D0, 1.371D0, 1.486D0, 1.648D0/)
  WETDRYRC_ZIA = (/1.009D0, 1.024D0, 1.210D0, 1.439D0, 1.639D0, 1.753D0, 1.917D0, 2.293D0/)
  RH_ZIA = (/0.3D0,0.5D0,0.7D0,0.75D0,0.8D0,0.85D0,0.9D0,0.95D0/)

  DO IRH = 1,NRH_ZIA
     GAMMA_FA(IRH) = 3.0*LOG(WETDRYRF_ZIA(IRH))/LOG(1/(1-RH_ZIA(IRH)))
     GAMMA_CA(IRH) = 3.0*LOG(WETDRYRC_ZIA(IRH))/LOG(1/(1-RH_ZIA(IRH)))
  END DO

  
  IF (RHI >= 0.7) THEN
     GAMMA_F = POLINT_SIMPLE(6, RH_ZIA(3:), GAMMA_FA(3:),RHI,4)
     GAMMA_C = POLINT_SIMPLE(6, RH_ZIA(3:), GAMMA_CA(3:),RHI,4)
  ELSEIF (RHI < 0.7) THEN
     GAMMA_F = POLINT_SIMPLE(3, RH_ZIA(:3), GAMMA_FA(:3),RHI,3)
     GAMMA_C = POLINT_SIMPLE(3, RH_ZIA(:3), GAMMA_CA(:3),RHI,3)
  END IF
  
RRH_F = ((1/(1-RHI))**GAMMA_F)**(1.0/3.0)*R0F
RRH_C = ((1/(1-RHI))**GAMMA_C)**(1.0/3.0)*R0C
END SUBROUTINE HYGROSCOPIC_GROWTH_IMIX



SUBROUTINE  HYGROSCOPIC_GROWTH_EMIX(R0DL,R0WS,R0BC,R0S,R0SS,RHI, RRH_DL,RRH_WS,RRH_BC,RRH_S,RRH_SS)

  IMPLICIT NONE
  INTEGER, PARAMETER :: NRHV=7
  REAL*8 :: GAMMA_SS, GAMMA_WS
  REAL*8, INTENT(IN) :: RHI,R0DL,R0WS,R0BC,R0S,R0SS
  REAL*8 :: GAMMAWS, GAMMASS
  REAL*8, INTENT(OUT) :: RRH_DL,RRH_WS,RRH_BC,RRH_S,RRH_SS
  REAL*8,DIMENSION(NRHV) :: GAMMA_WSA, GAMMA_SSA
  INTEGER :: IRH
  REAL*8 :: POLINT_SIMPLE
  REAL*8, DIMENSION(NRHV)::RRHWS,RRHSS, RHV, WDRWSA,WDRSSA
  REAL*8, PARAMETER :: VWS = 0.806D0, VSS = 0.708D0
  RRHWS = (/0.026D0,0.028D0,0.031D0,0.035D0,0.04D0,0.048D0,0.053D0/)
  RRHWS = EXP(LOG(RRHWS)+3.0D0*VWS*VWS)
  RRHSS = (/2.82D0,3.17D0,3.49D0,4.18D0,5.11D0,6.84D0,8.59D0/)
  RRHSS = EXP(LOG(RRHSS)+3.0D0*VSS*VSS)
  RHV = (/0.5D0,0.70D0,0.80D0,0.90D0,0.95D0,0.98D0,0.99D0/)
  WDRWSA = RRHWS/0.14744D0
  WDRSSA = RRHSS/7.8727D0

  DO IRH = 1,NRHV
     GAMMA_WSA(IRH) = 3.0*LOG(WDRWSA(IRH))/LOG(1/(1-RHV(IRH)))
     GAMMA_SSA(IRH) = 3.0*LOG(WDRSSA(IRH))/LOG(1/(1-RHV(IRH)))
       END DO

  IF(RHI >= 0.9) THEN
     GAMMA_WS = POLINT_SIMPLE(5, RHV(3:), GAMMA_WSA(3:),RHI,3)
  ELSEIF(RHI<0.9) THEN
     GAMMA_WS = POLINT_SIMPLE(3, RHV(:3), GAMMA_WSA(:3),RHI,2)
  ENDIF

  
  GAMMA_SS = POLINT_SIMPLE(NRHV, RHV(:), GAMMA_SSA(:),RHI,3)
  RRH_WS = ((1/(1-RHI))**GAMMA_WS)**(1.0d0/3.0d0)*R0WS
  RRH_SS = ((1/(1-RHI))**GAMMA_SS)**(1.0d0/3.0d0)*R0SS

  RRH_DL = R0DL
  RRH_BC = R0BC
  RRH_S = R0S

END SUBROUTINE  HYGROSCOPIC_GROWTH_EMIX

END MODULE AEROSOL_MICROPHYSICAL_MODEL
