! ===============================================================
!  RTSOS – Radiative Transfer model based on Successive Orders of Scattering
!  Copyright (C) 2025  Pengwang Zhai
!
!  Licensed under the Creative Commons Attribution–NonCommercial 4.0
!  International License (CC BY-NC 4.0).
!  You may use, modify, and share this code for research and
!  educational purposes with proper attribution.
!  Commercial use requires written permission from the author.
!
!  Full license: https://creativecommons.org/licenses/by-nc/4.0/
!  Contact: Pengwang Zhai  |  [pwzhai@gmail.com]
! ===============================================================

MODULE UNIVERSAL_CONSTANT
DOUBLE PRECISION,PARAMETER :: NAVOGADRO=6.02214D23, GAS_CONSTANT=8.31
END MODULE UNIVERSAL_CONSTANT

MODULE H2O_ABS_DATA
USE UNIVERSAL_CONSTANT
USE ATMOS_CONFIGURATION_DIRECTORY
IMPLICIT NONE

INTEGER,PARAMETER :: NPGRID_H2O_LUT=17,NWV_H2O_ABS_LUT=400000,NTEM_PERT_LUT=9, &
                     NH2OVMR_PERT=3

DOUBLE PRECISION,DIMENSION(NWV_H2O_ABS_LUT)::WV_H2O_ABS_LUT
DOUBLE PRECISION,DIMENSION(NPGRID_H2O_LUT):: PGRID_H2O_LUT,TEMREF_H2O_LUT,H2OVMR_REF_LUT
DOUBLE PRECISION,DIMENSION(NTEM_PERT_LUT)::TEM_PERT_LUT
DOUBLE PRECISION,DIMENSION(NH2OVMR_PERT)::H2OVMR_PERT
REAL,DIMENSION(NPGRID_H2O_LUT,NWV_H2O_ABS_LUT,NH2OVMR_PERT,NTEM_PERT_LUT):: &
                H2O_ABS_COEFF_LUT

DOUBLE PRECISION,DIMENSION(NPGRID_H2O_LUT,NTEM_PERT_LUT)::TEMGRID_H2O_LUT
DOUBLE PRECISION,DIMENSION(NPGRID_H2O_LUT,NH2OVMR_PERT):: H2OVMR_GRID_LUT
DOUBLE PRECISION,DIMENSION(2),PARAMETER :: WAVELENGTH_LUT_RANGE_H2O=(/396.0D0,2300.0D0/)

CONTAINS

SUBROUTINE H2O_ABS_READIN
USE HDF5
USE ISO_C_BINDING
IMPLICIT NONE

!INTEGER, PARAMETER :: real_kind_15 = SELECTED_REAL_KIND(Fortran_REAL_8)
INTEGER(HID_T)  :: file, space, dset ! Handles
INTEGER :: hdferr
TYPE(C_PTR) :: f_ptr
DOUBLE PRECISION,DIMENSION(:),TARGET,ALLOCATABLE :: HDF5RARRD1
REAL,DIMENSION(:,:,:,:),TARGET,ALLOCATABLE :: HDF5RARRD4

INTEGER :: IPRESSURE,ITEMP

CHARACTER(LEN=180) :: H2O_ABS_FILEDIR,H2O_ABS_FILENAME

call atmos_dir_readin

H2O_ABS_FILEDIR=trim(atmos_dir)//'/H2O/HITRAN2020/'
H2O_ABS_FILENAME='PACE_H2O_Abs_396to2300_Single_LUT2020.h5'
H2O_ABS_FILENAME=trim(H2O_ABS_FILEDIR)//trim(H2O_ABS_FILENAME)

CALL h5open_f(hdferr)
CALL h5fopen_f(H2O_ABS_FILENAME, H5F_ACC_RDONLY_F, file, hdferr)

ALLOCATE(HDF5RARRD1(NWV_H2O_ABS_LUT))
CALL h5dopen_f (file, '/wavelength_nm_grid', dset, hdferr)
CALL h5dget_space_f(dset,space, hdferr)
f_ptr = C_LOC(HDF5RARRD1(1))
CALL h5dread_f( dset, H5T_NATIVE_DOUBLE,f_ptr, hdferr)
CALL h5dclose_f(dset , hdferr)
CALL h5sclose_f(space, hdferr)
WV_H2O_ABS_LUT=HDF5RARRD1
DEALLOCATE(HDF5RARRD1)

ALLOCATE(HDF5RARRD1(NH2OVMR_PERT))
CALL h5dopen_f (file, '/nls_pert', dset, hdferr)
CALL h5dget_space_f(dset,space, hdferr)
f_ptr = C_LOC(HDF5RARRD1(1))
CALL h5dread_f( dset, H5T_NATIVE_DOUBLE,f_ptr, hdferr)
CALL h5dclose_f(dset , hdferr)
CALL h5sclose_f(space, hdferr)
H2OVMR_PERT=HDF5RARRD1
DEALLOCATE(HDF5RARRD1)

ALLOCATE(HDF5RARRD1(NPGRID_H2O_LUT))
CALL h5dopen_f (file, '/p_grid', dset, hdferr)
CALL h5dget_space_f(dset,space, hdferr)
f_ptr = C_LOC(HDF5RARRD1(1))
CALL h5dread_f( dset, H5T_NATIVE_DOUBLE,f_ptr, hdferr)
CALL h5dclose_f(dset , hdferr)
CALL h5sclose_f(space, hdferr)
PGRID_H2O_LUT=HDF5RARRD1
DEALLOCATE(HDF5RARRD1)

ALLOCATE(HDF5RARRD1(NPGRID_H2O_LUT))
CALL h5dopen_f (file, '/vmrs_ref', dset, hdferr)
CALL h5dget_space_f(dset,space, hdferr)
f_ptr = C_LOC(HDF5RARRD1(1))
CALL h5dread_f( dset, H5T_NATIVE_DOUBLE,f_ptr, hdferr)
CALL h5dclose_f(dset , hdferr)
CALL h5sclose_f(space, hdferr)
H2OVMR_REF_LUT=HDF5RARRD1
DEALLOCATE(HDF5RARRD1)

ALLOCATE(HDF5RARRD1(NPGRID_H2O_LUT))
CALL h5dopen_f (file, '/t_ref', dset, hdferr)
CALL h5dget_space_f(dset,space, hdferr)
f_ptr = C_LOC(HDF5RARRD1(1))
CALL h5dread_f( dset, H5T_NATIVE_DOUBLE,f_ptr, hdferr)
CALL h5dclose_f(dset , hdferr)
CALL h5sclose_f(space, hdferr)
TEMREF_H2O_LUT=HDF5RARRD1
DEALLOCATE(HDF5RARRD1)

ALLOCATE(HDF5RARRD1(NTEM_PERT_LUT))
CALL h5dopen_f (file, '/t_pert', dset, hdferr)
CALL h5dget_space_f(dset,space, hdferr)
f_ptr = C_LOC(HDF5RARRD1(1))
CALL h5dread_f( dset, H5T_NATIVE_DOUBLE,f_ptr, hdferr)
CALL h5dclose_f(dset , hdferr)
CALL h5sclose_f(space, hdferr)
TEM_PERT_LUT=HDF5RARRD1
DEALLOCATE(HDF5RARRD1)

ALLOCATE(HDF5RARRD4(NPGRID_H2O_LUT,NWV_H2O_ABS_LUT,NH2OVMR_PERT,NTEM_PERT_LUT))
CALL h5dopen_f (file, '/xsec', dset, hdferr)
CALL h5dget_space_f(dset,space, hdferr)
f_ptr = C_LOC(HDF5RARRD4(1,1,1,1))
CALL h5dread_f( dset, H5T_NATIVE_REAL,f_ptr, hdferr)
CALL h5dclose_f(dset , hdferr)
CALL h5sclose_f(space, hdferr)
H2O_ABS_COEFF_LUT=HDF5RARRD4
DEALLOCATE(HDF5RARRD4)

CALL h5fclose_f(file , hdferr)
CALL h5close_f(hdferr)

DO IPRESSURE=1,NPGRID_H2O_LUT
DO ITEMP=1,NTEM_PERT_LUT
  TEMGRID_H2O_LUT(IPRESSURE,ITEMP)=TEMREF_H2O_LUT(IPRESSURE)+TEM_PERT_LUT(ITEMP)
ENDDO

DO ITEMP=1,NH2OVMR_PERT
  H2OVMR_GRID_LUT(IPRESSURE,ITEMP)=H2OVMR_REF_LUT(IPRESSURE)*H2OVMR_PERT(ITEMP)
ENDDO
ENDDO

ENDSUBROUTINE H2O_ABS_READIN

SUBROUTINE H2O_ABS_SEARCH(NPRESSURE,NWAVELENGTH,WAVELENGTH,PRESSURE,TEMPERATURE, &
                          NUMDEN_TOTAL_FIELD,H2OVMR_FIELD,GAS_ABS_COEFF)
IMPLICIT NONE
INTEGER,INTENT(IN) :: NPRESSURE,NWAVELENGTH
DOUBLE PRECISION,INTENT(IN),DIMENSION(NPRESSURE)::PRESSURE,TEMPERATURE, &
                                        NUMDEN_TOTAL_FIELD,H2OVMR_FIELD
DOUBLE PRECISION,INTENT(INOUT),DIMENSION(NWAVELENGTH)::WAVELENGTH ! IN NANOMETER

DOUBLE PRECISION,INTENT(INOUT),DIMENSION(NWAVELENGTH,NPRESSURE)::GAS_ABS_COEFF

INTEGER :: IPRESSURE,IWV,MPL

INTEGER :: KLOPRESSURE,KLOWAVELENGTH,KLOVMR1,KLOVMR2,KLOTEMP1,KLOTEMP2,IULO

DOUBLE PRECISION :: NUMDEN !,CONV_FAC

DOUBLE PRECISION, ALLOCATABLE,DIMENSION(:)::XKT,XKP,XKVMR

DOUBLE PRECISION ::ABSCOEFF1,ABSCOEFF2,ABSCOEFF3,ABSCOEFF4,ABSCOEFF5,ABSCOEFF6,RTMP

DOUBLE PRECISION, DIMENSION(2)::XK,VK
DOUBLE PRECISION,DIMENSION(1) :: XI,YI
INTEGER,EXTERNAL:: bisearch

MPL=2

!CONV_FAC=NAVOGADRO/GAS_CONSTANT

ALLOCATE(XKT(NTEM_PERT_LUT),XKP(NPGRID_H2O_LUT),XKVMR(NH2OVMR_PERT))

DO IPRESSURE=1,NPRESSURE

!  NUMDEN=H2OVMR_FIELD(IPRESSURE)*CONV_FAC*PRESSURE(IPRESSURE)/TEMPERATURE(IPRESSURE)
  NUMDEN=NUMDEN_TOTAL_FIELD(IPRESSURE)*H2OVMR_FIELD(IPRESSURE)

!  write(*,*)'PRESSURE,H2O NUMDEN=',PRESSURE(IPRESSURE),NUMDEN
  IULO=bisearch(NPGRID_H2O_LUT,PGRID_H2O_LUT,PRESSURE(IPRESSURE))
  KLOPRESSURE=min(max(IULO-(MPL-1)/2,1),NPGRID_H2O_LUT+1-MPL)

  XKVMR=H2OVMR_GRID_LUT(KLOPRESSURE,:)
  IULO=bisearch(NH2OVMR_PERT,XKVMR,H2OVMR_FIELD(IPRESSURE))
  KLOVMR1=min(max(IULO-(MPL-1)/2,1),NH2OVMR_PERT+1-MPL)

  XKVMR=H2OVMR_GRID_LUT(KLOPRESSURE+1,:)
  IULO=bisearch(NH2OVMR_PERT,XKVMR,H2OVMR_FIELD(IPRESSURE))
  KLOVMR2=min(max(IULO-(MPL-1)/2,1),NH2OVMR_PERT+1-MPL)

  XKT=TEMGRID_H2O_LUT(KLOPRESSURE,:)
  IULO=bisearch(NTEM_PERT_LUT,XKT,TEMPERATURE(IPRESSURE))
  KLOTEMP1=min(max(IULO-(MPL-1)/2,1),NTEM_PERT_LUT+1-MPL)

  XKT=TEMGRID_H2O_LUT(KLOPRESSURE+1,:)
  IULO=bisearch(NTEM_PERT_LUT,XKT,TEMPERATURE(IPRESSURE))
  KLOTEMP2=min(max(IULO-(MPL-1)/2,1),NTEM_PERT_LUT+1-MPL)


  DO IWV=1,NWAVELENGTH
        IF(WAVELENGTH(IWV)<WAVELENGTH_LUT_RANGE_H2O(1) .OR.  &
           WAVELENGTH(IWV)>WAVELENGTH_LUT_RANGE_H2O(2)) THEN
            CYCLE
        ENDIF
		IULO=bisearch(NWV_H2O_ABS_LUT,WV_H2O_ABS_LUT,WAVELENGTH(IWV))
        KLOWAVELENGTH=min(max(IULO-(MPL-1)/2,1),NWV_H2O_ABS_LUT+1-MPL)

        XK(1)=WV_H2O_ABS_LUT(KLOWAVELENGTH)
        XK(2)=WV_H2O_ABS_LUT(KLOWAVELENGTH+1)

        VK(1)=H2O_ABS_COEFF_LUT(KLOPRESSURE,KLOWAVELENGTH,  KLOVMR1,KLOTEMP1  )
        VK(2)=H2O_ABS_COEFF_LUT(KLOPRESSURE,KLOWAVELENGTH+1,KLOVMR1,KLOTEMP1  )
		XI(1)=WAVELENGTH(IWV)
        CALL UVIP3P(1,2,XK,VK,1,XI,YI)
        ABSCOEFF1=YI(1)
        VK(1)=H2O_ABS_COEFF_LUT(KLOPRESSURE,KLOWAVELENGTH,  KLOVMR1,KLOTEMP1+1)
        VK(2)=H2O_ABS_COEFF_LUT(KLOPRESSURE,KLOWAVELENGTH+1,KLOVMR1,KLOTEMP1+1)

!		XI(1)=WAVELENGTH(IWV)
		CALL UVIP3P(1,2,XK,VK,1,XI,YI)
		ABSCOEFF2=YI(1)

        XK(1)=TEMGRID_H2O_LUT(KLOPRESSURE,KLOTEMP1)
        XK(2)=TEMGRID_H2O_LUT(KLOPRESSURE,KLOTEMP1+1)
        VK(1)=ABSCOEFF1
        VK(2)=ABSCOEFF2
		XI(1)=TEMPERATURE(IPRESSURE)
		CALL UVIP3P(1,2,XK,VK,1,XI,YI)
		ABSCOEFF3=YI(1)

        XK(1)=WV_H2O_ABS_LUT(KLOWAVELENGTH)
        XK(2)=WV_H2O_ABS_LUT(KLOWAVELENGTH+1)

        VK(1)=H2O_ABS_COEFF_LUT(KLOPRESSURE,KLOWAVELENGTH,  KLOVMR1+1,KLOTEMP1)
        VK(2)=H2O_ABS_COEFF_LUT(KLOPRESSURE,KLOWAVELENGTH+1,KLOVMR1+1,KLOTEMP1)
		XI(1)=WAVELENGTH(IWV)
		CALL UVIP3P(1,2,XK,VK,1,XI,YI)
		ABSCOEFF1=YI(1)

        VK(1)=H2O_ABS_COEFF_LUT(KLOPRESSURE,KLOWAVELENGTH,  KLOVMR1+1,KLOTEMP1+1)
        VK(2)=H2O_ABS_COEFF_LUT(KLOPRESSURE,KLOWAVELENGTH+1,KLOVMR1+1,KLOTEMP1+1)
!		XI(1)=WAVELENGTH(IWV)
		CALL UVIP3P(1,2,XK,VK,1,XI,YI)
		ABSCOEFF2=YI(1)

        XK(1)=TEMGRID_H2O_LUT(KLOPRESSURE,KLOTEMP1)
        XK(2)=TEMGRID_H2O_LUT(KLOPRESSURE,KLOTEMP1+1)
        VK(1)=ABSCOEFF1
        VK(2)=ABSCOEFF2
		XI(1)=TEMPERATURE(IPRESSURE)
		CALL UVIP3P(1,2,XK,VK,1,XI,YI)
		ABSCOEFF4=YI(1)

        XK(1)=H2OVMR_GRID_LUT(KLOPRESSURE,KLOVMR1)
        XK(2)=H2OVMR_GRID_LUT(KLOPRESSURE,KLOVMR1+1)
        VK(1)=ABSCOEFF3
        VK(2)=ABSCOEFF4
		XI(1)=H2OVMR_FIELD(IPRESSURE)
		CALL UVIP3P(1,2,XK,VK,1,XI,YI)
		ABSCOEFF5=YI(1)

        XK(1)=WV_H2O_ABS_LUT(KLOWAVELENGTH)
        XK(2)=WV_H2O_ABS_LUT(KLOWAVELENGTH+1)

        VK(1)=H2O_ABS_COEFF_LUT(KLOPRESSURE+1,KLOWAVELENGTH,  KLOVMR2,KLOTEMP2)
        VK(2)=H2O_ABS_COEFF_LUT(KLOPRESSURE+1,KLOWAVELENGTH+1,KLOVMR2,KLOTEMP2)
		XI(1)=WAVELENGTH(IWV)
		CALL UVIP3P(1,2,XK,VK,1,XI,YI)
		ABSCOEFF1=YI(1)

        VK(1)=H2O_ABS_COEFF_LUT(KLOPRESSURE+1,KLOWAVELENGTH,  KLOVMR2,KLOTEMP2+1)
        VK(2)=H2O_ABS_COEFF_LUT(KLOPRESSURE+1,KLOWAVELENGTH+1,KLOVMR2,KLOTEMP2+1)
!		XI(1)=WAVELENGTH(IWV)
		CALL UVIP3P(1,2,XK,VK,1,XI,YI)
		ABSCOEFF2=YI(1)

        XK(1)=TEMGRID_H2O_LUT(KLOPRESSURE+1,KLOTEMP2)
        XK(2)=TEMGRID_H2O_LUT(KLOPRESSURE+1,KLOTEMP2+1)
        VK(1)=ABSCOEFF1
        VK(2)=ABSCOEFF2
		XI(1)=TEMPERATURE(IPRESSURE)
		CALL UVIP3P(1,2,XK,VK,1,XI,YI)
		ABSCOEFF3=YI(1)

        XK(1)=WV_H2O_ABS_LUT(KLOWAVELENGTH)
        XK(2)=WV_H2O_ABS_LUT(KLOWAVELENGTH+1)

        VK(1)=H2O_ABS_COEFF_LUT(KLOPRESSURE+1,KLOWAVELENGTH,  KLOVMR2+1,KLOTEMP2)
        VK(2)=H2O_ABS_COEFF_LUT(KLOPRESSURE+1,KLOWAVELENGTH+1,KLOVMR2+1,KLOTEMP2)
		XI(1)=WAVELENGTH(IWV)
		CALL UVIP3P(1,2,XK,VK,1,XI,YI)
		ABSCOEFF1=YI(1)

        VK(1)=H2O_ABS_COEFF_LUT(KLOPRESSURE+1,KLOWAVELENGTH,  KLOVMR2+1,KLOTEMP2+1)
        VK(2)=H2O_ABS_COEFF_LUT(KLOPRESSURE+1,KLOWAVELENGTH+1,KLOVMR2+1,KLOTEMP2+1)
!		XI(1)=WAVELENGTH(IWV)
		CALL UVIP3P(1,2,XK,VK,1,XI,YI)
		ABSCOEFF2=YI(1)

        XK(1)=TEMGRID_H2O_LUT(KLOPRESSURE+1,KLOTEMP2)
        XK(2)=TEMGRID_H2O_LUT(KLOPRESSURE+1,KLOTEMP2+1)
        VK(1)=ABSCOEFF1
        VK(2)=ABSCOEFF2
		XI(1)=TEMPERATURE(IPRESSURE)
		CALL UVIP3P(1,2,XK,VK,1,XI,YI)
		ABSCOEFF4=YI(1)

        XK(1)=H2OVMR_GRID_LUT(KLOPRESSURE+1,KLOVMR2)
        XK(2)=H2OVMR_GRID_LUT(KLOPRESSURE+1,KLOVMR2+1)
        VK(1)=ABSCOEFF3
        VK(2)=ABSCOEFF4
		XI(1)=H2OVMR_FIELD(IPRESSURE)
		CALL UVIP3P(1,2,XK,VK,1,XI,YI)
		ABSCOEFF6=YI(1)

        XK(1)=PGRID_H2O_LUT(KLOPRESSURE)
        XK(2)=PGRID_H2O_LUT(KLOPRESSURE+1)
        VK(1)=ABSCOEFF5
        VK(2)=ABSCOEFF6
		XI(1)=PRESSURE(IPRESSURE)
		CALL UVIP3P(1,2,XK,VK,1,XI,YI)
		ABSCOEFF1=YI(1)

        GAS_ABS_COEFF(IWV,IPRESSURE)=GAS_ABS_COEFF(IWV,IPRESSURE)+ABSCOEFF1*NUMDEN
  ENDDO

ENDDO

DEALLOCATE(XKT,XKP,XKVMR)

ENDSUBROUTINE H2O_ABS_SEARCH

END MODULE H2O_ABS_DATA


MODULE CO2_ABS_DATA
USE UNIVERSAL_CONSTANT
USE ATMOS_CONFIGURATION_DIRECTORY
IMPLICIT NONE

INTEGER,PARAMETER :: NPGRID_CO2_LUT=35,NWV_CO2_ABS_LUT=303800,NTEM_PERT_LUT=9,&
                     NCO2VMR_PERT=1

DOUBLE PRECISION,DIMENSION(NWV_CO2_ABS_LUT)::WV_CO2_ABS_LUT
DOUBLE PRECISION,DIMENSION(NPGRID_CO2_LUT):: PGRID_CO2_LUT,TEMREF_CO2_LUT,CO2VMR_REF_LUT
DOUBLE PRECISION,DIMENSION(NTEM_PERT_LUT)::TEM_PERT_LUT
REAL,DIMENSION(NPGRID_CO2_LUT,NWV_CO2_ABS_LUT,1,NTEM_PERT_LUT):: &
                CO2_ABS_COEFF_LUT

DOUBLE PRECISION,DIMENSION(NPGRID_CO2_LUT,NTEM_PERT_LUT)::TEMGRID_CO2_LUT
DOUBLE PRECISION,DIMENSION(2),PARAMETER :: WAVELENGTH_LUT_RANGE_CO2=(/781.0D0,2300.0D0/)
CONTAINS

SUBROUTINE CO2_ABS_READIN
USE HDF5
USE ISO_C_BINDING
IMPLICIT NONE

!INTEGER, PARAMETER :: real_kind_15 = SELECTED_REAL_KIND(Fortran_REAL_8)
INTEGER(HID_T)  :: file, space, dset ! Handles
INTEGER :: hdferr
TYPE(C_PTR) :: f_ptr
DOUBLE PRECISION,DIMENSION(:),TARGET,ALLOCATABLE :: HDF5RARRD1
REAL,DIMENSION(:,:,:,:),TARGET,ALLOCATABLE :: HDF5RARRD4

INTEGER :: IPRESSURE,ITEMP

CHARACTER(LEN=180) :: CO2_ABS_FILEDIR,CO2_ABS_FILENAME

call atmos_dir_readin

CO2_ABS_FILEDIR=trim(atmos_dir)//'/CO2/HITRAN2020/'
CO2_ABS_FILENAME='PACE_CO2_Abs_781to2300_Single_LUT2020.h5'
CO2_ABS_FILENAME=trim(CO2_ABS_FILEDIR)//trim(CO2_ABS_FILENAME)

CALL h5open_f(hdferr)
CALL h5fopen_f(CO2_ABS_FILENAME, H5F_ACC_RDONLY_F, file, hdferr)

ALLOCATE(HDF5RARRD1(NWV_CO2_ABS_LUT))
CALL h5dopen_f (file, '/wavelength_nm_grid', dset, hdferr)
CALL h5dget_space_f(dset,space, hdferr)
f_ptr = C_LOC(HDF5RARRD1(1))
CALL h5dread_f( dset, H5T_NATIVE_DOUBLE,f_ptr, hdferr)
CALL h5dclose_f(dset , hdferr)
CALL h5sclose_f(space, hdferr)
WV_CO2_ABS_LUT=HDF5RARRD1
DEALLOCATE(HDF5RARRD1)

ALLOCATE(HDF5RARRD1(NPGRID_CO2_LUT))
CALL h5dopen_f (file, '/p_grid', dset, hdferr)
CALL h5dget_space_f(dset,space, hdferr)
f_ptr = C_LOC(HDF5RARRD1(1))
CALL h5dread_f( dset, H5T_NATIVE_DOUBLE,f_ptr, hdferr)
CALL h5dclose_f(dset , hdferr)
CALL h5sclose_f(space, hdferr)
PGRID_CO2_LUT=HDF5RARRD1
DEALLOCATE(HDF5RARRD1)

ALLOCATE(HDF5RARRD1(NPGRID_CO2_LUT))
CALL h5dopen_f (file, '/vmrs_ref', dset, hdferr)
CALL h5dget_space_f(dset,space, hdferr)
f_ptr = C_LOC(HDF5RARRD1(1))
CALL h5dread_f( dset, H5T_NATIVE_DOUBLE,f_ptr, hdferr)
CALL h5dclose_f(dset , hdferr)
CALL h5sclose_f(space, hdferr)
CO2VMR_REF_LUT=HDF5RARRD1
DEALLOCATE(HDF5RARRD1)

ALLOCATE(HDF5RARRD1(NPGRID_CO2_LUT))
CALL h5dopen_f (file, '/t_ref', dset, hdferr)
CALL h5dget_space_f(dset,space, hdferr)
f_ptr = C_LOC(HDF5RARRD1(1))
CALL h5dread_f( dset, H5T_NATIVE_DOUBLE,f_ptr, hdferr)
CALL h5dclose_f(dset , hdferr)
CALL h5sclose_f(space, hdferr)
TEMREF_CO2_LUT=HDF5RARRD1
DEALLOCATE(HDF5RARRD1)

ALLOCATE(HDF5RARRD1(NTEM_PERT_LUT))
CALL h5dopen_f (file, '/t_pert', dset, hdferr)
CALL h5dget_space_f(dset,space, hdferr)
f_ptr = C_LOC(HDF5RARRD1(1))
CALL h5dread_f( dset, H5T_NATIVE_DOUBLE,f_ptr, hdferr)
CALL h5dclose_f(dset , hdferr)
CALL h5sclose_f(space, hdferr)
TEM_PERT_LUT=HDF5RARRD1
DEALLOCATE(HDF5RARRD1)

ALLOCATE(HDF5RARRD4(NPGRID_CO2_LUT,NWV_CO2_ABS_LUT,NCO2VMR_PERT,NTEM_PERT_LUT))
CALL h5dopen_f (file, '/xsec', dset, hdferr)
CALL h5dget_space_f(dset,space, hdferr)
f_ptr = C_LOC(HDF5RARRD4(1,1,1,1))
CALL h5dread_f( dset, H5T_NATIVE_REAL,f_ptr, hdferr)
CALL h5dclose_f(dset , hdferr)
CALL h5sclose_f(space, hdferr)
CO2_ABS_COEFF_LUT=HDF5RARRD4
DEALLOCATE(HDF5RARRD4)

CALL h5fclose_f(file , hdferr)
CALL h5close_f(hdferr)

DO IPRESSURE=1,NPGRID_CO2_LUT
DO ITEMP=1,NTEM_PERT_LUT
  TEMGRID_CO2_LUT(IPRESSURE,ITEMP)=TEMREF_CO2_LUT(IPRESSURE)+TEM_PERT_LUT(ITEMP)
ENDDO
ENDDO

ENDSUBROUTINE CO2_ABS_READIN

SUBROUTINE CO2_ABS_SEARCH(NPRESSURE,NWAVELENGTH,WAVELENGTH,PRESSURE,TEMPERATURE, &
                          NUMDEN_TOTAL_FIELD,CO2VMR_FIELD,GAS_ABS_COEFF)
IMPLICIT NONE
INTEGER,INTENT(IN) :: NPRESSURE,NWAVELENGTH
DOUBLE PRECISION,INTENT(IN),DIMENSION(NPRESSURE)::PRESSURE,TEMPERATURE,NUMDEN_TOTAL_FIELD,CO2VMR_FIELD
DOUBLE PRECISION,INTENT(INOUT),DIMENSION(NWAVELENGTH)::WAVELENGTH ! IN NANOMETER

DOUBLE PRECISION,INTENT(INOUT),DIMENSION(NWAVELENGTH,NPRESSURE)::GAS_ABS_COEFF

INTEGER :: IPRESSURE,IWV,MPL

INTEGER :: KLOPRESSURE,KLOWAVELENGTH,KLOTEMP1,KLOTEMP2,IULO

DOUBLE PRECISION :: NUMDEN ! ,CONV_FAC

DOUBLE PRECISION, ALLOCATABLE,DIMENSION(:)::XKT,XKP

DOUBLE PRECISION ::ABSCOEFF1,ABSCOEFF2,ABSCOEFF3,ABSCOEFF4,ABSCOEFF5,ABSCOEFF6,RTMP
DOUBLE PRECISION, DIMENSION(2)::XK,VK
INTEGER, EXTERNAL :: bisearch
DOUBLE PRECISION,DIMENSION(1) :: XI,YI

MPL=2

!CONV_FAC=NAVOGADRO/GAS_CONSTANT

ALLOCATE(XKT(NTEM_PERT_LUT),XKP(NPGRID_CO2_LUT))

DO IPRESSURE=1,NPRESSURE

!  NUMDEN=CO2VMR_FIELD(IPRESSURE)*CONV_FAC*PRESSURE(IPRESSURE)/TEMPERATURE(IPRESSURE)
  NUMDEN=NUMDEN_TOTAL_FIELD(IPRESSURE)*CO2VMR_FIELD(IPRESSURE)
!  write(*,*)'PRESSURE,CO2 NUMDEN=',PRESSURE(IPRESSURE),NUMDEN
  IULO=bisearch(NPGRID_CO2_LUT,PGRID_CO2_LUT,PRESSURE(IPRESSURE))
  KLOPRESSURE=min(max(IULO-(MPL-1)/2,1),NPGRID_CO2_LUT+1-MPL)

  XKT=TEMGRID_CO2_LUT(KLOPRESSURE,:)
  IULO=bisearch(NTEM_PERT_LUT,XKT,TEMPERATURE(IPRESSURE))
  KLOTEMP1=min(max(IULO-(MPL-1)/2,1),NTEM_PERT_LUT+1-MPL)

  XKT=TEMGRID_CO2_LUT(KLOPRESSURE+1,:)
  IULO=bisearch(NTEM_PERT_LUT,XKT,TEMPERATURE(IPRESSURE))
  KLOTEMP2=min(max(IULO-(MPL-1)/2,1),NTEM_PERT_LUT+1-MPL)


  DO IWV=1,NWAVELENGTH
        IF(WAVELENGTH(IWV)<WAVELENGTH_LUT_RANGE_CO2(1) .OR.  &
           WAVELENGTH(IWV)>WAVELENGTH_LUT_RANGE_CO2(2)) THEN
            CYCLE
        ENDIF

		IULO=bisearch(NWV_CO2_ABS_LUT,WV_CO2_ABS_LUT,WAVELENGTH(IWV))
        KLOWAVELENGTH=min(max(IULO-(MPL-1)/2,1),NWV_CO2_ABS_LUT+1-MPL)

        XK(1)=WV_CO2_ABS_LUT(KLOWAVELENGTH)
        XK(2)=WV_CO2_ABS_LUT(KLOWAVELENGTH+1)

        VK(1)=CO2_ABS_COEFF_LUT(KLOPRESSURE,KLOWAVELENGTH,  1,KLOTEMP1)
        VK(2)=CO2_ABS_COEFF_LUT(KLOPRESSURE,KLOWAVELENGTH+1,1,KLOTEMP1)
		XI(1)=WAVELENGTH(IWV)
		CALL UVIP3P(1,2,XK,VK,1,XI,YI)
		ABSCOEFF1=YI(1)

        VK(1)=CO2_ABS_COEFF_LUT(KLOPRESSURE,KLOWAVELENGTH,  1,KLOTEMP1+1)
        VK(2)=CO2_ABS_COEFF_LUT(KLOPRESSURE,KLOWAVELENGTH+1,1,KLOTEMP1+1)
!		XI(1)=WAVELENGTH(IWV)
		CALL UVIP3P(1,2,XK,VK,1,XI,YI)
		ABSCOEFF2=YI(1)

        XK(1)=TEMGRID_CO2_LUT(KLOPRESSURE,KLOTEMP1)
        XK(2)=TEMGRID_CO2_LUT(KLOPRESSURE,KLOTEMP1+1)
        VK(1)=ABSCOEFF1
        VK(2)=ABSCOEFF2
		XI(1)=TEMPERATURE(IPRESSURE)
		CALL UVIP3P(1,2,XK,VK,1,XI,YI)
		ABSCOEFF3=YI(1)

        XK(1)=WV_CO2_ABS_LUT(KLOWAVELENGTH)
        XK(2)=WV_CO2_ABS_LUT(KLOWAVELENGTH+1)

        VK(1)=CO2_ABS_COEFF_LUT(KLOPRESSURE+1,KLOWAVELENGTH,  1,KLOTEMP2)
        VK(2)=CO2_ABS_COEFF_LUT(KLOPRESSURE+1,KLOWAVELENGTH+1,1,KLOTEMP2)
		XI(1)=WAVELENGTH(IWV)
		CALL UVIP3P(1,2,XK,VK,1,XI,YI)
		ABSCOEFF1=YI(1)

        VK(1)=CO2_ABS_COEFF_LUT(KLOPRESSURE+1,KLOWAVELENGTH,  1,KLOTEMP2+1)
        VK(2)=CO2_ABS_COEFF_LUT(KLOPRESSURE+1,KLOWAVELENGTH+1,1,KLOTEMP2+1)
!		XI(1)=WAVELENGTH(IWV)
		CALL UVIP3P(1,2,XK,VK,1,XI,YI)
		ABSCOEFF2=YI(1)

        XK(1)=TEMGRID_CO2_LUT(KLOPRESSURE+1,KLOTEMP2)
        XK(2)=TEMGRID_CO2_LUT(KLOPRESSURE+1,KLOTEMP2+1)
        VK(1)=ABSCOEFF1
        VK(2)=ABSCOEFF2
		XI(1)=TEMPERATURE(IPRESSURE)
		CALL UVIP3P(1,2,XK,VK,1,XI,YI)
		ABSCOEFF4=YI(1)

        XK(1)=PGRID_CO2_LUT(KLOPRESSURE)
        XK(2)=PGRID_CO2_LUT(KLOPRESSURE+1)
        VK(1)=ABSCOEFF3
        VK(2)=ABSCOEFF4
		XI(1)=PRESSURE(IPRESSURE)
		CALL UVIP3P(1,2,XK,VK,1,XI,YI)
		ABSCOEFF1=YI(1)

        GAS_ABS_COEFF(IWV,IPRESSURE)=GAS_ABS_COEFF(IWV,IPRESSURE)+ABSCOEFF1*NUMDEN

  ENDDO

ENDDO

DEALLOCATE(XKT,XKP)

ENDSUBROUTINE CO2_ABS_SEARCH

END MODULE CO2_ABS_DATA

MODULE CH4_ABS_DATA
USE UNIVERSAL_CONSTANT
USE ATMOS_CONFIGURATION_DIRECTORY
IMPLICIT NONE

INTEGER,PARAMETER :: NPGRID_CH4_LUT=35,NWV_CH4_ABS_LUT=243200,NTEM_PERT_LUT=9,&
                     NCH4VMR_PERT=1

DOUBLE PRECISION,DIMENSION(NWV_CH4_ABS_LUT)::WV_CH4_ABS_LUT
DOUBLE PRECISION,DIMENSION(NPGRID_CH4_LUT):: PGRID_CH4_LUT,TEMREF_CH4_LUT,CH4VMR_REF_LUT
DOUBLE PRECISION,DIMENSION(NTEM_PERT_LUT)::TEM_PERT_LUT
REAL,DIMENSION(NPGRID_CH4_LUT,NWV_CH4_ABS_LUT,1,NTEM_PERT_LUT):: &
                CH4_ABS_COEFF_LUT

DOUBLE PRECISION,DIMENSION(NPGRID_CH4_LUT,NTEM_PERT_LUT)::TEMGRID_CH4_LUT
DOUBLE PRECISION,DIMENSION(2),PARAMETER :: WAVELENGTH_LUT_RANGE_CH4=(/1084.D0,2300.0D0/)
CONTAINS

SUBROUTINE CH4_ABS_READIN
USE HDF5
USE ISO_C_BINDING
IMPLICIT NONE

!INTEGER, PARAMETER :: real_kind_15 = SELECTED_REAL_KIND(Fortran_REAL_8)
INTEGER(HID_T)  :: file, space, dset ! Handles
INTEGER :: hdferr
TYPE(C_PTR) :: f_ptr
DOUBLE PRECISION,DIMENSION(:),TARGET,ALLOCATABLE :: HDF5RARRD1
REAL,DIMENSION(:,:,:,:),TARGET,ALLOCATABLE :: HDF5RARRD4

INTEGER :: IPRESSURE,ITEMP

CHARACTER(LEN=180) :: CH4_ABS_FILEDIR,CH4_ABS_FILENAME

call atmos_dir_readin

CH4_ABS_FILEDIR=trim(atmos_dir)//'/CH4/HITRAN2020/'
CH4_ABS_FILENAME='PACE_CH4_Abs_1084to2300_Single_LUT2020.h5'
CH4_ABS_FILENAME=trim(CH4_ABS_FILEDIR)//trim(CH4_ABS_FILENAME)

CALL h5open_f(hdferr)
CALL h5fopen_f(CH4_ABS_FILENAME, H5F_ACC_RDONLY_F, file, hdferr)

ALLOCATE(HDF5RARRD1(NWV_CH4_ABS_LUT))
CALL h5dopen_f (file, '/wavelength_nm_grid', dset, hdferr)
CALL h5dget_space_f(dset,space, hdferr)
f_ptr = C_LOC(HDF5RARRD1(1))
CALL h5dread_f( dset, H5T_NATIVE_DOUBLE,f_ptr, hdferr)
CALL h5dclose_f(dset , hdferr)
CALL h5sclose_f(space, hdferr)
WV_CH4_ABS_LUT=HDF5RARRD1
DEALLOCATE(HDF5RARRD1)

ALLOCATE(HDF5RARRD1(NPGRID_CH4_LUT))
CALL h5dopen_f (file, '/p_grid', dset, hdferr)
CALL h5dget_space_f(dset,space, hdferr)
f_ptr = C_LOC(HDF5RARRD1(1))
CALL h5dread_f( dset, H5T_NATIVE_DOUBLE,f_ptr, hdferr)
CALL h5dclose_f(dset , hdferr)
CALL h5sclose_f(space, hdferr)
PGRID_CH4_LUT=HDF5RARRD1
DEALLOCATE(HDF5RARRD1)

ALLOCATE(HDF5RARRD1(NPGRID_CH4_LUT))
CALL h5dopen_f (file, '/vmrs_ref', dset, hdferr)
CALL h5dget_space_f(dset,space, hdferr)
f_ptr = C_LOC(HDF5RARRD1(1))
CALL h5dread_f( dset, H5T_NATIVE_DOUBLE,f_ptr, hdferr)
CALL h5dclose_f(dset , hdferr)
CALL h5sclose_f(space, hdferr)
CH4VMR_REF_LUT=HDF5RARRD1
DEALLOCATE(HDF5RARRD1)

ALLOCATE(HDF5RARRD1(NPGRID_CH4_LUT))
CALL h5dopen_f (file, '/t_ref', dset, hdferr)
CALL h5dget_space_f(dset,space, hdferr)
f_ptr = C_LOC(HDF5RARRD1(1))
CALL h5dread_f( dset, H5T_NATIVE_DOUBLE,f_ptr, hdferr)
CALL h5dclose_f(dset , hdferr)
CALL h5sclose_f(space, hdferr)
TEMREF_CH4_LUT=HDF5RARRD1
DEALLOCATE(HDF5RARRD1)

ALLOCATE(HDF5RARRD1(NTEM_PERT_LUT))
CALL h5dopen_f (file, '/t_pert', dset, hdferr)
CALL h5dget_space_f(dset,space, hdferr)
f_ptr = C_LOC(HDF5RARRD1(1))
CALL h5dread_f( dset, H5T_NATIVE_DOUBLE,f_ptr, hdferr)
CALL h5dclose_f(dset , hdferr)
CALL h5sclose_f(space, hdferr)
TEM_PERT_LUT=HDF5RARRD1
DEALLOCATE(HDF5RARRD1)

ALLOCATE(HDF5RARRD4(NPGRID_CH4_LUT,NWV_CH4_ABS_LUT,NCH4VMR_PERT,NTEM_PERT_LUT))
CALL h5dopen_f (file, '/xsec', dset, hdferr)
CALL h5dget_space_f(dset,space, hdferr)
f_ptr = C_LOC(HDF5RARRD4(1,1,1,1))
CALL h5dread_f( dset, H5T_NATIVE_REAL,f_ptr, hdferr)
CALL h5dclose_f(dset , hdferr)
CALL h5sclose_f(space, hdferr)
CH4_ABS_COEFF_LUT=HDF5RARRD4
DEALLOCATE(HDF5RARRD4)

CALL h5fclose_f(file , hdferr)
CALL h5close_f(hdferr)

DO IPRESSURE=1,NPGRID_CH4_LUT
DO ITEMP=1,NTEM_PERT_LUT
  TEMGRID_CH4_LUT(IPRESSURE,ITEMP)=TEMREF_CH4_LUT(IPRESSURE)+TEM_PERT_LUT(ITEMP)
ENDDO
ENDDO

ENDSUBROUTINE CH4_ABS_READIN

SUBROUTINE CH4_ABS_SEARCH(NPRESSURE,NWAVELENGTH,WAVELENGTH,PRESSURE,TEMPERATURE, &
                          NUMDEN_TOTAL_FIELD,CH4VMR_FIELD,GAS_ABS_COEFF)
IMPLICIT NONE
INTEGER,INTENT(IN) :: NPRESSURE,NWAVELENGTH
DOUBLE PRECISION,INTENT(IN),DIMENSION(NPRESSURE)::PRESSURE,TEMPERATURE,NUMDEN_TOTAL_FIELD,CH4VMR_FIELD
DOUBLE PRECISION,INTENT(INOUT),DIMENSION(NWAVELENGTH)::WAVELENGTH ! IN NANOMETER

DOUBLE PRECISION,INTENT(INOUT),DIMENSION(NWAVELENGTH,NPRESSURE)::GAS_ABS_COEFF

INTEGER :: IPRESSURE,IWV,MPL

INTEGER :: KLOPRESSURE,KLOWAVELENGTH,KLOTEMP1,KLOTEMP2,IULO

DOUBLE PRECISION :: NUMDEN !,CONV_FAC

DOUBLE PRECISION, ALLOCATABLE,DIMENSION(:)::XKT,XKP

DOUBLE PRECISION ::ABSCOEFF1,ABSCOEFF2,ABSCOEFF3,ABSCOEFF4,ABSCOEFF5,ABSCOEFF6,RTMP
DOUBLE PRECISION,DIMENSION(1) :: XI,YI
DOUBLE PRECISION, DIMENSION(2)::XK,VK
INTEGER, EXTERNAL :: bisearch
MPL=2

!CONV_FAC=NAVOGADRO/GAS_CONSTANT

ALLOCATE(XKT(NTEM_PERT_LUT),XKP(NPGRID_CH4_LUT))

DO IPRESSURE=1,NPRESSURE

!  NUMDEN=CH4VMR_FIELD(IPRESSURE)*CONV_FAC*PRESSURE(IPRESSURE)/TEMPERATURE(IPRESSURE)
  NUMDEN=NUMDEN_TOTAL_FIELD(IPRESSURE)*CH4VMR_FIELD(IPRESSURE)
!  write(*,*)'PRESSURE,CH4 NUMDEN=',PRESSURE(IPRESSURE),NUMDEN
  IULO=bisearch(NPGRID_CH4_LUT,PGRID_CH4_LUT,PRESSURE(IPRESSURE))

  KLOPRESSURE=min(max(IULO-(MPL-1)/2,1),NPGRID_CH4_LUT+1-MPL)

  XKT=TEMGRID_CH4_LUT(KLOPRESSURE,:)
  IULO=bisearch(NTEM_PERT_LUT,XKT,TEMPERATURE(IPRESSURE))
  KLOTEMP1=min(max(IULO-(MPL-1)/2,1),NTEM_PERT_LUT+1-MPL)

  XKT=TEMGRID_CH4_LUT(KLOPRESSURE+1,:)
  IULO=bisearch(NTEM_PERT_LUT,XKT,TEMPERATURE(IPRESSURE))
  KLOTEMP2=min(max(IULO-(MPL-1)/2,1),NTEM_PERT_LUT+1-MPL)


  DO IWV=1,NWAVELENGTH
        IF(WAVELENGTH(IWV)<WAVELENGTH_LUT_RANGE_CH4(1) .OR.   &
           WAVELENGTH(IWV)>WAVELENGTH_LUT_RANGE_CH4(2)) THEN
            CYCLE
        ENDIF

		IULO=bisearch(NWV_CH4_ABS_LUT,WV_CH4_ABS_LUT,WAVELENGTH(IWV))
        KLOWAVELENGTH=min(max(IULO-(MPL-1)/2,1),NWV_CH4_ABS_LUT+1-MPL)

        XK(1)=WV_CH4_ABS_LUT(KLOWAVELENGTH)
        XK(2)=WV_CH4_ABS_LUT(KLOWAVELENGTH+1)

        VK(1)=CH4_ABS_COEFF_LUT(KLOPRESSURE,KLOWAVELENGTH,  1,KLOTEMP1)
        VK(2)=CH4_ABS_COEFF_LUT(KLOPRESSURE,KLOWAVELENGTH+1,1,KLOTEMP1)
		XI(1)=WAVELENGTH(IWV)
		CALL UVIP3P(1,2,XK,VK,1,XI,YI)
		ABSCOEFF1=YI(1)

        VK(1)=CH4_ABS_COEFF_LUT(KLOPRESSURE,KLOWAVELENGTH,  1,KLOTEMP1+1)
        VK(2)=CH4_ABS_COEFF_LUT(KLOPRESSURE,KLOWAVELENGTH+1,1,KLOTEMP1+1)
!		XI(1)=WAVELENGTH(IWV)
		CALL UVIP3P(1,2,XK,VK,1,XI,YI)
		ABSCOEFF2=YI(1)

        XK(1)=TEMGRID_CH4_LUT(KLOPRESSURE,KLOTEMP1)
        XK(2)=TEMGRID_CH4_LUT(KLOPRESSURE,KLOTEMP1+1)
        VK(1)=ABSCOEFF1
        VK(2)=ABSCOEFF2
		XI(1)=TEMPERATURE(IPRESSURE)
		CALL UVIP3P(1,2,XK,VK,1,XI,YI)
		ABSCOEFF3=YI(1)

        XK(1)=WV_CH4_ABS_LUT(KLOWAVELENGTH)
        XK(2)=WV_CH4_ABS_LUT(KLOWAVELENGTH+1)

        VK(1)=CH4_ABS_COEFF_LUT(KLOPRESSURE+1,KLOWAVELENGTH,  1,KLOTEMP2)
        VK(2)=CH4_ABS_COEFF_LUT(KLOPRESSURE+1,KLOWAVELENGTH+1,1,KLOTEMP2)
		XI(1)=WAVELENGTH(IWV)
		CALL UVIP3P(1,2,XK,VK,1,XI,YI)
		ABSCOEFF1=YI(1)

        VK(1)=CH4_ABS_COEFF_LUT(KLOPRESSURE+1,KLOWAVELENGTH,  1,KLOTEMP2+1)
        VK(2)=CH4_ABS_COEFF_LUT(KLOPRESSURE+1,KLOWAVELENGTH+1,1,KLOTEMP2+1)
		XI(1)=WAVELENGTH(IWV)
		CALL UVIP3P(1,2,XK,VK,1,XI,YI)
		ABSCOEFF2=YI(1)

        XK(1)=TEMGRID_CH4_LUT(KLOPRESSURE+1,KLOTEMP2)
        XK(2)=TEMGRID_CH4_LUT(KLOPRESSURE+1,KLOTEMP2+1)
        VK(1)=ABSCOEFF1
        VK(2)=ABSCOEFF2
		XI(1)=TEMPERATURE(IPRESSURE)
		CALL UVIP3P(1,2,XK,VK,1,XI,YI)
		ABSCOEFF4=YI(1)

        XK(1)=PGRID_CH4_LUT(KLOPRESSURE)
        XK(2)=PGRID_CH4_LUT(KLOPRESSURE+1)
        VK(1)=ABSCOEFF3
        VK(2)=ABSCOEFF4
		XI(1)=PRESSURE(IPRESSURE)
		CALL UVIP3P(1,2,XK,VK,1,XI,YI)
		ABSCOEFF1=YI(1)

        GAS_ABS_COEFF(IWV,IPRESSURE)=GAS_ABS_COEFF(IWV,IPRESSURE)+ABSCOEFF1*NUMDEN

  ENDDO

ENDDO

DEALLOCATE(XKT,XKP)

ENDSUBROUTINE CH4_ABS_SEARCH

END MODULE CH4_ABS_DATA


MODULE OXYGEN2_ABS_DATA
USE UNIVERSAL_CONSTANT
USE ATMOS_CONFIGURATION_DIRECTORY

IMPLICIT NONE

INTEGER,PARAMETER :: NPGRID_OXYGEN2_LUT=35,NWV_OXYGEN2_ABS_LUT=162000,NTEM_PERT_LUT=9,&
                     NOXYGEN2VMR_PERT=1

DOUBLE PRECISION,DIMENSION(NWV_OXYGEN2_ABS_LUT)::WV_OXYGEN2_ABS_LUT
DOUBLE PRECISION,DIMENSION(NPGRID_OXYGEN2_LUT):: PGRID_OXYGEN2_LUT,TEMREF_OXYGEN2_LUT,OXYGEN2VMR_REF_LUT
DOUBLE PRECISION,DIMENSION(NTEM_PERT_LUT)::TEM_PERT_LUT
REAL,DIMENSION(NPGRID_OXYGEN2_LUT,NWV_OXYGEN2_ABS_LUT,1,NTEM_PERT_LUT):: &
                OXYGEN2_ABS_COEFF_LUT

DOUBLE PRECISION,DIMENSION(NPGRID_OXYGEN2_LUT,NTEM_PERT_LUT)::TEMGRID_OXYGEN2_LUT

DOUBLE PRECISION,DIMENSION(2,7):: WAVELENGTH_SEG_ENDPOINTS
INTEGER,DIMENSION(7) :: WAVELENGTH_SEG_INDEX_S,NUMBER_OF_WAVELENGTH_SEG

CONTAINS

SUBROUTINE OXYGEN2_ABS_READIN
USE HDF5
USE ISO_C_BINDING
IMPLICIT NONE
!INTEGER, PARAMETER :: real_kind_15 = SELECTED_REAL_KIND(Fortran_REAL_8)
INTEGER(HID_T)  :: file, space, dset ! Handles
INTEGER :: hdferr
TYPE(C_PTR) :: f_ptr
DOUBLE PRECISION,DIMENSION(:),TARGET,ALLOCATABLE :: HDF5RARRD1
REAL,DIMENSION(:,:,:,:),TARGET,ALLOCATABLE :: HDF5RARRD4

!INTEGER,DIMENSION(2,7):: WAVELENGTH_SEG_ENDPOINTS

INTEGER :: IPRESSURE,ITEMP
INTEGER ISEG,IWV
CHARACTER(LEN=180) :: OXYGEN2_ABS_FILEDIR,OXYGEN2_ABS_FILENAME

CHARACTER*180 :: CFILETMPS,CFILETMPE

call atmos_dir_readin

WAVELENGTH_SEG_ENDPOINTS=reshape((/1551,1603,1237,1308,1053,1084, &
    859,872,758,780,686,700,627,637/),shape(WAVELENGTH_SEG_ENDPOINTS))
WAVELENGTH_SEG_INDEX_S=(/1,26001,61501,77001,97001,122001,142001/)
NUMBER_OF_WAVELENGTH_SEG=(/26000,35500,15500,20000,25000,20000,20000/)

OXYGEN2_ABS_FILEDIR=trim(atmos_dir)//'/O2/HITRAN2020/'

DO ISEG=1,7


    IF(WAVELENGTH_SEG_ENDPOINTS(1,ISEG)>999)THEN
      WRITE(CFILETMPS,'(I4)')INT(WAVELENGTH_SEG_ENDPOINTS(1,ISEG))
    ELSE
      WRITE(CFILETMPS,'(I3)')INT(WAVELENGTH_SEG_ENDPOINTS(1,ISEG))
    ENDIF

    IF(WAVELENGTH_SEG_ENDPOINTS(2,ISEG)>999)THEN
      WRITE(CFILETMPE,'(I4)')INT(WAVELENGTH_SEG_ENDPOINTS(2,ISEG))
    ELSE
      WRITE(CFILETMPE,'(I3)')INT(WAVELENGTH_SEG_ENDPOINTS(2,ISEG))
    ENDIF

    OXYGEN2_ABS_FILENAME='PACE_O2_Abs_'//TRIM(CFILETMPS)//'to'//TRIM(CFILETMPE)//'_Single_LUT2020.h5'
    !WRITE(*,*)OXYGEN2_ABS_FILENAME
    OXYGEN2_ABS_FILENAME=trim(OXYGEN2_ABS_FILEDIR)//trim(OXYGEN2_ABS_FILENAME)

    CALL h5open_f(hdferr)
    CALL h5fopen_f(OXYGEN2_ABS_FILENAME, H5F_ACC_RDONLY_F, file, hdferr)

    ALLOCATE(HDF5RARRD1(NUMBER_OF_WAVELENGTH_SEG(ISEG)))
    CALL h5dopen_f (file, '/wavelength_nm_grid', dset, hdferr)
    CALL h5dget_space_f(dset,space, hdferr)
    f_ptr = C_LOC(HDF5RARRD1(1))
    CALL h5dread_f( dset, H5T_NATIVE_DOUBLE,f_ptr, hdferr)
    CALL h5dclose_f(dset , hdferr)
    CALL h5sclose_f(space, hdferr)
    WV_OXYGEN2_ABS_LUT(WAVELENGTH_SEG_INDEX_S(ISEG) : WAVELENGTH_SEG_INDEX_S(ISEG)+ &
                       NUMBER_OF_WAVELENGTH_SEG(ISEG)-1)=HDF5RARRD1
    DEALLOCATE(HDF5RARRD1)

    ALLOCATE(HDF5RARRD1(NPGRID_OXYGEN2_LUT))
    CALL h5dopen_f (file, '/p_grid', dset, hdferr)
    CALL h5dget_space_f(dset,space, hdferr)
    f_ptr = C_LOC(HDF5RARRD1(1))
    CALL h5dread_f( dset, H5T_NATIVE_DOUBLE,f_ptr, hdferr)
    CALL h5dclose_f(dset , hdferr)
    CALL h5sclose_f(space, hdferr)
    PGRID_OXYGEN2_LUT=HDF5RARRD1
    DEALLOCATE(HDF5RARRD1)

    ALLOCATE(HDF5RARRD1(NPGRID_OXYGEN2_LUT))
    CALL h5dopen_f (file, '/vmrs_ref', dset, hdferr)
    CALL h5dget_space_f(dset,space, hdferr)
    f_ptr = C_LOC(HDF5RARRD1(1))
    CALL h5dread_f( dset, H5T_NATIVE_DOUBLE,f_ptr, hdferr)
    CALL h5dclose_f(dset , hdferr)
    CALL h5sclose_f(space, hdferr)
    OXYGEN2VMR_REF_LUT=HDF5RARRD1
    DEALLOCATE(HDF5RARRD1)

    ALLOCATE(HDF5RARRD1(NPGRID_OXYGEN2_LUT))
    CALL h5dopen_f (file, '/t_ref', dset, hdferr)
    CALL h5dget_space_f(dset,space, hdferr)
    f_ptr = C_LOC(HDF5RARRD1(1))
    CALL h5dread_f( dset, H5T_NATIVE_DOUBLE,f_ptr, hdferr)
    CALL h5dclose_f(dset , hdferr)
    CALL h5sclose_f(space, hdferr)
    TEMREF_OXYGEN2_LUT=HDF5RARRD1
    DEALLOCATE(HDF5RARRD1)

    ALLOCATE(HDF5RARRD1(NTEM_PERT_LUT))
    CALL h5dopen_f (file, '/t_pert', dset, hdferr)
    CALL h5dget_space_f(dset,space, hdferr)
    f_ptr = C_LOC(HDF5RARRD1(1))
    CALL h5dread_f( dset, H5T_NATIVE_DOUBLE,f_ptr, hdferr)
    CALL h5dclose_f(dset , hdferr)
    CALL h5sclose_f(space, hdferr)
    TEM_PERT_LUT=HDF5RARRD1
    DEALLOCATE(HDF5RARRD1)

    ALLOCATE(HDF5RARRD4(NPGRID_OXYGEN2_LUT,NUMBER_OF_WAVELENGTH_SEG(ISEG),NOXYGEN2VMR_PERT,NTEM_PERT_LUT))
    CALL h5dopen_f (file, '/xsec', dset, hdferr)
    CALL h5dget_space_f(dset,space, hdferr)
    f_ptr = C_LOC(HDF5RARRD4(1,1,1,1))
    CALL h5dread_f( dset, H5T_NATIVE_REAL,f_ptr, hdferr)
    CALL h5dclose_f(dset , hdferr)
    CALL h5sclose_f(space, hdferr)
    OXYGEN2_ABS_COEFF_LUT(1:NPGRID_OXYGEN2_LUT,WAVELENGTH_SEG_INDEX_S(ISEG) : &
        WAVELENGTH_SEG_INDEX_S(ISEG)+NUMBER_OF_WAVELENGTH_SEG(ISEG)-1,1,1:NTEM_PERT_LUT) = &
        HDF5RARRD4(1:NPGRID_OXYGEN2_LUT,1:NUMBER_OF_WAVELENGTH_SEG(ISEG),1,1:NTEM_PERT_LUT)
    DEALLOCATE(HDF5RARRD4)
    CALL h5fclose_f(file , hdferr)
    CALL h5close_f(hdferr)
ENDDO

DO IPRESSURE=1,NPGRID_OXYGEN2_LUT
DO ITEMP=1,NTEM_PERT_LUT
  TEMGRID_OXYGEN2_LUT(IPRESSURE,ITEMP)=TEMREF_OXYGEN2_LUT(IPRESSURE)+TEM_PERT_LUT(ITEMP)

!TESTING
DO ISEG=1,7
DO IWV=WAVELENGTH_SEG_INDEX_S(ISEG),WAVELENGTH_SEG_INDEX_S(ISEG)+NUMBER_OF_WAVELENGTH_SEG(ISEG)-1
 IF(OXYGEN2_ABS_COEFF_LUT(IPRESSURE,IWV,1,ITEMP)<0.0d0)THEN
   OXYGEN2_ABS_COEFF_LUT(IPRESSURE,IWV,1,ITEMP)=0.0d0
!   write(*,*)'O2_LUT err',ISEG,WV_OXYGEN2_ABS_LUT(iwv),TEMGRID_OXYGEN2_LUT(IPRESSURE,ITEMP),&
!        PGRID_OXYGEN2_LUT(IPRESSURE),OXYGEN2_ABS_COEFF_LUT(IPRESSURE,IWV,1,ITEMP)

 ENDIF
ENDDO
ENDDO
! END TESTING


ENDDO
ENDDO

ENDSUBROUTINE OXYGEN2_ABS_READIN

SUBROUTINE OXYGEN2_ABS_SEARCH(NPRESSURE,NWAVELENGTH,WAVELENGTH,PRESSURE,TEMPERATURE, &
                          NUMDEN_TOTAL_FIELD,OXYGEN2VMR_FIELD,GAS_ABS_COEFF)
IMPLICIT NONE
INTEGER,INTENT(IN) :: NPRESSURE,NWAVELENGTH
DOUBLE PRECISION,INTENT(IN),DIMENSION(NPRESSURE)::PRESSURE,TEMPERATURE,NUMDEN_TOTAL_FIELD,OXYGEN2VMR_FIELD
DOUBLE PRECISION,INTENT(INOUT),DIMENSION(NWAVELENGTH)::WAVELENGTH ! IN NANOMETER

DOUBLE PRECISION,INTENT(INOUT),DIMENSION(NWAVELENGTH,NPRESSURE)::GAS_ABS_COEFF

INTEGER :: IPRESSURE,IWV,MPL,ISEG

INTEGER :: KLOPRESSURE,KLOWAVELENGTH,KLOTEMP1,KLOTEMP2,IULO

DOUBLE PRECISION :: NUMDEN !,CONV_FAC

DOUBLE PRECISION, ALLOCATABLE,DIMENSION(:)::XKT,XKP

DOUBLE PRECISION ::ABSCOEFF1,ABSCOEFF2,ABSCOEFF3,ABSCOEFF4,ABSCOEFF5,ABSCOEFF6,RTMP
DOUBLE PRECISION,DIMENSION(1) :: XI,YI
DOUBLE PRECISION, DIMENSION(2)::XK,VK
INTEGER, EXTERNAL :: bisearch
LOGICAL :: FLAG

MPL=2

!CONV_FAC=NAVOGADRO/GAS_CONSTANT

ALLOCATE(XKT(NTEM_PERT_LUT),XKP(NPGRID_OXYGEN2_LUT))

DO IPRESSURE=1,NPRESSURE

!  NUMDEN=OXYGEN2VMR_FIELD(IPRESSURE)*CONV_FAC*PRESSURE(IPRESSURE)/TEMPERATURE(IPRESSURE)
  NUMDEN=NUMDEN_TOTAL_FIELD(IPRESSURE)*OXYGEN2VMR_FIELD(IPRESSURE)
!  write(*,*)'PRESSURE,OXYGEN2 NUMDEN=',PRESSURE(IPRESSURE),NUMDEN
  IULO=bisearch(NPGRID_OXYGEN2_LUT,PGRID_OXYGEN2_LUT,PRESSURE(IPRESSURE))
  KLOPRESSURE=min(max(IULO-(MPL-1)/2,1),NPGRID_OXYGEN2_LUT+1-MPL)

  XKT=TEMGRID_OXYGEN2_LUT(KLOPRESSURE,:)
  IULO=bisearch(NTEM_PERT_LUT,XKT,TEMPERATURE(IPRESSURE))
  KLOTEMP1=min(max(IULO-(MPL-1)/2,1),NTEM_PERT_LUT+1-MPL)

  XKT=TEMGRID_OXYGEN2_LUT(KLOPRESSURE+1,:)
  IULO=bisearch(NTEM_PERT_LUT,XKT,TEMPERATURE(IPRESSURE))
  KLOTEMP2=min(max(IULO-(MPL-1)/2,1),NTEM_PERT_LUT+1-MPL)


  DO IWV=1,NWAVELENGTH

        FLAG=.FALSE.
        LOOP_SEG_SEARCH :DO ISEG=1,7
          IF(WAVELENGTH(IWV)>WAVELENGTH_SEG_ENDPOINTS(1,ISEG) .AND. &
             WAVELENGTH(IWV)<WAVELENGTH_SEG_ENDPOINTS(2,ISEG))THEN
             FLAG=.TRUE.
             EXIT LOOP_SEG_SEARCH
          ENDIF
        ENDDO LOOP_SEG_SEARCH
        IF(.NOT. FLAG)CYCLE

        IULO=bisearch(NWV_OXYGEN2_ABS_LUT,WV_OXYGEN2_ABS_LUT,WAVELENGTH(IWV))
        KLOWAVELENGTH=min(max(IULO-(MPL-1)/2,1),NWV_OXYGEN2_ABS_LUT+1-MPL)

        XK(1)=WV_OXYGEN2_ABS_LUT(KLOWAVELENGTH)
        XK(2)=WV_OXYGEN2_ABS_LUT(KLOWAVELENGTH+1)

        VK(1)=OXYGEN2_ABS_COEFF_LUT(KLOPRESSURE,KLOWAVELENGTH,  1,KLOTEMP1)
        VK(2)=OXYGEN2_ABS_COEFF_LUT(KLOPRESSURE,KLOWAVELENGTH+1,1,KLOTEMP1)
		XI(1)=WAVELENGTH(IWV)
		CALL UVIP3P(1,2,XK,VK,1,XI,YI)
		ABSCOEFF1=YI(1)

        VK(1)=OXYGEN2_ABS_COEFF_LUT(KLOPRESSURE,KLOWAVELENGTH,  1,KLOTEMP1+1)
        VK(2)=OXYGEN2_ABS_COEFF_LUT(KLOPRESSURE,KLOWAVELENGTH+1,1,KLOTEMP1+1)
!		XI(1)=WAVELENGTH(IWV)
		CALL UVIP3P(1,2,XK,VK,1,XI,YI)
		ABSCOEFF2=YI(1)

        XK(1)=TEMGRID_OXYGEN2_LUT(KLOPRESSURE,KLOTEMP1)
        XK(2)=TEMGRID_OXYGEN2_LUT(KLOPRESSURE,KLOTEMP1+1)
        VK(1)=ABSCOEFF1
        VK(2)=ABSCOEFF2
		XI(1)=TEMPERATURE(IPRESSURE)
		CALL UVIP3P(1,2,XK,VK,1,XI,YI)
		ABSCOEFF3=YI(1)

        XK(1)=WV_OXYGEN2_ABS_LUT(KLOWAVELENGTH)
        XK(2)=WV_OXYGEN2_ABS_LUT(KLOWAVELENGTH+1)

        VK(1)=OXYGEN2_ABS_COEFF_LUT(KLOPRESSURE+1,KLOWAVELENGTH,  1,KLOTEMP2)
        VK(2)=OXYGEN2_ABS_COEFF_LUT(KLOPRESSURE+1,KLOWAVELENGTH+1,1,KLOTEMP2)
		XI(1)=WAVELENGTH(IWV)
		CALL UVIP3P(1,2,XK,VK,1,XI,YI)
		ABSCOEFF1=YI(1)

        VK(1)=OXYGEN2_ABS_COEFF_LUT(KLOPRESSURE+1,KLOWAVELENGTH,  1,KLOTEMP2+1)
        VK(2)=OXYGEN2_ABS_COEFF_LUT(KLOPRESSURE+1,KLOWAVELENGTH+1,1,KLOTEMP2+1)
!		XI(1)=WAVELENGTH(IWV)
		CALL UVIP3P(1,2,XK,VK,1,XI,YI)
		ABSCOEFF2=YI(1)

        XK(1)=TEMGRID_OXYGEN2_LUT(KLOPRESSURE+1,KLOTEMP2)
        XK(2)=TEMGRID_OXYGEN2_LUT(KLOPRESSURE+1,KLOTEMP2+1)
        VK(1)=ABSCOEFF1
        VK(2)=ABSCOEFF2
		XI(1)=TEMPERATURE(IPRESSURE)
		CALL UVIP3P(1,2,XK,VK,1,XI,YI)
		ABSCOEFF4=YI(1)

        XK(1)=PGRID_OXYGEN2_LUT(KLOPRESSURE)
        XK(2)=PGRID_OXYGEN2_LUT(KLOPRESSURE+1)
        VK(1)=ABSCOEFF3
        VK(2)=ABSCOEFF4
		XI(1)=PRESSURE(IPRESSURE)
		CALL UVIP3P(1,2,XK,VK,1,XI,YI)
		ABSCOEFF1=YI(1)

        GAS_ABS_COEFF(IWV,IPRESSURE)=GAS_ABS_COEFF(IWV,IPRESSURE)+ABSCOEFF1*NUMDEN
!IF(ABSCOEFF1*NUMDEN<0.0d0)THEN
!  WRITE(*,*)'OXYGEN2_ABS_SEARCH TESTING',NUMDEN,PRESSURE(IPRESSURE),TEMPERATURE(IPRESSURE),WAVELENGTH(IWV),ABSCOEFF1
!  WRITE(*,*)'OXYGEN2_ABS_SEARCH TEST P2',XK,VK
!  STOP
!ENDIF

  ENDDO

ENDDO

DEALLOCATE(XKT,XKP)

ENDSUBROUTINE OXYGEN2_ABS_SEARCH

END MODULE OXYGEN2_ABS_DATA


MODULE OZONE_ABS_DATA
USE UNIVERSAL_CONSTANT
USE ATMOS_CONFIGURATION_DIRECTORY
IMPLICIT NONE

INTEGER,PARAMETER :: NPGRID_OZONE_LUT=1,NWV_OZONE_ABS_LUT=88668

DOUBLE PRECISION,DIMENSION(NWV_OZONE_ABS_LUT)::WV_OZONE_ABS_LUT
DOUBLE PRECISION,DIMENSION(NPGRID_OZONE_LUT):: PGRID_OZONE_LUT,TEMREF_OZONE_LUT,OZONEVMR_REF_LUT

DOUBLE PRECISION, DIMENSION(NWV_OZONE_ABS_LUT) :: C0_ARRAY_OZONE,C1_ARRAY_OZONE,C2_ARRAY_OZONE
DOUBLE PRECISION,DIMENSION(2),PARAMETER :: WAVELENGTH_LUT_RANGE_OZONE=(/116.650D0,850.0D0/)

CONTAINS

SUBROUTINE OZONE_ABS_READIN
IMPLICIT NONE
INTEGER :: NHEADER
INTEGER :: IPRESSURE,ITEMP
DOUBLE PRECISION :: WAVELENGTH_TEMP,C0_TEMP,C1_TEMP,C2_TEMP
CHARACTER(LEN=180) :: OZONE_ABS_FILEDIR,OZONE_ABS_FILENAME

call atmos_dir_readin

OZONE_ABS_FILEDIR=trim(atmos_dir)//'/O3/'

OZONE_ABS_FILENAME='Ozone_abs_x_wTemperatureFit.dat'
NHEADER=10

OZONE_ABS_FILENAME=trim(OZONE_ABS_FILEDIR)//trim(OZONE_ABS_FILENAME)

PGRID_OZONE_LUT=5000.0D0
TEMREF_OZONE_LUT=273.15D0
OZONEVMR_REF_LUT=0.0D0
OPEN(UNIT=1,FILE=OZONE_ABS_FILENAME,STATUS='OLD',ACTION='READ')
DO ITEMP=1,NHEADER
  READ(1,*)
ENDDO

DO ITEMP=NWV_OZONE_ABS_LUT,1,-1
  READ(1,*)WAVELENGTH_TEMP,C0_TEMP,C1_TEMP,C2_TEMP
  WV_OZONE_ABS_LUT(ITEMP)=WAVELENGTH_TEMP
  C0_ARRAY_OZONE(ITEMP)=C0_TEMP
  C1_ARRAY_OZONE(ITEMP)=C1_TEMP
  C2_ARRAY_OZONE(ITEMP)=C2_TEMP
ENDDO
CLOSE(1)
ENDSUBROUTINE OZONE_ABS_READIN

SUBROUTINE OZONE_ABS_SEARCH(NPRESSURE,NWAVELENGTH,WAVELENGTH,PRESSURE,TEMPERATURE, &
                          NUMDEN_TOTAL_FIELD,OZONEVMR_FIELD,GAS_ABS_COEFF)
IMPLICIT NONE
INTEGER,INTENT(IN) :: NPRESSURE,NWAVELENGTH
DOUBLE PRECISION,INTENT(IN),DIMENSION(NPRESSURE)::PRESSURE,TEMPERATURE,NUMDEN_TOTAL_FIELD,OZONEVMR_FIELD
DOUBLE PRECISION,INTENT(INOUT),DIMENSION(NWAVELENGTH)::WAVELENGTH ! IN NANOMETER

DOUBLE PRECISION,INTENT(INOUT),DIMENSION(NWAVELENGTH,NPRESSURE)::GAS_ABS_COEFF


INTEGER :: IPRESSURE,IWV,MPL,KLOWAVELENGTH,IULO

DOUBLE PRECISION :: NUMDEN!,CONV_FAC

DOUBLE PRECISION ::ABS_CRS_M2,ABSCOEFF1,ABSCOEFF2,ABSCOEFF3,RTMP,TEMPERATURE_DIFF
DOUBLE PRECISION,DIMENSION(1) :: XI,YI
DOUBLE PRECISION, DIMENSION(2)::XK,VK
INTEGER, EXTERNAL :: bisearch
MPL=2

!CONV_FAC=NAVOGADRO/GAS_CONSTANT

DO IPRESSURE=1,NPRESSURE

!  NUMDEN=OZONEVMR_FIELD(IPRESSURE)*CONV_FAC*PRESSURE(IPRESSURE)/TEMPERATURE(IPRESSURE)
  NUMDEN=NUMDEN_TOTAL_FIELD(IPRESSURE)*OZONEVMR_FIELD(IPRESSURE)
!  write(*,*)'PRESSURE,OZONE NUMDEN=',PRESSURE(IPRESSURE),NUMDEN
  TEMPERATURE_DIFF=TEMPERATURE(IPRESSURE)-TEMREF_OZONE_LUT(1)

  DO IWV=1,NWAVELENGTH
        IF(WAVELENGTH(IWV)<WAVELENGTH_LUT_RANGE_OZONE(1) .OR.   &
           WAVELENGTH(IWV)>WAVELENGTH_LUT_RANGE_OZONE(2)) THEN
            CYCLE
        ENDIF

        IULO=bisearch(NWV_OZONE_ABS_LUT,WV_OZONE_ABS_LUT,WAVELENGTH(IWV))
        KLOWAVELENGTH=min(max(IULO-(MPL-1)/2,1),NWV_OZONE_ABS_LUT+1-MPL)

        XK(1:2)=WV_OZONE_ABS_LUT(KLOWAVELENGTH:KLOWAVELENGTH+1)
        VK(1:2)=C0_ARRAY_OZONE(KLOWAVELENGTH:KLOWAVELENGTH+1)
		XI(1)=WAVELENGTH(IWV)
		CALL UVIP3P(1,2,XK,VK,1,XI,YI)
		ABSCOEFF1=YI(1)

        VK(1:2)=C1_ARRAY_OZONE(KLOWAVELENGTH:KLOWAVELENGTH+1)
!		XI(1)=WAVELENGTH(IWV)
		CALL UVIP3P(1,2,XK,VK,1,XI,YI)
		ABSCOEFF2=YI(1)

        VK(1:2)=C2_ARRAY_OZONE(KLOWAVELENGTH:KLOWAVELENGTH+1)
!		XI(1)=WAVELENGTH(IWV)
		CALL UVIP3P(1,2,XK,VK,1,XI,YI)
		ABSCOEFF3=YI(1)

        ABS_CRS_M2=(ABSCOEFF1+ABSCOEFF2*TEMPERATURE_DIFF + ABSCOEFF3*(TEMPERATURE_DIFF**2)) &
                    *1.0E-20*1.0E-4

        IF(ABS_CRS_M2<0.0D0)ABS_CRS_M2=0.0D0
        GAS_ABS_COEFF(IWV,IPRESSURE)=GAS_ABS_COEFF(IWV,IPRESSURE)+ABS_CRS_M2*NUMDEN

!if(isnan(ABS_CRS_M2) .or. GAS_ABS_COEFF(IWV,IPRESSURE)>1.0e30 .or. GAS_ABS_COEFF(IWV,IPRESSURE)<0)THEN
!write(*,*)WAVELENGTH(IWV),WAVELENGTH_LUT_RANGE_OZONE(1),WAVELENGTH_LUT_RANGE_OZONE(2),&
!ABSCOEFF1,ABSCOEFF2,ABSCOEFF3,TEMPERATURE_DIFF,ABS_CRS_M2,NUMDEN,&
!pressure(IPRESSURE),TEMPERATURE(IPRESSURE)
!stop 'check ozone'
!endif

  ENDDO

ENDDO

ENDSUBROUTINE OZONE_ABS_SEARCH

END MODULE OZONE_ABS_DATA


MODULE NO2_ABS_DATA
USE UNIVERSAL_CONSTANT
USE ATMOS_CONFIGURATION_DIRECTORY
IMPLICIT NONE

INTEGER,PARAMETER :: NPGRID_NO2_LUT=1,NWV_NO2_ABS_LUT=5189

DOUBLE PRECISION,DIMENSION(NWV_NO2_ABS_LUT)::WV_NO2_ABS_LUT
DOUBLE PRECISION,DIMENSION(NPGRID_NO2_LUT):: PGRID_NO2_LUT,TEMREF_NO2_LUT,NO2VMR_REF_LUT

DOUBLE PRECISION, DIMENSION(NWV_NO2_ABS_LUT) :: C0_ARRAY_NO2,C1_ARRAY_NO2,C2_ARRAY_NO2
DOUBLE PRECISION,DIMENSION(2),PARAMETER :: WAVELENGTH_LUT_RANGE_NO2=(/241.10D0,759.9D0/)

CONTAINS

SUBROUTINE NO2_ABS_READIN
IMPLICIT NONE
INTEGER,PARAMETER :: NHEADER=10
INTEGER :: IPRESSURE,ITEMP
DOUBLE PRECISION :: WAVELENGTH_TEMP,C0_TEMP,C1_TEMP,C2_TEMP
CHARACTER(LEN=180) :: NO2_ABS_FILEDIR,NO2_ABS_FILENAME
call atmos_dir_readin

NO2_ABS_FILEDIR=trim(atmos_dir)//'/NO2/'
NO2_ABS_FILENAME='crs_NO2_UBremen_cf.dat'
NO2_ABS_FILENAME=trim(NO2_ABS_FILEDIR)//trim(NO2_ABS_FILENAME)

PGRID_NO2_LUT=5000.0D0
TEMREF_NO2_LUT=273.15D0
NO2VMR_REF_LUT=0.0D0
OPEN(UNIT=1,FILE=NO2_ABS_FILENAME,STATUS='OLD',ACTION='READ')
DO ITEMP=1,NHEADER
  READ(1,*)
ENDDO

DO ITEMP=NWV_NO2_ABS_LUT,1,-1
  READ(1,*)WAVELENGTH_TEMP,C0_TEMP,C1_TEMP,C2_TEMP
  WV_NO2_ABS_LUT(ITEMP)=WAVELENGTH_TEMP
  C0_ARRAY_NO2(ITEMP)=C0_TEMP
  C1_ARRAY_NO2(ITEMP)=C1_TEMP
  C2_ARRAY_NO2(ITEMP)=C2_TEMP
ENDDO
CLOSE(1)
ENDSUBROUTINE NO2_ABS_READIN

SUBROUTINE NO2_ABS_SEARCH(NPRESSURE,NWAVELENGTH,WAVELENGTH,PRESSURE,TEMPERATURE, &
                          NUMDEN_TOTAL_FIELD,NO2VMR_FIELD,GAS_ABS_COEFF)
IMPLICIT NONE
INTEGER,INTENT(IN) :: NPRESSURE,NWAVELENGTH
DOUBLE PRECISION,INTENT(IN),DIMENSION(NPRESSURE)::PRESSURE,TEMPERATURE,NUMDEN_TOTAL_FIELD,NO2VMR_FIELD
DOUBLE PRECISION,INTENT(INOUT),DIMENSION(NWAVELENGTH)::WAVELENGTH ! IN NANOMETER

DOUBLE PRECISION,INTENT(INOUT),DIMENSION(NWAVELENGTH,NPRESSURE)::GAS_ABS_COEFF


INTEGER :: IPRESSURE,IWV,MPL,KLOWAVELENGTH,IULO

DOUBLE PRECISION :: NUMDEN !,CONV_FAC

DOUBLE PRECISION ::ABS_CRS_M2,ABSCOEFF1,ABSCOEFF2,ABSCOEFF3,RTMP,TEMPERATURE_DIFF
DOUBLE PRECISION,DIMENSION(1) :: XI,YI
DOUBLE PRECISION, DIMENSION(2)::XK,VK
INTEGER, EXTERNAL :: bisearch
MPL=2

!CONV_FAC=NAVOGADRO/GAS_CONSTANT

DO IPRESSURE=1,NPRESSURE

!  NUMDEN=NO2VMR_FIELD(IPRESSURE)*CONV_FAC*PRESSURE(IPRESSURE)/TEMPERATURE(IPRESSURE)
  NUMDEN=NUMDEN_TOTAL_FIELD(IPRESSURE)*NO2VMR_FIELD(IPRESSURE)
!  write(*,*)'Pressure,NUMDEN_TOTAL_FIELD,NO2VMR_FIELD=',PRESSURE(IPRESSURE),&
!              NUMDEN_TOTAL_FIELD(IPRESSURE),NO2VMR_FIELD(IPRESSURE)
  TEMPERATURE_DIFF=TEMPERATURE(IPRESSURE)-TEMREF_NO2_LUT(1)

  DO IWV=1,NWAVELENGTH
        IF(WAVELENGTH(IWV)<WAVELENGTH_LUT_RANGE_NO2(1) .OR.   &
           WAVELENGTH(IWV)>WAVELENGTH_LUT_RANGE_NO2(2)) THEN
            CYCLE
        ENDIF

        IULO=bisearch(NWV_NO2_ABS_LUT,WV_NO2_ABS_LUT,WAVELENGTH(IWV))
        KLOWAVELENGTH=min(max(IULO-(MPL-1)/2,1),NWV_NO2_ABS_LUT+1-MPL)

        XK(1:2)=WV_NO2_ABS_LUT(KLOWAVELENGTH:KLOWAVELENGTH+1)
        VK(1:2)=C0_ARRAY_NO2(KLOWAVELENGTH:KLOWAVELENGTH+1)
		XI(1)=WAVELENGTH(IWV)
		CALL UVIP3P(1,2,XK,VK,1,XI,YI)
		ABSCOEFF1=YI(1)

        VK(1:2)=C1_ARRAY_NO2(KLOWAVELENGTH:KLOWAVELENGTH+1)
!		XI(1)=WAVELENGTH(IWV)
		CALL UVIP3P(1,2,XK,VK,1,XI,YI)
		ABSCOEFF2=YI(1)

        VK(1:2)=C2_ARRAY_NO2(KLOWAVELENGTH:KLOWAVELENGTH+1)
!		XI(1)=WAVELENGTH(IWV)
		CALL UVIP3P(1,2,XK,VK,1,XI,YI)
		ABSCOEFF3=YI(1)

        ABS_CRS_M2=(ABSCOEFF1+ABSCOEFF2*TEMPERATURE_DIFF + ABSCOEFF3*(TEMPERATURE_DIFF**2)) &
                    *1.0E-20*1.0E-4

        IF(ABS_CRS_M2<0.0D0)ABS_CRS_M2=0.0D0

        GAS_ABS_COEFF(IWV,IPRESSURE)=GAS_ABS_COEFF(IWV,IPRESSURE)+ABS_CRS_M2*NUMDEN

!if(isnan(ABS_CRS_M2) .or. GAS_ABS_COEFF(IWV,IPRESSURE)>1.0e30 .or. GAS_ABS_COEFF(IWV,IPRESSURE)<0)THEN
!write(*,*)WAVELENGTH(IWV),WAVELENGTH_LUT_RANGE_NO2(1),WAVELENGTH_LUT_RANGE_NO2(2),&
!           ABSCOEFF1,ABSCOEFF2,ABSCOEFF3,TEMPERATURE_DIFF,ABS_CRS_M2,NUMDEN,&
!           pressure(IPRESSURE),TEMPERATURE(IPRESSURE)
!stop 'check no2'
!endif

  ENDDO

ENDDO

ENDSUBROUTINE NO2_ABS_SEARCH

END MODULE NO2_ABS_DATA

MODULE O4_ABS_DATA
!!!
!Calculate the O2-O2 collision pair absorption cross section at T=296K
!based on Greenblatt et al (1990).
!
!@ARTICLE{Greenblatt1990,
!	AUTHOR  = "Gary D. Greenblatt and John J. Orlando and James
!				  B. Burkholder and A. R. Ravishankara",
!	TITLE   = "{Absorption measurements of oxygen between 330 and 1140
!				  nm}",
!	JOURNAL = JGR,
!	VOLUME  = "95",
!	YEAR    = "1990",
!	PAGES   = "18,577-18,582"}
!
!!!
USE UNIVERSAL_CONSTANT
USE ATMOS_CONFIGURATION_DIRECTORY
INTEGER,PARAMETER :: NUM_BAND_SEG=9
DOUBLE PRECISION,DIMENSION(NUM_BAND_SEG) :: WV_O4_ABS_LUT=(/343.4D0,360.5D0,380.2D0,446.7D0,&
                                      477.3D0,532.2D0,577.2D0,630.0D0,1065.2D0/)
DOUBLE PRECISION,DIMENSION(NUM_BAND_SEG) :: CRS_O4_LUT=(/1.20D0,4.10D0,2.4D0,0.57D0,6.3D0,1.0D0,11.0D0,7.2D0,12.0D0/)
DOUBLE PRECISION,DIMENSION(NUM_BAND_SEG) :: FWHM_O4_LUT=(/4.2D0,4.8D0,4.4D0,5.6D0,6.2D0,10.2D0, 11.6D0,13.8D0,27.3D0/)

INTEGER :: NFWHM=3

CONTAINS
SUBROUTINE O4_ABS_SEARCH(NPRESSURE,NWAVELENGTH,WAVELENGTH,PRESSURE,TEMPERATURE, &
                         NUMDEN_TOTAL_FIELD,O4VMR_FIELD,GAS_ABS_COEFF)
IMPLICIT NONE
INTEGER,INTENT(IN) :: NPRESSURE,NWAVELENGTH
DOUBLE PRECISION,INTENT(IN),DIMENSION(NPRESSURE)::PRESSURE,TEMPERATURE,NUMDEN_TOTAL_FIELD,O4VMR_FIELD
DOUBLE PRECISION,INTENT(INOUT),DIMENSION(NWAVELENGTH)::WAVELENGTH ! IN NANOMETER

DOUBLE PRECISION,INTENT(INOUT),DIMENSION(NWAVELENGTH,NPRESSURE)::GAS_ABS_COEFF

DOUBLE PRECISION :: NUMDEN !,CONV_FAC
DOUBLE PRECISION :: WAVELENGTH_DIFF,LN2,FACT1,FACT2

INTEGER :: I_BAND_SEG
INTEGER :: IPRESSURE,IWV,MPL,KLOWAVELENGTH,IULO
DOUBLE PRECISION ::ABS_CRS_M2,ABSCOEFF1,ABSCOEFF2,ABSCOEFF3,RTMP

MPL=2
!CONV_FAC=NAVOGADRO/GAS_CONSTANT
LN2 = LOG(2.0D0)

DO IPRESSURE=1,NPRESSURE

!  NUMDEN=O4VMR_FIELD(IPRESSURE)*CONV_FAC*PRESSURE(IPRESSURE)/TEMPERATURE(IPRESSURE)
  NUMDEN=NUMDEN_TOTAL_FIELD(IPRESSURE)*O4VMR_FIELD(IPRESSURE)
  !  write(*,*)'PRESSURE,NO2 NUMDEN=',PRESSURE(IPRESSURE),NUMDEN

  DO IWV=1,NWAVELENGTH

     DO I_BAND_SEG=1,NUM_BAND_SEG
        WAVELENGTH_DIFF=WAVELENGTH(IWV)-WV_O4_ABS_LUT(I_BAND_SEG)
        IF(ABS(WAVELENGTH_DIFF)>2.0D0*FWHM_O4_LUT(I_BAND_SEG)) CYCLE
        FACT1 = CRS_O4_LUT(I_BAND_SEG) ! UNIT 1.0D-46 CM^5/MOLECULE^2
        FACT2 = FWHM_O4_LUT(I_BAND_SEG)*FWHM_O4_LUT(I_BAND_SEG) / (4.0*LN2);
        ABSCOEFF1 = FACT1 * EXP(-(WAVELENGTH_DIFF*WAVELENGTH_DIFF/FACT2));

        GAS_ABS_COEFF(IWV,IPRESSURE)=GAS_ABS_COEFF(IWV,IPRESSURE) + &
             ABSCOEFF1*NUMDEN*NUMDEN*1.0D-10*1.0D-46

     ENDDO
  ENDDO
ENDDO
END SUBROUTINE O4_ABS_SEARCH
END MODULE O4_ABS_DATA
