MODULE RTTYPE
INTEGER, PARAMETER :: I4B = SELECTED_INT_KIND(9)
INTEGER, PARAMETER :: I2B = SELECTED_INT_KIND(4)
INTEGER, PARAMETER :: I1B = SELECTED_INT_KIND(2)
INTEGER, PARAMETER :: SP = KIND(1.0)
INTEGER, PARAMETER :: DP = KIND(1.0D0)
INTEGER, PARAMETER :: SPC = KIND((1.0,1.0))
INTEGER, PARAMETER :: DPC = KIND((1.0D0,1.0D0))
INTEGER, PARAMETER :: LGT = KIND(.true.)
REAL(DP), PARAMETER :: PI=3.141592653589793238462643383279502884197_dp
REAL(DP), PARAMETER :: TINY1=1.0d-12,                     &
                       TINY2=1.0d-12,LARGERN=1.0D32
REAL(DP), PARAMETER :: FACTOR=PI/180.0_DP, TWOPI=2.0_DP*PI,       &
                       FOURPI=4.0_DP*PI

TYPE MATRIX44
    REAL(DP),DIMENSION(4,4) ::PHMX
END TYPE MATRIX44

TYPE ARRAY4
    REAL(DP),DIMENSION(4) :: VRAD
END TYPE ARRAY4

TYPE PIXEL  !PIXEL PLANE PARALLEL LAYERS OF THE ATMOSPHERE
    INTEGER(I4B) :: IPT,NTAU,ITAUS,ITAUE
          ! IPT INDEX OF PARTILCE TYPE : 1-N MIE PARTICLES
          ! NTAU: NUMBER OF SUB TAU TO DO INTEGRATION OVER TAU
		  ! ITAUS: STARTING NUMBER OF TAU IN THIS LAYER

    REAL(DP) :: TAUB,TAUT,DTAU,WAVELENGTH,TEMPERATURE
	! TAUB = THE TAU FOR THE BOTTOM OF THE LAYER.
	! TAUT = THE TAU FOR THE TOP OF THE LAYER.
	! TAUT = TAUB OF THE PREVIOUS LAYER.
	! TAUB INCREASES AS INDEX OF LAYERS INCREASES.
	! DTAU IS THE DELTA TAU IN THIS LAYER TO DO TAU INTEGRATION

    REAL(DP) :: LBDOM, EFLRSC
    ! LBDOM: THE SINGLE SCATTERING ALBEDO IN THIS LAYER.
	! EFLRSC: THE FLUORESCENCE EMISSION IRRADIANCE
	
END TYPE PIXEL

END MODULE RTTYPE

MODULE RTUTILITY

USE RTTYPE

LOGICAL :: SCL,OSFREXP,OCEAN,OCEAN_NO_TRAN,LAMB,pBRDF,FLATO,SHDWFLG,&
           ENGFACNORM,WCFLG,RSRADDFLG,LINEXP,DETA,DETO,ENORM_FLAT,WLR_FLAG,   &
           OC_IF_DS,SNG_RAD_CORR,SEC_RAD_CORR,RAD_MAP,       &
           DOUBLE_GAUSSIAN_QUAD,PSEUDO_VIEWING_QUAD,                &
           SAVE_RAMAN_FLAG,SAVE_FLUORESCENCE_FLAG,                  &
           RAMAN_SOURCE_FLAG,FLUORESCENCE_SOURCE_FLAG
LOGICAL :: PSEUDO_SPHERICAL_SHELL = .FALSE.
LOGICAL :: DIFFUSE_TRANSMITTANCE = .FALSE.
REAL(DP),PARAMETER :: RADIUS_EARTH=6371.0d0 ! GLOBAL AVERAGE
                     !RADIUS_EARTH=6357.0D0 POLAR RADIUS
REAL(DP) :: RAYLEIGH_SCALE_HEIGHT=5.0D0 
	 ! SCL = .TRUE. SCALAR CALCULATION
     ! OSFREXP = .TRUE. USING SERIES EXPANSION TO CALCULATE 
	 !                  OCEAN REFLECTANCE AND TRANSMITTANCE
	 !                  MATRICES
     ! OCEAN = .TRUE. OCEAN LAYERS WILL BE ALLOCATED AND CALCULATED
     ! OCEAN_NO_TRAN = .TRUE. NO OCEAN TRANSMITTANCE WILL BE CALCULATED
	 ! LAMB = .TRUE. LAMBERTIAN BOTTOM WILL BE CALCULATED
     ! DOUBLE_GAUSSIAN_QUAD=.TRUE. USE DOUBLE GAUSSIAN QUADRATURE RULE FOR OCEAN
     ! PSEUDO_VIEWING_QUAD=.TRUE. USE PSEUDO QUADRATURE SCHEME FOR USER SPECFIED
     !                     VIEWING ANGLES
	 ! PSEUDO_SPHERICAL_SHELL =.TRUE. USE PSEUDO_SPHERICAL_SHELL APPROXIMATION
     ! PSEUDO_SPHERICAL_SHELL =.FALSE. USE PLANE PARALLEL APPROXIMATION

INTEGER :: DELTAM
     ! DELTAM = 0 USE DELTA M FIT FOR THE PHASE MATRIX
     !          1 USE DELTA M + FIT
     !          2 USE DELTA FIT

INTEGER(I4B) :: NLAYER,NALYR,NOLYR,NQUADA,NQUADO,NQUADSO,NQDAD2,NQDOD2, &
           NQUADDIF,NCOL,NTTAU,NTTAUA,NDTAUA,NDTAUO,NLEG,NQUADI
          ! NLAYER TOTAL number of the layers
		  ! NALYR,NOLYR   Number of ATMOSPHERE AND OCEAN LAYERS
		  ! NQUAD  Number of quadratures to do angular integration.
          ! NCOL   Number of scattering orders for convergence
          ! NTTAU  TOTAL NUMBER OF TAUS TO DO INTEGRATION

TYPE(PIXEL), DIMENSION(:), ALLOCATABLE ::ALYR,OLYR
          !ATMOSPHERE AND OCEAN LAYERS SPECIFICATION
REAL(DP) :: DELTATAUA,DELTATAUO,TOTALTAU,TOTALTAU_PRSV,GLBDO,FLAM,FWC,WCLBDO,RSR0P
REAL(DP) :: OITAU,OITAU_PRSV,NWRE,NWIM,NRELRE,NRELIM,NSQW,NAIR,NSQA,&
            WNDSPD,SIGMASQ,NMBRE,NMBIM,pBRDFa,pBRDFk,pBRDFb,pBRDFe
           !OITAU WATER SURFACE POSITION IN TERMS OF TAU,
           !OITAU_PRSV OITAU WITHOUT SCALE 
		   ! OPTICAL DEPTH FROM THE TOP
           ! NWRE: REAL PART WATER REFRECTIVE INDEX.
           ! NWIM: IMAGINARY PART WATER REFRECTIVE INDEX.
		   ! NAIR: AIR REFRECTIVE INDEX
		   ! WNDSPD: WIND SPEED
           ! LAMBERTIAN FRACTUAL FRESNEL REFLECTION INDEX OF REFRACTION
INTEGER(I4B) :: NUMMIE,MAXLORD,MAXMORD,MAXKORD,MAXSORD
INTEGER,PARAMETER :: NUMMIEANGMAX=4200
    ! NUMMIE NUMBER OF MIE SCATTERING MATRIX. USE FOR INPUT.
    ! MAXLORD: TOTAL NUMBER OF THE INPUT ORDER OF MIE EXPANSION COEFFICIENTS.
    ! MAXMORD: TOTAL NUMBER OF FOURIER ORDER OF RADIANCE EXPANSION.
	! MAXKORD: TOTAL NUMBER OF WAVE COEFFICIENT EXPANSION
	! MAXSORD: TOTAL NUMBER OF REFLECTANCE OR TRANSMITTANCE EXPANSION
	! MAXWORD: =MAXSORD+MAXKORD; MAXIMUM WAVE FOURIER EXPANSION 

INTEGER(I4B),DIMENSION(:),ALLOCATABLE::NUMORD

REAL(DP), DIMENSION(4) :: ESUN

REAL(DP), PARAMETER :: ANGLE_TRUNCATION=5.0D0
REAL(DP), DIMENSION(:),ALLOCATABLE:: FTRUNC
REAL(DP), DIMENSION(:,:),ALLOCATABLE:: &
          BETAL,ALPHAL,ZETAL,DELTAL,GAMMAL,EPSILONL


INTEGER(I4B),DIMENSION(:),ALLOCATABLE::NUMMIEANG ! NUMMIEANG(IMIE),IMIE=1,NUMMIE
REAL(DP),DIMENSION(:,:),ALLOCATABLE :: THETA_SNG,MU_SNG 
      ! SCATTERING ANGLE AND MU FOR INPUT SINGLE SCATTERING MATRICES
      ! THETA_SNG(I,J), I=1, NUMMIE AND J=1,NUMMIEANG
      ! MU_SNG(I,J), I=1, NUMMIE AND J=1,NUMMIEANG
TYPE(MATRIX44), DIMENSION(:,:),ALLOCATABLE :: PM_AO_SNG
REAL*8,DIMENSION(:,:),ALLOCATABLE :: PHF_RESIDUE

INTEGER,DIMENSION(:),ALLOCATABLE :: NUMFULLBETAL
REAL*8,DIMENSION(:,:),ALLOCATABLE :: FULLBETAL
  ! SINGLE SCATTERING MATRIX FOR INPUT PARTICLES
  ! PM_AO_SNG(I,J),I=1, NUMMIE AND J=1,NUMMIEANG

INTEGER :: NMU_CM
REAL(DP),DIMENSION(:),ALLOCATABLE :: MU_CM,REFL_CM_AT,TRAN_CM_AT,&
                                     REFL_CM_OT,TRAN_CM_OT

REAL(DP), DIMENSION(:,:),ALLOCATABLE:: &
          WBETAL,WALPHAL,WZETAL,WDELTAL,WGAMMAL,WEPSILONL
 ! BETAL(I,J), I=1~4,J=1,NUMORD. EXPANSION COEFFICIENTS
 ! I==1 light incident from air to water, reflectance
 ! I==2 light incident from air to water, transmittance
 ! I==3 light incident from water to air, reflectance
 ! I==4 light incident from water to air, transmittance
REAL(DP),DIMENSION(:),ALLOCATABLE :: HEIGHT_ATMOSPHERE,SECANT_THETAL,SECANT_THETAL_PRSV
REAL(DP),DIMENSION(:),ALLOCATABLE ::   TAU,TAU_PRSV,LBDO_A_PRSV,LBDO_O_PRSV
REAL(DP),DIMENSION(:,:),ALLOCATABLE :: DTAUMUADW,DTAUMUAUP,  &
        DTAUMUODW,DTAUMUOUP,EXPTAUADW,EXPTAUAUP,EXPTAUODW,EXPTAUOUP


REAL(DP),DIMENSION(:,:,:),ALLOCATABLE :: DML0A,DML2PA,DML2NA,    &
                       DML0O,DML2PO,DML2NO,DML0SO,DML2PSO,DML2NSO,&
                       DML0XA,DML2PXA,DML2NXA,DML0XO,DML2PXO,DML2NXO
REAL(DP),DIMENSION(:,:,:,:),ALLOCATABLE ::DML0AT,DML2PAT,DML2NAT,&
                       DML0OT,DML2POT,DML2NOT
REAL(DP),DIMENSION(:,:),ALLOCATABLE ::SDML0,SDML2P,SDML2N, &
                         SRDML0,SRDML2P,SRDML2N
! WIGNER d function as a function of:
! order L,variable MU, order M

! DML0  = d^l_{m,0}
! DML2P = (d^l_{m,2}+d^l_{m,-2})/2
! DML2N = (d^l_{m,2}-d^l_{m,-2})/2

! WIGNER d function as a function of:
! order L, order M, MU=MU0, -MU0


TYPE(ARRAY4),DIMENSION(:,:,:),ALLOCATABLE :: LSPA,LSPANM1,LSPAN,LSPMNA,     &
                              LSPO,LSPONM1,LSPON,LSPMNO,  &
                              LRADO_SNG,LSPMNA_SNG,LSPA_SNG_RO,&
                              LSPMNAX_SNG,LSPMNO_SNG,LSPMNO_INELASTIC_SNG
TYPE(ARRAY4),DIMENSION(:,:,:),ALLOCATABLE :: LRADA,LRADO,LRADA_SNG
TYPE(ARRAY4),DIMENSION(:,:),ALLOCATABLE :: LSPAIRAD,LSPAIRADNM1,LSPAIRADN,&
                                           LSPOIRAD,LSPOIRADNM1,LSPOIRADN
!LSP: RADIANCE VECTOR as a functions of
!     variable MU,optical depth tau,order M

!LSPMN: RADIANCE VECTOR AT SCATTERING ORDER N as a functions of  
!     variable MU,optical depth tau,order M

!LSPAIRAD, LSPAIRADNM1,LSPAIRADN,LSPOIRAD, LSPOIRADNM1,LSPOIRADN:
! ARRAY TO RECORD CORRECT TOTAL IRRADIANCE FOR WATER LEAVING RADIANCE DETECTOR
! or SINGLE SCATTERING CORRECTION FLAG IS ON
LOGICAL :: FWDCN_CORR_FLAG
INTEGER,PARAMETER :: MAXLFULL=10000
INTEGER,PARAMETER :: NMUFWDCN=38,NPHIFWDCN=37
REAL*8,DIMENSION(NMUFWDCN):: MUFWDCN_LCL
REAL*8,DIMENSION(NPHIFWDCN):: PHIFWDCN_LCL
REAL*8,DIMENSION(NMUFWDCN,NPHIFWDCN):: MUFWDCN,PHIFWDCN
REAL*8 :: MINMUFWDCN
TYPE(ARRAY4),DIMENSION(:,:,:),ALLOCATABLE :: LRADA_FWDCN_SNG

! FORWARD CONE CORRECTION VARIABLES

INTEGER(I4B),DIMENSION(:),ALLOCATABLE:: INDXDETA,INDXDETO,INDXREVA,&
                                        INDXDETA_SNGSCAT,INDXDETO_SNGSCAT
                                        
REAL(DP),DIMENSION(:),ALLOCATABLE::COEFALUP,COEFALDW

TYPE(ARRAY4),DIMENSION(:,:,:),ALLOCATABLE :: SOURCEFA,SOURCEFO, &
                              SRCFAP,SRCFOP
!SOURCE FUNCTION: as a functions of 
!     variable MU,optical depth tau,order M

TYPE(MATRIX44), DIMENSION(:,:,:,:),ALLOCATABLE :: PMA,PMO,SPMO,PMAX,PMOX
TYPE(MATRIX44), DIMENSION(:,:,:),ALLOCATABLE :: SPMA,SRPMA
!TYPE(MATRIX44), DIMENSION(:,:,:),ALLOCATABLE :: SPMAX
  ! PM()%PHMX IS A MATRIX OF: COLOUM NUMBER 1-4, ROW NUMBER 1-4
  ! RTWVSF,PM() IS FUNCTIONS OF: VARIABLE MU',VARIABLE MU, 
					 !    NUMBER OF MIE (TAU), ORDER M 

  ! SPM(VARIABLE MU0)%PHMX IS A MATRIX OF COLOUM NUMBER 1-4, ROW NUMBER 1-4
  ! SPM(VARIABLE MU0) IS FUNCTIONS OF:
		!VARIABLE MU0,VARIABLE MU,NUMBER OF MIE (TAU), ORDER M 


TYPE(MATRIX44), DIMENSION(:,:),ALLOCATABLE :: SFRES_TRANA,SFRES_REFLA
TYPE(MATRIX44),DIMENSION(:,:,:), ALLOCATABLE :: FRES_REFLA,FRES_TRANA, & 
            FRES_TRANO,FRES_REFLO
  ! FRES_TRAN, REFL%PHMX IS A MATRIX OF: COLOUM NUMBER 1-4, ROW NUMBER 1-4
  ! IS FUNCTIONS OF: VARIABLE MU',VARIABLE MU,ORDER M 

REAL(DP),DIMENSION(:,:,:),ALLOCATABLE :: FRSNLAR,FRSNLWR,&
                   FRSNLAT,FRSNLWT

REAL(DP),DIMENSION(:,:,:),ALLOCATABLE :: FRSNLMBR

!INTEGER(I4B) :: NTHETAIN,NTHETAOUT,NPHIOUT
!REAL(DP), DIMENSION(:), ALLOCATABLE :: THETA_IN,MU_IN
!REAL(DP),DIMENSION(:),ALLOCATABLE :: PHIOUT,THETAOUT,MUOUT

REAL(DP),DIMENSION(:),ALLOCATABLE :: XJA,WTA,XJO,WTO,XJSO,WTSO,XJAI,XJOI
REAL(DP),DIMENSION(:,:),ALLOCATABLE :: XJAT,WTAT,XJOT,WTOT

REAL*8,DIMENSION(:),ALLOCATABLE :: SHDWXJA,SHDWXJO


REAL(DP),DIMENSION(:),ALLOCATABLE :: DMM0FCTR,DMM2FCTR,      &
                             COEF1,COEF2,COEF3,COEF4,COEF5,COEF6

END MODULE RTUTILITY

MODULE RAMANDATA
INTEGER, PARAMETER :: NKGRID=8
REAL*8, DIMENSION(4), PARAMETER :: Aj=(/0.41D0, 0.39D0, 0.10D0, 0.10D0/);
REAL*8, DIMENSION(4), PARAMETER :: Kj=(/3250D0, 3425D0, 3530D0, 3625D0/);
REAL*8, DIMENSION(4), PARAMETER :: deltaKj=(/210D0, 175D0, 140D0, 140d0/);
REAL*8, DIMENSION(NKGRID),PARAMETER::KppGrid=(/2960.0d0,3080.0d0,3200.0d0,&
           3320.0d0,3440.0d0,3560.0d0,3680.0d0,3800.0d0/)
REAL*8, DIMENSION(NKGRID),PARAMETER::KppWeight=(/60.0d0,120.0d0,120.0d0,&
              120.0d0,120.0d0,120.0d0,120.0d0,60.0d0/)
REAL*8,DIMENSION(NKGRID):: LAMBDAEX,fRfuncjEX

CONTAINS
SUBROUTINE FRFUNCJCAL(LAMBDAEM)
IMPLICIT NONE
REAL*8,INTENT(IN) :: LAMBDAEM
REAL*8 :: KEM,KEX,fRfuncj,fNormC,FNORMFAC
INTEGER :: IKPP,IJ
KEM=1.0D7/LAMBDAEM
fRfuncjEX=0.0D0
DO IKPP=1,NKGRID
  KEX=KEM+KppGrid(IKPP)
  LAMBDAEX(IKPP)=1.0E7/KEX
  fRfuncj=0.0D0
  fNormC=0.0D0
  DO IJ=1,4
    fRfuncj=fRfuncj+Aj(IJ)/deltaKj(IJ)*exp(-4.0D0*log(2.0D0)* &
                  ((KppGrid(IKPP)-Kj(IJ))**2)/(deltaKj(IJ)**2));
    fNormC=fNormC+sqrt(3.14159265D0/4.0D0/log(2.0D0))*Aj(IJ);
  ENDDO
  fRfuncjEX(IKPP)=fRfuncj/fNormC
ENDDO
FNORMFAC=SUM(fRfuncjEX*KppWeight)
!WRITE(*,*)'FNORMFAC=',FNORMFAC
!fRfuncjEX=fRfuncjEX/FNORMFAC

END SUBROUTINE FRFUNCJCAL

END MODULE RAMANDATA

MODULE FLUORESCENCEDATA
INTEGER :: NFLRSCGRID
INTEGER,PARAMETER ::N_FCDOM_TYPE=9,N_FCDOM_WAVELENGTH=10

LOGICAL :: NPQ_FLAG
REAL*8 :: QUANTUM_YIELD_CHLA_MIN,QUANTUM_YIELD_CHLA_MAX, &
          QUANTUM_YIELD_CHLA_EK,QUANTUM_YIELD_CHLA_ET,QUANTUM_YIELD_CHLA_MLD,   &
          QUANTUM_YIELD_CHLA_QI, DELTALAMBDAEXFLRSC,                            &
          LAMBDAEX_CDOM_BEG,LAMBDAEX_CDOM_END,&
          LAMBDAEX_CHLA_BEG,LAMBDAEX_CHLA_END,&
          LAMBDAEX_FLRSC_BEG,LAMBDAEX_FLRSC_END

REAL*8,DIMENSION(:), ALLOCATABLE :: LAMBDAEXFLRSC,fCDOMfuncjEX,fCHLAfuncjEX
! HAWES, SPIE, 1992 DATA
! INCLUDES 9 SAMPLES: FA7, FA8, FA9, FA11, HA1, HA2, HA4, HA6, HA8.
! THIS IS ALSO THE ORDER OF MATRIX DATA IS ORGANIZED.
! HA5 AND HA10 ARE EXCLUDED BECAUSE OF MISSING DATA 

REAL*8,DIMENSION(N_FCDOM_WAVELENGTH,N_FCDOM_TYPE) :: A0_CDOM
REAL*8,DIMENSION(N_FCDOM_WAVELENGTH) :: WAVELENGTH_FCDOM_TABLE=(/310.0D0,330.0D0,&
                  350.0D0,370.0D0,390.0D0,410.0D0,430.0D0,450.0D0,470.0D0,490.0D0/)
REAL*8,DIMENSION(N_FCDOM_TYPE)::WEIGHT_CDOM_TYPE
REAL*8,DIMENSION(N_FCDOM_TYPE)::A1_CDOM=(/0.470d0,0.389d0,0.466d0,0.471d0,0.304d0,&
                                          0.379d0,0.346d0,0.447d0,0.356d0/)
REAL*8,DIMENSION(N_FCDOM_TYPE)::A2_CDOM=(/0.407d0,0.386d0,0.386d0,0.386d0,0.591d0,&
                                          0.362d0,0.411d0,0.417d0,0.406d0/)
REAL*8,DIMENSION(N_FCDOM_TYPE)::B1_CDOM=(/8.077d-4,10.073d-4, 8.340d-4,8.204d-4, &
                               12.169d-4,10.043d-4,10.891d-4,8.594d-4,10.694d-4/)
REAL*8,DIMENSION(N_FCDOM_TYPE)::B2_CDOM=(/-4.57d-4,-4.20d-4,-4.13d-4,-4.20d-4,   &
                                 -9.39d-4,-3.17d-4,-4.60d-4,-4.64d-4,-4.42d-4/)

CONTAINS

SUBROUTINE FFLRWVRGCAL(OCEAN_FCHLA_FLAG,OCEAN_FCDOM_FLAG,OCEAN_RAMAN_FLAG,HYSPECTRAL_FLAG)
IMPLICIT NONE
LOGICAL, INTENT(IN)::OCEAN_FCHLA_FLAG,OCEAN_FCDOM_FLAG,OCEAN_RAMAN_FLAG,HYSPECTRAL_FLAG
INTEGER :: ILAMBDAPP
REAL*8 :: FNORMFAC_CDOM,FNORMFAC_CHLA
IF(OCEAN_RAMAN_FLAG .AND. HYSPECTRAL_FLAG)THEN
  DELTALAMBDAEXFLRSC=5.0D0
ELSE
  DELTALAMBDAEXFLRSC=10.0D0
ENDIF
LAMBDAEX_CDOM_BEG=300.0D0    !SHOULD BE 250.0D0, CHANGE TO 300 FOR BIO-OPTICAL MODELS LIMITATIONS
LAMBDAEX_CDOM_END=490.0D0
LAMBDAEX_CHLA_BEG=370.0D0
LAMBDAEX_CHLA_END=690.0D0


IF(OCEAN_FCDOM_FLAG)THEN
   LAMBDAEX_FLRSC_BEG=LAMBDAEX_CDOM_BEG
   LAMBDAEX_FLRSC_END=LAMBDAEX_CDOM_END
ENDIF

IF(OCEAN_FCHLA_FLAG)THEN
   LAMBDAEX_FLRSC_BEG=LAMBDAEX_CHLA_BEG
   LAMBDAEX_FLRSC_END=LAMBDAEX_CHLA_END
ENDIF

IF((OCEAN_FCHLA_FLAG .AND. OCEAN_FCDOM_FLAG) .OR. OCEAN_RAMAN_FLAG)THEN
  LAMBDAEX_FLRSC_BEG=MIN(LAMBDAEX_CDOM_BEG,LAMBDAEX_CHLA_BEG)
  LAMBDAEX_FLRSC_END=MAX(LAMBDAEX_CDOM_END,LAMBDAEX_CHLA_END)
ENDIF
NFLRSCGRID=CEILING(LAMBDAEX_FLRSC_END-LAMBDAEX_FLRSC_BEG)/DELTALAMBDAEXFLRSC+1

ALLOCATE(LAMBDAEXFLRSC(NFLRSCGRID))

DO ILAMBDAPP=1,NFLRSCGRID
  LAMBDAEXFLRSC(ILAMBDAPP)=LAMBDAEX_FLRSC_BEG+(ILAMBDAPP-1)*DELTALAMBDAEXFLRSC
ENDDO

A0_CDOM=transpose(reshape([ &
 5.18D-5,  4.48D-5,  5.21D-5, 5.09D-5, 2.49D-5, 2.78D-5, 4.83D-5, 5.77D-5, 3.61D-5, &
 6.34D-5,  5.67D-5,  6.57D-5, 6.27D-5, 2.68D-5, 3.13D-5, 5.11D-5, 6.86D-5, 4.01D-5, &
 8.00D-5,  7.23D-5,  7.93D-5, 7.93D-5, 2.95D-5, 3.73D-5, 5.94D-5, 7.27D-5, 0.46D-5, &
 9.89D-5,  9.26D-5,  9.93D-5, 9.76D-5, 3.34D-5, 4.42D-5, 7.20D-5, 8.37D-5, 5.48D-5, &
 9.39D-5,  9.06D-5,  0.93D-5, 8.72D-5, 2.77D-5, 4.03D-5, 6.53D-5, 7.08D-5, 5.06D-5, &
10.48D-5,  9.22D-5,  9.47D-5, 7.93D-5, 2.26D-5, 3.91D-5, 6.41D-5, 7.80D-5, 5.05D-5, &
12.59D-5, 10.14D-5, 10.21D-5, 8.15D-5, 2.63D-5, 4.41D-5, 7.66D-5, 8.90D-5, 5.66D-5, &
13.48D-5,  9.90D-5, 10.08D-5, 7.75D-5, 2.72D-5, 4.52D-5, 7.55D-5, 9.30D-5, 5.70D-5, &
13.61D-5,  9.70D-5, 10.11D-5, 7.70D-5, 2.65D-5, 4.75D-5, 7.88D-5, 8.41D-5, 5.32D-5, &
 9.27D-5,  7.90D-5,  8.34D-5, 5.98D-5, 2.20D-5, 4.29D-5, 6.81D-5, 6.68D-5, 4.42D-5],&
    shape(transpose(A0_CDOM))))

END SUBROUTINE FFLRWVRGCAL


SUBROUTINE FFLRfuncjEXCAL(OCEAN_FCHLA_FLAG,OCEAN_FCDOM_FLAG,LAMBDAEM)
USE RTTYPE, ONLY : TWOPI
IMPLICIT NONE
LOGICAL, INTENT(IN)::OCEAN_FCHLA_FLAG,OCEAN_FCDOM_FLAG
REAL*8,INTENT(IN) :: LAMBDAEM

REAL*8 :: SIGMA_CHLA,LAMBDA0CHLA,FAC1,GCHLAFAC,HCFAC,FCFAC1,FCFAC2
INTEGER :: ILAMBDAPP,FCDOM_FH_indx
REAL*8 :: FNORMFAC_CDOM,FNORMFAC_CHLA

REAL*8,DIMENSION(N_FCDOM_WAVELENGTH) :: A0_CDOM_TEMP
REAL*8 :: A0_CDOM_LOCAL

REAL*8, EXTERNAL :: POLINT_SIMPLE

IF(OCEAN_FCDOM_FLAG) THEN
  ALLOCATE(fCDOMfuncjEX(NFLRSCGRID))
  fCDOMfuncjEX=0.0D0
  DO FCDOM_FH_indx=1,N_FCDOM_TYPE
  A0_CDOM_TEMP=A0_CDOM(:,FCDOM_FH_indx)
  DO ILAMBDAPP=1,NFLRSCGRID
    IF((LAMBDAEXFLRSC(ILAMBDAPP) < LAMBDAEX_CDOM_BEG) .OR. &
       (LAMBDAEXFLRSC(ILAMBDAPP) > LAMBDAEX_CDOM_END)) CYCLE

    A0_CDOM_LOCAL=POLINT_SIMPLE(N_FCDOM_WAVELENGTH,WAVELENGTH_FCDOM_TABLE,&
                                 A0_CDOM_TEMP,LAMBDAEXFLRSC(ILAMBDAPP),3)

  ! EQUATION 5.101, MOBLEY, 1994, LIGHT&WATERS
    FCFAC1=1.0D0/LAMBDAEM-A1_CDOM(FCDOM_FH_indx)/LAMBDAEXFLRSC(ILAMBDAPP) &
           -B1_CDOM(FCDOM_FH_indx)
    FCFAC2=0.6D0*(A2_CDOM(FCDOM_FH_indx)/LAMBDAEXFLRSC(ILAMBDAPP) &
                  +B2_CDOM(FCDOM_FH_indx))

    fCDOMfuncjEX(ILAMBDAPP)=fCDOMfuncjEX(ILAMBDAPP)                     &
                         +  WEIGHT_CDOM_TYPE(FCDOM_FH_indx)             &
                         *  A0_CDOM_LOCAL*EXP(-(FCFAC1/FCFAC2)**2)      &
                         *  LAMBDAEXFLRSC(ILAMBDAPP)/LAMBDAEM
!write(*,*)LAMBDAEM,LAMBDAEXFLRSC(ILAMBDAPP),fCDOMfuncjEX(ILAMBDAPP)
  ENDDO
  ENDDO
ENDIF

IF(OCEAN_FCHLA_FLAG) THEN

! QUANTUM YIELD MODEL FOLLOWS: J. Ruairidh Morrison, 
!    'In situ determination of the quantum yield of phytoplankton 
!     chlorophyll a fluorescence: A simple algorithm, observations, and a model,'
!     Limnol. Oceanogr. Vol. 48, Page 618-631, (2003)
! Morrison and Goodwin, 'phytoplankton photocompensation from space-based fluorescence measurements'
! Geophysical research letters, vol. 37, L06603, doi:10.1029/2009GL041799, 2010

  QUANTUM_YIELD_CHLA_MIN=0.03D0
  QUANTUM_YIELD_CHLA_MAX=0.090D0
  QUANTUM_YIELD_CHLA_EK=55.0D0  ! UNIT=MICRO MOL QUANTA m^{-2} s^{-1}
  QUANTUM_YIELD_CHLA_ET=634.0D0 ! UNIT=MICRO MOL QUANTA m^{-2} s^{-1}
  QUANTUM_YIELD_CHLA_QI=0.35d0   ! median value from Fig. 9 in Morrison, LO, 2003
  QUANTUM_YIELD_CHLA_MLD=30 ! meters, a median value from Morisson and Goodwin.

  SIGMA_CHLA=10.6D0
  LAMBDA0CHLA=685.0D0
  FAC1=1.0D0/SQRT(TWOPI)/SIGMA_CHLA

  ALLOCATE(fCHLAfuncjEX(NFLRSCGRID))
  fCHLAfuncjEX=0.0D0

  DO ILAMBDAPP=1,NFLRSCGRID
    IF(LAMBDAEXFLRSC(ILAMBDAPP) > LAMBDAEX_CHLA_BEG .AND. &
       LAMBDAEXFLRSC(ILAMBDAPP) < LAMBDAEX_CHLA_END)          THEN
          GCHLAFAC=1.0D0
    ELSE
          GCHLAFAC=0.0D0
    ENDIF
    HCFAC=FAC1*EXP(-0.5D0*(((LAMBDAEM-LAMBDA0CHLA)/SIGMA_CHLA)**2))

  ! EQUATION 5.102, MOBLEY, 1994, LIGHT&WATERS, WITHOUT QUANTUM YIELD, WHICH WILL
  ! BE MULTIPLIED AFTER E0 IS DETERMINED.
     fCHLAfuncjEX(ILAMBDAPP)=GCHLAFAC*HCFAC* &
                            LAMBDAEXFLRSC(ILAMBDAPP)/LAMBDAEM
  ENDDO
ENDIF

END SUBROUTINE FFLRfuncjEXCAL

SUBROUTINE PHOTOCHEMICAL_QUENCHING_IPAR_AVG_CAL(NWATER_DEPTH, &
                                         WATER_DEPTH,IPAR_SCALAR,IPAR_AVG)
INTEGER, INTENT(IN) :: NWATER_DEPTH
REAL*8,DIMENSION(NWATER_DEPTH),INTENT(IN)::WATER_DEPTH,IPAR_SCALAR
REAL*8,INTENT(OUT)::IPAR_AVG

INTEGER :: ILAYERW

IPAR_AVG=0.0D0
DO ILAYERW=2,NWATER_DEPTH
  IPAR_AVG=IPAR_AVG+0.5d0*(IPAR_SCALAR(ILAYERW)+IPAR_SCALAR(ILAYERW-1)) * &
                          (WATER_DEPTH(ILAYERW)-WATER_DEPTH(ILAYERW-1))
  IF(WATER_DEPTH(ILAYERW)>QUANTUM_YIELD_CHLA_MLD)EXIT
ENDDO
IPAR_AVG=IPAR_AVG/QUANTUM_YIELD_CHLA_MLD !AVERAGED IPAR FROM 0 TO MIXED LAYER DEPTH.

END SUBROUTINE

SUBROUTINE PHOTOCHEMICAL_QUENCHING_ET_CAL(IPAR_AVG)
REAL*8,INTENT(IN) :: IPAR_AVG
REAL*8, EXTERNAL :: POLINT_SIMPLE
REAL*8,DIMENSION(1:12) ::Ig_SORT,ET_SORT ! DATA FROM MORRISON AND GOODWIN, FIG. 2a, 2c, and 3c.
! First Ipar, MLD, Ig, and ET are digtized. Then kd490 is derived using Ipar, Ig, and MLD.
! Ig_modified is calculated with Ig_modified=integral(Ipar*exp(-kd490*z)dz/MLD
! Then Ig_modified and ET are sorted according to Ig_modified. The resultant LUT is
REAL*8,DIMENSION(1:12) :: Ig_log
REAL*8 :: IPAR_AVG_log
Ig_SORT=(/71.414d0,109.34d0,125.88d0,169.63d0,188.4d0,262.55d0,329.53d0,&
       515.89d0,733.2d0,1028.4d0,1090.8d0,1186.5d0/)
ET_SORT=(/       506.36d0,858.89d0,822.06d0,932.55d0,987.8d0,1295.6d0,  &
       1253.5d0,1240.4d0,1150.9d0,1158.8d0,1182.5d0,1190.4d0/)

Ig_log=log(Ig_SORT)
IPAR_AVG_log=log(IPAR_AVG)

QUANTUM_YIELD_CHLA_ET=POLINT_SIMPLE(12,Ig_log,ET_SORT,IPAR_AVG_log,2)

END SUBROUTINE

END MODULE FLUORESCENCEDATA
