MODULE SURFACE_GLINT
IMPLICIT NONE
LOGICAL :: SURFACE_GLINT_FLAG = .FALSE.
! if SURFACE_GLINT_FLAG==.true. output glint contribution to DSTOKES_GLINT

DOUBLE PRECISION,DIMENSION(:,:,:,:),ALLOCATABLE :: DSTOKES_GLINT
! DSTOKES_GLINT(NDET,       NTHETAOUT,       NPHIOUT,         4)

CONTAINS

SUBROUTINE SURFACE_GLINT_ALLO(NDET,NTHETA,NPHI)
INTEGER,INTENT(IN) :: NDET,NTHETA,NPHI

ALLOCATE(DSTOKES_GLINT(NDET,NTHETA,NPHI,4))

END SUBROUTINE SURFACE_GLINT_ALLO

SUBROUTINE SURFACE_GLINT_DEALLO

DEALLOCATE(DSTOKES_GLINT)

END SUBROUTINE SURFACE_GLINT_DEALLO


END MODULE SURFACE_GLINT
